### ISSUE TITLE
可以支持热重启吗

### ISSUE THREAD

**Issue by hhf666feng** [hhxsv5/laravel-s#10]
可以支持热重启吗

**Comment by hhxsv5** [comment]
执行reload命令即可。
一般生产环境是手动发布，不是自动发布。
如确实需要发布代码就自动重启，可以结合[inotify](http://php.net/manual/zh/book.inotify.php)来实现。

**Comment by fanybook** [comment]
可以是用 pm2 之类的工具  监控代码变化  重启

**Comment by hhxsv5** [comment]
v1.9.1 已经支持Inotify Reload，修改代码后自动Reload worker进程，建议开发环境使用。[具体配置](https://github.com/hhxsv5/laravel-s/blob/master/Settings-CN.md)

至于Laravel队列的worker监控已经超出开发此项目的初衷了。
