### ISSUE TITLE
WebSocket刷新页面无法触发onClose事件

### ISSUE THREAD

**Issue by swlhyyh** [hhxsv5/laravel-s#100]
想在onClose事件里面对用户ID跟fd进行解绑，发现触发不了onClose事件。

**Comment by Evilleo424** [comment]
也是同样的问题
按照文档推荐的配置设置的nginx
dispatch_mode设置为2
刷新页面之后可以触发onOpen事件 无法触发onClose事件
在onClose事件里需要另外写什么方法来关闭与客户端的链接吗

**Comment by hhxsv5** [comment]
@Evilleo424 onMessage事件能触发不？就onClose事件无效？

**Comment by Evilleo424** [comment]
> @Evilleo424 onMessage事件能触发不？就onClose事件无效？

onMessage也不能触发，刷新页面之后只能触发onOpen事件。

**Comment by hhxsv5** [comment]
@Evilleo424  你是多端口协议加的WebSocket？

**Comment by Evilleo424** [comment]
> @Evilleo424 你是多端口协议加的WebSocket？

不是，所有的配置都是按示例来设置的

**Comment by hhxsv5** [comment]
@Evilleo424 加QQ群细聊：62075835

**Comment by Evilleo424** [comment]
之前家过群 但qq密码忘了 暂时上不了q
问题找到了 因为我这边的业务场景是每秒从redis取一组数据返回给客户端，所以用ws长链接来实现，每秒这里我用了tick，就是这里出了问题，tick的回掉方法里我引入了$frame，这里的$frame->fd没有更新还是之前那次链接的id，所以导致客户端收不到数据
$server->tick(1000, function () use ($server, $frame, $redis) {
	$heart_rate = $redis->hget('redis_hash', time() - 20);
	$server->push($frame->fd, json_encode(['code' => 200, 'time' => date('Y-m-d H:i:s'), 'heart_rate' => $heart_rate]));
	});
像这种情况下$frame该怎么使用才能使用正确的fd呢

**Comment by hhxsv5** [comment]
那你完全可以用[毫秒定时器](https://github.com/hhxsv5/laravel-s/blob/master/README-CN.md#%E6%AF%AB%E7%A7%92%E7%BA%A7%E5%AE%9A%E6%97%B6%E4%BB%BB%E5%8A%A1)写个定时任务来实现你的需求。如果你是针对所有连接都需要定时推送消息，那可以在定时任务中直接遍历`app('swoole')-> connections`拿到所有fd；如果你是不同fd关联不同用户，发送不同消息，可以用[Table存储UserId与FD的关联](https://github.com/hhxsv5/laravel-s/blob/master/README-CN.md#%E4%BD%BF%E7%94%A8swooletable)，定时任务中获取这个关系。

**Comment by Evilleo424** [comment]
已解决，但不是用你说的这个方法，我感觉你这样做会稍微麻烦一些。
今天看swoole文档定时器那里tick的第一句话就是“设置一个间隔时钟定时器，与after定时器不同的是tick定时器会持续触发，直到调用Timer::clear清除。”所以说我之前的代码没有更新$frame是因为之前的定时器没有清除掉，因此就无法更新$frame，解决的办法是增加一个$time_id的私有变量存储每一个定时器的id，当触发onclose事件的时候执行clearTime()方法，就可以解决。
