### ISSUE TITLE
发现单个任务Task中finish函数不执行的？

### ISSUE THREAD

**Issue by dafa168** [hhxsv5/laravel-s#101]
1. Tell us your software version
    How to know it?
    ```Bash
    # PHP
    php -v
    # Swoole
    php --ri swoole    4.2.0 
    # Laravel
    grep 'laravel/framework' composer.json  5.6
    # Lumen
    grep 'laravel/lumen-framework' composer.json 5.6
    ```

    | Software | Version |
    | --------- | --------- |
    | PHP | `TODO` |
    | Swoole | `TODO` |
    | Laravel/Lumen | `TODO` |

2. Detail description about this issue(error/log)

### 下面这段代码，我测试了下，根本没有执行到。不知道啥原因？ 
     // 可选的，完成事件，任务处理完后的逻辑，运行在Worker进程中，可以投递任务
    public function finish()
    {
        \Log::info(__CLASS__ . ':finish start', [$this->result]);
        Task::deliver(new TestTask2('task2')); // 投递其他任务
    }

3. Give us a `reproducible` code block and `steps`

    ```PHP
    //TODO: Your code
    ```

**Comment by hhxsv5** [comment]
在哪里投递的任务？

**Comment by dafa168** [comment]
在Task任务的 finish 函数中投递其它的任务。

**Comment by hhxsv5** [comment]
我问的是第一个Task是在哪里投递的？

**Comment by dafa168** [comment]
嗯嗯 明白了。谢谢。

**Comment by dafa168** [comment]
我试了下貌似不行的。我在定时器中投递任务的。
具体请看代码： 
定时器代码： 
```
<?php

namespace App\Jobs\Timer;

use App\Tasks\TestTask;
use Hhxsv5\LaravelS\Swoole\Task\Task;
use Hhxsv5\LaravelS\Swoole\Timer\CronJob;

/**
 *
 * Class TestCronJob
 * @package App\Jobs\Timer
 */
class TestCronJob extends CronJob
{

    protected $i = 0;

    // 声明没有参数的构造函数
    public function __construct()
    {
    }

    public function interval()
    {
        return 1000;// 每1秒运行一次
    }

    public function run()
    {
        Task::deliver(new TestTask('test'));
        return true;
    }
}
````

任务1 代码： 
```
<?php

namespace App\Tasks;


use Hhxsv5\LaravelS\Swoole\Task\Task;

class TestTask extends Task
{

    private $data;

    public function __construct($data)
    {
        $this->data = $data;
    }

    public function handle()
    {
        echo __METHOD__ . $this->data . PHP_EOL;
    }

    public function finish()
    {

        Task::deliver(new Test2Task('test 2 data'));

    }

}
```
任务2 代码： 
```
<?php 
namespace App\Tasks;


use Hhxsv5\LaravelS\Swoole\Task\Task;

class Test2Task extends Task
{

    private $data;

    public function __construct($data)
    {
        $this->data = $data;
    }

    public function handle()
    {
        echo __METHOD__ . $this->data . PHP_EOL;
    }
}
```

执行 php artisan laravels start  报错如下： 
[2018-11-16 11:48:30] [ERROR] LaravelS: Uncaught exception 'ErrorException': [0]Swoole\Server::task(): task method can only be used in the worker process. called in /data/www/frans_test/c1data/vendor/hhxsv5/laravel-s/src/Swoole/Task/Task.php:73
#0 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(2, 'Swoole\\Server::...', '/data/www/frans...', 73, Array)

**Comment by hhxsv5** [comment]
定时器、自定义进程中投递任务第二个参数必须为true，所以这类Task是不支持finish回调的

**Comment by dafa168** [comment]
嗯嗯 好的。 还希望在文档中有相关提示哦。感激不尽！

**Comment by hhxsv5** [comment]
文档注释中有。
