### ISSUE TITLE
按照文档配置完成后访问502

### ISSUE THREAD

**Issue by anyesuifengs** [hhxsv5/laravel-s#102]
按照文档安装laravels后，访问提示502 Bad Gateway。
我之前在其他服务器安装是正常的，这一次配置和前几次配置也没有感觉到什么不同。
nginx错误日志只有 `[notice] 13163#0: signal process started` 

nginx访问日志中有静态资源返回200，首页返回502的记录

请问是否有更好的排查思路或方向？目前卡着不知道如何解决

**Comment by hhxsv5** [comment]
1.请按issue模板提交issue
2.502表示Nginx到Swoole不可达，检查Nginx error log

**Comment by guandaxia** [comment]
看看配置文件有没有问题，检查`php artisan laravels start`是否启动正常了

**Comment by anyesuifengs** [comment]
粗心导致，配置文件被缓存了。

**Comment by tangqi198707** [comment]
@anyesss 我也遇到了同样的问题，请问下是什么配置文件？config/laravels.php？

**Comment by anyesss** [comment]
> @anyesss 我也遇到了同样的问题，请问下是什么配置文件？config/laravels.php？

因为时间过去太久了，我也不太记得，不过看我之前的描述，应该是指配置文件被缓存了，导致修改配置之后没有生效，所以502，清除laravel的配置缓存即刻  config:clear

**Comment by tangqi198707** [comment]
感谢回复，我也清除缓存试了，但是还是502。
