### ISSUE TITLE
laravel 组合laravels后，DB查询返回数组或对象问题？

### ISSUE THREAD

**Issue by dafa168** [hhxsv5/laravel-s#103]
1. Tell us your software version
    How to know it?
    ```Bash
    # PHP
    php -v
    # Swoole
    php --ri swoole
    # Laravel
    grep 'laravel/framework' composer.json
    # Lumen
    grep 'laravel/lumen-framework' composer.json
    ```

    | Software | Version |
    | --------- | --------- |
    | PHP | `7.2.8` |
    | Swoole | `4.2.0` |
    | Laravel/Lumen | `5.7` |

2. Detail description about this issue(error/log)

我在这个文件中加入了此段代码： 
app/Providers/EventServiceProvider.php

```
<?php
namespace App\Providers;
use Illuminate\Support\Facades\Event;
use Laravel\Lumen\Providers\EventServiceProvider as ServiceProvider;
use Illuminate\Database\Events\StatementPrepared;
class EventServiceProvider extends ServiceProvider
{
    /**
     * The event listener mappings for the application.
     *
     * @var array
     */
    protected $listen = [
        'App\Events\ExampleEvent' => [
            'App\Listeners\ExampleListener',
        ],
    ];

    public function boot()
    {
        parent::boot();

        /**
！！！就是这里！！！
         * **设置POD返回数组**
         */
        Event::listen(StatementPrepared::class, function ($event) {
            $event->statement->setFetchMode(\PDO::FETCH_ASSOC);
        });

    }
}

```

    
问题： 当我在 laravel本身的命令行中使用DB::get()->toArray() 查询出来得到的是二位数组里面是一维数组。

但是在 laravels 启动的异步任务中使用 DB::get()->toArray() 查询出来得到的是二位数组里面是对象 ？

感觉是laravels中应该是没有执行到上面的事件代码吧

3. Give us a `reproducible` code block and `steps`

    ```PHP
    //TODO: Your code
    ```

**Comment by hhxsv5** [comment]
未复现。

![image](https://user-images.githubusercontent.com/7278743/48981062-e2fd8580-f10b-11e8-83a8-b27c07986145.png)
![image](https://user-images.githubusercontent.com/7278743/48981056-ceb98880-f10b-11e8-85ca-3ab51fa88065.png)

**Comment by hhxsv5** [comment]
https://laravel-china.org/docs/laravel/5.3/queries/1187#retrieving-results
https://laravel-china.org/docs/laravel/5.2/queries/1137#retrieving-results

Laravel 5.3之前版本是返回数组，5.3及以后版本返回Collection集合对象。
