### ISSUE TITLE
开启任务后报错 Swoole\Server::sendMessage(): large task pack failed.

### ISSUE THREAD

**Issue by dafa168** [hhxsv5/laravel-s#104]
1. Tell us your software version
    How to know it?
    ```Bash
    # PHP
    php -v
    # Swoole
    php --ri swoole
    # Laravel
    grep 'laravel/framework' composer.json
    # Lumen
    grep 'laravel/lumen-framework' composer.json
    ```

    | Software | Version |
    | --------- | --------- |
    | PHP | `TODO` |
    | Swoole | `TODO` |
    | Laravel/Lumen | `TODO` |

2. Detail description about this issue(error/log)

[2018-11-16 21:16:36] [ERROR] LaravelS: Uncaught exception 'ErrorException': [0]Swoole\Server::sendMessage(): large task pack failed. called in /data/www/frans_test/c1data/vendor/hhxsv5/laravel-s/src/Swoole/Task/Task.php:77

3. Give us a `reproducible` code block and `steps`

    ```PHP
    //TODO: Your code
    ```

**Comment by hhxsv5** [comment]
此错误的意思是你的Task对象太大了

**Comment by dafa168** [comment]
嗯嗯，今早来做了测试，在构造函数中传递的参数（对象）过大了。删除就好了。谢谢。

**Comment by never615** [comment]
直接设置        'task_max_pack_size' => 20 * 1024 * 1024,  也行吧

**Comment by uptonyuan** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
