### ISSUE TITLE
不使用nginx的情况下是否可以访问静态资源

### ISSUE THREAD

**Issue by xiongchao123** [hhxsv5/laravel-s#105]
1. Tell us your software version
 
    | Software | Version |
    | --------- | --------- |
    | PHP | 7.2.12 |
    | Swoole | 4.2.8 |
    | Laravel/Lumen |5.6.7 |

2. Detail description about this issue(error/log)
   不使用nginx的情况下是否可以访问静态资源

3. Give us a `reproducible` code block and `steps`

**Comment by hhxsv5** [comment]
当然可以，开启[handle_static](https://github.com/hhxsv5/laravel-s/blob/master/Settings-CN.md)即可。但你需要清楚一点，[Swoole Http Server](https://wiki.swoole.com/wiki/page/326.html)对Http协议支持不完整，建议仅作为应用服务器，在前端增加Nginx作为代理。

**Comment by xiongchao123** [comment]
不好意思，我文档没有看仔细，多谢！
