### ISSUE TITLE
WebSocket 请求 onOpen 方法报错：Call to a member function resetSession() on unknown

### ISSUE THREAD

**Issue by Jasongzj** [hhxsv5/laravel-s#108]
1. Tell us your software version
    How to know it?
    ```Bash
    # PHP
    php -v
    # Swoole
    php --ri swoole
    # Laravel
    grep 'laravel/framework' composer.json
    # Lumen
    grep 'laravel/lumen-framework' composer.json
    ```

    | Software | Version |
    | --------- | --------- |
    | PHP | `5.6.38` |
    | Swoole | `1.10.6` |
    | Laravel/Lumen | `5.2.45` |

2. Detail description about this issue(error/log)

    启用 WebSocket 服务器，请求连接对应的地址成功，但是 `onOpen` 方法不能正常推送消息，出现如下报错：`Call to a member function resetSession() on unknown`
![image](https://user-images.githubusercontent.com/24838580/49523031-dfc08180-f8e3-11e8-971a-157a59897998.png)

3. 解决方法：

    不要使用 v1.10.6 版本的 swoole ，重新安装一个 v1.10.5 的swoole 即可解决该问题。

**Comment by hhxsv5** [comment]
Nice!
