### ISSUE TITLE
Login once, logged in everywhere. 在一处登录后，所有设备均显示已登录。

### ISSUE THREAD

**Issue by moycat** [hhxsv5/laravel-s#109]
1. Tell us your software version

    | Software | Version |
    | --------- | --------- |
    | PHP | `7.2.12` |
    | Swoole | `4.2.10-alpha` |
    | Laravel/Lumen | `5.7.*` |

2. Detail description about this issue(error/log)

    使用 Laravel 内置的用户系统时，只要在一处登录，在其他任何地方访问均显示我已登录，清空 Cookies 也无效。

    我已经按照 #99、#50 中的描述设置了 `config/laravels.php` 中的「register_providers」，但是并没有用。按照前一个 issue 提出者所说将 `cleanRequest` 函数里那两行取消注释，还是这样。

    这个 bug 并不稳定，不能 100% 复现。但它的确存在，用一个从未访问过此网站的手机打开也可能触发。

    我觉得就是那两个 issue 中的相关问题，但我想知道如何修复。

    When I use the built-in user system of Laravel, if I login once, the site shows I am logged in everywhere, even after I cleaned my cookies.

    I have set the "register_providers" in `config/laravels.php` to the following as mentioned in #99 and #50, but it did no good.  Neither did uncommenting the two lines in the `cleanRequest` function.

    This bug isn't consistent, but it does exists. I have ever used a phone that never visited the site to browse it, and it said I was logged in.

    I think the bug is related to the two issues above. I want to know how to fix it.

    `config/laravels.php`:
```php
return [
    //......
    'register_providers'       => [
        '\App\Providers\AuthServiceProvider',
        '\Illuminate\Auth\AuthServiceProvider',
        '\Illuminate\Auth\Passwords\PasswordResetServiceProvider',
    ],
    //......
];
```
![image](https://user-images.githubusercontent.com/12007097/49606901-92b9d980-f9cf-11e8-950c-f0a0d91faefd.png)

请求头中没有 cookies，但还是显示已登录。

No cookies passed to server. Still shows logged in.

3. Give us a `reproducible` code block and `steps`

    创建一个最简单的应用：
    1. `laravel new test`，进入目录，用 composer 安装 laravel-s。
    2. `php artisan laravels publish`，修改 `config/laravels.php`。
    3. 使用 SQLite 数据库（只是简单起见，用 PostgreSQL 也一样），`php artisan migrate`。
    4. 打开 `http://127.0.0.1:5200` 注册并登录。
    5. 清除 Cookies / 关闭浏览器，再打开这个站点，依然显示已登录。

    Just create a most simplified application (also the steps to have this bug):
    1. `laravel new test` and cd into it, install laravel-s via composer.
    2. `php artisan laravels publish` and modify the `config/laravels.php` file.
    2. `php artisan make:auth` to enable the user system.
    3. Change the database to SQLite (just to simplify. using PostgreSQL doesn't help), and `php artisan migrate`.
    4. Open `http://127.0.0.1:5200`, register a user, login.
    5. Clean the cookies / close the browser / change the device, re-open the site. It shows you are still online.

**Comment by wi1dcard** [comment]
居然.... 写两份，大佬666

**Comment by hhxsv5** [comment]
这是已知问题，guards被缓存在单例中了。下个版本会修复。

**Comment by ibrunotome** [comment]
Hi @hhxsv5, do you have an estimated date to release?

**Comment by hhxsv5** [comment]
@ibrunotome It has not been solved yet, a bit troublesome.

**Comment by ibrunotome** [comment]
@hhxsv5 in swooletw/laravel-swoole I was able to solve reseting the providers:

```php
        Illuminate\Auth\AuthServiceProvider::class,
        Tymon\JWTAuth\Providers\LaravelServiceProvider::class,
        Illuminate\Pagination\PaginationServiceProvider::class,
```

But I can't replicate in your package.

**Comment by hhxsv5** [comment]
@ibrunotome The solution is much the same

Try the following methods：

- Re-register providers
```php
# config/laravels.php
'register_providers'       => [
    App\Providers\AuthServiceProvider::class,
    //...
],
```

- Clear facade in [event](https://github.com/hhxsv5/laravel-s/blob/master/README.md#system-events)
```php
Event::listen('laravels.received_request', function (\Illuminate\Http\Request $req, $app) {
     Facade::clearResolvedInstance('auth');
 });
```

**Comment by hhxsv5** [comment]
@ibrunotome In the next few days, I will delve into this issue and try to give a solution. 
- About coroutine, there are a large number of singletons and static properties in Laravel, they are `unsafe` in coroutine, so I want LaravelS to run in synchronous mode, not in coroutine mode. 
- At the same time, [smf](https://github.com/open-smf/smf) will come out, a minimalist coroutine micro-framework.

**Comment by jianhuawang** [comment]
Both setps must be done will solve this problem.

**Step1:** Re-register providers :  config/laravels.php
'register_providers'       => [
    Illuminate\Auth\AuthServiceProvider::class, // not this one "Illuminate\Auth\AuthServiceProvider::class,"
    //...
],

**Setp2:** Clear facade in event
Event::listen('laravels.received_request', function (\Illuminate\Http\Request $req, $app) {
     Facade::clearResolvedInstance('auth');
 });

good luck!

**Comment by star-xiong** [comment]
问题还是存在啊！

**Comment by jianhuawang** [comment]
> 问题还是存在啊！

刚开始的时候是可以的。过一段时间以后就有问题了，试试把所有providers都加近去吧。我正在测试

**Comment by star-xiong** [comment]
把所有providers都加进去，也不行。

**Comment by greenhat616** [comment]
=，= 所以修复版本会在何时发布呢？ 可以说这个 bug  将导致无法生产， 不是应该列入紧急修复列表么。 试问guard缓存的管理员权限被普通用户所使用， 就很可能可以窃取到管理员的信息（比如apiToken， 再比如邮箱， 订单管理， 甚至是金额调用）

**Comment by Yoruchiaki** [comment]
还是解决不了

**Comment by flymorn** [comment]
解决方法：
第一步：config/laravels.php
```
'register_providers' => [
        // 重载auth相关服务
        \Illuminate\Auth\AuthServiceProvider::class,
        \App\Providers\AuthServiceProvider::class,
        /*\Tymon\JWTAuth\Providers\LaravelServiceProvider::class,*/
    ]
```

第二步，建立全局中间件  EveryRequest.php
```
public function handle($request, Closure $next)
    {
        // swoole请求进来的时候删掉缓存
        if (PHP_SAPI == 'cli') {
            \Illuminate\Support\Facades\Facade::clearResolvedInstance('auth');// swoole下解决auth单例问题
        }

        return $next($request);
    }
```

以上2步缺一不可

**Comment by pingcheng** [comment]
> @ibrunotome The solution is much the same
> 
> Try the following methods：
> 
> * Re-register providers
> 
> ```
> # config/laravels.php
> 'register_providers'       => [
>     App\Providers\AuthServiceProvider::class,
>     //...
> ],
> ```
> 
> * Clear facade in [event](https://github.com/hhxsv5/laravel-s/blob/master/README.md#system-events)
> 
> ```
> Event::listen('laravels.received_request', function (\Illuminate\Http\Request $req, $app) {
>      Facade::clearResolvedInstance('auth');
>  });
> ```

| PHP                                     | 7.2.15                  |
| Swoole                                | 4.2.10-beta        |
| LaravelS                              | 3.3.9                   |
| Laravel Framework [local] | 5.7.19                  |

问题还是存在

**Comment by jianhuawang** [comment]
@pingcheng 
试试这个配置，try like following:
'register_providers' => [
Illuminate\Auth\AuthServiceProvider::class,
Illuminate\Broadcasting\BroadcastServiceProvider::class,
Illuminate\Bus\BusServiceProvider::class,
Illuminate\Cache\CacheServiceProvider::class,
Illuminate\Foundation\Providers\ConsoleSupportServiceProvider::class,
Illuminate\Cookie\CookieServiceProvider::class,
Illuminate\Database\DatabaseServiceProvider::class,
Illuminate\Encryption\EncryptionServiceProvider::class,
Illuminate\Filesystem\FilesystemServiceProvider::class,
Illuminate\Foundation\Providers\FoundationServiceProvider::class,
Illuminate\Hashing\HashServiceProvider::class,
Illuminate\Mail\MailServiceProvider::class,
Illuminate\Notifications\NotificationServiceProvider::class,
Illuminate\Pagination\PaginationServiceProvider::class,
Illuminate\Pipeline\PipelineServiceProvider::class,
Illuminate\Queue\QueueServiceProvider::class,
Illuminate\Redis\RedisServiceProvider::class,
Illuminate\Auth\Passwords\PasswordResetServiceProvider::class,
Illuminate\Session\SessionServiceProvider::class,
Illuminate\Translation\TranslationServiceProvider::class,
Illuminate\Validation\ValidationServiceProvider::class,
Illuminate\View\ViewServiceProvider::class,
App\Providers\AppServiceProvider::class,
App\Providers\AuthServiceProvider::class,
// App\Providers\BroadcastServiceProvider::class,
App\Providers\EventServiceProvider::class,
App\Providers\RouteServiceProvider::class,
],

**Comment by pingcheng** [comment]
> @pingcheng
> 试试这个配置，try like following:
> 'register_providers' => [
> Illuminate\Auth\AuthServiceProvider::class,
> Illuminate\Broadcasting\BroadcastServiceProvider::class,
> Illuminate\Bus\BusServiceProvider::class,
> Illuminate\Cache\CacheServiceProvider::class,
> Illuminate\Foundation\Providers\ConsoleSupportServiceProvider::class,
> Illuminate\Cookie\CookieServiceProvider::class,
> Illuminate\Database\DatabaseServiceProvider::class,
> Illuminate\Encryption\EncryptionServiceProvider::class,
> Illuminate\Filesystem\FilesystemServiceProvider::class,
> Illuminate\Foundation\Providers\FoundationServiceProvider::class,
> Illuminate\Hashing\HashServiceProvider::class,
> Illuminate\Mail\MailServiceProvider::class,
> Illuminate\Notifications\NotificationServiceProvider::class,
> Illuminate\Pagination\PaginationServiceProvider::class,
> Illuminate\Pipeline\PipelineServiceProvider::class,
> Illuminate\Queue\QueueServiceProvider::class,
> Illuminate\Redis\RedisServiceProvider::class,
> Illuminate\Auth\Passwords\PasswordResetServiceProvider::class,
> Illuminate\Session\SessionServiceProvider::class,
> Illuminate\Translation\TranslationServiceProvider::class,
> Illuminate\Validation\ValidationServiceProvider::class,
> Illuminate\View\ViewServiceProvider::class,
> App\Providers\AppServiceProvider::class,
> App\Providers\AuthServiceProvider::class,
> // App\Providers\BroadcastServiceProvider::class,
> App\Providers\EventServiceProvider::class,
> App\Providers\RouteServiceProvider::class,
> ],

好的 谢谢，我先尝试一下，感觉这样需要reset的类有点多

**Comment by fishtrees** [comment]
It's work for me: 
```
+----------------------+---------+
| Component            | Version |
+----------------------+---------+
| PHP                  | 7.1.11  |
| Swoole               | 4.2.13  |
| LaravelS             | 3.3.9   |
| Laravel Framework [] | 5.5.44  |
+----------------------+---------+
```
```PHP
class ClearUserForSwoole
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
        if (Auth::check()) {
            $guard = app(\Illuminate\Auth\AuthManager::class)->guard('api');
            $guardRef = new \ReflectionObject($guard);
            $userRef = $guardRef->getProperty('user');
            $userRef->setAccessible(true);
            $userRef->setValue($guard, null);
        }
        return $next($request);
    }
}
```

**Comment by ibrunotome** [comment]
No one of the suggestions above have worked for me :/
Still using swooletw/laravel-swoole until this

**Comment by u5de6** [comment]
@hhxsv5 3.3.10版本解决这个bug没有  目前有没有好的方案处理  感谢了
| PHP                       | 7.3.1   |
| Swoole                    | 4.2.9   |
| LaravelS                  | 3.3.9   |
| Laravel Framework [local] | 5.5.44  |

**Comment by ibrunotome** [comment]
@u5de6 using which settings in config/laravels.php?

**Comment by hhxsv5** [comment]
Sorry, I am busy at work now, and will start to check this issue in my free time at night.

**Comment by LaoZhangRen** [comment]
加油鸭！！！！快点解决

**Comment by hhxsv5** [comment]
@all After a week of debugging, I have passed the test locally for the Laravel/Lumen 5.1-5.8 user authorization. Please try the `Master` branch code(`composer require hhxsv5/laravel-s:dev-master -vvv`), if there is no problem, I will release v3.4.0, thanks for your support.

**Comment by hhxsv5** [comment]
And you need to republish configuration `php artisan laravels publish`.

**Comment by hhxsv5** [comment]
Core code:
- [src/Illuminate/Cleaners/AuthCleaner.php](https://github.com/hhxsv5/laravel-s/blob/master/src/Illuminate/Cleaners/AuthCleaner.php)
- [src/Illuminate/Cleaners/SessionCleaner.php](https://github.com/hhxsv5/laravel-s/blob/master/src/Illuminate/Cleaners/SessionCleaner.php)

**Comment by ibrunotome** [comment]
@hhxsv5 Tested, I'm getting logged out using tymon jwt

**Comment by hhxsv5** [comment]
@ibrunotome Please tell me the specific version of laravel & jwt.

**Comment by hhxsv5** [comment]
@ibrunotome Added JWTCleaner
```php
'cleaners'  => [
        Hhxsv5\LaravelS\Illuminate\Cleaners\SessionCleaner::class,
        Hhxsv5\LaravelS\Illuminate\Cleaners\AuthCleaner::class,
        Hhxsv5\LaravelS\Illuminate\Cleaners\JWTCleaner::class, // If you use the package "tymon/jwt-auth", please uncomment this line
        Hhxsv5\LaravelS\Illuminate\Cleaners\RequestCleaner::class,
        // ...
],
```

**Comment by ibrunotome** [comment]
@hhxsv5 Confirmed, it's working now :) Nice job!

**Comment by hhxsv5** [comment]
Thank you. @ibrunotome

**Comment by hhxsv5** [comment]
[v3.4.0](https://github.com/hhxsv5/laravel-s/releases/tag/v3.4.0)

**Comment by lisgroup** [comment]
Good job!

**Comment by justcy** [comment]
+--------------------------+-----------------------------------------+
| Component                | Version                                 |
+--------------------------+-----------------------------------------+
| PHP                      | 7.2.23                                  |
| Swoole                   | 4.6.5-dev                               |
| LaravelS                 | 3.7.21                                  |
| Laravel Framework [prod] | Lumen (7.2.2) (Laravel Components ^7.0) |
+--------------------------+-----------------------------------------+

Auth::User串号，auth清理不成功，最后我将AuthCleaner修改了就好了

求大神解释下
```php
<?php

namespace Hhxsv5\LaravelS\Illuminate\Cleaners;


use Illuminate\Container\Container;
use Illuminate\Support\Facades\Facade;

class AuthCleaner extends BaseCleaner
{
    private $guards;

    public function __construct(Container $currentApp, Container $snapshotApp)
    {
        parent::__construct($currentApp, $snapshotApp);

        if (!isset($this->currentApp['auth'])) {
            return;
        }
        $ref = new \ReflectionObject($this->currentApp['auth']);
        if ($ref->hasProperty('guards')) {
            $this->guards = $ref->getProperty('guards');
        } else {
            $this->guards = $ref->getProperty('drivers');
        }
        $this->guards->setAccessible(true);
    }

    public function clean()
    {
        if (!isset($this->currentApp['auth'])) {
            return;
        }
        $this->guards->setValue($this->currentApp['auth'], []);
        $this->currentApp->forgetInstance('auth');
        Facade::clearResolvedInstance('auth');
    }
}
```

**Comment by seth-shi** [comment]
Do not add `\App\Providers\AppServiceProvider::class` to `register_providers` as this will cause memory leaks
