### ISSUE TITLE
可以给个apache的mod_proxy配置吗

### ISSUE THREAD

**Issue by kency** [hhxsv5/laravel-s#11]
用apache访问静态资源,php反向代理给laravel-s

**Comment by hhxsv5** [comment]
Enjoy!
[与apache配合使用](https://github.com/hhxsv5/laravel-s/blob/master/README-CN.md#与apache配合使用)

不过强烈建议使用Nginx，静态文件处理能力好很多。

**Comment by kency** [comment]
谢啦

**Comment by kency** [comment]
还是要再谢一遍!

**Comment by hhxsv5** [comment]
为什么要关gzip

**Comment by kency** [comment]
都在nginx或者apache里处理gzip，这样不会出现压缩两次或者apache解码等额外开销，不过swoole的server是不是应该在代理的客户端不请求gzip头的时候不反回压缩过的还没测试过

**Comment by hhxsv5** [comment]
那确实，选择一方gzip就行了。

**Comment by adon988** [comment]
請問在Apache 的 websocket  proxy部分，也有參考配置說明嗎？

**Comment by hhxsv5** [comment]
@adon988 [官方文档](https://httpd.apache.org/docs/2.4/mod/mod_proxy_wstunnel.html)
