### ISSUE TITLE
部分 worker 未重启 nginx 出现 499

### ISSUE THREAD

**Issue by pauldo** [hhxsv5/laravel-s#111]
1. Tell us your software version

    | Software | Version |
    | --------- | --------- |
    | PHP | `7.0.12` |
    | Swoole | `2.0.6` |
    | Laravel/Lumen | `5.5.*` |

2. Detail description about this issue(error/log)

    声明该问题可能非 laravel-s 导致, 怀疑应该是业务代码某个环节当时网络或数据库延迟导致, 借贵地问一下有没有相关同学遇到过, 提供个思路.

    问题描述:
    生产环境运行一段时间后, nginx 出现部分请求 499, `ps` 命令查看 swoole 进程, 有一个 worker 进程与其他 worker 进程 stime 差异较大, 怀疑未重启(不知道是因为未重启导致499错误, 还是因响应慢导致该进程 `max_request` 未处理完阻塞)

3. Give us a `reproducible` code block and `steps`

    未复现的问题, 提供截图如下:
![16_22_19__12_24_2018](https://user-images.githubusercontent.com/4898520/50394395-27765280-0798-11e9-9330-da51aadc4221.jpg)

**Comment by hhxsv5** [comment]
关于[499](https://github.com/xuxiangwork/Sharing/wiki/nginx-499-%E4%BA%A7%E7%94%9F%E7%9A%84%E5%8E%9F%E5%9B%A0)，不难看出问题在于，服务端没有在客户端规定的时间内给出响应，客户端不耐烦了，超时断开连接。
建议：
- 检查499的接口代码，是否会在特殊情况下导致死循环或阻塞，Worker不能退出
- 升级Swoole版本，也可能是Swoole的Bug
- 另外，你的LaravelS版本较低，建议升级

**Comment by pauldo** [comment]
> 关于[499](https://github.com/xuxiangwork/Sharing/wiki/nginx-499-%E4%BA%A7%E7%94%9F%E7%9A%84%E5%8E%9F%E5%9B%A0)，不难看出问题在于，服务端没有在客户端规定的时间内给出响应，客户端不耐烦了，超时断开连接。
> 建议：
> 
> * 检查499的接口代码，是否会在特殊情况下导致死循环或阻塞，Worker不能退出
> * 升级Swoole版本，也可能是Swoole的Bug
> * 另外，你的LaravelS版本较低，建议升级

谢谢, 我去研究下

**Comment by fising** [comment]
遇到相同问题。每隔几天就会 `499`，目前只能监控 + 重启大法：

| Component  | Version |
|--|--|
| PHP                            | 7.3.17-1+ubuntu16.04.1+deb.sury.org+1     |
| Swoole                         | 4.4.2                                     |
| LaravelS                       | 3.5.8                                     |
| Laravel Framework [production] | Lumen (5.8.10) (Laravel Components 5.8.*) |
