### ISSUE TITLE
取消Controller对象常驻内存

### ISSUE THREAD

**Issue by soloqi** [hhxsv5/laravel-s#112]
应用中有不少配置会在__construct中初始化，有时候需要时时取db数据，常驻会造成使用不便。如果对性能损失不大的话，Controller这种实例最好是每个请求独立，用完销毁，要不从fpm迁过来还要改代码结构

**Comment by Yoruchiaki** [comment]
你在说什么呢?

**Comment by soloqi** [comment]
> 你在说什么呢?

sorry,可能是我描述太抽象了，我贴代码举例子吧
class TestController extends Controller
{
    public $a = 0;
    public $user;
    public function __construct(Request $request){
        $this->a = rand(1,10000);
        $this->user = Auth::user();  //举例，也可能是别的config
    }

    public function b(){
        return json_encode($this->a);
    }
}
swoole只启一个worker，按照上述代码执行，每次请求结果看到的结果是不会变的，同理，所有人用到的都是一个user，在这里希望Controller这种类在使用完成能从容器里面destroy掉
^_^ 只是个人的一点想法

**Comment by hhxsv5** [comment]
这个可以考虑，建议先临时在系统事件或中间件中去清理。

**Comment by hhxsv5** [comment]
支持请👍，反对请👎。

**Comment by sandersyao** [comment]
@Barbery 虽然是简单的做法清理了Controller，但还是清理不了其他静态变量

**Comment by linxbin** [comment]
👍，考虑到大部分人的开发习惯，我赞成取消Controller对象常驻内存

**Comment by liupeng1993** [comment]
👍，考虑到大部分人的开发习惯，我赞成取消Controller对象常驻内存，大佬救救孩子吧。改了吧

**Comment by tracenull** [comment]
> 👍，考虑到大部分人的开发习惯，我赞成取消Controller对象常驻内存

那就没有性能优势了

**Comment by tracenull** [comment]
建议通过开关控制，再提供一个检测机制 扫描整个项目控制器，有没有单例问题。有问题就把开关打开，没问题可以选择不打开

**Comment by sandersyao** [comment]
@tracenull  性能优势的损失相比fpm应该不多

**Comment by hhxsv5** [comment]
比较理想的代码应该是 `控制器属性、构造方法不包含请求级的数据`，比如用户Id，这种请求级数据只应该只应在Action通过Request对象获取。

**Comment by hhxsv5** [comment]
> @tracenull 性能优势的损失相比fpm应该不多

性能影响其实不大，一个请求只会增加一个控制器的初始化开销。

**Comment by eiixy** [comment]
> 支持此问题的请在`本条评论`上打👍，反对打👎，通过开关控制是否取消打😁。
可以做成黑名单/白名单吗？

**Comment by linxbin** [comment]
> > 👍，考虑到大部分人的开发习惯，我赞成取消Controller对象常驻内存
> 
> 那就没有性能优势了

性能优势还是有的，取消控制器常驻只会额外增加一点点的开销，影响应该不大

**Comment by isjyi** [comment]
建议做成配置，兼容两种人群，通过配置开关来控制控制器的常住状态，如果能再结合黑白名单那就再好不过了

**Comment by hhxsv5** [comment]
> > 支持此问题的请在`本条评论`上打👍，反对打👎，通过开关控制是否取消打😁。
> > 可以做成黑名单/白名单吗？

`config/laravels.php`中增加一项配置：
```php
'destroy_controllers'      => [
    'enable'     => true,
    'white_list' => [
        XxxController:class, //保持常驻的白名单，空列表表示取消所有Controller常驻内存
     ],
],
```

**Comment by hhxsv5** [comment]
[v3.5.6](https://github.com/hhxsv5/laravel-s/releases/tag/v3.5.6)
