### ISSUE TITLE
按照你docker/compose项目配置环境后访问一直502

### ISSUE THREAD

**Issue by u5de6** [hhxsv5/laravel-s#114]
1. Tell us your software version
    How to know it?
    ```Bash
    # PHP
    php -v
    # Swoole
    php --ri swoole
    # Laravel
    grep 'laravel/framework' composer.json
    # Lumen
    grep 'laravel/lumen-framework' composer.json
    ```

    | Software | Version |
    | --------- | --------- |
    | PHP                       | 7.3.0   |
    | Swoole                    | 4.2.9   |
    | LaravelS                  | 3.3.9   |
    | Laravel Framework [local] | 5.5.44  |

2. Detail description about this issue(error/log)

    按照你的[docker-compose](https://github.com/hhxsv5/docker)来部署的开发环境，laravels.com普通的静态资源访问ok，但其他路由访问出现502
    php7容器内访问是正常的 
    ```Bash
    $ winpty docker-compose exec php7 sh
    # curl http://127.0.0.1:5200
    敬请期待...
    #
    ```

3. Give us a `reproducible` code block and `steps`

    ```Bash
    nginx的配置没做其他的调整
    nginx的错误提示：
    [error] 7#7: *31 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: laras.io, request: "GET / HTTP/1.1", upstream: "http://172.18.0.6:5200/", host: "laras.io"
    ```

**Comment by hhxsv5** [comment]
`listen_ip`配置`0.0.0.0`了吗？

**Comment by oknixus** [comment]
请教一个问题，如果是宿主机访问容器中的项目，都必须监听`0.0.0.0`吗？有没有不指定`0.0.0.0`的？
实际测试中 `docker run -p 127.0.0.1:5200:5200 镜像名 sh`时，也是502错误，只有将`listen_ip`改为`0.0.0.0`才能正常访问，在laravel-s中这个是固定设置吗？
谢谢！

**Comment by hhxsv5** [comment]
@oknixus 了解下`0.0.0.0`与`127.0.0.1`区别，Docker 网络模式`host` `bridge`。

**Comment by oknixus** [comment]
区别还是知道的，记得之前MongoDB的一直都是`0.0.0.0`全网监听，后来就发生了几次安全事件，才改为`127.0.0.1`

**Comment by oknixus** [comment]
可以在`.env`文件中设置`LARAVELS_LISTEN_IP=php`，这里的`php`是`docker-compose.yml`中`php`服务的名称
