### ISSUE TITLE
使用overtrue的easywechat时，出现oauth获取不到code的问题

### ISSUE THREAD

**Issue by u5de6** [hhxsv5/laravel-s#115]
1. Tell us your software version
    How to know it?
    ```Bash
    # PHP
    php -v
    # Swoole
    php --ri swoole
    # Laravel
    grep 'laravel/framework' composer.json
    # Lumen
    grep 'laravel/lumen-framework' composer.json
    ```

    | Software | Version |
    | --------- | --------- |
    | PHP                       | 7.3.1   |
    | Swoole                    | 4.2.9   |
    | LaravelS                  | 3.3.9   |
    | Laravel Framework [local] | 5.5.44  |

2. Detail description about this issue(error/log)

    `使用overtrue的easywechat时，oauth授权拿不到code去access_token的问题，出现41008问题`

3. Give us a `reproducible` code block and `steps`

    ```PHP
    //TODO: Your code
    ```

**Comment by u5de6** [comment]
使用中间件的方式来操作oauth的

**Comment by hhxsv5** [comment]
通常情况下，是easywechat拿不到请求Request，需要手动赋值下，已知问题有提及。

**Comment by u5de6** [comment]
嗯  ok  我看到以前有提及   你在配置项里已经加入了需要重新注册的配置
两大神器融合一起 如虎添翼啊  感谢大佬了

**Comment by hhxsv5** [comment]
那你需要在你那个中间件之前赋值request对象给easywechat。
