### ISSUE TITLE
 php artisan laravels publish报错

### ISSUE THREAD

**Issue by EdFuy** [hhxsv5/laravel-s#116]
# PHP
    php -v
7.17
    # Swoole
    php --ri swoole

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.2.12
Built => Jan 10 2019 10:17:01
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.0.2k-fips  26 Jan 2017
pcre => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.fast_serialize => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608

    # Laravel
    grep 'laravel/framework' composer.json
        "laravel/framework": "5.4.*",

error:  Command "laravels" is not defined.

**Comment by hhxsv5** [comment]
1. 请按Issue模板提交问题。
2. Laravel 5.5+支持包自动发现，你的是5.4，需要注册Provider。请认真阅读[安装向导文档](https://github.com/hhxsv5/laravel-s/blob/master/README-CN.md#%E5%AE%89%E8%A3%85)。
