### ISSUE TITLE
新版本laravel-s启动不了

### ISSUE THREAD

**Issue by MrVokia** [hhxsv5/laravel-s#117]
1. Tell us your software version
    How to know it?

    | Software | Version |
    | --------- | --------- |
    | PHP | `7.3.0` |
    | Swoole | `4.2.12` |
    | Lumen | `5.7.6` |
    | hhxsv5/laravel-s | `3.3.9` |

2. Detail description about this issue(error/log)

```
[2019-01-25 16:55:44 $35604.0]	WARNING	swManager_check_exit_status: worker#8 abnormal exit, status=0, signal=11
A bug occurred in Swoole-v4.2.12, please report it.
The Swoole developers probably don't know about it,
and unless you report it, chances are it won't be fixed.
You can read How to report a bug doc before submitting any bug reports:
>> https://github.com/swoole/swoole-src/issues/2000
Please do not send bug reports in the mailing list or personal letters.
The issue page is also suitable to submit feature requests.

[2019-01-25 16:55:44 #35586.16]	WARNING	swServer_signal_handler: Fatal Error: manager process exit. status=0, signal=[Segmentation fault: 11].

```

3. Give us a `reproducible` code block and `steps`

    执行
    ```shell
    php bin/laravels start -i
    ```
    后，swoole.log产生警告，启动流程被挂起(未启动相关进程)。

    之前使用的hhxsv5/laravel-s 3.2.1版本没这个问题，由于处理jwt认证token不失效的问题想尝试一下新版本。

**Comment by MrVokia** [comment]
救命！

**Comment by MrVokia** [comment]
@hhxsv5 不好意思前段时间没看邮件，是这样的：

1. 启动就报错？
> 是的, 启动的时候swoole.log就会产出这两条警告, 这点从启动界面是看不出什么问题的
![image](https://user-images.githubusercontent.com/9609834/52120620-d3447500-2657-11e9-9588-ef9aa26bdfde.png)

2. 在这个错WARNING	swManager_check_exit_status 之前控制台有其他错误吗？
> 没有, console没有任何报错, 每次启动laravels时, swoole.log也仅产出这两条警告, 且警告影响到项目运行。

3. Lumen日志中有发现吗?
> 没有, Lumen未产出任何DEBUG以上级别的错误日志，甚至PHP也未产出任何错误日志。

**Comment by hhxsv5** [comment]
@MrVokia 监听地址要填IP，我看你写的是localhost。

**Comment by MrVokia** [comment]
@hhxsv5 好的，收到~ 我稍后整理一下发上来

**Comment by MrVokia** [comment]
127.0.0.1有试过了


<https://maas.mail.163.com/dashi-web-extend/html/proSignature.html?iconUrl=https%3A%2F%2Fmail-online.nosdn.127.net%2Fqiyelogo%2FdefaultAvatar.png&name=vokia&uid=example%40163.com&ftlId=3&items=%5B%22%E9%82%AE%E7%AE%B1%EF%BC%9Awsadwsadqe%40hotmail.com%22%5D>
[https://mail-online.nosdn.127.net/qiyelogo/defaultAvatar.png]
vokia
邮箱：wsadwsadqe@hotmail.com


Signature is customized by Netease Mail Master<https://mail.163.com/dashi/dlpro.html?from=mail88>

在2019年02月01日 20:09，Xie Biao<mailto:notifications@github.com> 写道：

@MrVokia<https://github.com/MrVokia> 监听地址要填IP，我看你写的是localhost。

**Comment by MrVokia** [comment]
[lumen-laravels-bug-version.zip](https://github.com/hhxsv5/laravel-s/files/2821817/lumen-laravels-bug-version.zip)
@hhxsv5 传上来了, 麻烦你了~

**Comment by hhxsv5** [comment]
Docker中PHP 7.3.0也是正常

![image](https://user-images.githubusercontent.com/7278743/52127745-f417c500-266d-11e9-9392-51f1e7181264.png)
![image](https://user-images.githubusercontent.com/7278743/52127755-009c1d80-266e-11e9-9f09-92a52a0119ba.png)

你尝试删掉vendor，再`composer install`试试。

**Comment by MrVokia** [comment]
谢谢 @hhxsv5 ，我晚上尝试了下：

1. 删除vendor，清理composer cache，再`composer install`不行；
2. 使用pecl移除swoole-4.2.12，重新尝试安装了swoole-4.2.11和swoole-4.2.13版本还是不行；

想安装Valgrind试试看能否追踪tracking，结果：
> configure: error: Valgrind works on Darwin 10.x, 11.x, 12.x, 13.x, 14.x, 15.x, 16.x and 17.x (Mac OS X 10.6/7/8/9/10/11 and macOS 10.12/13)

😂😂😂
