### ISSUE TITLE
请问和swooletw/laravel-swoole这个package有什么区别？

### ISSUE THREAD

**Issue by vergil1989** [hhxsv5/laravel-s#118]
作者你好，最近在了解laravel性能优化相关的方案，看替代方案里有这个包，请问这两个项目有什么差异吗？

**Comment by hhxsv5** [comment]
功能类似，目的都是为了加速laravel
各有优缺点
- laravel-s: 特性多，多个公司上线使用(包括本人所在公司)，QQ群沟通快，更新活跃
- swooletw: 台湾社区维护，支持socket.io

**Comment by vergil1989** [comment]
> 功能类似，目的都是为了加速laravel
> 各有优缺点
> 
> * laravel-s: 特性多，多个公司上线使用(包括本人所在公司)，QQ群沟通快，更新活跃
> * swooletw: 台湾社区维护，支持socket.io

感谢及时回答，支持laravel-s!
