### ISSUE TITLE
auth账户认证串号问题

### ISSUE THREAD

**Issue by ChenSee** [hhxsv5/laravel-s#121]
1. Tell us your software version
    How to know it?

    | Software | Version |
    | --------- | --------- |
    | PHP | `7.2.10` |
    | Swoole | `4.2.12` |
    | LaravelS | `3.3.10` |
    | Laravel/Lumen | `5.7.27` |

2. Detail description about this issue(error/log)

    `auth账户认证串号问题，多端登陆不同账号后触发串号机制。使用laravel-swoole没有问题。但是大大你的功能完善，实在不想弃用。issue所提到的方法一一尝试过了，无法解决。`

3. Give us a `reproducible` code block and `steps`

    ```PHP
    # laravels.php
    'register_providers' => [
        /* middleware service providers */
        Dingo\Api\Provider\DingoServiceProvider::class,
        Dingo\Api\Provider\HttpServiceProvider::class,
        /* auth service providers */
        Illuminate\Auth\AuthServiceProvider::class,
        App\Providers\AuthServiceProvider::class,
        Tymon\JWTAuth\Providers\LaravelServiceProvider::class,
    ],
    ```

    ```PHP
    # EventServiceProvider
    /**
     * Register any events for your application.
     *
     * @return void
     */
    public function boot()
    {
        parent::boot();
        //
        Event::listen('laravels.received_request', function (\Illuminate\Http\Request $req, $app) {
            Facade::clearResolvedInstance('auth');
        });
    }
    ```

**Comment by hhxsv5** [comment]
能否提供一个可重现问题的精简包？

**Comment by ChenSee** [comment]
多谢大佬，麻烦了。https://pan.baidu.com/s/1acAKs3CA3Ihll-Yz07h1Cg	密码:1234

**Comment by pingcheng** [comment]
基本同样的问题哈，清空了auth类，没有效果，但laravel_swoole可以

**Comment by ChenSee** [comment]
@hhxsv5 laravel 5.6 可以使用无这个问题，5.7.27有此问题

**Comment by hhxsv5** [comment]
@ChenSee 不同版本Laravel 存储Auth数据位置不一样，还不好统一处理。

**Comment by ChenSee** [comment]
@hhxsv5 大佬该如何处理这个问题呢？

**Comment by dafa168** [comment]
我也刚发现这个问题，登陆一个账号之后，所有浏览器这个账号默认就登陆了。

**Comment by dafa168** [comment]
我这边laravel 版本是 5.5 LTS

**Comment by hhxsv5** [comment]
@all After a week of debugging, I have passed the test locally for the Laravel/Lumen 5.1-5.8 user authorization. Please try the `Master` branch code(`composer require hhxsv5/laravel-s:dev-master -vvv`), if there is no problem, I will release v3.4.0, thanks for your support.

**Comment by hhxsv5** [comment]
see #109

**Comment by hhxsv5** [comment]
[v3.4.0](https://github.com/hhxsv5/laravel-s/releases/tag/v3.4.0)
