### ISSUE TITLE
Illuminate/Events/Dispatcher 类中的fire 方法 已经被移除

### ISSUE THREAD

**Issue by fifths** [hhxsv5/laravel-s#122]
https://github.com/hhxsv5/laravel-s/blob/4dd99c7416cf678671a4edb0fa647945f37f5e1b/src/Illuminate/Laravel.php#L279

事件
fire 方法

Illuminate/Events/Dispatcher 类中的fire 方法 （在Larevel 5.4中不赞成使用）5.8 已经被移除 了。
你应当使用它的替代方法 dispatch 。

**Comment by hhxsv5** [comment]
谢谢，欢迎提PR。

**Comment by fifths** [comment]
#123  @hhxsv5

**Comment by hhxsv5** [comment]
Merged
