### ISSUE TITLE
为什么生成的swoole-2019-03.log类似这样的log，里面的内容全是空的 ？

### ISSUE THREAD

**Issue by pensacola1989** [hhxsv5/laravel-s#124]
1. Tell us your software version
    How to know it?
    ```Bash
    # PHP
    php -v
    # Swoole
    php --ri swoole
    # Laravel
    grep 'laravel/framework' composer.json
    # Lumen
    grep 'laravel/lumen-framework' composer.json
    ```

    | Software | Version |
    | --------- | --------- |
    | PHP | `TODO` |
    | Swoole | `TODO` |
    | Laravel/Lumen | `TODO` |

2. Detail description about this issue(error/log)

    `TODO`

3. Give us a `reproducible` code block and `steps`

    ```PHP
    //TODO: Your code
    ```

**Comment by hhxsv5** [comment]
如果你使用`Supervisor`托管或者非守护的方式运行，日志是直接输出在标准输出的，即控制台。swoole.log中只记录了`WARNING`级别以上的日志，可以通过修改[log_level](https://wiki.swoole.com/wiki/page/538.html)来调整。

**Comment by dafa168** [comment]
前面我这边产生的日志是出现两份， swoole-xx.log 和lumen-xx.log， 如果系统产生日志，这两个地方都会写入同样的日志， 那么出现这种问题，也是要调整 log_level 吧？

**Comment by hhxsv5** [comment]
@dafa168 不应该哦，swoole-xx.log是由Swoole扩展输出的，lumen-xx.log是由Lumen框架输出，这是两种类型的日志，你可以贴下日志内容。

**Comment by dafa168** [comment]
嗯嗯，今天在家，明天去公司了，我看看日志。
