### ISSUE TITLE
 WARNING swServer_master_onAccept (ERROR 9002): Too many connections [now: 10000]

### ISSUE THREAD

**Issue by pensacola1989** [hhxsv5/laravel-s#126]
1. Tell us your software version
    How to know it?
    ```Bash
    # PHP
    PHP 7.2.13-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Dec  7 2018 08:07:08) ( NTS )
    Copyright (c) 1997-2018 The PHP Group
    Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
        with Zend OPcache v7.2.13-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
        # Swoole
    swoole support => enabled
    Version => 4.2.11
    Author => Swoole Group[email: team@swoole.com]
    coroutine => enabled
    epoll => enabled
    eventfd => enabled
    signalfd => enabled
    cpu_affinity => enabled
    spinlock => enabled
    rwlock => enabled
    pcre => enabled
    mutex_timedlock => enabled
    pthread_barrier => enabled
    futex => enabled
    async_redis => enabled

    Directive => Local Value => Master Value
    swoole.enable_coroutine => On => On
    swoole.aio_thread_num => 2 => 2
    swoole.display_errors => On => On
    swoole.use_shortname => On => On
    swoole.fast_serialize => Off => Off
    swoole.unixsock_buffer_size => 8388608 => 8388608
    # Lumen
        "laravel/lumen-framework": "5.6.4",    ```
    | Software | Version |
    | --------- | --------- |
    | PHP | `7.2` |
    | Swoole | `4.2.11` |
    | Laravel/Lumen | `5.6.4` |

2. Detail description about this issue(error/log)

    `TODO`

3. Give us a `reproducible` code block and `steps`

重现方式：
运行一段时间之后，就会满了，是不是有啥配置不对么》？
看样子不是并发连接数的问题，我们没有那么多连接，
看起来是有些连接没释放，
我们项目重，用到的连接用mysql，redis，没有做特别的配置

**Comment by hhxsv5** [comment]
1. 请按模板提交Issue吧，有效信息太少了。
2. 你是配置了[max_conn](https://wiki.swoole.com/wiki/page/282.html)吗？一般不需配置，系统读取`ulimit -n`配置，[Swoole 报错点](https://github.com/swoole/swoole-src/blob/83cb61e5be2d1d424d6959c03eaf11782c5e002f/src/server/master.cc#L124)。

**Comment by pensacola1989** [comment]
好

**Comment by pensacola1989** [comment]
已经更新模板了。。多谢

**Comment by pensacola1989** [comment]
我没有配置max_conn @hhxsv5

**Comment by pensacola1989** [comment]
因为是运行一段时间之后才会 崩溃，直接502了。。。所以怀疑是connection并没有释放

**Comment by pensacola1989** [comment]
这个其实是个WARNING 按理说应该不影响？，但是其实是502了。。。只能看到swoole-2019-03.log里面有如题的日志

**Comment by hhxsv5** [comment]
1. 根据Swoole这错误提示，说明你的并发连接数上万，达到了它的上限。
2. 检查下Lumen错误日志。
3. 502时 直接 curl http://ip:port看看，你可以加个debug-swoole的接口，返回$server->stats()的统计信息，这样就能试试观察Swoole的情况。
我们公司集成了grafana来看：
![image](https://user-images.githubusercontent.com/7278743/54493432-fdea4480-490a-11e9-89b2-7663e8f73d27.png)
4. 尝试升级下Swoole吧，这应该不是LaravelS层能解决的。

**Comment by hhxsv5** [comment]
@pensacola1989 能否提供一个可重现的例子，最好能用原生Swoole重现。

**Comment by pensacola1989** [comment]
1. 其实我们的并发数，高峰也就80个/min，所以看情况，不是并发的问题，而是慢慢积累起来，也不知道是哪里没有释放掉
2.已经502了。。所以请求的都进不来。。更别提lumen的日志了
3.我试试看。
4.  swoole版本4.2.11还老了？

总之非常感谢你的回复

**Comment by pensacola1989** [comment]
对了。补充一下。502的时候，curl localhost, curl localhost:5200直接没有响应的。。。我是在容器里跑的。。。每次重启重启就ok里。。连接被释放里。就ok了。。

**Comment by hhxsv5** [comment]
你非生产环境下压测，看能不能复现吧。

**Comment by pensacola1989** [comment]
压力测试没测处毛病，请问一下，swoole或者linux可以检查当前连接数的命令么？没搜到:p

**Comment by hhxsv5** [comment]
woole用`stats()`函数，linux用`netstat`命令。
