### ISSUE TITLE
请问如何实现swoole框架WebSocket\Server中的onRequest事件回调?

### ISSUE THREAD

**Issue by lestat220255** [hhxsv5/laravel-s#127]
1. Tell us your software version

    | Software | Version |
    | --------- | --------- |
    | PHP | `7.2.12` |
    | Swoole | `4.3.1` |
    | Laravel | `5.5` |

2. Detail description about this issue(error/log)

你好,我在开发中遇到一个问题想请教一下
目前的场景是需要websocket server主动向部分指定clients推送消息。但在文档中的`WebSocketService`只看到`onOpen`,`onMessage`,`onClose`几个事件,我希望通过server端主动触发批量推送操作(服务端在特定时候主动向websocket发起http请求来触发websocket中的[onRequest](https://wiki.swoole.com/wiki/page/397.html#entry_h2_0)事件实现向指定的clients发起消息推送),请问在laravel-s中推荐怎么实现?

**Comment by hhxsv5** [comment]
LaravelS 中默认启动 Http Server，但当开启 WebSocket 后启动的是 WebSocket Server，然后绑定的onRequest 事件到 Laravel 的路由中。你需要主动推送消息，你可以在Controller中拿到 Swoole Server 对象app('swoole')，就能遍历得到FD并且push发送 app('swoole')->push()。

也就是说  onRequest 事件走 Laravel 的路由，WebSocket 的其他事件(onOpen onMessage onClose)走你配置的 handler。

**Comment by lestat220255** [comment]
看来是我理解不到位...按你的方法已经解决了,感谢!

**Comment by honglibin** [comment]
请问通过app('swoole')获取到swoole实例后，如何遍历得到FD，swoole小白，求大大请教~

**Comment by honglibin** [comment]
> 看来是我理解不到位...按你的方法已经解决了,感谢!
请问您是如何得到fd的呀

**Comment by honglibin** [comment]
知道了，原谅我文档没看清楚，Server->getClientList()就能拿到啦

**Comment by JeaNile** [comment]
```php
$swoole = app('swoole');
// 遍历所有 websocket 连接用户的 fd，给所有用户推送
foreach ($swoole->connections as $fd) {
    // 如果连接不可用则忽略
    if (!$swoole->isEstablished($fd)) {
        continue;
    }
    $swoole->push($fd,time());
}
```
