### ISSUE TITLE
Docker里面启动 定时脚本不工作

### ISSUE THREAD

**Issue by handsomedeveloper** [hhxsv5/laravel-s#128]
### 本地环境
![image](https://user-images.githubusercontent.com/20430369/54984212-5abfbc00-4fe9-11e9-89bf-4f403d7bf2c6.png)

### Docker运行情况 无任何输出
![image](https://user-images.githubusercontent.com/20430369/54984262-71661300-4fe9-11e9-8033-22de633cd31b.png)

### 本地运行情况，虽然报错了 但是定时脚本在跑
![image](https://user-images.githubusercontent.com/20430369/54984382-bb4ef900-4fe9-11e9-89ec-906b8c474bae.png)

是否是因为两个环境php版本不一样

**Comment by hhxsv5** [comment]
这看不出来问题，要报错才能看到在跑？有可能定时任务本身没有错误，没有输出，你应该尝试 Log 下。顺便说下，请按模板提交Issue。

**Comment by handsomedeveloper** [comment]
我有打log的，本地会产生log， Docker里面没有。

**Comment by hhxsv5** [comment]
真是疑难杂症，加QQ群`62075835`详聊。

**Comment by handsomedeveloper** [comment]
问题已经解决，xdebug和swoole冲突了，多谢帮助
