### ISSUE TITLE
Deliver tasks not working after v3.4.1

### ISSUE THREAD

**Issue by ibrunotome** [hhxsv5/laravel-s#129]
1. Tell us your software version

    | Software | Version |
    | --------- | --------- |
    | PHP | `7.2.16` |
    | Swoole | `4.2.13` |
    | Laravel/Lumen | `5.8.7` |

2. Detail description about this issue(error/log)

The last hhxsv5/laravel-s that works here is v3.4.0, after this version (v3.4.1 and v3.4.2), I receive the below error when I try to deliver a task:

<img width="1291" alt="Screenshot 2019-03-26 20 37 29" src="https://user-images.githubusercontent.com/4256471/55040541-9b2e3280-5007-11e9-813e-b18ead851366.png">

3. Give us a `reproducible` code block and `steps`

```PHP
Task::deliver(new DispatchOrderHistoryUpdatedEvent($order));
```

And in the Event

```PHP
use Hhxsv5\LaravelS\Swoole\Task\Task;

class DispatchOrderHistoryUpdatedEvent extends Task
{
    private $order;

    public function __construct(Order $order)
    {
        $this->order = $order;
    }

    public function handle()
    {
        broadcast(new OrderHistoryUpdatedEvent($this->order));
    }
}

```

**Comment by ibrunotome** [comment]
Ok, I think this is related to `'enable_coroutine_runtime' => true,` as I was trying to dispatch an asynchronous event from an observer (but on v3.4.0 it works).

**Comment by ibrunotome** [comment]
Also, this package [fntneves/laravel-transactional-events](https://github.com/fntneves/laravel-transactional-events) doesn't work anymore after v3.4.1 of your package. I know that is not related to your package, but it works normally in the v3.4.0 and I think that you can help, because both of the packages are essentially for me.

`[27-Mar-2019 00:36:04 UTC] PHP Fatal error:  Uncaught TypeError: Argument 2 passed to Neves\Events\TransactionalDispatcher::__construct() must be an instance of Illuminate\Events\Dispatcher, instance of Neves\Events\TransactionalDispatcher given, called in /app/vendor/fntneves/laravel-transactional-events/src/Neves/Events/EventServiceProvider.php on line 29 and defined in /app/vendor/fntneves/laravel-transactional-events/src/Neves/Events/TransactionalDispatcher.php:69`

**Comment by hhxsv5** [comment]
This issue is a bit complicated, I compared the two tags, here is the difference between [v3.4.0-v3.4.2](https://github.com/hhxsv5/laravel-s/compare/v3.4.0...hhxsv5:v3.4.2),  but did not find anything.
I noticed that the constructor of DispatchOrderHistoryUpdatedEvent is an Order object. Try changing it to an array?

**Comment by ibrunotome** [comment]
Hi @hhxsv5, I will try, but the Task is a minor problem, can you help me find why your package is influencing the fntneves/laravel-transactional-events?

**Comment by ibrunotome** [comment]
If I remove the type EventDispatcher from this:

```php
    /**
     * Create a new transactional event dispatcher instance.
     *
     * @param  \Illuminate\Database\ConnectionResolverInterface  $connectionResolver
     * @param  \Illuminate\Contracts\Events\Dispatcher  $eventDispatcher
     */
    public function __construct(ConnectionResolverInterface $connectionResolver, EventDispatcher $eventDispatcher)
    {
        $this->connectionResolver = $connectionResolver;
        $this->dispatcher = $eventDispatcher;
        $this->setUpListeners();
    }
```

to this

```php
    /**
     * Create a new transactional event dispatcher instance.
     *
     * @param  \Illuminate\Database\ConnectionResolverInterface  $connectionResolver
     * @param  \Illuminate\Contracts\Events\Dispatcher  $eventDispatcher
     */
    public function __construct(ConnectionResolverInterface $connectionResolver, $eventDispatcher)
    {
        $this->connectionResolver = $connectionResolver;
        $this->dispatcher = $eventDispatcher;
        $this->setUpListeners();
    }
```

It works normally, I know that you don't need to support issues with third parties, but I would like to know why the swoole package is influencing a third party package.

**Comment by hhxsv5** [comment]
I think package `laravel-transactional-events` is not compatible with Swoole Server, because the `events` instance is a singleton, but `laravel-transactional-events` [extends](https://github.com/fntneves/laravel-transactional-events/blob/master/src/Neves/Events/EventServiceProvider.php#L28) and overwrites the original `events` instance.

So you can try to write a [Cleaner](https://github.com/hhxsv5/laravel-s/blob/master/Settings.md) and `reset` the `events` instance for every request.

```php
class EventsCleaner implements CleanerInterface
{
    public function clean(Container $app, Container $snapshot)
    {
        $app->forgetInstance('events');
        Facade::clearResolvedInstance('events');
    }
}
```

**Comment by ibrunotome** [comment]
Tested, the problem continues, what I don't understand is that it only happens after v3.4.1.
