### ISSUE TITLE
Performance decreased 10 times after upgrade to v3.4.2

### ISSUE THREAD

**Issue by zjuxxd** [hhxsv5/laravel-s#130]
1. Tell us your software version
    How to know it?
    ```Bash
    # PHP
    php -v
    # Swoole
    php --ri swoole
    # Laravel
    grep 'laravel/framework' composer.json
    # Lumen
    grep 'laravel/lumen-framework' composer.json
    ```

    | Software | Version |
    | --------- | --------- |
| PHP                       | 7.1.24  |
| Swoole                    | 4.3.1   |
| LaravelS                  | 3.4.2   |
| Laravel Framework [local] | 5.5.44  |

2. Detail description about this issue(error/log)

    After upgrade from v3.0.5 to v3.4.2, the performance decreased by about 10 times. 

3. Give us a `reproducible` code block and `steps`

[blog.tar.gz](https://github.com/hhxsv5/laravel-s/files/3013112/blog.tar.gz)

1. With the attached code sample, the API: /api/test/2 will have throughput about 700/s
2. upgrade with command: php composer upgrade hhxsv5/laravel-s, it will upgrade laravel-s (v3.0.5 => v3.4.2), the the config file is override during upgrade
3. change the config/laravels.php, change the listen_ip to 0.0.0.0
4. The same benchmark in step1 will only 70/s

**Comment by hhxsv5** [comment]
Because Coroutine and Coroutine Runtime are turned `ON` in `v3.0.5`  by default, but they are turned `OFF` in `v3.4.2` by default. Please see [readme](https://github.com/hhxsv5/laravel-s/blob/master/README.md#coroutine).

**Comment by zjuxxd** [comment]
@hhxsv5 thanks for the feedback. After enable the coroutine settings, the performance is back to the same as v3.0.5 in above sample code. But when I apply the same change on my business project, the performance is slower than nginx+php-fpm. When laravel is run under nginx+php-fpm, the throughput is about 15/s, CPU is 90% loaded. But when run the laravel  with laravel-s+swoole, the performance is about 6/s(enable_coroutine_runtime and enable_coroutine are set to true). And CPU load is only about 33%. Increase the concurrency in jmeter will not increase the CPU load. The throughput have no big difference. Meanwhile, I see following error in the console:
`
+---------------------------+---------+
| Component                 | Version |
+---------------------------+---------+
| PHP                       | 7.1.24  |
| Swoole                    | 4.3.1   |
| LaravelS                  | 3.4.2   |
| Laravel Framework [stage] | 5.5.44  |
+---------------------------+---------+
>>> Protocols
+-----------+--------+-------------------+--------------+
| Protocol  | Status | Handler           | Listen At    |
+-----------+--------+-------------------+--------------+
| Main HTTP | On     | Laravel Framework | 0.0.0.0:5200 |
+-----------+--------+-------------------+--------------+
>>> Feedback: https://github.com/hhxsv5/laravel-s
[2019-03-28 02:48:54] [TRACE] Swoole is running, press Ctrl+C to quit.
[2019-03-28 02:49:04] [ERROR] worker[1] error: exitCode=0, signal=11
[2019-03-28 02:49:04] [ERROR] worker[0] error: exitCode=0, signal=11
[2019-03-28 02:49:04] [ERROR] onRequest: Uncaught exception "TypeError"([0]Argument 1 passed to Hhxsv5\LaravelS\LaravelS::convertRequest() must be an instance of Hhxsv5\LaravelS\Illuminate\Laravel, null given, called in path/vendor/hhxsv5/laravel-s/src/LaravelS.php on line 139) at path/vendor/hhxsv5/laravel-s/src/LaravelS.php:127,
#0 path/vendor/hhxsv5/laravel-s/src/LaravelS.php(139): Hhxsv5\LaravelS\LaravelS->convertRequest(NULL, Object(Swoole\Http\Request))
#1 {main}
`

Any suggestion on the problem?

**Comment by hhxsv5** [comment]
This is an error caused by using coroutines, because code execution is not sequential in coroutines, global variables and static variables are easily contaminated, and they need to be isolated by coroutine ID. It is not recommended to use coroutines in Laravel. But it is relatively safe to use coroutines in custom processes and cron jobs.

**Comment by zjuxxd** [comment]
This is a big limitation and looks I can not use it in my project.  :-(

**Comment by hhxsv5** [comment]
Improving performance mainly depends on three points:
1.Swoole Http Server performance is much higher than Nginx+FPM.
2.Common resources are resident in memory, only need to be initialized once.
3.Swoole has many features that are not available under FPM.
