### ISSUE TITLE
Sessions and Validations

### ISSUE THREAD

**Issue by prmdeveloper** [hhxsv5/laravel-s#131]
# PHP

PHP 7.1.22 (cli) (built: Sep 12 2018 07:22:13) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.1.22, Copyright (c) 1999-2018, by Zend Technologies

# Swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.3.1
Built => Mar 22 2019 11:17:41
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
openssl => OpenSSL 1.0.2k-fips  26 Jan 2017
http2 => enabled
pcre => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608    

# Laravel

laravel/framework": "5.6.*

# Detail description about this issue(error/log)

After running the project based on the Swolle server, and setting the (cleaners) setting in laravels.php, all validation returns are not processed.

Sessions are behaving normally, keeping the user logged on or logged off, however after login all of the validations of the forms are executed but the returns of the errors are not visualized in the forms.

# Give us a `reproducible` code block and `steps`

>Blade
 
```
 @if ($errors->has('end_period'))
      <strong>
          <label id="end_period-error" class="help-block" for="end_period"><i class="fa 
                  fa-info-circle" aria-hidden="true"></i>{{ $errors->first('end_period') }} 
            </label>
        </strong>
  @endif
```

>PHP

The back-end returns the as validation error, however the formal does not draw this block warning the user about the error.
 I believe that temporary session variables are being cleaned, however these should survive for the validations and for the redirects as in the example: (with)

`return redirect()->guest(route('users.profile'))->with('UnauthorizedAccess', 'true');`

**Comment by prmdeveloper** [comment]
Simple Simulation

1 - Create a new laravel project

2 - Create authentication pattern
        make: auth

3 - Include package hhxsv5 / laravel-s

4 - Up server laravel-s

5 - Try to log in several times with the wrong data.

6 - Check that after the first attempt the error indication is not being displayed.

**Comment by hhxsv5** [comment]
![image](https://user-images.githubusercontent.com/7278743/55290059-cc8c7100-5400-11e9-82ca-e5e35edb4c97.png)
I have not reproduced this issue here, could you please give me a zip file?

**Comment by hhxsv5** [comment]
Fixed in [903a317](https://github.com/hhxsv5/laravel-s/commit/903a31713e7a97320be914c3dc088609451e811e), please try dev-master.

**Comment by prmdeveloper** [comment]
Perfect, thank you.

**Comment by hhxsv5** [comment]
You are welcome, release [v3.4.3](https://github.com/hhxsv5/laravel-s/releases/tag/v3.4.3).
