### ISSUE TITLE
formData 文件无法接收

### ISSUE THREAD

**Issue by wslsq** [hhxsv5/laravel-s#132]
1. Tell us your software version
    php 7.3.3
    swoole 4.30
   laravels 3.4.2
   larevel 5.5.45
2. Detail description about this issue(error/log)
在线代码格式错乱，麻烦看看附件，谢谢

**Comment by wslsq** [comment]
[index.txt](https://github.com/hhxsv5/laravel-s/files/3016251/index.txt)
代码在附件，谢谢！

**Comment by hhxsv5** [comment]
经过测试，可以上传。是否你的文件大小达到Swoole[上限](https://github.com/hhxsv5/laravel-s/blob/master/KnownIssues-CN.md#%E5%A4%A7%E5%B0%8F%E9%99%90%E5%88%B6)？
```php
public function uploadFile(Request $request)
{
    if ($request->hasFile('file1')) {
        $file = $request->file('file1');
        $file->move(storage_path(), 'test.jpg');
        echo 'src: ', $file->getPath(), PHP_EOL;
        echo $file->getFilename() . ' uploaded into ' . storage_path('test.jpg');
    } else {
        echo 'no file';
    }
}
```
![image](https://user-images.githubusercontent.com/7278743/55133053-561d1400-515f-11e9-8b05-4877ddc86fbe.png)

**Comment by wslsq** [comment]
经查是上传的文件 中文名太长 导致，是laravel本身的问题。
打扰了作者，实在不好意思。
