### ISSUE TITLE
扩展包 sentry/sentry 无法正常工作

### ISSUE THREAD

**Issue by SakyaVarro** [hhxsv5/laravel-s#133]
1. Tell us your software version
    | Software | Version |
    | --------- | --------- |
    | PHP | `7.2.16` |
    | Swoole | `4.3.1` |
    | Laravel/Lumen | `5.5` |

2. Detail description about this issue(error/log)

    扩展包 [sentry/sentry](https://packagist.org/packages/sentry/sentry) 无法正常工作。

    当程序发生异常时，在方法 `\Sentry\Transport\HttpTransport::send` 中会发送一次异步 curl 请求来告知 sentry 发生了异常，然后可以在 sentry 控制台中看到具体的异常信息。使用 php-fpm 的情况下，一切都正常运行。但在使用 swoole 的情况下，这次异步 curl 请求似乎没发出去？以下是来自扩展包 [sentry/sentry] 的相关代码：
```php
    vendor/sentry/sentry/src/Transport/HttpTransport.php:72

    public function send(Event $event): ?string
    {
        $request = $this->requestFactory->createRequest(
            'POST',
            sprintf('/api/%d/store/', $this->config->getProjectId()),
            ['Content-Type' => 'application/json'],
            JSON::encode($event)
        );

        $promise = $this->httpClient->sendAsyncRequest($request);

        // This function is defined in-line so it doesn't show up for type-hinting
        $cleanupPromiseCallback = function ($responseOrException) use ($promise) {
            $index = array_search($promise, $this->pendingRequests, true);

            if (false !== $index) {
                unset($this->pendingRequests[$index]);
            }

            // 这行是我加的测试代码，在 swoole 下，没有任何信息输出到标准输出
            dump($responseOrException);

            return $responseOrException;
        };

        $promise->then($cleanupPromiseCallback, $cleanupPromiseCallback);

        $this->pendingRequests[] = $promise;

        return $event->getId();
    }
```

**Comment by hhxsv5** [comment]
请贴出异常信息。

**Comment by SakyaVarro** [comment]
不好意思，没描述清楚。

我在某处写了一行错误的代码，所以在运行时会报错：

![image](https://user-images.githubusercontent.com/24671424/55300326-83bcd280-5469-11e9-855b-4efda09a90d2.png)
![image](https://user-images.githubusercontent.com/24671424/55300365-acdd6300-5469-11e9-83ed-aac9493641d0.png)

现在根据 [sentry/sentry](https://packagist.org/packages/sentry/sentry) 的文档安装，添加一下代码到 `App/Exceptions/Handler.php` 并配置好配置文件 ：
```php
public function report(Exception $exception)
{
    if (app()->bound('sentry') && $this->shouldReport($exception)){
        app('sentry')->captureException($exception);
    }

    parent::report($exception);
}
```

现在的问题就在于，当我使用 php-fpm 的方式跑这段异常代码时，我在 sentry 的控制台中可以看到发生了什么异常：
![image](https://user-images.githubusercontent.com/24671424/55300510-63414800-546a-11e9-96cb-c9471483083a.png)

而使用 swoole 跑这段代码时，sentry 后台不会收到异常通知。

扩展包 sentry 的工作大概就是当程序发生异常时，使用 guzzle 发送一次异步 curl 请求到 sentry 服务器，然后可以在 sentry 的控制台中展示出异常的具体信息。

laravel-s 本身没有发生异常，只是我不太明白是什么原因导致 sentry 无法正常工作，或者用什么方法可以使它能正常工作。

**Comment by hhxsv5** [comment]
swoole下调试最好用Log，dump不一定能输出。然后确认下能否走到`sendAsyncRequest`。
