### ISSUE TITLE
memory usage increase to 140MB from 30MB momently 

### ISSUE THREAD

**Issue by jiangruichang** [hhxsv5/laravel-s#136]
1. Tell us your software version
php 7.0.22
swoole 2.0.6
laravel 5.2.29
laravels 3.3.10

2. Detail description about this issue(error/log)

when we malloc an new big array,about 2MB, the process memory usage from 30MB  increase to 140MB

**Comment by hhxsv5** [comment]
Can you give us a code example?

**Comment by jiangruichang** [comment]
> Can you give us a code example?

linux process memory 30.55MB
php memory_get_usage 12.43MB

$accounts = self::where('device_id',$device_id)
            ->lists('account_id')->toArray();

linux process memory 140.32MB
php memory_get_usage 14.83MB

after this DB array operation , linux worker memory usage increase to 140MB

**Comment by hhxsv5** [comment]
Could you please check the length of array ?
How many rows of data are in the table ? try limit ?

**Comment by jiangruichang** [comment]
> Could you please check the length of array ?
> How many rows of data are in the table ? try limit ?

thanks, already resolved by limit length of array , but how can linux process malloc 100MB memory for a small packed array um. about 50 thousand length

**Comment by hhxsv5** [comment]
[memory-limit](https://www.php.net/manual/en/ini.core.php#ini.memory-limit) is `128M` default, so your `100M` is expected effect. But [memory_get_usage](https://www.php.net/manual/en/function.memory-get-usage.php) does not track memory that is not allocated by `emalloc()`, so memory_get_usage is `14M`.

**Comment by jiangruichang** [comment]
> [memory-limit](https://www.php.net/manual/en/ini.core.php#ini.memory-limit) is `128M` default, so your `100M` is expected effect. But [memory_get_usage](https://www.php.net/manual/en/function.memory-get-usage.php) does not track memory that is not allocated by `emalloc()`, so memory_get_usage is `14M`.

thanks a lot！
