### ISSUE TITLE
祼测laravel5.5 感觉性能没有大的提升，是我的操作方式有误么？

### ISSUE THREAD

**Issue by boyisire** [hhxsv5/laravel-s#137]
想在生产环境中使用swoole,我用laravel-s做测试时，发现性能没有大的变化，是我的使用方法不正确么？（所有配置都用的默认值）

======================================

1. 配置信息：
+---------------------------+---------+
| Component                 | Version |
+---------------------------+---------+
| PHP                       | 7.1.27  |
| Swoole                    | 4.3.1   |
| LaravelS                  | 3.4.4   |
| Laravel Framework [local] | 5.5.45  |
+---------------------------+---------+

2. 测试详情
2.1 空项目 
注：test方法中，就写了一个"return 0"
<1>. siege -c 100 -r 20 "https://m.mydev.com/test"
Transactions: 2000 hits 
Availability: 100.00 % 
Elapsed time: 19.17 secs 
Data transferred: 0.04 MB 
Response time: 0.54 secs 
Transaction rate: 104.33 trans/sec 
Throughput: 0.00 MB/sec 
Concurrency: 55.88 
Successful transactions: 2000 
Failed transactions: 0 
Longest transaction: 15.16 
Shortest transaction: 0.03

<2>. siege -c 100 -r 20 "https://m.mydev.com/test"
Transactions: 2000 hits 
Availability: 100.00 % 
Elapsed time: 15.24 secs 
Data transferred: 0.04 MB 
Response time: 0.57 secs 
Transaction rate: 131.23 trans/sec 
Throughput: 0.00 MB/sec 
Concurrency: 74.83 
Successful transactions: 2000 
Failed transactions: 0 
Longest transaction: 7.17 
Shortest transaction: 0.04

<3>. siege -c 100 -r 20 "https://m.mydev.com/test"
Transactions: 2000 hits 
Availability: 100.00 % 
Elapsed time: 17.13 secs 
Data transferred: 0.04 MB 
Response time: 0.58 secs 
Transaction rate: 116.75 trans/sec 
Throughput: 0.00 MB/sec 
Concurrency: 67.96 
Successful transactions: 2000 
Failed transactions: 0 
Longest transaction: 7.72 
Shortest transaction: 0.04

2.2 使用Laravel-s后
<1>. siege -c 100 -r 20 "https://m.mydev.com/test"
Transactions:	2000 hits
Availability:	100.00 %
Elapsed time:	16.36 secs
Data transferred:	0.00 MB
Response time:	0.57 secs
Transaction rate:	122.25 trans/sec
Throughput:	0.00 MB/sec
Concurrency:	69.71
Successful transactions: 2000
Failed transactions:	0
Longest transaction:	14.03
Shortest transaction:	0.03

<2>. siege -c 100 -r 20 "https://m.mydev.com/test"
Transactions:	2000 hits
Availability:	100.00 %
Elapsed time:	18.47 secs
Data transferred:	0.00 MB
Response time:	0.51 secs
Transaction rate:	108.28 trans/sec
Throughput:	0.00 MB/sec
Concurrency:	54.94
Successful transactions: 2000
Failed transactions:	0
Longest transaction:	13.78
Shortest transaction:	0.03

<3>. siege -c 100 -r 20 "https://m.mydev.com/test"
Transactions:	2000 hits
Availability:	100.00 %
Elapsed time:	18.13 secs
Data transferred:	0.00 MB
Response time:	0.53 secs
Transaction rate:	110.31 trans/sec
Throughput:	0.00 MB/sec
Concurrency:	58.38
Successful transactions: 2000
Failed transactions:	0
Longest transaction:	14.19
Shortest transaction:	0.03

**Comment by hhxsv5** [comment]
你确认请求已经走到 `Swoole` 上了？

**Comment by boyisire** [comment]
> 你确认请求已经走到 `Swoole` 上了？
swoole停了，接口就报502了。而且压测试，ps -aux，能看到进程有消费变化。

**Comment by boyisire** [comment]
Nginx 配置：

**Comment by hhxsv5** [comment]
测试项目打包，发来看看。

**Comment by hhxsv5** [comment]
压测注意事项：
1. 先阅读：https://wiki.swoole.com/wiki/page/62.html
2. 注意各个中间件（包括全局中间件和路由中间件），默认的Session中间件基于文件，IO性能非常差。
3. 压空接口，目的在于对比框架的消耗，对比FPM，快慢都是相对的。
4. 如果代码中有类似`sleep`的同步阻塞操作，那QPS自然不会高。
5. 压测时最好在内网测试，避免网络带宽因素影响结果。

![image](https://user-images.githubusercontent.com/7278743/56013522-ac738080-5d23-11e9-93d9-b2fda5e36523.png)

![image](https://user-images.githubusercontent.com/7278743/56013451-64ecf480-5d23-11e9-9c8a-e18661475a36.png)
