### ISSUE TITLE
定时任务之间是否是异步的呢？

### ISSUE THREAD

**Issue by honglibin** [hhxsv5/laravel-s#143]
我在代码里设置了4个定时任务，我本来以为任务之间的异步执行的，但是我发现其中一个任务因为执行时间过长，导致其他定时任务没有执行，要等到该任务执行完成后，其他任务才会继续执行。

**Comment by hhxsv5** [comment]
参考[tick函数](https://wiki.swoole.com/wiki/page/412.html)。

**Comment by honglibin** [comment]
> 参考[tick函数](https://wiki.swoole.com/wiki/page/412.html)。

好的，谢谢
