### ISSUE TITLE
Failed CSRF validation returns 200 instead of 419. 

### ISSUE THREAD

**Issue by ayaka209** [hhxsv5/laravel-s#145]
1. Tell us your software version

    | Software | Version |
    | --------- | --------- |
    | PHP | `7.2` |
    | Swoole | `4.3.4` |
    | Laravel/Lumen | `5.7` |

2. Detail description about this issue(error/log)

Failed CSRF validation returns 200 instead of 419. 

It shows "Page Expired" error correctly, but status code should be 419, It's 200 now.

3. Give us a `reproducible` code block and `steps`

just post anything without csrf token to a route

**Comment by hhxsv5** [comment]
Swoole Http Server does not support HTTP status code 419.

```php
$http = new Swoole\Http\Server('127.0.0.1', 5200);
$http->on('request', function (\Swoole\Http\Request $request, \Swoole\Http\Response $response) {
    $response->status(419);
    $response->end('Test for HTTP 419');
});
$http->start();
```

**Comment by ayaka209** [comment]
In this case, failing CSRF validation should return other error code instead of being 200

**Comment by hhxsv5** [comment]
I suggest you submit the issue to [Swoole](https://github.com/swoole/swoole-src/issues/new).

**Comment by ayaka209** [comment]
ok, thank you.
