### ISSUE TITLE
5.1.31的laravel版本是不支持么？

### ISSUE THREAD

**Issue by we3613040** [hhxsv5/laravel-s#15]
如题，目前路由不起作用，还有就是，这个东西怎么设置env参数，比如用fastcgi的话是可以设置fastcgi_param这个的，意思是不写在项目里，在服务端设置

**Comment by hhxsv5** [comment]
1. 支持5.1-5.6
2. env和laravel一样设置在.env文件

**Comment by hhxsv5** [comment]
路由不起作用考虑清除路由缓存和重启worker进程。

**Comment by hhxsv5** [comment]
若依然不能解决，加QQ群交流 698480528

**Comment by we3613040** [comment]
好的，谢谢

**Comment by soloqi** [comment]
> 3\. env和laravel一样设置在.env文件

还是没明白多env文件怎么指定，就是之前的--env=test 这种

**Comment by soloqi** [comment]
> > 3. env和laravel一样设置在.env文件
> 
> 还是没明白多env文件怎么指定，就是之前的--env=test 这种



> @soloqi 什么多env？请把问题上下文交代清楚

.env.dev  开发环境配置
.env.test  测试环境
.env.production 线上环境
通过laravel自己的artisan  可以 根据--env=xxx来指定加载配置文件 
现在的启动模式好像没有env选择了

**Comment by hhxsv5** [comment]
#110 V3.3.X 确实不支持了，没考虑过`--env`来指定配置文件，这个不难，这个版本加上。

**Comment by hhxsv5** [comment]
@soloqi [v3.3.8](https://github.com/hhxsv5/laravel-s/releases/tag/v3.3.8) 开启支持`--env`。

**Comment by soloqi** [comment]
> @soloqi [v3.3.8](https://github.com/hhxsv5/laravel-s/releases/tag/v3.3.8) 开启支持`--env`。

厉害了 ^_^
