### ISSUE TITLE
Add support to inotifywait

### ISSUE THREAD

**Issue by drzippie** [hhxsv5/laravel-s#152]
Add support to inotifywait

inotifywait is a command (bundled  in inotify-tools) available for Linux.

**Comment by hhxsv5** [comment]
Thanks for your nice PR!
The `--event` only contains `modify`?
Is `create,delete,modify,move` better?

**Comment by drzippie** [comment]
Yes, Done!
https://github.com/hhxsv5/laravel-s/pull/153/commits/fa0c3894c63f8cf80e7f0f7f3c3e11edc3f27024

**Comment by hhxsv5** [comment]
Merged.
