### ISSUE TITLE
项目使用LaravelS后，数据库的事物会锁住，而php-fpm没有问题

### ISSUE THREAD

**Issue by cheerego** [hhxsv5/laravel-s#161]
1. Tell us your software version
    | Software | Version |
    | --------- | --------- |
    | PHP | `7.2.19` |
    | Swoole | `4.3.5` |
    | Laravel/Lumen | `5.4.*` |

2. Detail description about this issue(error/log)

![image](https://user-images.githubusercontent.com/13394349/60483661-05bad280-9cc9-11e9-94b9-853a8e34556a.png)

将公司项目从迁移到swoole后，就会报这个错。最后没有办法，切回的fpm这个问题就没有了。

3. Give us a `reproducible` code block and `steps`

    ```PHP
    //TODO: Your code
    ```

**Comment by hhxsv5** [comment]
数据库连接是单例，请检查是否有开启的事务 没有被提交或回滚。

**Comment by cheerego** [comment]
检查过，不存在没有commit或者rollback 的情况

**Comment by liulianjun1995** [comment]
我之前也有这个错误 就是因为事务没有提交或回滚

**Comment by cheerego** [comment]
@liulianjun1995 我的php-fpm 运行没有这个问题。你也是这样吗?

**Comment by xeonselina** [comment]
经过我们检查，的确是因为事务没有commit和回滚，而是函数直接return了导致的

**Comment by hhxsv5** [comment]
@xeonselina 可以提供下错误的示例，便于其他人发现问题。

**Comment by xeonselina** [comment]
我们出错的代码类似于这样
`
DB::beginTransaction();
try{
  if($userIsNotValid){
    return false;
  }
  DB::doSomeInsertOrUpdate();
  DB::commit();
}
catch(\Exception $e){
  throw $e;
}
`

**Comment by August2012** [comment]
> 数据库连接是单例，请检查是否有开启的事务 没有被提交或回滚。

数据库操作中目前发现一个问题：
用户A  发生如
```
DB::beginTransaction();
try{
  if($userIsNotValid){
    return false;
  }
  DB::doSomeInsertOrUpdate();
  DB::commit();
}
catch(\Exception $e){
  DB::rollback();
  throw $e;
}
```
此时数据库事务锁住了，
用户B，C，D等提交事务，对于他们来讲，数据显示正常，数据库的ID也占用了，但是没有真实提交到数据库。

如果重启laravelS服务, 此时 B，C，D的数据会丢失

请问改怎么解决
 @hhxsv5 @cheerego

**Comment by cheerego** [comment]
```
DB::beginTransaction();
try{
  if($userIsNotValid){
   DB::rollback(); 
    return false;
  }
  DB::doSomeInsertOrUpdate();
  DB::commit();
}
catch(\Exception $e){
  DB::rollback();
  throw $e;
}
```

在 if 的里面

@August2012

**Comment by August2012** [comment]
> ```
> DB::beginTransaction();
> try{
>   if($userIsNotValid){
>    DB::rollback(); 
>     return false;
>   }
>   DB::doSomeInsertOrUpdate();
>   DB::commit();
> }
> catch(\Exception $e){
>   DB::rollback();
>   throw $e;
> }
> ```
> 
> 在 if 的里面
> 
> @August2012

恩恩，谢谢，您说的这种处理是没问题的。

就想请教下，如果发生了这种情况（比如开发代码考虑不周等情况）。没有走到rollback, 数据库死锁。
该如何操作才能不造成数据丢失。
我们遇到情况： 重启服务，系统回复正常，数据丢失;  不重启服务，数据库 go away 宕机~
不知道有没有办法隔离~

**Comment by L-Y** [comment]
> > ```
> > DB::beginTransaction();
> > try{
> >   if($userIsNotValid){
> >    DB::rollback(); 
> >     return false;
> >   }
> >   DB::doSomeInsertOrUpdate();
> >   DB::commit();
> > }
> > catch(\Exception $e){
> >   DB::rollback();
> >   throw $e;
> > }
> > ```
> > 
> > 
> > 在 if 的里面
> > @August2012
> 
> 恩恩，谢谢，您说的这种处理是没问题的。
> 
> 就想请教下，如果发生了这种情况（比如开发代码考虑不周等情况）。没有走到rollback, 数据库死锁。
> 该如何操作才能不造成数据丢失。
> 我们遇到情况： 重启服务，系统回复正常，数据丢失; 不重启服务，数据库 go away 宕机~
> 不知道有没有办法隔离~

我也遇到数据丢失的问题

**Comment by tai1030** [comment]
#270
