### ISSUE TITLE
原本的laravel项目在引入本包用swoole启动后，发现请求参数会“串”

### ISSUE THREAD

**Issue by MukuroSama** [hhxsv5/laravel-s#164]
比如请求接口/api?param=a
结果正常
然后请求/api
结果也正常
再重复请求一次/api
发现结果是/api?param=a的内容（此时确认请求的参数没有问题，就是接口返回了“之前请求过的参数的内容”）

时有时无，但不是偶然，而是非常容易触发！

我用的laravel是5.5，加上了dingo api包。

**Comment by hhxsv5** [comment]
1.首先`dingoapi`不支持常驻内存模式，不兼容`Swoole` #28 ；
2.请新建一个工程，不用`dingoapi`，验证是否有问题，如果有，请上传。

**Comment by MukuroSama** [comment]
这不是新项目选型，而是老项目为了提高并发而加上的swoole，已经没办法剔除掉dingo了。
能否麻烦告知下，与dingo的不兼容具体体现在哪里？
我没有遇到其他issue里说的中间件无效的情况。现在唯一发现的问题就是参数会在不同的请求里串起来。

**Comment by hhxsv5** [comment]
目前收到的反馈就只有中间件问题，你的问题也可能是其他包引起的，请新建工程来排查。

**Comment by MukuroSama** [comment]
我再详细描述下吧：
目前只在列表展示页面的接口发现问题，其他接口暂未发现问题，待试验。

情况是这样的——
api有search参数（get），不加search参数，返回所有结果
在这个页面，先不加参数请求一次，返回所有结果，正常
搜索关键词A请求一次，返回A相关的结果集
搜索关键词B请求一次，返回B相关的结果集
然后再不加关键词请求（也可以是加别的search关键词请求），重复地请求，返回结果在[所有结果，A相关的结果集，B相关的结果集]中随机，且没有任何规律。
如果继续搜索关键词C，可能压根就不会出现C相关的结果。（接受了前几次请求后，结果就只会在前几次请求的结果中随机返回了，不接收新的请求了。具体几次没有试验过）

结果集的查询，我用的是[andersao/l5-repository](https://github.com/andersao/l5-repository)这个库，现在重点怀疑也在这上面。

**Comment by hhxsv5** [comment]
这应该是常驻内存带来的问题，请看[注意事项](https://github.com/hhxsv5/laravel-s/blob/master/README-CN.md#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9)。你可以建`config/laravels.php`中`worker_num`置为1，开两个页面，带search和不带search来回请求。

**Comment by MukuroSama** [comment]
测试了workor_num=1,没用。

又做了几个测试：
1.确保多次请求中，虽然结果不对，但结果不对时传入的参数都是对的（参数对的为什么不按参数查询？）
2.完全不使用l5-repository，只用laravel原生的model结合参数进行查询，结果完全是正常的
3.虽然使用了l5-repository，但没用它自带的方法，而是使用repository类中自定义的方法（带参数查询），也完全没有问题。

结合以上3点，加上出问题部分的代码，我严重怀疑是andersao/l5-repository库中的pushCriteria方法引起的
[文档链接](https://github.com/andersao/l5-repository#using-the-criteria-in-a-controller)

**参数进来，对每一个参数做逻辑判断，然后push参数对应的criteria到repository中，最后用带有多个criteria的的repository获取结果集。问题就出在这一步，95%以上的概率。**

大佬能不能看下是不是这个点导致的问题？

**Comment by hhxsv5** [comment]
```php
namespace App\Http\Controllers;

use App\PostRepository;

class PostsController extends BaseController {

    /**
     * @var PostRepository
     */
    protected $repository;

    public function __construct(PostRepository $repository){
        $this->repository = $repository;
    }


    public function index()
    {
        $this->repository->pushCriteria(new MyCriteria1());
        $this->repository->pushCriteria(MyCriteria2::class);
        $posts = $this->repository->all();
		...
    }

}
```
控制器是单例，会被常驻于内存，所以`$repository`对象也被常驻于内存，应该是这个问题[单例控制器](https://github.com/hhxsv5/laravel-s/blob/master/KnownIssues-CN.md#%E5%8D%95%E4%BE%8B%E6%8E%A7%E5%88%B6%E5%99%A8)。

**Comment by MukuroSama** [comment]
应该是这个问题了，耽搁了大佬这么久，还回复地这么快，真是万分感谢！
都怪我一开始没看完文档，只看了安装部署运行就上了。
——————————
不过既然这个问题的真相是这样，那dingo不兼容问题、中间件问题，我好像并没有遇到啊。。。

**Comment by MukuroSama** [comment]
仔细看了文档中单例的问题，也尝试了两个解决方案。

**我个人是倾向于在配置中添加destory_controllers列表的，但反复尝试后发现。。。根本没用！**

没办法只好去改controller代码试试了（这样要改动的地方就很多了，愁）

把controller成员变量中的xxxRepository全删了，不再在__construct()中依赖注入，改为在具体的controller方法中$xxxRepo = resolve(xxxRepository::class);每次都单独实例化它。
否则这个repo一直不被清除，每次请求都会把criteria堆积进去，越堆越多，查询结果最终就会为空了（条件太多，找不到满足条件的数据）。
而之前之所以会在几个结果间左右横跳，是因为swoole不止一个worker，单例的repo存在与多个woker中，请求的criteria也堆积在了不同woker的repo里。

**Comment by hhxsv5** [comment]
自动销毁控制器特性是要求`LaravelS 3.5.6+`，另外`excluded_list`是被`排除`销毁的控制器列表，不是将要销毁的控制器列表。将`enable`置为`true`后，即会销毁所有控制器。

**Comment by MukuroSama** [comment]
啊，我又眼瞎了。。。。。尴尬。。。。代码改一半了。。。。

**Comment by MukuroSama** [comment]
版本3.5.8
`
'destroy_controllers' => [
        'enable' => true,
        'excluded_list' => [
    ],
],
`
貌似还是无效。

**Comment by hhxsv5** [comment]
你在控制器构造函数中打下日志，就知道是否销毁成功了。如果销毁成功，应该每次请求会打出日志。

**Comment by MukuroSama** [comment]
我能说，时有时无么。。。。
给一个controller的construct里加了log，20%的情况会有log，80%都没有。。。

**Comment by hhxsv5** [comment]
既然这样，请提供`可重现问题`的代码包，按`Issue模板`提供各组件的版本信息，以后请按模板提交Issue，减少你我的沟通成本。如果还有疑问 请加QQ群`62075835 `详聊。

**Comment by uniteweiwei** [comment]
dingo不用到它的返回,只用它的错误处理,api管理,是没有问题的
