### ISSUE TITLE
创建自定义进程后，laravels无法启动

### ISSUE THREAD

**Issue by 742445211** [hhxsv5/laravel-s#167]
PHP                       | 7.1.3   |
| Swoole                    | 4.3.1   |
| LaravelS                  | 3.4.4   |
| Laravel Framework [local] | 5.6.39 

PHP Warning:  class_implements(): object or string expected in /var/www/html/wechat/vendor/hhxsv5/laravel-s/src/Swoole/Traits/CustomProcessTrait.php on line 25

Warning: class_implements(): object or string expected in /var/www/html/wechat/vendor/hhxsv5/laravel-s/src/Swoole/Traits/CustomProcessTrait.php on line 25
PHP Notice:  Array to string conversion in /var/www/html/wechat/vendor/hhxsv5/laravel-s/src/Swoole/Traits/CustomProcessTrait.php on line 29

Notice: Array to string conversion in /var/www/html/wechat/vendor/hhxsv5/laravel-s/src/Swoole/Traits/CustomProcessTrait.php on line 29
[2019-07-18 07:39:45] [ERROR] Uncaught exception "InvalidArgumentException"([0]Array must implement the interface Hhxsv5\LaravelS\Swoole\Process\CustomProcessInterface) at /var/www/html/wechat/vendor/hhxsv5/laravel-s/src/Swoole/Traits/CustomProcessTrait.php:26, 
#0 /var/www/html/wechat/vendor/hhxsv5/laravel-s/src/LaravelS.php(72): Hhxsv5\LaravelS\LaravelS->addCustomProcesses(Object(Swoole\Http\Server), '/var/www/html/w...', Array, Array)
#1 /var/www/html/wechat/vendor/hhxsv5/laravel-s/src/Console/Portal.php(132): Hhxsv5\LaravelS\LaravelS->__construct(Array, Array)
#2 /var/www/html/wechat/vendor/hhxsv5/laravel-s/src/Console/Portal.php(56): Hhxsv5\LaravelS\Console\Portal->start()
#3 /var/www/html/wechat/vendor/symfony/console/Command/Command.php(255): Hhxsv5\LaravelS\Console\Portal->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /var/www/html/wechat/bin/laravels(10): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 {main}

**Comment by hhxsv5** [comment]
请附上配置文件`config/laravels.php`。

**Comment by 742445211** [comment]
"hhxsv5/laravel-s": "~3.4",版本不低吧~~


------------------ 原始邮件 ------------------
发件人: "谢彪"<notifications@github.com>;
发送时间: 2019年7月21日(星期天) 中午1:52
收件人: "hhxsv5/laravel-s"<laravel-s@noreply.github.com>;
抄送: "张津川"<742445211@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [hhxsv5/laravel-s] 创建自定义进程后，laravels无法启动 (#167)




请附上配置文件config/laravels.php。

**Comment by hhxsv5** [comment]
因为[3.5.0](https://github.com/hhxsv5/laravel-s/releases/tag/v3.5.0)才支持最新文档中那种自定义进程的注册方式。你看的文档是`master`分支的，是针对最新代码的文档；但你用的LaravelS不是最新的，导致配置文件和LaravelS不匹配。

现在你有两个选择：
- 升级LaravelS到最新`3.5.8`（推荐）；
- 看[3.4.x](https://github.com/hhxsv5/laravel-s/blob/v3.4.4/README-CN.md#%E8%87%AA%E5%AE%9A%E4%B9%89%E8%BF%9B%E7%A8%8B)的文档，修改配置。
