### ISSUE TITLE
如何实现分布式websocket

### ISSUE THREAD

**Issue by jinuary** [hhxsv5/laravel-s#168]
我想通过websocket实现分布式部署，通过消息队列广播时，需要server通过来发送客户端消息，请问每台服务器的这个server对象应该如何保存呢，或者说这台服务器，如何通知其他服务器发起广播功能

**Comment by hhxsv5** [comment]
你可以通过开`自定义进程`订阅消息队列，在该进程中能够拿到server对象，就能完成推送。

**Comment by jinuary** [comment]
好的，我试试
