### ISSUE TITLE
Using persistent connection for Predis leads to the conflict of database selection

### ISSUE THREAD

**Issue by ashuiccc** [hhxsv5/laravel-s#177]
1. Tell us your software version
    How to know it?
    ```Bash
    # PHP
    php -v
    # Swoole
    php --ri swoole
    # Laravel
    grep 'laravel/framework' composer.json
    # Lumen
    grep 'laravel/lumen-framework' composer.json
    ```

    | Software | Version |
    | --------- | --------- |
    | PHP | `7.3.8` |
    | Swoole | `4.3.5` |
    | Laravel/Lumen | `5.8.30` |

2. Detail description about this issue(error/log)

    `redis缓存设置持久化连接后,更新缓存统计数据,数据无变化,去掉持久化连接选项后,恢复正常`

3. Give us a `reproducible` code block and `steps`

    ```PHP
   \Cache::store('redis')->increment('statics');//假如值为100,更新数据后无变化
    ```

去除cache中的持久化连接,缓存数据更新成功
<img width="721" alt="QQ20190806-181524@2x" src="https://user-images.githubusercontent.com/50192266/62532123-54cec700-b876-11e9-8b7c-ad21b423da22.png">

**Comment by ashuiccc** [comment]
如下是去除后的,不知道其他选项的持久化连接会不会有影响
<img width="576" alt="QQ20190806-184428@2x" src="https://user-images.githubusercontent.com/50192266/62533847-3d91d880-b87a-11e9-8312-fda199047a25.png">

**Comment by hhxsv5** [comment]
请按模板提交issue，目前缺少版本、示例代码，无法排查。

**Comment by ashuiccc** [comment]
> 请按模板提交issue，目前缺少版本、示例代码，无法排查。

已按模板提交 @hhxsv5

**Comment by Rivsen** [comment]
这个问题我跟踪了，如果你的redis配置除了default之外，还有其它的配置，比如default是db1，session是db0，queue是db2，并且这些db在同一个redis server上，发现开启持久连接之后，laravel中RedisManager虽然把不同的redis连接放在了一个数组中，用连接的名称（session、default、queue）进行保存，但是拿到连接之后，并不一定是对应的db，要看上一次发送command时使用的是哪个db，然后我这里是出现了，在开始的db是对的，但是后边读取了一次cache（db1），然后再写入session，session会写入到db1，而不是db0，如果在写入session之前，又去写入了queue，那么session会写到db2里

**Comment by Rivsen** [comment]
这是predis包的一个bug，我已经做了个最小重现，提了issue： https://github.com/nrk/predis/issues/577

有兴趣的可以继续跟这个issue看后续的进展。

**Comment by hhxsv5** [comment]
@Rivsen 的确，在开启持久连接的情况下，使用[predis](https://github.com/nrk/predis)会是同一个连接，`db`会冲突，而[phpredis](https://github.com/phpredis/phpredis)则表现正常。
@ashuiccc 可将Redis client切换为`phpredis`，参考[此文档](https://learnku.com/docs/laravel/5.8/redis/3930#phpredis)。
@Rivsen 感谢支持。

**Comment by ashuiccc** [comment]
> 这是predis包的一个bug，我已经做了个最小重现，提了issue： [nrk/predis#577](https://github.com/nrk/predis/issues/577)
> 
> 有兴趣的可以继续跟这个issue看后续的进展。

感谢,反馈已收到

**Comment by ashuiccc** [comment]
> @Rivsen 的确，在开启持久连接的情况下，使用[predis](https://github.com/nrk/predis)会是同一个连接，`db`会冲突，而[phpredis](https://github.com/phpredis/phpredis)则表现正常。
> @ashuiccc 可将Redis client切换为`phpredis`，参考[此文档](https://learnku.com/docs/laravel/5.8/redis/3930#phpredis)。
> @Rivsen 感谢支持。

感谢,反馈已收到

**Comment by ashuiccc** [comment]
> @Rivsen 的确，在开启持久连接的情况下，使用[predis](https://github.com/nrk/predis)会是同一个连接，`db`会冲突，而[phpredis](https://github.com/phpredis/phpredis)则表现正常。
> @ashuiccc 可将Redis client切换为`phpredis`，参考[此文档](https://learnku.com/docs/laravel/5.8/redis/3930#phpredis)。
> @Rivsen 感谢支持。

您好,经测试,还是不行哦

**Comment by hhxsv5** [comment]
> > @Rivsen 的确，在开启持久连接的情况下，使用[predis](https://github.com/nrk/predis)会是同一个连接，`db`会冲突，而[phpredis](https://github.com/phpredis/phpredis)则表现正常。
> > @ashuiccc 可将Redis client切换为`phpredis`，参考[此文档](https://learnku.com/docs/laravel/5.8/redis/3930#phpredis)。
> > @Rivsen 感谢支持。
> 
> 您好,经测试,还是不行哦

开一个redis-cli，MONITOR看看。

**Comment by ashuiccc** [comment]
> > > @Rivsen 的确，在开启持久连接的情况下，使用[predis](https://github.com/nrk/predis)会是同一个连接，`db`会冲突，而[phpredis](https://github.com/phpredis/phpredis)则表现正常。
> > > @ashuiccc 可将Redis client切换为`phpredis`，参考[此文档](https://learnku.com/docs/laravel/5.8/redis/3930#phpredis)。
> > > @Rivsen 感谢支持。
> > 
> > 
> > 您好,经测试,还是不行哦
> 
> 开一个redis-cli，MONITOR看看。

`1567142279.400906 [0 127.0.0.1:41800] "SELECT" "2"
1567142279.402869 [2 127.0.0.1:41800] "GET" "newpay_database_newpay_cache:uGpiewuqFPBYMp0siadg5DfdNftq9NN9PyrBstMc"
1567142279.546283 [0 127.0.0.1:41802] "SELECT" "1"
1567142279.546365 [1 127.0.0.1:41802] "GET" "newpay_database_newpay_cache:DfOrderCount"
1567142279.554732 [2 127.0.0.1:41800] "SETEX" "newpay_database_newpay_cache:uGpiewuqFPBYMp0siadg5DfdNftq9NN9PyrBstMc" "7200" "s:307:\"a:4:{s:6:\"_token\";s:40:\"M4mkpD8pBxeGbcPWUZdogwEJsUc6t0vKAcsHv77m\";s:52:\"login_admin_59ba36addc2b2f9401580f014c7f58ea4e30989d\";i:1;s:9:\"_previous\";a:1:{s:3:\"url\";s:85:\"http://newpay.test/abcpayadmin/dfOrder/create?_ifraem_id_=iframe__abcpayadmin_dfOrder\";}s:6:\"_flash\";a:2:{s:3:\"old\";a:0:{}s:3:\"new\";a:0:{}}}\";"
1567142299.486328 [0 127.0.0.1:41804] "SELECT" "2"
1567142299.488315 [2 127.0.0.1:41804] "GET" "newpay_database_newpay_cache:uGpiewuqFPBYMp0siadg5DfdNftq9NN9PyrBstMc"
1567142299.637156 [0 127.0.0.1:41806] "SELECT" "1"
1567142299.637235 [1 127.0.0.1:41806] "GET" "newpay_database_newpay_cache:DfOrderCount"
1567142299.645163 [2 127.0.0.1:41804] "SETEX" "newpay_database_newpay_cache:uGpiewuqFPBYMp0siadg5DfdNftq9NN9PyrBstMc" "7200" "s:307:\"a:4:{s:6:\"_token\";s:40:\"M4mkpD8pBxeGbcPWUZdogwEJsUc6t0vKAcsHv77m\";s:52:\"login_admin_59ba36addc2b2f9401580f014c7f58ea4e30989d\";i:1;s:9:\"_previous\";a:1:{s:3:\"url\";s:85:\"http://newpay.test/abcpayadmin/dfOrder/create?_ifraem_id_=iframe__abcpayadmin_dfOrder\";}s:6:\"_flash\";a:2:{s:3:\"old\";a:0:{}s:3:\"new\";a:0:{}}}\";"
1567142319.365693 [0 127.0.0.1:41808] "SELECT" "2"
1567142319.367643 [2 127.0.0.1:41808] "GET" "newpay_database_newpay_cache:uGpiewuqFPBYMp0siadg5DfdNftq9NN9PyrBstMc"`

**Comment by hhxsv5** [comment]
@ashuiccc 格式化下，说明你要操作的key和db

**Comment by Rivsen** [comment]
> @Rivsen 的确，在开启持久连接的情况下，使用[predis](https://github.com/nrk/predis)会是同一个连接，`db`会冲突，而[phpredis](https://github.com/phpredis/phpredis)则表现正常。
> @ashuiccc 可将Redis client切换为`phpredis`，参考[此文档](https://learnku.com/docs/laravel/5.8/redis/3930#phpredis)。
> @Rivsen 感谢支持。

感谢指导～

**Comment by callmebinge** [comment]
你好，同遇到这个问题，如果切换为phpredis，不是不能用持久连接吗，怎么破

**Comment by hhxsv5** [comment]
@callmebinge 可以使用

**Comment by callmebinge** [comment]
> @callmebinge 可以使用

我用predis，一个页面打开，放十几分钟后，再刷新的时候就会报如下这样的错，phpredis却不会，难道不是因为predis不支持持久连接吗

/vendor/predis/predis/src/Connection/AbstractConnection.php,Error Error while reading line from the server. [tcp://127.0.0.1:6379]

laravel 5.5

database.redis 配置如下

        'client' => 'predis',

        'cluster' => false,

        'default' => [
            'host' => env('REDIS_HOST', 'localhost'),
            'password' => env('REDIS_PASSWORD', null),
            'port' => env('REDIS_PORT', 6379),
            'database' => 1,
            'persistent' => true, 
        ],
        'session' => [
            'host' => env('REDIS_HOST', 'localhost'),
            'password' => env('REDIS_PASSWORD', null),
            'port' => env('REDIS_PORT', 6379),
            'database' => 2,
            'persistent' => true, 
        ],
        'pet' => [
            'host' => env('REDIS_HOST', 'localhost'),
            'password' => env('REDIS_PASSWORD', null),
            'port' => env('REDIS_PORT', 6379),
            'database' => 3,
            'persistent' => true, 
        ],

**Comment by callmebinge** [comment]
> > @callmebinge 可以使用
> 
> 我用predis，一个页面打开，放十几分钟后，再刷新的时候就会报如下这样的错，phpredis却不会，难道不是因为predis不支持持久连接吗
> 
> /vendor/predis/predis/src/Connection/AbstractConnection.php,Error Error while reading line from the server. [tcp://127.0.0.1:6379]
> 
> laravel 5.5
> 
> database.redis 配置如下
> 
> ```
>     'client' => 'predis',
> 
>     'cluster' => false,
> 
>     'default' => [
>         'host' => env('REDIS_HOST', 'localhost'),
>         'password' => env('REDIS_PASSWORD', null),
>         'port' => env('REDIS_PORT', 6379),
>         'database' => 1,
>         'persistent' => true, 
>     ],
>     'session' => [
>         'host' => env('REDIS_HOST', 'localhost'),
>         'password' => env('REDIS_PASSWORD', null),
>         'port' => env('REDIS_PORT', 6379),
>         'database' => 2,
>         'persistent' => true, 
>     ],
>     'pet' => [
>         'host' => env('REDIS_HOST', 'localhost'),
>         'password' => env('REDIS_PASSWORD', null),
>         'port' => env('REDIS_PORT', 6379),
>         'database' => 3,
>         'persistent' => true, 
>     ],
> ```



> @callmebinge 可以使用

获取实例是这样的
Redis::connection('pet');
Redis::connection('session');

**Comment by hhxsv5** [comment]
[phpredis](https://github.com/phpredis/phpredis)和[predis](https://github.com/nrk/predis)是不同的Redis客户端。

**Comment by callmebinge** [comment]
> [phpredis](https://github.com/phpredis/phpredis)和[predis](https://github.com/nrk/predis)是不同的Redis客户端，phpredis没有问题，predis底层有问题。

就是phpredis连接的db错乱，才用predis的呀，结果出现上图的问题，有办法解决吗

**Comment by hhxsv5** [comment]
请使用`phpredis`，然后`redis-cli`执行`monitor`命令监控，再将监控结果发出来。

**Comment by callmebinge** [comment]
> 请使用`phpredis`，然后`redis-cli`执行`monitor`命令监控，再将监控结果发出来。

找到原因了，应该是每次操作redis前没有执行select db

**Comment by callmebinge** [comment]
> 请使用`phpredis`，然后`redis-cli`执行`monitor`命令监控，再将监控结果发出来。

多谢指导！

**Comment by hhxsv5** [comment]
因为同一`Worker`进程内的`Redis`连接是被该`Worker`所有请求共享的，既然在`database.redis`中配置了连接的`database`，那就不要在使用时`select`，避免后续请求使用之前请求`select`的`database`，而导致看似数据写入失败，实际是写到其他`database`中了。

**Comment by callmebinge** [comment]
我这边业务是这样的情况，同一个host端口多个database，而在同一个请求中，会从多个database拿数据，如果请求前不select database就会存取错乱

DEMO1:
       `$db1 =  Redis::connection('default');
        $db1->set('test_key', 'data1');

        $db2 =  Redis::connection('session');
        $db2->set('test_key', 'data2');

        $db3 = Redis::connection('pet');
        $db3->set('test_key', 'data3');

        dump($db1->get('test_key'));
        dump($db2->get('test_key'));
        dump($db3->get('test_key'));
        return;`

结果是输出 三个data3，我看了下monitor，貌似是连接的时候select database跟命令执行不是顺序来的，monitor如下
1568193062.588536 [2 127.0.0.1:52878] "AUTH" "123456"
1568193062.588684 [2 127.0.0.1:52878] "SELECT" "2"
1568193062.595507 [2 127.0.0.1:52878] "AUTH" "123456"
1568193062.595659 [2 127.0.0.1:52878] "SELECT" "1"
1568193062.595788 [1 127.0.0.1:52878] "SET" "test_key" "data1"
1568193062.595886 [1 127.0.0.1:52878] "SET" "test_key" "data2"
1568193062.596044 [1 127.0.0.1:52878] "AUTH" "123456"
1568193062.596129 [1 127.0.0.1:52878] "SELECT" "3"
1568193062.596262 [3 127.0.0.1:52878] "SET" "test_key" "data3"
1568193062.596415 [3 127.0.0.1:52878] "GET" "test_key"
1568193062.606710 [3 127.0.0.1:52878] "GET" "test_key"
1568193062.606999 [3 127.0.0.1:52878] "GET" "test_key"

DEMO2：
       `$db1 =  Redis::connection('default');
        $db1->select(1);
        $db1->set('test_key', 'data1');

        $db2 =  Redis::connection('session');
        $db2->select(2);
        $db2->set('test_key', 'data2');

        $db3 = Redis::connection('pet');
        $db3->select(3);
        $db3->set('test_key', 'data3');

        $db1->select(1);
        dump($db1->get('test_key'));
        $db2->select(2);
        dump($db2->get('test_key'));
        $db3->select(3);
        dump($db3->get('test_key'));
        return;`

结果依次输出data1，data2，data3，monitor如下

1568193265.010198 [3 127.0.0.1:53028] "SELECT" "1"
1568193265.010493 [1 127.0.0.1:53028] "SET" "test_key" "data1"
1568193265.010624 [1 127.0.0.1:53028] "SELECT" "2"
1568193265.010719 [2 127.0.0.1:53028] "SET" "test_key" "data2"
1568193265.010878 [2 127.0.0.1:53028] "SELECT" "3"
1568193265.010969 [3 127.0.0.1:53028] "SET" "test_key" "data3"
1568193265.011082 [3 127.0.0.1:53028] "SELECT" "1"
1568193265.011174 [1 127.0.0.1:53028] "GET" "test_key"
1568193265.011544 [1 127.0.0.1:53028] "SELECT" "2"
1568193265.012025 [2 127.0.0.1:53028] "GET" "test_key"
1568193265.012240 [2 127.0.0.1:53028] "SELECT" "3"
1568193265.012497 [3 127.0.0.1:53028] "GET" "test_key"

**Comment by hhxsv5** [comment]
@callmebinge 提供一个可复现问题的项目压缩包。

**Comment by callmebinge** [comment]
> @callmebinge 提供一个可复现问题的项目压缩包。

就是上面两段代码，跟业务无关的
