### ISSUE TITLE
单例清除怎样去查看

### ISSUE THREAD

**Issue by ashuiccc** [hhxsv5/laravel-s#178]
1. Tell us your software version
    How to know it?
    ```Bash
    # PHP
    php -v
    # Swoole
    php --ri swoole
    # Laravel
    grep 'laravel/framework' composer.json
    # Lumen
    grep 'laravel/lumen-framework' composer.json
    ```

    | Software | Version |
    | --------- | --------- |
    | PHP | `7.3.8` |
    | Swoole | `4.4.5` |
    | Laravel/Lumen | `5.8.30` |

2. Detail description about this issue(error/log)

    `单例清除,我应该怎样去查看所有单例,$this->app?假如我想清除mysql的单例或者是redis的单例等等.我担心不清除单例会内存溢出,或者mysql或redis最大连接数超上限问题`

3. Give us a `reproducible` code block and `steps`

    ```PHP
    //TODO: Your code
    ```

**Comment by hhxsv5** [comment]
`Application`是继承自`Container`，所以$app就是一个容器的实例，通过调用$app->getBindings()来去获取绑定的所有实例，其中`shared`为true的是单例。
大部分情况下，这些单例没有问题，如果有问题，可使用重新注册Provider或写个Cleaner来清理。
