### ISSUE TITLE
生命周期添加hook钩子

### ISSUE THREAD

**Issue by heirychen** [hhxsv5/laravel-s#179]
能否在 start stop 这些环节添加 hook ，方便做一些特殊处理，盼复，感谢。

**Comment by hhxsv5** [comment]
参考[配置Swoole的事件回调函数](https://github.com/hhxsv5/laravel-s/blob/master/README-CN.md#%E9%85%8D%E7%BD%AEswoole%E7%9A%84%E4%BA%8B%E4%BB%B6%E5%9B%9E%E8%B0%83%E5%87%BD%E6%95%B0)。
