### ISSUE TITLE
overtrue/socialite git hub 登录失败

### ISSUE THREAD

**Issue by hedeqiang** [hhxsv5/laravel-s#180]
| Software | Version |
    | --------- | --------- |
    | PHP | 7.3.8 |
    | Swoole | 4.4.4 |
    | Laravel/Lumen | 5.8.* |

![image](https://user-images.githubusercontent.com/31909061/63265351-05e65000-c2c0-11e9-88d9-ccdf60ef7716.png)

**Comment by juberjj** [comment]
Hey @hedeqiang , 

Have you included socialite on your config/laravels -> Providers?

**Comment by hedeqiang** [comment]
@juberjj  Hey 
Yes, I have added。

```
'register_providers'       => [
        Overtrue\LaravelSocialite\ServiceProvider::class,

        \Illuminate\Auth\AuthServiceProvider::class,
        \App\Providers\AuthServiceProvider::class,
        Dingo\Api\Provider\DingoServiceProvider::class,
        Dingo\Api\Provider\HttpServiceProvider::class,
       Tymon\JWTAuth\Providers\LaravelServiceProvider::class,
   ],
    'cleaners'                 => [
        Hhxsv5\LaravelS\Illuminate\Cleaners\SessionCleaner::class, // If you use the session or authentication in your project, please uncomment this line
        Hhxsv5\LaravelS\Illuminate\Cleaners\AuthCleaner::class,    // If you use the authentication or passport in your project, please uncomment this line
        Hhxsv5\LaravelS\Illuminate\Cleaners\JWTCleaner::class,     // If you use the package "tymon/jwt-auth" in your project, please uncomment this line
        // ...
    ],
```

**Comment by juberjj** [comment]
@hedeqiang 

At the moment we are using socialite package but not initiating it there and it's working fine.

![image](https://user-images.githubusercontent.com/16324958/63340707-944de680-c33f-11e9-9b86-a57ff28d9c89.png)

**Comment by hedeqiang** [comment]
@juberjj  Thanks,May be my problem?

**Comment by hhxsv5** [comment]
@hedeqiang Solved?

**Comment by hedeqiang** [comment]
@hhxsv5  not yet

**Comment by xyj2156** [comment]
@hedeqiang 我有一个临时的解决办法，虽然很烂，但是，在没有有修复的情况下，可以使用了。
我使用的是 `laravel/socialite ` 。
我找到的问题根源是，通过自身的 `request` 得不到参数 `state` 和 `code`。
解决办法简单粗暴：
验证 `state(hasInvalidState方法)` 那里，把`return ! (strlen($state) > 0 && $this->request->input('state') === $state);` 修改为 `return ! (strlen($state) > 0 && request() -> input('state') === $state);`

获取 `code (getCode)` 那里 把 `return $this->request->input('code');` 修改为 `return request() -> input('code');`

**Comment by hedeqiang** [comment]
@xyj2156   是的，你这个方法完全没有问题，可以解决，看下官方怎么解决吧

**Comment by apollopy** [comment]
不侵入插件，可以试试 `https://github.com/hhxsv5/laravel-s/blob/master/KnownIssues-CN.md#%E4%BD%BF%E7%94%A8%E5%8C%85-jenssegersagent`

这种办法，监听 `laravels.received_request` 事件，显性 setRequest

**Comment by xyj2156** [comment]
@apollopy 你使用那个办法解决问题了没有？

**Comment by apollopy** [comment]
> @apollopy 你使用那个办法解决问题了没有？

我们用的不是这个插件，但其他插件遇到类似问题，我们是这么解决的

我看 overtrue/socialite 的文档有提到 https://github.com/overtrue/socialite#custom-session-or-request-instance

也就是说，通过事件或者中间键来在具体业务之前，显式的将当前的 request 传进去是能做到的。

**Comment by apollopy** [comment]
> @apollopy 你使用那个办法解决问题了没有？

看上去，这个插件

```php
$socialite = new SocialiteManager($config);
// 改成
$socialite = new SocialiteManager($config, request());
```

就好了

**Comment by xyj2156** [comment]
> > @apollopy 你使用那个办法解决问题了没有？
> 
> 看上去，这个插件
> 
> ```
> $socialite = new SocialiteManager($config);
> // 改成
> $socialite = new SocialiteManager($config, request());
> ```
> 
> 就好了

明白了，使用传入的 request对象而不是他自己获取的。

**Comment by shin-ltp** [comment]
@xyj2156 
用laravel/socialite，遇到同样的问题。
laravel/socialite的provider类提供了setRequest()的方法，做callback的时候，在调用user()方法之前，
调用setRequest()，把Request对象替换掉，然后user()就可以取到认证的用户信息了。
还是希望官方能尽早解决这个问题吧。

**Comment by wyq2214368** [comment]
> @xyj2156
> 用laravel/socialite，遇到同样的问题。
> laravel/socialite的provider类提供了setRequest()的方法，做callback的时候，在调用user()方法之前，
> 调用setRequest()，把Request对象替换掉，然后user()就可以取到认证的用户信息了。
> 还是希望官方能尽早解决这个问题吧。

补充一下，不只是callback时调用setRequest()方法，在redirect前也要主动调用setRequest()方法，不然第一次正常，之后就不正常了，因为redirect时向session中设置state值也调用了 $this->request 

```php
/**
     * Put state to session storage and return it.
     *
     * @return string|bool
     */
    protected function makeState()
    {
        if (!$this->request->hasSession()) {
            return false;
        }

        $state = sha1(uniqid(mt_rand(1, 1000000), true));
        $session = $this->request->getSession();     // <--------here

        if (is_callable([$session, 'put'])) {
            $session->put('state', $state);
        } elseif (is_callable([$session, 'set'])) {
            $session->set('state', $state);
        } else {
            return false;
        }

        return $state;
    }
```
如果只在callback设置request，无法获取到之前存入session的state值。所以redirect和callback都要主动调用下setRequest()方法。
