### ISSUE TITLE
reload 之后 504

### ISSUE THREAD

**Issue by JimChenWYU** [hhxsv5/laravel-s#181]
1. Tell us your software version
    How to know it?
    ```Bash
    # PHP
    PHP 7.0.30-0ubuntu0.16.04.1
    # Swoole
swoole support => enabled
Version => 2.2.0
Author => tianfeng.han[email: mikan.tenny@gmail.com]
coroutine => enabled
epoll => enabled
eventfd => enabled
timerfd => enabled
signalfd => enabled
cpu affinity => enabled
spinlock => enabled
rwlock => enabled
async http/websocket client => enabled
openssl => enabled
Linux Native AIO => enabled
pcre => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
mysqlnd => enabled

Directive => Local Value => Master Value
swoole.aio_thread_num => 2 => 2
swoole.display_errors => On => On
swoole.use_namespace => On => On
swoole.use_shortname => On => On
swoole.fast_serialize => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608

    # Laravel
    "laravel/framework": "5.5.*",
    # Lumen
    grep 'laravel/lumen-framework' composer.json
    ```

+-------------------+-------------------------+
| Component         | Version                 |
+-------------------+-------------------------+
| PHP               | 7.0.30-0ubuntu0.16.04.1 |
| Swoole            | 2.2.0                   |
| Laravel Framework | 5.5.40                  |
+-------------------+-------------------------+

2. Detail description about this issue(error/log)

    当执行 `php artisan laravels reload` 之后 nginx 日志显示请求都是504，只有当 `php artisan laravels restart` 才能正常, 我使用的 laravels 版本是 v2.0.2

3. Give us a `reproducible` code block and `steps`

    ```PHP
    //TODO: Your code
    ```

**Comment by hhxsv5** [comment]
1.`curl http://127.0.0.1:5200/`.
2.Check the logs of Laravel & Swoole.
3.Try to upgrade Swoole to 4.x.
