### ISSUE TITLE
Undefined index: REQUEST_URI

### ISSUE THREAD

**Issue by slarkes** [hhxsv5/laravel-s#182]
1.版本
+---------------------------+--------------------------------------+
| Component                 | Version                              |
+---------------------------+--------------------------------------+
| PHP                       | 7.2.4-1+ubuntu16.04.1+deb.sury.org+1 |
| Swoole                    | 4.3.6                                |
| LaravelS                  | 3.5.9                                |
| Laravel Framework [local] | 5.5.48                               |
+---------------------------+--------------------------------------+

2.报错
```
[2019-08-24 05:44:44] [ERROR] onRequest: Uncaught exception "ErrorException"([0]Undefined index: REQUEST_URI) at /var/www/aix-system_zhoushan_gansu/vendor/hhxsv5/laravel-s/src/Swoole/Request.php:66, 
#0 /var/www/aix-system_zhoushan_gansu/vendor/hhxsv5/laravel-s/src/Swoole/Request.php(66): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Undefined index...', '/var/www/aix-sy...', 66, Array)
#1 /var/www/aix-system_zhoushan_gansu/vendor/hhxsv5/laravel-s/src/LaravelS.php(130): Hhxsv5\LaravelS\Swoole\Request->toIlluminateRequest(Array, Array)
#2 /var/www/aix-system_zhoushan_gansu/vendor/hhxsv5/laravel-s/src/LaravelS.php(137): Hhxsv5\LaravelS\LaravelS->convertRequest(Object(Hhxsv5\LaravelS\Illuminate\Laravel), Object(Swoole\Http\Request))
#3 [internal function]: Hhxsv5\LaravelS\LaravelS->onRequest(Object(Swoole\Http\Request), Object(Swoole\Http\Response))
#4 /var/www/aix-system_zhoushan_gansu/vendor/hhxsv5/laravel-s/src/Swoole/Server.php(357): Swoole\Server->start()
#5 /var/www/aix-system_zhoushan_gansu/vendor/hhxsv5/laravel-s/src/Console/Portal.php(137): Hhxsv5\LaravelS\Swoole\Server->run()
#6 /var/www/aix-system_zhoushan_gansu/vendor/hhxsv5/laravel-s/src/Console/Portal.php(56): Hhxsv5\LaravelS\Console\Portal->start()
#7 /var/www/aix-system_zhoushan_gansu/vendor/symfony/console/Command/Command.php(255): Hhxsv5\LaravelS\Console\Portal->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/aix-system_zhoushan_gansu/bin/laravels(160): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 {main}
```

在生产环境会偶现这个问题.还没进行入我的代码就报错了.看代码是对REQUEST_URI做了判断,我打印了没有REQUEST_URI的swooleRequest.发现什么都没有:
```
Swoole\Http\Request {#10758
  +fd: 10
  +streamId: 0
  +header: []
  +server: array:4 [
    "server_port" => 5200
    "remote_port" => 52504
    "remote_addr" => "172.29.0.9"
    "master_time" => 1566596665
  ]
  +request: null
  +cookie: null
  +get: null
  +files: null
  +post: null
  +tmpfiles: null
}
```
我用的是laradock环境.看不出来这个是什么请求

**Comment by hhxsv5** [comment]
可能是不正确的HTTP请求，例如该urlencode的没有encode、报文格式不对，可以先忽略。
尝试记录原始HTTP报文`$swooleRequest->getData()`，看看请求是什么样的。

**Comment by phper5** [comment]
遇到了同样的问题，我尝试打印了$swooleRequest->getData()。
`bucket=storagecnszrkt3&object=app%2Flightpdf%2Ftranscoding%2Fvideo%2Fcfcd208495d565ef66e7dff9f98764da%2F3cd59b6a-d449-3e1d-ae42-dc454bdf144e.mov&etag=F448173521C66598470B903243C35950&size=52973523&mime_type=video%2Fquicktime&image_height=&image_width=&image_format=&x:app_id=0044eb2b-e03a-3d58-b689-8882e697c003&x:user_id=0&x:task_id=6dff2ad2-7eaf-3953-86b4-28cf7752ebe9&x:real_user_id=-1567046966`

发现都是阿里云的回调。
url一般都含有中文 POST /api/callbacks/inputoss?x:original_name=公司视频_clip(1).mov

**Comment by hhxsv5** [comment]
@phper5 我使用该path和body并未重现，你重现了吗？

**Comment by phper5** [comment]
> @phper5 我使用该path和body并未重现，你重现了吗？

我本地测试也不能重现，但是服务器上处理阿里云的回调，url中有中文，必现。我贴一个完成的数据

`Swoole\Http\Request Object
(
    [fd] => 3913
    [streamId] => 0
    [header] => Array
        (
        )

    [server] => Array
        (
            [server_port] => 5204
            [remote_port] => 58736
            [remote_addr] => 127.0.0.1
            [master_time] => 1567175173
        )

    [request] =>
    [cookie] =>
    [get] =>
    [files] =>
    [post] =>
    [tmpfiles] =>
)
POST /api/callbacks/inputoss?x:original_name=19年公需科目.jpeg HTTP/1.0^M
Connection: keep-alive^M
X-Real-IP: 47.106.63.26^M
Host: 127.0.0.1:5204^M
Content-Length: 403^M
Authorization: c2hsoU2jy777WXsoR6tJsCMP9bMI2YByqzEWRCMKI7BLYK7s4gD1GQpgR2kBtBoEAq6u+lmhf8wxy9ryjEs9oA==^M
Content-MD5: 7af9Te8iT2aUpa2fI0iv9w==^M
Content-Type: application/x-www-form-urlencoded^M
Date: Fri, 30 Aug 2019 14:26:14 GMT^M
User-Agent: aliyun-oss-callback^M
x-oss-additional-headers: ^M
x-oss-bucket: storagecnszrkt3^M
x-oss-owner: 1192499683634878^M
x-oss-pub-key-url: aHR0cHM6Ly9nb3NzcHVibGljLmFsaWNkbi5jb20vY2FsbGJhY2tfcHViX2tleV92MS5wZW0=^M
x-oss-request-id: 5D6932034ABA219CB10BD12E^M
x-oss-requester: 1192499683634878^M
x-oss-signature-version: 1.0^M
x-oss-tag: CALLBACK^M
eagleeye-rpcid: 0.1^M
^M
bucket=storagecnszrkt3&object=app%2Flightpdf%2Ftranscoding%2Fvideo%2Fcfcd208495d565ef66e7dff9f98764da%2F373cab84-7b74-3033-8342-57378f2be9df.jpeg&etag=386D6FD33134F76752EABE2C8FEA8521&size=1405179&mime_type=image%2Fjpeg&image_height=4608&image_width=3456&image_format=jpg&x:app_id=0044eb2b-e03a-3d58-b689-8882e697c003&x:user_id=0&x:task_id=4453a17b-1bc1-3812-ae37-d8ae218c786d&x:real_user_id=-1567175150Array
(
    [server_port] => 5204
    [remote_port] => 58736
    [remote_addr] => 127.0.0.1
    [master_time] => 1567175173
)`

一个正常的应该是这样的
`Swoole\Http\Request Object
(
    [fd] => 366
    [streamId] => 0
    [header] => Array
        (
            [connection] => keep-alive
            [x-real-ip] => 127.0.0.1
            [host] => 127.0.0.1:5204
            [content-length] => 178
            [user-agent] => GuzzleHttp/6.3.3 curl/7.29.0 PHP/7.3.8
            [content-type] => application/json
        )

    [server] => Array
        (
            [request_method] => GET
            [request_uri] => /api/urls
            [path_info] => /api/urls
            [request_time] => 1567175381
            [request_time_float] => 1567175381.8257
            [server_protocol] => HTTP/1.0
            [server_port] => 5204
            [remote_port] => 47270
            [remote_addr] => 127.0.0.1
            [master_time] => 1567175381
        )

    [request] =>
    [cookie] =>
    [get] =>
    [files] =>
    [post] =>
    [tmpfiles] =>
)
GET /api/urls HTTP/1.0^M
Connection: keep-alive^M
X-Real-IP: 127.0.0.1^M
Host: 127.0.0.1:5204^M
Content-Length: 178^M
User-Agent: GuzzleHttp/6.3.3 curl/7.29.0 PHP/7.3.8^M
Content-Type: application/json^M
^M
{"api_token":"4061e291fee05f3321f6190630ce56e3","id_list":"[\"5bd960de-5e78-3ca6-95f3-fe75a3ee4465\"]","width_list":"[\"1080\",\"160\",\"original\"]","time":3600,"auto_orient":1}Array
(
    [request_method] => GET
    [request_uri] => /api/urls
    [path_info] => /api/urls
    [request_time] => 1567175381
    [request_time_float] => 1567175381.8257
    [server_protocol] => HTTP/1.0
    [server_port] => 5204
    [remote_port] => 47270
    [remote_addr] => 127.0.0.1
    [master_time] => 1567175381
)
`
上面的代码里，我分别打印了 swooleRequest， swooleRequest->getData()  swooleRequest->server

**Comment by phper5** [comment]
> @phper5 我使用该path和body并未重现，你重现了吗？

php 7.3.4 ， swoole 4.3.3  测试 ` curl -X POST http://127.0.0.1:9505/?x:a=你好 -d "a=2312&b=1234"
` swoole的request：
`Swoole\Http\Request Object
(
    [fd] => 1
    [streamId] => 0
    [header] => Array
        (
        )
    [server] => Array
        (
            [request_method] => POST
            [request_uri] => /
            [path_info] => /
            [request_time] => 1567403511
            [request_time_float] => 1567403512.2902
            [server_port] => 9505
            [remote_port] => 36012
            [remote_addr] => 127.0.0.1
            [master_time] => 1567403511
            [server_protocol] => HTTP/1.0
        )
    [request] => 
    [cookie] => 
    [get] => 
    [files] => 
    [post] => 
    [tmpfiles] => 
)
 `
swoole 改为4.4。4
`Swoole\Http\Request Object
(
    [fd] => 1
    [streamId] => 0
    [header] => Array
        (
        )
    [server] => Array
        (
            [server_port] => 9505
            [remote_port] => 36010
            [remote_addr] => 127.0.0.1
            [master_time] => 1567403448
        )
    [request] => 
    [cookie] => 
    [get] => 
    [files] => 
    [post] => 
    [tmpfiles] => 
)`
swoole升级到4.4.5
`[2019-09-02 13:58:01 *46560.3]	NOTICE	request is illegal and it has been discarded, 161 bytes unprocessed
[2019-09-02 13:58:01 *46560.3]	NOTICE	swFactoryProcess_finish (ERRNO 1005): connection[fd=3] does not exists
`
请问你的不能重现的版本是哪个版本的php和swoole

**Comment by hhxsv5** [comment]
@phper5 Swoole 4.4.4 已经修复[此Bug](https://github.com/swoole/swoole-src/issues/2751)，对于未Encode的URI响应400。

```
root@cb93956bb4d5:~# curl -i -X POST http://127.0.0.1:5200/?x:a=你好 -d "a=2312&b=1234"
HTTP/1.1 400 Bad Request
```
Swoole日志中会有Notice：

```
[2019-09-02 14:37:13 *47843.3]	NOTICE	request is illegal and it has been discarded, 161 bytes unprocessed
```
