### ISSUE TITLE
respond send方法

### ISSUE THREAD

**Issue by wtry** [hhxsv5/laravel-s#183]
1. Tell us your software version
    How to know it?
    ```Bash
    # PHP
    php -v
    # Swoole
    php --ri swoole
    # Laravel
    grep 'laravel/framework' composer.json
    # Lumen
    grep 'laravel/lumen-framework' composer.json
    ```

    | Software | Version |
    | --------- | --------- |
    | PHP | `PHP 7.3.7-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Jul 10 2019 06:54:46) ( NTS )` |
    | Swoole | `4.4.4` |
    | Laravel/Lumen | `5.8.12` |

2. Detail description about this issue(error/log)

    `我有一个方法error()；这个方法直接reponse()->send();直接通过nginx，可以获取到返回数据，通过laravel-s无法获得返回数据`

3. Give us a `reproducible` code block and `steps`

    ```PHP
        function error(string $msg, int $err = 0, $e = null) {
        if ($e instanceof Throwable) {
            $message = CurrentEnvInfoTrait::ThrowInfo($e);
            $msg     .= $e->getMessage();
        } else {
            $message = (array)$e;
        }
        false === app()->runningInConsole() && dispatch(new ErrorLogJob($message));
        return response()->json(['err' => $err, 'msg' => $msg])->setEncodingOptions(320)->setStatusCode($err < 200 ? 200 : $err)->send();
    }
    ```
```PHP
    public function me() {
        try {
            $this->test();
            return $this->success($this->request->user()->only(['nickname', 'username', 'phone', 'avatar', 'description', 'permissions']));
        } catch (Throwable $e) {
            error('aa', 501);
        }
    }

    public function test() {
        return error(123,500);
    }
```
![微信截图_20190826181910](https://user-images.githubusercontent.com/13792519/63683920-4bf66300-c82e-11e9-9662-c3b73ac7a4ae.png)
![微信截图_20190826181945](https://user-images.githubusercontent.com/13792519/63683923-4d279000-c82e-11e9-8e26-9101b3c34906.png)

**Comment by hhxsv5** [comment]
不能调send()，只能在控制器中返回Response对象来实现响应。
因为FPM与Swoole的响应请求方式是不同的，FPM下echo、exit等标准输出都行，但Swoole中只能调[$swooleResponse->end()](https://wiki.swoole.com/wiki/page/339.html)。
