### ISSUE TITLE
 Interface 'Hhxsv5\LaravelS\Swoole\WebsocketHandlerInterface' not found

### ISSUE THREAD

**Issue by cruelwolfking** [hhxsv5/laravel-s#186]
ws 启动报 Interface 'Hhxsv5\LaravelS\Swoole\WebsocketHandlerInterface' not found

**Comment by hhxsv5** [comment]
Class names are case sensitive, it should be`Hhxsv5\LaravelS\Swoole\WebSocketHandlerInterface`.
