### ISSUE TITLE
php7.0 artisan laravels start报错

### ISSUE THREAD

**Issue by mountainguan** [hhxsv5/laravel-s#19]
In LaravelSCommand.php line 69:
                                               
  Call to undefined function swoole_version();

我已经安装好了swoole 2.1.1，phpinfo里已经显示enable

**Comment by mountainguan** [comment]
原来是我的php cli未配置extension=swoole.so

**Comment by hhxsv5** [comment]
一般情况下，web服务器php.ini和php-cli.ini是分开的
控制台下使用下列命令检查swoole是否正常安装。
```Bash
php --ri swoole
```
