### ISSUE TITLE
请教一下为什么 composer 里 swoole/ide-helper 是 require 而不是 require-dev ？

### ISSUE THREAD

**Issue by apollopy** [hhxsv5/laravel-s#190]
是有什么原因吗？swoole/ide-helper 看上去只是一个开发依赖的包。

**Comment by hhxsv5** [comment]
IDE提示，支持Swoole的函数与类。

**Comment by apollopy** [comment]
只有 dev 模式下才需要 IDE 提示啊，但我看到

https://github.com/hhxsv5/laravel-s/commit/f662e52e4690a65e2b0fb2d287257f8a223d7f7e#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780

特意把这个包从 require-dev 移动到 require。

这样会导致在正式业务运行环境也安装这个包，看上去并没有必要。

https://docs.phpcomposer.com/03-cli.html#init-Options

**Comment by doesDWQ** [comment]
这个包应该只是在开发时使用的，我的composer.json里面都没有这个包，我参考的是这个文档集成的laravels：https://xueyuanjun.com/post/9801.html
，
------------------ 原始邮件 ------------------
发件人: "ApolloPY"<notifications@github.com>;
发送时间: 2019年9月29日(星期天) 上午10:53
收件人: "hhxsv5/laravel-s"<laravel-s@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [hhxsv5/laravel-s] 请教一下为什么 composer 里 swoole/ide-helper 是 require 而不是 require-dev ？ (#190)




只有 dev 模式下才需要 IDE 提示啊，但我看到
 
f662e52#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780
 
特意把这个包从 require-dev 移动到 require。
 
这样会导致在正式业务运行环境也安装这个包，看上去并没有必要。
 
https://docs.phpcomposer.com/03-cli.html#init-Options

**Comment by apollopy** [comment]
@doesDWQ 你装的是什么版本？我看这个包是 3.5.1 引入的。

并不是安装指南里要求在自己项目的 composer 文件里声明这个包，而是3.5.1开始，装 hhxsv5/laravel-s 会带上这个包。

虽然在正式业务运行环境里，装这个包看上去也不会有引起什么问题。但出于洁癖吧，毕竟这只是 IDE 提示用的

**Comment by doesDWQ** [comment]
"hhxsv5/laravel-s": "^3.5",


------------------ 原始邮件 ------------------
发件人: "ApolloPY"<notifications@github.com>;
发送时间: 2019年9月29日(星期天) 中午11:21
收件人: "hhxsv5/laravel-s"<laravel-s@noreply.github.com>;
抄送: "如梦令"<2354513578@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [hhxsv5/laravel-s] 请教一下为什么 composer 里 swoole/ide-helper 是 require 而不是 require-dev ？ (#190)




@doesDWQ 你装的是什么版本？我看这个包是 3.5.1 引入的。
 
并不是安装指南里要求在自己项目的 composer 文件里声明这个包，而是3.5.1开始，装 hhxsv5/laravel-s 会带上这个包。
 
虽然在正式业务运行环境里，装这个包看上去也不会有引起什么问题。但出于洁癖吧，毕竟这只是 IDE 提示用的

**Comment by apollopy** [comment]
@doesDWQ 你看一下你的 vendor/swoole/ide-helper 是否存在。

**Comment by doesDWQ** [comment]
存在的，



------------------ 原始邮件 ------------------
发件人: "ApolloPY"; 
发送时间: 2019年9月29日(星期天) 中午11:25
收件人: "hhxsv5/laravel-s";
抄送: "doesDWQ"<2354513578@qq.com>;"Mention";
主题: Re: [hhxsv5/laravel-s] 请教一下为什么 composer 里 swoole/ide-helper 是 require 而不是 require-dev ？ (#190)




@doesDWQ 你看一下你的 vendor/swoole/ide-helper 是否存在。
 
&mdash;

**Comment by doesDWQ** [comment]
你是自己研究这个还是直接上公司项目，我是直接上的公司项目，性能是提升了很多，但是没有协程总是感觉cpu资源被浪费了，相对于纯协程跑要差挺多的。




------------------ 原始邮件 ------------------
发件人: "ApolloPY"<notifications@github.com>;
发送时间: 2019年9月29日(星期天) 中午11:25
收件人: "hhxsv5/laravel-s"<laravel-s@noreply.github.com>;
抄送: "如梦令"<2354513578@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [hhxsv5/laravel-s] 请教一下为什么 composer 里 swoole/ide-helper 是 require 而不是 require-dev ？ (#190)




@doesDWQ 你看一下你的 vendor/swoole/ide-helper 是否存在。

**Comment by apollopy** [comment]
目前只是调研阶段。这种胶水型项目，某些场景下是合适的折中方案。

**Comment by hhxsv5** [comment]
@apollopy 不仅仅开发`laravel-s`时要用`swoole/ide-helper` 包，`laravel-s`的使用者也需要用。
比如使用[自定义进程](https://github.com/hhxsv5/laravel-s/blob/master/README-CN.md#%E8%87%AA%E5%AE%9A%E4%B9%89%E8%BF%9B%E7%A8%8B)时，该类中需要定义回调函数`callback(Server $swoole, Process $process)`，其中的参数也需要IDE提示。

**Comment by apollopy** [comment]
@hhxsv5 我明白。

但这只是使用 `laravel-s` 的程序员，在**开发**时候需要，而不是依赖 `laravel-s` 的业务代码，在线上运行时需要吧？

这种情况下，将 `swoole/ide-helper` 放在 `laravel-s` 的 `require-dev` 配置中。并且建议安装 `laravel-s` 的程序员，可以在自己项目中执行 `composer require --dev swoole/ide-helper:@dev`，以得到 IDE 提示。可能是一个给到开发者更灵活的方案。

当然，这对于不是很了解 composer 的开发者，可能会有一点门槛。

只是一个建议。
