### ISSUE TITLE
laravels.json文件存放问题

### ISSUE THREAD

**Issue by 71sprite** [hhxsv5/laravel-s#191]
1. Tell us your software version

    | Software | Version |
    | --------- | --------- |
    | LaravelS | `3.5.11` |

2. Detail description about this issue(error/log)

    `Console/Portal.php:272，获取laravels.json文件的地址，像laravels.pid一样放在配置文件里会不会好一些？因为开发环境和线上环境配置内容肯定不一致，这里可配置就不用考虑发布代码时文件覆盖的问题了。`

**Comment by hhxsv5** [comment]
可以忽略`laravels.json`，因为每次`start`时会重新生成，所以不必担心。

**Comment by 71sprite** [comment]
嗯现在是忽略掉的，只是感觉配置路径会更灵活一些
