### ISSUE TITLE
请问在自定义进程中能否开协程来查询数据库

### ISSUE THREAD

**Issue by doesDWQ** [hhxsv5/laravel-s#192]
请问在自定义进程中能否开协程来查询数据库？

**Comment by hhxsv5** [comment]
可以，同一个进程内，协程实际是串行执行的，通过IO情况合理安排执行顺序。

**Comment by doesDWQ** [comment]
谢谢------------------ 原始邮件 ------------------
发件人: "谢彪"<notifications@github.com>
发送时间: 2019年10月11日(星期五) 晚上8:26
收件人: "hhxsv5/laravel-s"<laravel-s@noreply.github.com>;
抄送: "doesDWQ"<2354513578@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [hhxsv5/laravel-s] 请问在自定义进程中能否开协程来查询数据库 (#192)



可以，同一个进程内，协程实际是串行执行的，通过IO情况合理安排执行顺序。
 
&mdash;

**Comment by doesDWQ** [comment]
再弱弱的问个问题，我想利用自定义进程里面通过协程和通道封装一个循环查库的东东（整合多个接口这样的需求），然后通过ipc通信将数据返回出去，这样会不会造成不同请求之间返回的数据的混乱？------------------ 原始邮件 ------------------
发件人: "谢彪"<notifications@github.com>
发送时间: 2019年10月11日(星期五) 晚上8:26
收件人: "hhxsv5/laravel-s"<laravel-s@noreply.github.com>;
抄送: "doesDWQ"<2354513578@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [hhxsv5/laravel-s] 请问在自定义进程中能否开协程来查询数据库 (#192)



可以，同一个进程内，协程实际是串行执行的，通过IO情况合理安排执行顺序。
 
&mdash;

**Comment by hhxsv5** [comment]
不建议这样做，自定义进程只有一个，占用一个核，效率不高。如果多个接口累计耗时太多，建议从业务上优化。

**Comment by doesDWQ** [comment]
好的，有没有什么方法能够在请求上用上协程？如果不能用上的话，感觉swoole就被弱化了很多。------------------ 原始邮件 ------------------
发件人: "谢彪"<notifications@github.com>
发送时间: 2019年10月12日(星期六) 晚上9:27
收件人: "hhxsv5/laravel-s"<laravel-s@noreply.github.com>;
抄送: "doesDWQ"<2354513578@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [hhxsv5/laravel-s] 请问在自定义进程中能否开协程来查询数据库 (#192)



不建议这样做，自定义进程只有一个，占用一个核，效率不高。如果多个接口累计耗时太多，建议从业务上优化。
 
&mdash;

**Comment by hhxsv5** [comment]
使用协程框架，例如swoft，hyperf

**Comment by doesDWQ** [comment]
谢谢，但是项目在线上跑，换框架似乎不容易。------------------ 原始邮件 ------------------
发件人: "谢彪"<notifications@github.com>
发送时间: 2019年10月14日(星期一) 上午10:18
收件人: "hhxsv5/laravel-s"<laravel-s@noreply.github.com>;
抄送: "doesDWQ"<2354513578@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [hhxsv5/laravel-s] 请问在自定义进程中能否开协程来查询数据库 (#192)



使用协程框架，例如swoft，hyperf
 
&mdash;
