### ISSUE TITLE
Too many arguments, expected arguments "command"

### ISSUE THREAD

**Issue by mtjo** [hhxsv5/laravel-s#193]
Laravel Framework 5.6.39
启动输出这 Too many arguments, expected arguments "command"
/data/laravel5/Laravel # php bin/laravels start 
PHP Symfony\Component\Console\Exception\RuntimeException:  Too many arguments, expected arguments "command". in /data/laravel5/Laravel/vendor/symfony/console/Input/ArgvInput.php on line 183
PHP Stack trace:
PHP   1. {main}() /data/laravel5/Laravel/artisan:0
PHP   2. App\Console\Kernel->handle($input = class Symfony\Component\Console\Input\ArgvInput { private $tokens = array (0 => 'laravels', 1 => 'config'); private $parsed = array (); protected $definition = class Symfony\Component\Console\Input\InputDefinition { private $arguments = array (...); private $requiredCount = 1; private $hasAnArrayArgument = FALSE; private $hasOptional = FALSE; private $options = array (...); private $shortcuts = array (...) }; protected $stream = NULL; protected $options = array (); protected $arguments = array ('command' => 'laravels'); protected $interactive = FALSE }, $output = class Symfony\Component\Console\Output\ConsoleOutput { private $stderr = class Symfony\Component\Console\Output\StreamOutput { private $stream = resource(61) of type (stream); private ${Symfony\Component\Console\Output\Output}verbosity = 32; private ${Symfony\Component\Console\Output\Output}formatter = class Symfony\Component\Console\Formatter\OutputFormatter { ... } }; private $consoleSectionOutputs = array (); private ${Symfony\Component\Console\Output\StreamOutput}stream = resource(53) of type (stream); private ${Symfony\Component\Console\Output\Output}verbosity = 32; private ${Symfony\Component\Console\Output\Output}formatter = class Symfony\Component\Console\Formatter\OutputFormatter { private $decorated = TRUE; private $styles = array (...); private $styleStack = class Symfony\Component\Console\Formatter\OutputFormatterStyleStack { ... } } }) /data/laravel5/Laravel/artisan:37
PHP   3. Illuminate\Console\Application->run($input = class Symfony\Component\Console\Input\ArgvInput { private $tokens = array (0 => 'laravels', 1 => 'config'); private $parsed = array (); protected $definition = class Symfony\Component\Console\Input\InputDefinition { private $arguments = array (...); private $requiredCount = 1; private $hasAnArrayArgument = FALSE; private $hasOptional = FALSE; private $options = array (...); private $shortcuts = array (...) }; protected $stream = NULL; protected $options = array (); protected $arguments = array ('command' => 'laravels'); protected $interactive = FALSE }, $output = class Symfony\Component\Console\Output\ConsoleOutput { private $stderr = class Symfony\Component\Console\Output\StreamOutput { private $stream = resource(61) of type (stream); private ${Symfony\Component\Console\Output\Output}verbosity = 32; private ${Symfony\Component\Console\Output\Output}formatter = class Symfony\Component\Console\Formatter\OutputFormatter { ... } }; private $consoleSectionOutputs = array (); private ${Symfony\Component\Console\Output\StreamOutput}stream = resource(53) of type (stream); private ${Symfony\Component\Console\Output\Output}verbosity = 32; private ${Symfony\Component\Console\Output\Output}formatter = class Symfony\Component\Console\Formatter\OutputFormatter { private $decorated = TRUE; private $styles = array (...); private $styleStack = class Symfony\Component\Console\Formatter\OutputFormatterStyleStack { ... } } }) /data/laravel5/Laravel/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:122
PHP   4. Illuminate\Console\Application->run($input = class Symfony\Component\Console\Input\ArgvInput { private $tokens = array (0 => 'laravels', 1 => 'config'); private $parsed = array (); protected $definition = class Symfony\Component\Console\Input\InputDefinition { private $arguments = array (...); private $requiredCount = 1; private $hasAnArrayArgument = FALSE; private $hasOptional = FALSE; private $options = array (...); private $shortcuts = array (...) }; protected $stream = NULL; protected $options = array (); protected $arguments = array ('command' => 'laravels'); protected $interactive = FALSE }, $output = class Symfony\Component\Console\Output\ConsoleOutput { private $stderr = class Symfony\Component\Console\Output\StreamOutput { private $stream = resource(61) of type (stream); private ${Symfony\Component\Console\Output\Output}verbosity = 32; private ${Symfony\Component\Console\Output\Output}formatter = class Symfony\Component\Console\Formatter\OutputFormatter { ... } }; private $consoleSectionOutputs = array (); private ${Symfony\Component\Console\Output\StreamOutput}stream = resource(53) of type (stream); private ${Symfony\Component\Console\Output\Output}verbosity = 32; private ${Symfony\Component\Console\Output\Output}formatter = class Symfony\Component\Console\Formatter\OutputFormatter { private $decorated = TRUE; private $styles = array (...); private $styleStack = class Symfony\Component\Console\Formatter\OutputFormatterStyleStack { ... } } }) /data/laravel5/Laravel/vendor/laravel/framework/src/Illuminate/Console/Application.php:89
PHP   5. Illuminate\Console\Application->doRun($input = class Symfony\Component\Console\Input\ArgvInput { private $tokens = array (0 => 'laravels', 1 => 'config'); private $parsed = array (); protected $definition = class Symfony\Component\Console\Input\InputDefinition { private $arguments = array (...); private $requiredCount = 1; private $hasAnArrayArgument = FALSE; private $hasOptional = FALSE; private $options = array (...); private $shortcuts = array (...) }; protected $stream = NULL; protected $options = array (); protected $arguments = array ('command' => 'laravels'); protected $interactive = FALSE }, $output = class Symfony\Component\Console\Output\ConsoleOutput { private $stderr = class Symfony\Component\Console\Output\StreamOutput { private $stream = resource(61) of type (stream); private ${Symfony\Component\Console\Output\Output}verbosity = 32; private ${Symfony\Component\Console\Output\Output}formatter = class Symfony\Component\Console\Formatter\OutputFormatter { ... } }; private $consoleSectionOutputs = array (); private ${Symfony\Component\Console\Output\StreamOutput}stream = resource(53) of type (stream); private ${Symfony\Component\Console\Output\Output}verbosity = 32; private ${Symfony\Component\Console\Output\Output}formatter = class Symfony\Component\Console\Formatter\OutputFormatter { private $decorated = TRUE; private $styles = array (...); private $styleStack = class Symfony\Component\Console\Formatter\OutputFormatterStyleStack { ... } } }) /data/laravel5/Laravel/vendor/symfony/console/Application.php:149
PHP   6. Symfony\Component\Console\Input\ArgvInput->bind($definition = class Symfony\Component\Console\Input\InputDefinition { private $arguments = array ('command' => class Symfony\Component\Console\Input\InputArgument { ... }); private $requiredCount = 1; private $hasAnArrayArgument = FALSE; private $hasOptional = FALSE; private $options = array ('help' => class Symfony\Component\Console\Input\InputOption { ... }, 'quiet' => class Symfony\Component\Console\Input\InputOption { ... }, 'verbose' => class Symfony\Component\Console\Input\InputOption { ... }, 'version' => class Symfony\Component\Console\Input\InputOption { ... }, 'ansi' => class Symfony\Component\Console\Input\InputOption { ... }, 'no-ansi' => class Symfony\Component\Console\Input\InputOption { ... }, 'no-interaction' => class Symfony\Component\Console\Input\InputOption { ... }, 'env' => class Symfony\Component\Console\Input\InputOption { ... }); private $shortcuts = array ('h' => 'help', 'q' => 'quiet', 'v' => 'verbose', 'vv' => 'verbose', 'vvv' => 'verbose', 'V' => 'version', 'n' => 'no-interaction') }) /data/laravel5/Laravel/vendor/symfony/console/Application.php:208
PHP   7. Symfony\Component\Console\Input\ArgvInput->parse() /data/laravel5/Laravel/vendor/symfony/console/Input/Input.php:55
PHP   8. Symfony\Component\Console\Input\ArgvInput->parseArgument($token = 'config') /data/laravel5/Laravel/vendor/symfony/console/Input/ArgvInput.php:86
 _                               _  _____ 
| |                             | |/ ____|
| |     __ _ _ __ __ ___   _____| | (___  
| |    / _` | '__/ _` \ \ / / _ \ |\___ \ 
| |___| (_| | | | (_| |\ V /  __/ |____) |
|______\__,_|_|  \__,_| \_/ \___|_|_____/ 
                                           
Speed up your Laravel/Lumen
>>> Components
+---------------------------+---------+
| Component                 | Version |
+---------------------------+---------+
| PHP                       | 7.2.21  |
| Swoole                    | 4.4.5   |
| LaravelS                  | 3.5.12  |
| Laravel Framework [local] | 5.6.39  |
+---------------------------+---------+
>>> Protocols
+-----------+--------+-------------------+----------------+
| Protocol  | Status | Handler           | Listen At      |
+-----------+--------+-------------------+----------------+
| Main HTTP | On     | Laravel Framework | 127.0.0.1:5200 |
+-----------+--------+-------------------+----------------+
>>> Feedback: https://github.com/hhxsv5/laravel-s
[2019-10-12 15:55:12] [TRACE] Swoole is running, press Ctrl+C to quit.

**Comment by hhxsv5** [comment]
Issue格式乱了，我本地未重现，请提交一个工程的压缩包。
