### ISSUE TITLE
laravelS和laravel-excel3.1冲突，导致报错无法导出数据

### ISSUE THREAD

**Issue by WangQuanTang** [hhxsv5/laravel-s#196]
[2019-10-21 16:53:27] [TRACE] Swoole is running, press Ctrl+C to quit.
PHP Fatal error:  Method Encore\Admin\Grid\Tools\Paginator::__toString() must not throw an exception, caught BadMethodCallException: Method Illuminate\Database\Eloquent\Collection::firstItem does not exist. in /www/wwwroot/XXX/storage/framework/views/7e133bcce95b35842dc3896fa8ba106ca4f271b1.php on line 0

   Symfony\Component\Debug\Exception\FatalErrorException  : Method Encore\Admin\Grid\Tools\Paginator::__toString() must not throw an exception, caught BadMethodCallException: Method Illuminate\Database\Eloquent\Collection::firstItem does not exist.
在未安装使用LaravelS的项目下，使用laravel-excel没有问题和报错，但是在有的项目下，就会报错！使用框架自带的数据导出报错：swoole exit;查询了swoole文档：
https://wiki.swoole.com/wiki/page/501.html ,修改了相应的方法之后还是不行，报了其他错！

**Comment by hhxsv5** [comment]
给个重现的示例。

**Comment by WangQuanTang** [comment]
> 给个重现的示例。
环境和相关版本：
laravel：laravel/framework": "5.8.*； 
laravel-excel：maatwebsite/excel": "^3.1；
php: "^7.1.3",
laravel-admin：encore/laravel-admin": "^1.7.2
按照laravel-excel的文档（https://docs.laravel-excel.com/3.1/getting-started/installation.html）的安装方式安装成功！


> **使用方式：**

1.创建导出类。
    
    <?php

    namespace App\Admin\Extensions;

    use Encore\Admin\Grid\Exporters\ExcelExporter; 

    class PostsExporter extends ExcelExporter
    {
        protected $fileName = '文章列表.xlsx';

        protected $columns = [
            'id'      => 'ID',
            'title'   => '标题',
            'content' => '内容',
        ];
    }`

2.在模板控制器中使用（laravel-admin的grid中）：

    use App\Admin\Extensions\PostsExporter;

    $grid->exporter(new PostsExporter());
具体操作可参考：https://laravel-admin.org/docs/zh/model-grid-export

使用：
laravel-S在putty运行状态：
` _                               _  _____
| |                             | |/ ____|
| |     __ _ _ __ __ ___   _____| | (___
| |    / _` | '__/ _` \ \ / / _ \ |\___ \
| |___| (_| | | | (_| |\ V /  __/ |____) |
|______\__,_|_|  \__,_| \_/ \___|_|_____/

Speed up your Laravel/Lumen
>>> Components
+---------------------------+---------+
| Component                 | Version |
+---------------------------+---------+
| PHP                       | 7.2.20  |
| Swoole                    | 4.3.5   |
| LaravelS                  | 3.5.10  |
| Laravel Framework [local] | 5.8.35  |
+---------------------------+---------+
>>> Protocols
+----------------+--------+-----------------------+----------------+
| Protocol       | Status | Handler               | Listen At      |
+----------------+--------+-----------------------+----------------+
| Main HTTP      | On     | Laravel Framework     | 127.0.0.1:8200 |
| Main WebSocket | On     | App\Service\WebSocket | 127.0.0.1:8200 |
+----------------+--------+-----------------------+----------------+
>>> Feedback: https://github.com/hhxsv5/laravel-s
[2019-10-25 11:22:43] [TRACE] Swoole is running, press Ctrl+C to quit.
`
使用导出全部后，窗口提示：
PHP Fatal error:  Method Encore\Admin\Grid\Tools\Paginator::__toString() must no                                                                                                                                                             t throw an exception, caught BadMethodCallException: Method Illuminate\Database\                                                                                                                                                             Eloquent\Collection::firstItem does not exist. in /www/wwwroot/sdxz.yunnto.cn/st                                                                                                                                                             orage/framework/views/de157d8e42a184e1ba9ef4552aea83053705a3f4.php on line 0

   Symfony\Component\Debug\Exception\FatalErrorException  : Method Encore\Admin\                                                                                                                                                             Grid\Tools\Paginator::__toString() must not throw an exception, caught BadMethod                                                                                                                                                             CallException: Method Illuminate\Database\Eloquent\Collection::firstItem does no                                                                                                                                                             t exist.

  at /www/wwwroot/sdxz.yunnto.cn/storage/framework/views/de157d8e42a184e1ba9ef45                                                                                                                                                             52aea83053705a3f4.php:0
    1| <div class="box">
    2|     <?php if(isset($title)): ?>
    3|     <div class="box-header with-border">
    4|         <h3 class="box-title"> <?php echo e($title, false); ?></h3>
    5|     </div>
    6|     <?php endif; ?>
    7|
    8|     <?php if( $grid->showTools() || $grid->showExportBtn() || $grid->show                                                                                                                                                             CreateBtn() ): ?>
    9|     <div class="box-header with-border">


   Whoops\Exception\ErrorException  : Method Encore\Admin\Grid\Tools\Paginator::                                                                                                                                                             __toString() must not throw an exception, caught BadMethodCallException: Method                                                                                                                                                              Illuminate\Database\Eloquent\Collection::firstItem does not exist.

  at /www/wwwroot/sdxz.yunnto.cn/storage/framework/views/de157d8e42a184e1ba9ef45                                                                                                                                                             52aea83053705a3f4.php:0
    1| <div class="box">
    2|     <?php if(isset($title)): ?>
    3|     <div class="box-header with-border">
    4|         <h3 class="box-title"> <?php echo e($title, false); ?></h3>
    5|     </div>
    6|     <?php endif; ?>
    7|
    8|     <?php if( $grid->showTools() || $grid->showExportBtn() || $grid->show                                                                                                                                                             CreateBtn() ): ?>
    9|     <div class="box-header with-border">

  Exception trace:

  1   Whoops\Run::handleError("Method Encore\Admin\Grid\Tools\Paginator::__toStr                                                                                                                                                             ing() must not throw an exception, caught BadMethodCallException: Method Illumin                                                                                                                                                             ate\Database\Eloquent\Collection::firstItem does not exist.", "/www/wwwroot/sdxz                                                                                                                                                             .yunnto.cn/storage/framework/views/de157d8e42a184e1ba9ef4552aea83053705a3f4.php"                                                                                                                                                             )
      /www/wwwroot/sdxz.yunnto.cn/vendor/filp/whoops/src/Whoops/Run.php:433

  2   Whoops\Run::handleShutdown()
      [internal]:0
注：1-9里为blade模板的html代码，被屏蔽！

**Comment by WangQuanTang** [comment]
> 给个重现的示例。

感谢作者百忙之中的回复！

**Comment by hhxsv5** [comment]
@WangQuanTang 调整下markdown格式，乱了

**Comment by WangQuanTang** [comment]
> @WangQuanTang 调整下markdown格式，乱了

`    
    >>> Feedback: https://github.com/hhxsv5/laravel-s

    [2019-10-25 17:21:42] [TRACE] Swoole is running, press Ctrl+C to quit.
    PHP Fatal error:  Method Encore\Admin\Grid\Tools\Paginator::__toString() must not throw an exception, 
    caught BadMethodCallException: 
    Method Illuminate\Database\Eloquent\Collection::firstItem does not exist. 
    in/www/wwwroot/sdxz.yunnto.cn/storage/framework/views/de157d8e42a184e1ba9ef4552aea83053705a3f4.php on line 0                                                                                                                                                           

    Symfony\Component\Debug\Exception\FatalErrorException  : Method Encore\Admin\ 
    Grid\Tools\Paginator::__toString() must not throw an exception, caught BadMethod CallException: Method Illuminate\Database\Eloquent\Collection::firstItem does not  exist.at /www/wwwroot/sdxz.yunnto.cn/storage/framework/views/de157d8e42a184e1ba9ef45

    1| <div class="box">
    2|     <?php if(isset($title)): ?>
    3|     <div class="box-header with-border">
    4|         <h3 class="box-title"> <?php echo e($title, false); ?></h3>
    5|     </div>
    6|     <?php endif; ?>
    7|
    8|     <?php if( $grid->showTools() || $grid->showExportBtn() || $grid->show 
    CreateBtn() ): ?>
    9|     <div class="box-header with-border">
    Whoops\Exception\ErrorException  : Method Encore\Admin\Grid\Tools\Paginator::__toString() must not throw an exception, caught BadMethodCallException: Method  Illuminate\Database\Eloquent\Collection::firstItem does not exist.
    at /www/wwwroot/sdxz.yunnto.cn/storage/framework/views/de157d8e42a184e1ba9ef45   
    52aea83053705a3f4.php:0

    1| <div class="box">
    2|     <?php if(isset($title)): ?>
    3|     <div class="box-header with-border">
    4|         <h3 class="box-title"> <?php echo e($title, false); ?></h3>
    5|     </div>
    6|     <?php endif; ?>
    7|
    8|     <?php if( $grid->showTools() || $grid->showExportBtn() || $grid->showCreateBtn() ): ?>
    9|     <div class="box-header with-border">

    Exception trace:

    1   Whoops\Run::handleError("Method Encore\Admin\Grid\Tools\Paginator::__toString() must not throw an exception, caught BadMethodCallException: Method Illuminate\Database\Eloquent\Collection::firstItem does not exist.","/www/wwwroot/sdxz.yunnto.cn/storage/framework/views/de157d8e42a184e1ba9ef4552aea83053705a3f4.php")
      /www/wwwroot/sdxz.yunnto.cn/vendor/filp/whoops/src/Whoops/Run.php:433
    2   Whoops\Run::handleShutdown()
      [internal]:0
    
`

**Comment by uniteweiwei** [comment]
对的,使用任何导出包,全部是有die或者exit
