### ISSUE TITLE
laravels使用tcp-rpc远程调用hyperf协程框架

### ISSUE THREAD

**Issue by doesDWQ** [hhxsv5/laravel-s#197]
一直想用swoole的协程，奈何laravsls在请求中无法直接使用到协程，看到hyperf框架，觉得不错，开发者们和用户都很活跃，生态相对来说还是传统php比较完善(而且公司项目也是跑在lavravels上面，不可能完全废弃)，所以就想用一个性能损耗比较小的方式来调用hyperf，看到了hyperf文档上的json-rpc的tcp调用方式觉得性能损耗相对较小,单个远程调用的平均耗时在个位数毫秒级别（本地虚拟机测试的结果），于是封装了一个简单的客户端，写的比较简单，各位大牛看一下，如果有什么问题，请不吝指出。以下是代码：

`<?php

namespace App\Services;

class HyperfJsonRpc
{
    private static $client = null;
    private static $host = '';
    private static $port = 0;

    private static function createClient() {
        //初始化端口和ip
        if(empty(self::$host) || empty(self::$port)){
            self::$host = config('hyperf_rpc.host');
            self::$port = config('hyperf_rpc.port');
        }

        //创建新的client并且返回
        $client = new \Swoole\Client(SWOOLE_SOCK_TCP);  //默认创建的client就是同步阻塞的
        try{
            //连接超时时间设置为2秒
            if(!$client->connect(self::$host, self::$port, 2)){
                throw new \Error("connect failed. Error: {$client->errCode}\n");    //正常情况下应该写日志
            }
        }catch (\Exception $e){
            throw new \Error('rpc服务端连接失败:'.$e->getMessage());
        }

        self::$client = $client;
    }

    //为什么不每次连接tcp客户端后都关闭连接呢？因为频繁的连接和关闭会消耗服务端的性能，非常多的tcp连接会处于close_wait的状态下面，实际上swoole在收到关闭信号的时候会自动关闭掉客户端，即使不关闭每条进程一个close_wai也不影响服务端的性能,返回数据为空字符串的情况，1重试次数超过3次，2 hyperf rpc服务端关闭
    public static function callRpcMethod(string $method,array $params){
        $data = [
            'jsonrpc'=>'2.0',
            'method'=>$method,
            'params'=>$params,
            'id'=>null,
        ];

        if(!self::$client){
            self::createClient();
        }

        $message = json_encode($data)."\r\n";
        $data = "";
        //当rpc-tcp服务端报错的时候send函数和recv函数都会报错，所以这里需要捕捉异常
        $i = 0;
        while(true){
            try{
                self::$client->send($message);
                $data = self::$client->recv();
            }catch (\Exception $e){
                //在hyperf重启时tcp连接会丢失产生错误，此时需要重新连接
                self::createClient();
            }
            //数据不为空，或者重试超过3次时退出循环，一般来说就是三次，次数太多会出现问题
            if(!empty($data) || $i>3){
                break;
            }
            $i++;
        }

        //return $data;
        //处理一下结果
        if(!empty($data)){
            $data = (array)json_decode($data,true);
            if(isset($data['result'])){
                return $data['result'];
            }else{
                return false;
            }
        }else{
            return false;   //不存在的时候返回false
        }

    }
}`

**Comment by hhxsv5** [comment]
请格式化你的代码，现在这样没法看。

**Comment by doesDWQ** [comment]
哎呀，那天我提交的时候不是这样的，非常抱歉，明天早上再提交一下更完善的代码

**Comment by doesDWQ** [comment]
issue提的太少了，没经验，没格式化代码，抱歉。

**Comment by tai1030** [comment]
我的項目現在已生產環境上，用Laravel (PHP-FPM) 作客戶端，以JSON RPC的協議調用Hyperf的服務端。
我們同時實現了TCP及HTTP雙協議，供應用方 (Laravel) 以配置的方式自行選擇協議。

在Hyperf，要同時打開HTTP及TCP進入同一RPC服務不困難，
但在Laravel客戶端，需要實作兩個不同的RPC客戶端。
HTTP，選用了 [graze/guzzle-jsonrpc](https://github.com/graze/guzzle-jsonrpc) 這個套件，
能完美地接駁Hyperf的JSON-RPC服務端，而且支援guzzle promise異步等待。
TCP那邊，在github上找不到好用的套件，所以自行用stream_socket_client, fwrite, stream_socket_recvfrom實現。
能設定 "STREAM_CLIENT_PERSISTENT" 以打開長連接模式。
而且因為stream能以非阻塞模式讀取回應，所以能實現guzzle promise。
但是在生產環境運行了一段時間，發現穩定性有待改善，fclose那些不易處理。
所以暫時切換使用HTTP，由於很多事情已被curl及guzzle處理得很好，速度不是相差十分遠，但穩定性較高。

TCP請求格式如下，如你參考一下：
```
json_encode([
    'jsonrpc' => '2.0',
    'method' => '/aaa_bbb_ccc/methodNameAbc',
    'params' => [
        'var1' => 'aaa',
        'var2' => 'bbb',
    ],
    'id' => Uuid::generate(),
], JSON_UNESCAPED_UNICODE);
// json encode後，結尾再加一個 \r\n 作EOF
```

假設你在Hyperf的服務類名稱是"AaaBbbCcc"，方法名是 "methodNameAbc"，
那method就是 '/aaa_bbb_ccc/methodNameAbc'

目前這個Laravel的項目，正在由PHP-FPM升級到LaravelS中。

**Comment by JimChan191** [comment]
> 我的項目現在已生產環境上，用Laravel (PHP-FPM) 作客戶端，以JSON RPC的協議調用Hyperf的服務端。
> 我們同時實現了TCP及HTTP雙協議，供應用方 (Laravel) 以配置的方式自行選擇協議。
> 
> 在Hyperf，要同時打開HTTP及TCP進入同一RPC服務不困難，
> 但在Laravel客戶端，需要實作兩個不同的RPC客戶端。
> HTTP，選用了 [graze/guzzle-jsonrpc](https://github.com/graze/guzzle-jsonrpc) 這個套件，
> 能完美地接駁Hyperf的JSON-RPC服務端，而且支援guzzle promise異步等待。
> TCP那邊，在github上找不到好用的套件，所以自行用stream_socket_client, fwrite, stream_socket_recvfrom實現。
> 能設定 "STREAM_CLIENT_PERSISTENT" 以打開長連接模式。
> 而且因為stream能以非阻塞模式讀取回應，所以能實現guzzle promise。
> 但是在生產環境運行了一段時間，發現穩定性有待改善，fclose那些不易處理。
> 所以暫時切換使用HTTP，由於很多事情已被curl及guzzle處理得很好，速度不是相差十分遠，但穩定性較高。
> 
> TCP請求格式如下，給你參考一下：
> 
> ```
> json_encode([
>     'jsonrpc' => '2.0',
>     'method' => '/aaa_bbb_ccc/methodNameAbc',
>     'params' => [
>         'var1' => 'aaa',
>         'var2' => 'bbb',
>     ],
>     'id' => Uuid::generate(),
> ], JSON_UNESCAPED_UNICODE);
> // json encode後，結尾再加一個 \r\n 作EOF
> ```
> 
> 假設你在Hyperf的服務類名稱是"AaaBbbCcc"，方法名是 "methodNameAbc"，
> 那method就是 '/aaa_bbb_ccc/methodNameAbc'
> 
> 目前這個Laravel的項目，正在由PHP-FPM升級到LaravelS中。
> 這個HTTP+TCP雙協議的JSON RPC Guzzle Promise客戶端，下周我會把它套件化，放到github上讓大家PR改良一下^^

**tai1030** 雷猴哇！有个问题请教一下雷哋：

**服务端：hyperf2.0 +jsonrpc-http**

```
namespace App\Service;

use Hyperf\RpcServer\Annotation\RpcService;

/**
 *
 * @RpcService(name="AuthorizeService", protocol="jsonrpc-http", server="jsonrpc-http")
 */
class AuthorizeService implements AuthorizeServiceInterface
{
    public function add(int $a, int $b): int
    {
        // 这里是服务方法的具体实现
        return $a + $b;
    }
}

```
**配置文件 config/autoload/server.php** ：

```
<?php

declare(strict_types=1);
/**
 * This file is part of Hyperf.
 *
 * @link     https://www.hyperf.io
 * @document https://hyperf.wiki
 * @contact  group@hyperf.io
 * @license  https://github.com/hyperf/hyperf/blob/master/LICENSE
 */
use Hyperf\Server\Server;
use Hyperf\Server\SwooleEvent;

return [
    'mode' => SWOOLE_PROCESS,
    'servers' => [
        [
            'name' => 'http',
            'type' => Server::SERVER_HTTP,
            'host' => '0.0.0.0',
            'port' => 9501,
            'sock_type' => SWOOLE_SOCK_TCP,
            'callbacks' => [
                SwooleEvent::ON_REQUEST => [Hyperf\HttpServer\Server::class, 'onRequest'],
            ],
        ],
        [
            'name' => 'jsonrpc-http',
            'type' => Server::SERVER_HTTP,
            'host' => '0.0.0.0',
            'port' => 9504,
            'sock_type' => SWOOLE_SOCK_TCP,
            'callbacks' => [
                SwooleEvent::ON_REQUEST => [\Hyperf\JsonRpc\HttpServer::class, 'onRequest'],
            ],
        ],
    ],

];

```


**客户端：使用Lumen8.0 + graze/guzzle-jsonrpc 3.0.0**

```
<?php


namespace App\Http\Controllers;

use Graze\GuzzleHttp\JsonRpc\Client as JsonRpcClient;

class DeviceController extends Controller
{
    public function login()
    {
        $client = JsonRpcClient::factory('http://127.0.0.1:9504');
        $response = $client->send($client->request(121,'/authorize_service/add',["a" => 1, "b" => 2]));
        return $response;
    }
}
```

**结果为：**

```
{
    "jsonrpc": "2.0",
    "id": 121,
    "error": {
        "code": -32601,
        "message": "Method not found.",
        "data": null
    },
    "context": []
}
```

“method not found ” 是不是由于客户端的url拼接不对导致的呢？正确的调用是怎么样的？
请帮忙睇下，多谢噻！
