### ISSUE TITLE
laravel-s每天都会报错component ticket is expired hint，要手动重启才正常

### ISSUE THREAD

**Issue by Double-Jin** [hhxsv5/laravel-s#198]
## 我用的环境

* PHP 版本：7.2.22
* overtrue/wechat 版本：4.1
* 是否使用了框架？框架名称：laravel-s

## 问题及现象
项目是第三方平台，需要接收绑定商户ticket，查看日志是有接收到授权事件url的，当laravel-s启动后接收到授权事件url是正常的，第当第二天后就会报60015 component ticket is expired hint，需要重启laravel-s第下一次接收才正常，有没有解决方法

![1573002695359](https://user-images.githubusercontent.com/48013971/68260925-6db76600-0079-11ea-8e66-e36a7ba582c2.jpg)
![1573002963193](https://user-images.githubusercontent.com/48013971/68260929-73ad4700-0079-11ea-9002-7efeb1992e3f.jpg)
![1573004387126](https://user-images.githubusercontent.com/48013971/68260934-76a83780-0079-11ea-8210-4f6dc0b6e7ae.jpg)

**Comment by Double-Jin** [comment]
改为redis后好像正常

**Comment by hhxsv5** [comment]
可能是`easywechat`缓存问题，建议你跟踪代码排查。
