### ISSUE TITLE
swManager_check_exit_status

### ISSUE THREAD

**Issue by Harrypoters** [hhxsv5/laravel-s#199]
1. Tell us your software version
    How to know it?
    ```Bash
    # PHP
    php -v
    # Swoole
    php --ri swoole
    # Laravel
    grep 'laravel/framework' composer.json
    # Lumen
    grep 'laravel/lumen-framework' composer.json
    ```

    | Software | Version |
    | --------- | --------- |
    | PHP | 7.1.10 |
    | Swoole | 4.2.5 |
    | Laravel/Lumen | Laravel (5.8.30) |

2. Detail description about this issue(error/log)

WARNING	swManager_check_exit_status: worker#6 abnormal exit, status=255, signal=0 [2019-11-08 08:49:22 *23603.15]	ERROR	zm_deactivate_swoole (ERROR 503): Fatal error: Uncaught TypeError: Argument 1 passed to Illuminate\Auth\SessionGuard::setRequest() must be an instance of Symfony\Component\HttpFoundation\Request, null given, called in **************/vendor/laravel/framework/src/Illuminate/Auth/AuthManager.php on line 139 and defined in **************/vendor/laravel/framework/src/Illuminate/Auth/SessionGuard.php:795 Stack trace: #0 **************/vendor/laravel/framework/src/Illuminate/Auth/AuthManager.php(139): Illuminate\Auth\SessionGuard->setRequest(NULL) #1 **************/vendor/laravel/framework/src/Illuminate/Auth/AuthManager.php(94): Illuminate\Auth\AuthManager->createSessionDriver('web', Array) #2 **************/vendor/laravel/framework/src/Illuminate/Auth/AuthManager.php(68): Illuminate\Auth\AuthManager->resolve('web') #3 **************/vendor/laravel/framework/src/Illuminate/Auth/AuthManager.php(297): Illuminate\Auth\AuthManager->guard()

3. Give us a `reproducible` code block and `steps`
      在laravels.php 加入SessionCleaner、AuthCleaner这两个之后出现警示
 ```
 'cleaners' => [
        Hhxsv5\LaravelS\Illuminate\Cleaners\SessionCleaner::class,
        Hhxsv5\LaravelS\Illuminate\Cleaners\AuthCleaner::class,
        Hhxsv5\LaravelS\Illuminate\Cleaners\JWTCleaner::class,
    ],
```

**Comment by hhxsv5** [comment]
我本地没有重现，可否上传一个你的例子到这里？

**Comment by Harrypoters** [comment]
@hhxsv5 
https://github.com/Harrypoters/laravel-swoole-test.git
用本地环境没问题，用 homestead 环境的话，会出现
![image](https://user-images.githubusercontent.com/24694539/68844204-62f97280-0704-11ea-867e-0c02ffeec2d8.png)

**Comment by hhxsv5** [comment]
你这是用了[Dingo API](https://github.com/dingo/api)，它不兼容Swoole的运行模式。

**Comment by Harrypoters** [comment]
那有什么办法可以兼容的吗

**Comment by Harrypoters** [comment]
@hhxsv5 也不对吧，Swoole\Table 这个报错，我是在本地运行没有问题的哦；
你说的Dingo 不兼容，导致 TypeError: Argument 1 passed to Illuminate\Auth\SessionGuard::setRequest() 报错么？

**Comment by hhxsv5** [comment]
`Swoole\Table`是Swoole扩展没配置对(可能fastcgi/cli的php.ini是分离的)，你看那调用栈，入口文件是`index.php`，说明还是走的FPM，而不是LaravelS。`Dingo`会导致那个TypeError。

**Comment by Harrypoters** [comment]
尝试过了，没有 `Dingo` 也会出现 `TypeError` 错误
