### ISSUE TITLE
启动的时候有未知事件监听

### ISSUE THREAD

**Issue by kency** [hhxsv5/laravel-s#20]
php7.1.14 swoole2.0.7
Warning: Swoole\Server::on(): Unknown event types[WorkerExit] in /workspace/localsite/eMonitor/vendor/hhxsv5/laravel-s/src/Swoole/Server.php on line 54

第54行
if (version_compare(\swoole_version(), '1.9.17', '>=')) {
            $this->swoole->on('WorkerExit', [$this, 'onWorkerExit']);
        }

swoole2.0.7 的server里是不是没有了workerExit事件，swoole文档真tm差劲

**Comment by hhxsv5** [comment]
收到，谢谢反馈！

**Comment by hhxsv5** [comment]
解决的两个方案
1. 升级`Swoole` `>=2.0.8`，[Swoole Issue](https://github.com/swoole/swoole-src/issues/1538)。
2. LaravelS移除`WorkerExit`事件，见[v1.10.7](https://github.com/hhxsv5/laravel-s/releases/tag/v1.10.7)。

**Comment by kency** [comment]
速度，谢谢
