### ISSUE TITLE
Assets (css, js) being redirected to https rather than http

### ISSUE THREAD

**Issue by juber-ivre** [hhxsv5/laravel-s#201]
![image](https://user-images.githubusercontent.com/48788224/68547737-e18ca200-03dc-11ea-9b33-bf89a77f4190.png)

Had that working fine for a while but right now the application starts well on http but all assets are pointing to https. 

Thought initially was something with nginx in which I'm using the suggested configuration but even if I hit the exposed port 5200 I get the same results.

![image](https://user-images.githubusercontent.com/48788224/68547770-4d6f0a80-03dd-11ea-93cd-2a13c84b003c.png)

Any thoughts guys???

Many thanks in advance.

**Comment by hhxsv5** [comment]
It is recommended to respond the static resources via Nginx.
Of course, you can also respond to them via Swoole, so you need to enable [handle_static](https://github.com/hhxsv5/laravel-s/blob/master/Settings.md).

**Comment by juber-ivre** [comment]
Yep, that what I have but it's still redirecting to https. 

![image](https://user-images.githubusercontent.com/48788224/68549589-bceef500-03f1-11ea-89f6-7a1081cc7862.png)

I set it as false and left it down to nginx and set it to true to test that locally but I got same results.

**Comment by qq2504021719** [comment]
-  `swoole`默认没有支持`https`，需要配置

- `laravels.php`加配置如下
```php
'swoole' => [
    ...
    // HTTPS
    'ssl_cert_file'      => 'HTTPS证书',
    'ssl_key_file'       => 'HTTPS证书',
    ...
],
```

- 注意,`nginx`就不用再配置`https`了

**Comment by juber-ivre** [comment]
Cheers @qq2504021719  will try that out.
