### ISSUE TITLE
[2006] mysql has gone away

### ISSUE THREAD

**Issue by logan-liang** [hhxsv5/laravel-s#202]
1. Tell us your software version
    How to know it?
    ```Bash
    # PHP
    php -v
    # Swoole
    php --ri swoole
    # Laravel
    grep 'laravel/framework' composer.json
    # Lumen
    grep 'laravel/lumen-framework' composer.json
    ```

    | Software | Version |
    | --------- | --------- |
     PHP                       | 7.1.6                                    |
    | Swoole                    | 4.2.7                                    |
   | LaravelS                  | 3.5.10                                   |
| Laravel Framework [local] | Lumen (5.5.2) (Laravel Components 5.5.*)

2. Detail description about this issue(error/log)

    我在使用laravel-s时，mysql总是会提示mysql has gone away。配置文件已经重新注册了单利模式。

3. Give us a `reproducible` code block and `steps`

    
![image](https://user-images.githubusercontent.com/51988601/68551035-8a6de800-0443-11ea-8b04-796c21c6c0af.png)

**Comment by hhxsv5** [comment]
不需要清理这两个Provider，你开启持久连接了吗？

**Comment by logan-liang** [comment]
![image](https://user-images.githubusercontent.com/51988601/68570223-13643e00-049b-11ea-9b6d-4fe4b196527f.png)

是开启了的，我看到文档上说明，如果连接断开，会自动处理，但是目前好像不生效。

**Comment by hhxsv5** [comment]
我本地没复现，上传一个脱敏的、简单的、可重现的例子(打包工程)吧

**Comment by zhimma** [comment]
我也遇到了，并且也是开启了PDO::ATTR_PERSISTENT    => true

**Comment by hhxsv5** [comment]
Laravel 5.1+ 在执行SQL时会[检测连接状态](https://github.com/laravel/framework/blob/6.x/src/Illuminate/Database/DetectsLostConnections.php#L20)，如果连接断开，会自动重连。
这里有一个详细的文章来解释"MySQL server has gone away"：https://haydenjames.io/mysql-server-has-gone-away-error-solutions/

**Comment by xianlinzhang** [comment]
这边也遇到了，有解决方案吗？ # @zhimma @logan-liang @hhxsv5
