### ISSUE TITLE
http和https压测出来QPS相差几倍，大家知道是什么问题吗?

### ISSUE THREAD

**Issue by qq2504021719** [hhxsv5/laravel-s#203]
####  http和https压测出来QPS相差几倍,大家知道是什么问题吗?

> 服务器`4核16G`,同一个接口地址，把https`配置在NGINX`和`配置在Laravel-s`里面结果都是一样的

    # http QPS
    454
    # https QPS
    102

#### 推测

> 是不是`swoole`效验`HTTPS`的耗时

#### 对比图

![image](https://user-images.githubusercontent.com/17893768/68576190-9b9d1000-04a8-11ea-86da-5d2504496e99.png)

**Comment by hhxsv5** [comment]
看起来这个压测走了外网？

压测注意事项：
1. 先阅读：https://wiki.swoole.com/wiki/page/62.html
2. 注意各个中间件，默认的Session中间件基于文件，io性能非常差。
3. 压空接口，目的在于对比框架的消耗，对比fpm，快慢都是相对的。
4. 如果代码中有类似sleep的同步阻塞操作，那qps自然不会高。
5. 压测时最好在内网测试，避免网络带宽因素影响结果。

**Comment by totwoto** [comment]
请问一下 , 怎么样才能 把https配置在NGINX或者配置在Laravel-s 呢?

**Comment by qq2504021719** [comment]
> 看起来这个压测走了外网？
> 
> 压测注意事项：
> 
> 1. 先阅读：https://wiki.swoole.com/wiki/page/62.html
> 2. 注意各个中间件，默认的Session中间件基于文件，io性能非常差。
> 3. 压空接口，目的在于对比框架的消耗，对比fpm，快慢都是相对的。
> 4. 如果代码中有类似sleep的同步阻塞操作，那qps自然不会高。
> 5. 压测时最好在内网测试，避免网络带宽因素影响结果。



> 看起来这个压测走了外网？
> 
> 压测注意事项：
> 
> 1. 先阅读：https://wiki.swoole.com/wiki/page/62.html
> 2. 注意各个中间件，默认的Session中间件基于文件，io性能非常差。
> 3. 压空接口，目的在于对比框架的消耗，对比fpm，快慢都是相对的。
> 4. 如果代码中有类似sleep的同步阻塞操作，那qps自然不会高。
> 5. 压测时最好在内网测试，避免网络带宽因素影响结果。

**Comment by qq2504021719** [comment]
### laravel-s配置
-  `swoole`默认没有支持`https`，需要配置

- `laravels.php`加配置如下
```php
'swoole' => [
    ...
    // HTTPS
    'ssl_cert_file'      => 'HTTPS证书存储目录',
    'ssl_key_file'       => 'HTTPS证书存储目录',
    ...
],
```

- 注意,这里`nginx`就不用再配置`https`了。

### nginx配置

> 百度，nginx配置https。

**Comment by totwoto** [comment]
好,多谢指点



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "潘亮"<notifications@github.com&gt;; 
发送时间: 2019年11月12日(星期二) 下午5:00
收件人: "hhxsv5/laravel-s"<laravel-s@noreply.github.com&gt;; 
抄送: "胡辰飞"<1028385671@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [hhxsv5/laravel-s] http和https压测出来QPS相差几倍，大家知道是什么问题吗? (#203)




laravel-s配置
  
 
swoole默认没有支持https，需要配置
 
 
 
laravels.php加配置如下
 
  'swoole' =&gt; [     ...     // HTTPS     'ssl_cert_file'      =&gt; 'HTTPS证书存储目录',     'ssl_key_file'       =&gt; 'HTTPS证书存储目录',     ... ],
  
注意,这里nginx就不用再配置https了。
  
nginx配置
  
百度，nginx配置https。

**Comment by totwoto** [comment]
你好,能再请教你个问题吗?
我用官网提供的 结合apache使用的例子,发现,无论是动态资源还是静态资源,都被转发到了 swoole监听的端口上,
按官网提供的例子,怎样配置能做到动态请求和静态请求分离呢?







------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"潘亮"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月12日(星期二) 下午5:00
收件人:&nbsp;"hhxsv5/laravel-s"<laravel-s@noreply.github.com&gt;;
抄送:&nbsp;"胡辰飞"<1028385671@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [hhxsv5/laravel-s] http和https压测出来QPS相差几倍，大家知道是什么问题吗? (#203)




laravel-s配置
  
 
swoole默认没有支持https，需要配置
 
 
 
laravels.php加配置如下
 
  'swoole' =&gt; [     ...     // HTTPS     'ssl_cert_file'      =&gt; 'HTTPS证书存储目录',     'ssl_key_file'       =&gt; 'HTTPS证书存储目录',     ... ],
  
注意,这里nginx就不用再配置https了。
  
nginx配置
  
百度，nginx配置https。

**Comment by RussellCao824** [comment]
> ### laravel-s配置
> * `swoole`默认没有支持`https`，需要配置
> * `laravels.php`加配置如下
> 
> ```
> 'swoole' => [
>     ...
>     // HTTPS
>     'ssl_cert_file'      => 'HTTPS证书存储目录',
>     'ssl_key_file'       => 'HTTPS证书存储目录',
>     ...
> ],
> ```
> 
> * 注意,这里`nginx`就不用再配置`https`了。
> 
> ### nginx配置
> > 百度，nginx配置https。



> ### laravel-s配置
> * `swoole`默认没有支持`https`，需要配置
> * `laravels.php`加配置如下
> 
> ```
> 'swoole' => [
>     ...
>     // HTTPS
>     'ssl_cert_file'      => 'HTTPS证书存储目录',
>     'ssl_key_file'       => 'HTTPS证书存储目录',
>     ...
> ],
> ```
> 
> * 注意,这里`nginx`就不用再配置`https`了。
> 
> ### nginx配置
> > 百度，nginx配置https。

您好，我试了你这种配置，但是启动异常，是用不了ssl,你能看看是什么问题引起的吗？
[https://github.com/hhxsv5/laravel-s/issues/302](url)

**Comment by RussellCao824** [comment]
> ### laravel-s配置
> * `swoole`默认没有支持`https`，需要配置
> * `laravels.php`加配置如下
> 
> ```
> 'swoole' => [
>     ...
>     // HTTPS
>     'ssl_cert_file'      => 'HTTPS证书存储目录',
>     'ssl_key_file'       => 'HTTPS证书存储目录',
>     ...
> ],
> ```
> 
> * 注意,这里`nginx`就不用再配置`https`了。
> 
> ### nginx配置
> > 百度，nginx配置https。

您好，我试了你这种配置，但是启动异常，是用不了ssl,你能看看是什么问题引起的吗？
[https://github.com/hhxsv5/laravel-s/issues/302](url)
