### ISSUE TITLE
laravels启动失败

### ISSUE THREAD

**Issue by yymmhh** [hhxsv5/laravel-s#204]
1. Tell us your software version
    How to know it?
    ```Bash
    # PHP
   PHP 7.2.19 (cli) (built: Jun 28 2019 03:58:08) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.19, Copyright (c) 1999-2018, by Zend Technologies
    # Swoole
    swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.4.2
Built => Nov 12 2019 03:26:58
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
spinlock => enabled
rwlock => enabled
http2 => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

    # Laravel
   "laravel/framework": "^6.2",

    # Lumen
    grep 'laravel/lumen-framework' composer.json
    ```

    | Software | Version |
    | --------- | --------- |
    | PHP | `7.2.19` |
    | Swoole | `4.4.2` |
    | Laravel/Lumen | `6.5.0` |

2. Detail description about this issue(error/log)

>>> Feedback: https://github.com/hhxsv5/laravel-s
[2019-11-12 12:44:48] [WARNING] Swoole[PID=1] is already running.
bash-5.0# php bin/laravels restart
[2019-11-12 12:44:55] [INFO] The max time of waiting to forcibly stop is 60s.
[2019-11-12 12:44:55] [INFO] Waiting Swoole[PID=1] to stop. [1]

3. Give us a `reproducible` code block and `steps`

   centos7.7
lsof -i:5200  
netstat -anp|grep 5200
都没有

restart  也是返回这个错误

用的dnmp  docker 镜像安装的

**Comment by yymmhh** [comment]
laravel 版本太高的问题,切回5.5 正常

**Comment by hhxsv5** [comment]
```
[2019-11-12 12:44:48] [WARNING] Swoole[PID=1] is already running.
```
注意这行，PID=1 这不对。
start命令后会自动存储Master进程的PID到`storage/laravels.pid`文件，检查该文件的读写权限、删除它，然后再start试试。

btw，你的issue markdown格式是乱的。

**Comment by yymmhh** [comment]
找到原因了,不可以在宿主中运行 **`php bin/laravels start`**

> https://github.com/yeszao/dnmp/blob/master/bash.alias.sample

必须在容器中运行   **`php bin/laravels start`**
