### ISSUE TITLE
请问是否支持Laravel 6.x？

### ISSUE THREAD

**Issue by 602000** [hhxsv5/laravel-s#208]
1. Tell us your software version
    How to know it?
    ```Bash
    # PHP
    php -v
    # Swoole
    php --ri swoole
    # Laravel
    grep 'laravel/framework' composer.json
    # Lumen
    grep 'laravel/lumen-framework' composer.json
    ```

    | Software | Version |
    | --------- | --------- |
    | PHP | `TODO` |
    | Swoole | `TODO` |
    | Laravel/Lumen | `6.x` |

2. Detail description about this issue(error/log)

    `TODO`

3. Give us a `reproducible` code block and `steps`

    ```PHP
    //TODO: Your code
    ```

**Comment by hhxsv5** [comment]
`Laravel 6`依赖了`ignition`，目前会出现兼容性问题[Action Facade\Ignition\Http\Controllers\ShareReportController not defined.](https://github.com/facade/ignition/issues/202)，根本原因是`Swoole`运行在`cli`模式下，而`ignition`根据运行模式做了[特殊处理](https://github.com/facade/ignition/blob/1.13.0/src/IgnitionServiceProvider.php#L135)。
可配置环境变量`APP_RUNNING_IN_CONSOLE`来临时解决。
```
APP_RUNNING_IN_CONSOLE=false
```

**Comment by juslintek** [comment]
Do not use `APP_RUNNING_IN_CONSOLE=false` if you use Horizon for job management and monitoring.
