### ISSUE TITLE
POST异步请求头中包含 content-type  "application/json"  无法获取到$request->input() 参数

### ISSUE THREAD

**Issue by dynamohuang** [hhxsv5/laravel-s#21]
- 重现curl如下
`curl 'http://discover.vesync.com/api/deal/6'  -H 'Content-Type: application/json;charset=UTF-8'   -d 'a=1&b=2' -X 'POST'`

- 去掉 -H 'Content-Type: application/json;charset=UTF-8' 就可以获取得到$request->input() 

- 前端采用axios   异步提交  默认带上了这个头信息

- 用fpm方式laravel框架能够解析获取

**Comment by hhxsv5** [comment]
谢谢反馈，`v1.10.9` 已修复。
