### ISSUE TITLE
Xdebug VScode

### ISSUE THREAD

**Issue by juber-ivre** [hhxsv5/laravel-s#210]
![image](https://user-images.githubusercontent.com/48788224/69817518-ae2a7f80-11f2-11ea-9bd4-670d0266219f.png)

Perhaps more as a question than a bug but does anyone knows how to make xdebug work properly with Docker container?

I have it installed and enabled as per screenshot below but no luck in having it working with VScode. Seems to be something small I'm missing.

![image](https://user-images.githubusercontent.com/48788224/69817630-ee89fd80-11f2-11ea-87a3-34309695738e.png)

Any help / suggestion are very well appreciated.

Thanks in advance.

**Comment by hhxsv5** [comment]
Swoole is not compatible with Xdebug, try [sdebug](https://github.com/mabu233/sdebug).

**Comment by juber-ivre** [comment]
Thanks a lot @hhxsv5. Iwill give it a try.
