### ISSUE TITLE
看教成安装使用的

### ISSUE THREAD

**Issue by kzabc** [hhxsv5/laravel-s#211]
是不是和dingo 有冲突 有大佬解决办法吗

{
    "message": "swoole exit",
    "status_code": 500,
    "debug": {
        "line": 24,
        "file": "/Users/edz/coding/php/new/optometry/app/Http/Controllers/CustomerAuth/LoginController.php",
        "class": "Swoole\\ExitException",
        "trace": [
            "#0 [internal function]: App\\Http\\Controllers\\CustomerAuth\\LoginController->login(Object(App\\Http\\Requests\\CustomerLogin))",
            "#1 /Users/edz/coding/php/new/optometry/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)",
            "#2 /Users/edz/coding/php/new/optometry/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('login', Array)",
            "#3 /Users/edz/coding/php/new/optometry/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\CustomerAuth\\LoginController), 'login')",
            "#4 /Users/edz/coding/php/new/optometry/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\\Routing\\Route->runController()",
            "#5 /Users/edz/coding/php/new/optometry/vendor/laravel/framework/src/Illuminate/Routing/Router.php(680): Illuminate\\Routing\\Route->run()",
            "#6 /Users/edz/coding/php/new/optometry/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#7 /Users/edz/coding/php/new/optometry/vendor/dingo/api/src/Http/Middleware/PrepareController.php(45): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#8 /Users/edz/coding/php/new/optometry/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Dingo\\Api\\Http\\Middleware\\PrepareController->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
            "#9 /Users/edz/coding/php/new/optometry/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#10 /Users/edz/coding/php/new/optometry/vendor/laravel/framework/src/Illuminate/Routing/Router.php(682): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))",
            "#11 /Users/edz/coding/php/new/optometry/vendor/laravel/framework/src/Illuminate/Routing/Router.php(657): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Dingo\\Api\\Http\\Request))",
            "#12 /Users/edz/coding/php/new/optometry/vendor/laravel/framework/src/Illuminate/Routing/Router.php(623): Illuminate\\Routing\\Router->runRoute(Object(Dingo\\Api\\Http\\Request), Object(Illuminate\\Routing\\Route))",
            "#13 /Users/edz/coding/php/new/optometry/vendor/laravel/framework/src/Illuminate/Routing/Router.php(612): Illuminate\\Routing\\Router->dispatchToRoute(Object(Dingo\\Api\\Http\\Request))",
            "#14 /Users/edz/coding/php/new/optometry/vendor/dingo/api/src/Routing/Adapter/Laravel.php(88): Illuminate\\Routing\\Router->dispatch(Object(Dingo\\Api\\Http\\Request))",
            "#15 /Users/edz/coding/php/new/optometry/vendor/dingo/api/src/Routing/Router.php(514): Dingo\\Api\\Routing\\Adapter\\Laravel->dispatch(Object(Dingo\\Api\\Http\\Request), 'v1')",
            "#16 /Users/edz/coding/php/new/optometry/vendor/dingo/api/src/Http/Middleware/Request.php(126): Dingo\\Api\\Routing\\Router->dispatch(Object(Dingo\\Api\\Http\\Request))",
            "#17 /Users/edz/coding/php/new/optometry/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Dingo\\Api\\Http\\Middleware\\Request->Dingo\\Api\\Http\\Middleware\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#18 /Users/edz/coding/php/new/optometry/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#19 /Users/edz/coding/php/new/optometry/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
            "#20 /Users/edz/coding/php/new/optometry/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#21 /Users/edz/coding/php/new/optometry/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
            "#22 /Users/edz/coding/php/new/optometry/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#23 /Users/edz/coding/php/new/optometry/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
            "#24 /Users/edz/coding/php/new/optometry/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#25 /Users/edz/coding/php/new/optometry/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
            "#26 /Users/edz/coding/php/new/optometry/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#27 /Users/edz/coding/php/new/optometry/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Fideloper\\Proxy\\TrustProxies->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
            "#28 /Users/edz/coding/php/new/optometry/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#29 /Users/edz/coding/php/new/optometry/vendor/dingo/api/src/Http/Middleware/Request.php(127): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))",
            "#30 /Users/edz/coding/php/new/optometry/vendor/dingo/api/src/Http/Middleware/Request.php(103): Dingo\\Api\\Http\\Middleware\\Request->sendRequestThroughRouter(Object(Dingo\\Api\\Http\\Request))",
            "#31 /Users/edz/coding/php/new/optometry/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Dingo\\Api\\Http\\Middleware\\Request->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
            "#32 /Users/edz/coding/php/new/optometry/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))",
            "#33 /Users/edz/coding/php/new/optometry/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))",
            "#34 /Users/edz/coding/php/new/optometry/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))",
            "#35 /Users/edz/coding/php/new/optometry/vendor/hhxsv5/laravel-s/src/Illuminate/Laravel.php(155): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))",
            "#36 /Users/edz/coding/php/new/optometry/vendor/hhxsv5/laravel-s/src/LaravelS.php(209): Hhxsv5\\LaravelS\\Illuminate\\Laravel->handleDynamic(Object(Illuminate\\Http\\Request))",
            "#37 /Users/edz/coding/php/new/optometry/vendor/hhxsv5/laravel-s/src/LaravelS.php(157): Hhxsv5\\LaravelS\\LaravelS->handleDynamicResource(Object(Hhxsv5\\LaravelS\\Illuminate\\Laravel), Object(Illuminate\\Http\\Request), Object(Swoole\\Http\\Response))",
            "#38 [internal function]: Hhxsv5\\LaravelS\\LaravelS->onRequest(Object(Swoole\\Http\\Request), Object(Swoole\\Http\\Response))",
            "#39 /Users/edz/coding/php/new/optometry/vendor/hhxsv5/laravel-s/src/Swoole/Server.php(349): Swoole\\Server->start()",
            "#40 /Users/edz/coding/php/new/optometry/vendor/hhxsv5/laravel-s/src/Console/Portal.php(137): Hhxsv5\\LaravelS\\Swoole\\Server->run()",
            "#41 /Users/edz/coding/php/new/optometry/vendor/hhxsv5/laravel-s/src/Console/Portal.php(196): Hhxsv5\\LaravelS\\Console\\Portal->start()",
            "#42 /Users/edz/coding/php/new/optometry/vendor/hhxsv5/laravel-s/src/Console/Portal.php(62): Hhxsv5\\LaravelS\\Console\\Portal->restart()",
            "#43 /Users/edz/coding/php/new/optometry/vendor/symfony/console/Command/Command.php(255): Hhxsv5\\LaravelS\\Console\\Portal->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))",
            "#44 /Users/edz/coding/php/new/optometry/bin/laravels(160): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))",
            "#45 {main}"
        ]
    }
}

**Comment by hhxsv5** [comment]
看[注意事项](https://github.com/hhxsv5/laravel-s/blob/master/README-CN.md#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9)，不能使用`exit` `die` `dd`。

**Comment by kzabc** [comment]
谢谢大佬
