### ISSUE TITLE
 Horizon 貌似不支持~

### ISSUE THREAD

**Issue by August2012** [hhxsv5/laravel-s#213]
1. Tell us your software version
    How to know it?
    ```Bash
    # PHP
    PHP 7.3.11 (cli) (built: Oct 24 2019 11:29:00) ( NTS )
    Copyright (c) 1997-2018 The PHP Group
    Zend Engine v3.3.11, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.11, Copyright (c) 1999-2018, by Zend Technologies
    # Swoole
    4.4.13-alpha
    # Laravel
    Laravel 6.5

    | Software | Version |
    | --------- | --------- |
    | PHP | 7.3 |
    | Swoole | 4.4.13-alpha |
    | Laravel/Lumen | 6.5|

2. Detail description about this issue(error/log)

   Horizon 安装出错
   
![image](https://user-images.githubusercontent.com/5556668/70399161-91950f80-1a5c-11ea-86fc-92179e356139.png)

**Comment by hhxsv5** [comment]
Laravel 6.x 还未支持 Horizon。

**Comment by August2012** [comment]
> Laravel 6.x 还未支持 Horizon。

![image](https://user-images.githubusercontent.com/5556668/70404660-c06baf80-1a75-11ea-9bc8-867910903c90.png)

你好，我测试了一下，最新版本的Laravel 6.6.2是可以安装的
![image](https://user-images.githubusercontent.com/5556668/70404703-db3e2400-1a75-11ea-90d2-304546c2e8ec.png)

**Comment by hhxsv5** [comment]
[Laravel 6.x](https://github.com/laravel/laravel/releases)还不稳定，不建议使用，6.6.x 已经被删除了。

**Comment by August2012** [comment]
> [Laravel 6.x](https://github.com/laravel/laravel/releases)还不稳定，不建议使用，6.6.x 已经被删除了。

哦哦，有推荐的Laravel 版本吗？ 正式项目用。

**Comment by hhxsv5** [comment]
5.8或6.0都行。

**Comment by August2012** [comment]
有没有类似的队列管理推荐~
