### ISSUE TITLE
请问一下Controller中怎么向WebSocket发送消息

### ISSUE THREAD

**Issue by wujingke** [hhxsv5/laravel-s#214]
1. Tell us your software version
    How to know it?
    ```Bash
    # PHP
    php -v
    # Swoole
    php --ri swoole
    # Laravel
    grep 'laravel/framework' composer.json
    # Lumen
    grep 'laravel/lumen-framework' composer.json
    ```

    | Software | Version |
    | --------- | --------- |
    | PHP | `TODO` |
    | Swoole | `TODO` |
    | Laravel/Lumen | `TODO` |

2. Detail description about this issue(error/log)

    `TODO`

3. Give us a `reproducible` code block and `steps`

    ```PHP
    //TODO: Your code
    ```

**Comment by hhxsv5** [comment]
[在你的项目中使用SwooleServer实例
](https://github.com/hhxsv5/laravel-s/blob/master/README-CN.md#%E5%9C%A8%E4%BD%A0%E7%9A%84%E9%A1%B9%E7%9B%AE%E4%B8%AD%E4%BD%BF%E7%94%A8swooleserver%E5%AE%9E%E4%BE%8B)

```php
app('swoole')->push();
```
