### ISSUE TITLE
laravel6内存不断增涨问题

### ISSUE THREAD

**Issue by boyfoo** [hhxsv5/laravel-s#216]
laravel 版本 `"laravel/framework": "^6.2"`

api文件下:
```
Route::get('/swoole', 'Controller@stats');
```
```
public function stats(Request $request) {
     return round(memory_get_usage() / 1024 / 1024, 4) . 'MB';
}
```
代码一共就这两句 新拉取的项目 只返回当前内存 每次返回的内存占用会递增 一次递增 0.003mb左右 

公司项目的代码laravel5.5 也是返回一样的代码 每次递增0.02mb 

可以帮忙解决下么

**Comment by jqhph** [comment]
内存没有正常释放，这种问题在swoole框架中比较常见，代码越复杂越难排查。现在swoole就是缺少成熟的内存泄漏排查工具。

**Comment by hhxsv5** [comment]
@boyfoo 这点儿增长不算问题，可以尝试大请求量压测，观察进程内存增涨情况，只要内存不随着请求量增加而一直增加，就不用担心。我司每日千万级PV，laravel-s是经受住了考验才开源出来的。

**Comment by hhxsv5** [comment]
传统PHP FPM下从不关心内存释放，常驻进程后就必须要关心，一般是操作单例、全局变量导致。可以尝试[Swoole Tracker](https://www.swoole-cloud.com/tracker.html)跟踪问题。
