### ISSUE TITLE
和腾讯云sdk冲突

### ISSUE THREAD

**Issue by questionlin** [hhxsv5/laravel-s#220]
1. Your software version (Screenshot of your startup)
    
+--------------------------------+---------+
| Component                      | Version |
+--------------------------------+---------+
| PHP                            | 7.3.11  |
| Swoole                         | 4.4.12  |
| LaravelS                       | 3.5.17  |
| Laravel Framework [production] | 6.9.0   |
+--------------------------------+---------+

2. Detail description about this issue(error/log)

    提示
>    [2019-12-30 15:47:15] production.ERROR: Class 'TencentCloud\Sms\v20190711\Models\SendSmsRequest' not found {"exception":"[object]

这个代码在 mac php -S 下能运行，linux swoole 下报错。因为mac swoole 模式不响应，所以没法调试。

3. Some `reproducible` code blocks and `steps`

    ```PHP
    <?php

    namespace App\Http\Controllers\API;

    use App\Http\Controllers\Controller;
    use Illuminate\Http\Request;
    use Illuminate\Support\Facades\Cache;
    use Auth;
    use App\User;
    use TencentCloud\Sms\v20190711\Models\SendSmsRequest;

    class UserController extends Controller
    {
        /**
         * 短信验证码
         */
        public function smscode(Request $request)
        {
            $request->validate([
                'phone' => 'required'
            ]);
        
            if(!$this->isPhone($request->phone)){
                abort(400);
            }
            // 记录code
            $str = (string)(rand(1000,9999));
            Cache::put('smscode'.$request->phone, $str, 600);
            // 发送短信
            $req = new SendSmsRequest(); // 执行到这里就报错了，忽略下面业务代码
        }
    }
    ```

composer.json
```json
{
    "require": {
        "php": "^7.2",
        "barryvdh/laravel-cors": "^0.11.4",
        "fideloper/proxy": "^4.0",
        "hhxsv5/laravel-s": "~3.5.0",
        "laravel/framework": "^6.0",
        "laravel/passport": "^8.0",
        "tencentcloud/tencentcloud-sdk-php": "^3.0"
    },
}
```

**Comment by questionlin** [comment]
是这个包本身的问题

**Comment by hhxsv5** [comment]
😂
