### ISSUE TITLE
Action Facade\Ignition\Http\Controllers\ExecuteSolutionController not defined.

### ISSUE THREAD

**Issue by Edinewone** [hhxsv5/laravel-s#221]
(1/1) InvalidArgumentExceptionAction Facade\Ignition\Http\Controllers\ExecuteSolutionController not defined.
--
in UrlGenerator.php line 453
at UrlGenerator->action('Facade\\Ignition\\Http\\Controllers\\ExecuteSolutionController', array(), true)in helpers.php line 103
at action('\\Facade\\Ignition\\Http\\Controllers\\ExecuteSolutionController')in SolutionTransformer.php line 32
at SolutionTransformer->toArray()in ErrorPageViewModel.php line 106
at ErrorPageViewModel->solutions()in ErrorPageViewModel.php line 177
at ErrorPageViewModel->toArray()in ErrorPageHandler.php line 73
at ErrorPageHandler->renderException(object(ErrorPageViewModel))in ErrorPageHandler.php line 52
at ErrorPageHandler->handle(object(ErrorException))in IgnitionWhoopsHandler.php line 25
at IgnitionWhoopsHandler->handle(object(ErrorException))in Run.php line 296
at Run->handleException(object(ErrorException))in Handler.php line 362
at Handler->renderExceptionWithWhoops(object(ErrorException))in Handler.php line 341
at Handler->renderExceptionContent(object(ErrorException))in Handler.php line 325
at Handler->convertExceptionToResponse(object(ErrorException))in Handler.php line 304
at Handler->prepareResponse(object(Request), object(ErrorException))in Handler.php line 209
at Handler->render(object(Request), object(ErrorException))in Handler.php line 49
at Handler->render(object(Request), object(ErrorException))in ExceptionHandler.php line 68
at ExceptionHandler->render(object(Request), object(ErrorException))in Pipeline.php line 51
at Pipeline->handleException(object(Request), object(ErrorException))in Pipeline.php line 132
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in SubstituteBindings.php line 41
at SubstituteBindings->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in VerifyCsrfToken.php line 76
at VerifyCsrfToken->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in ShareErrorsFromSession.php line 49
at ShareErrorsFromSession->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in StartSession.php line 56
at StartSession->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in AddQueuedCookiesToResponse.php line 37
at AddQueuedCookiesToResponse->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in EncryptCookies.php line 66
at EncryptCookies->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 105
at Pipeline->then(object(Closure))in Router.php line 683
at Router->runRouteWithinStack(object(Route), object(Request))in Router.php line 658
at Router->runRoute(object(Request), object(Route))in Router.php line 624
at Router->dispatchToRoute(object(Request))in Router.php line 613
at Router->dispatch(object(Request))in Kernel.php line 170
at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))in Pipeline.php line 130
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in TransformsRequest.php line 21
at TransformsRequest->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in TransformsRequest.php line 21
at TransformsRequest->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in ValidatePostSize.php line 27
at ValidatePostSize->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in CheckForMaintenanceMode.php line 63
at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in TrustProxies.php line 57
at TrustProxies->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 105
at Pipeline->then(object(Closure))in Kernel.php line 145
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php line 110
at Kernel->handle(object(Request))in Laravel.php line 155
at Laravel->handleDynamic(object(Request))in LaravelS.php line 211
at LaravelS->handleDynamicResource(object(Laravel), object(Request), object(Response))in LaravelS.php line 157
at LaravelS->onRequest(object(Request), object(Response))
at Server->start()in Server.php line 346
at Server->run()in Portal.php line 137
at Portal->start()in Portal.php line 196
at Portal->restart()in Portal.php line 62
at Portal->execute(object(ArgvInput), object(ConsoleOutput))in Command.php line 255
at Command->run(object(ArgvInput), object(ConsoleOutput))in laravels line 160

我运行文档里的例子遇到的问题  
$fd = 1; // Find fd by userId from a map [userId=>fd].
/**@var \Swoole\WebSocket\Server $swoole */
$swoole = app('swoole');  //我没有找到laravel 容器注册过swoole  application里没有
$success = $swoole->push($fd, 'Push data to fd#1 in Controller');
var_dump($success);

**Comment by Edinewone** [comment]
我的环境
PHP                           7.2.24-0ubuntu0.18.04.1
Swoole                    4.4.14                  
LaravelS                  3.6.1                   
Laravel Framework [local] | 6.10.1

**Comment by hhxsv5** [comment]
参考 #208
