### ISSUE TITLE
apache使用例子建议

### ISSUE THREAD

**Issue by totwoto** [hhxsv5/laravel-s#223]
官网的apache例子,没有给出真实ip的获取
建议加上如下配置 (Ubuntu下)

LoadModule remoteip_module /yourpath/modules/mod_remoteip.so

RemoteIPHeader X-Forwarded-For

然后使用 a2enmod remoteip 安装
使用 systemctl restart apache2 重启

**Comment by totwoto** [comment]
如果使用了多层转发,建议在laravel中,使用 request()->header('x-forwarded-for') 来获取真实ip,字符串的第一个ip为真实ip

**Comment by hhxsv5** [comment]
感谢，欢迎直接提PR。

**Comment by Niroj11** [comment]
Question: I am trying to deploy this app to the server and I use apache2 web-server. I saw that the proxy is being redirected and it doesn't work unless the app is server.

Is that the only way we can deploy?
Can we simply use virtual host the application.

**Comment by hhxsv5** [comment]
> Question: I am trying to deploy this app to the server and I use apache2 web-server. I saw that the proxy is being redirected and it doesn't work unless the app is server.
> 
> Is that the only way we can deploy?
> Can we simply use virtual host the application??

Please try the following simple demo?
```
ProxyPassReverse / http://127.0.0.1:5200/
```

**Comment by totwoto** [comment]
> Question: I am trying to deploy this app to the server and I use apache2 web-server. I saw that the proxy is being redirected and it doesn't work unless the app is server.
> 
> Is that the only way we can deploy?
> Can we simply use virtual host the application??

Or use this slightly richer example code


        ProxyRequests Off
        ProxyMaxForwards 100
        ProxyPreserveHost On

        #This means that you want to forward the current request to port 8080 of this machine, and carry the original IP reverse proxy

        ProxyPass / http://127.0.0.1:8080/
        ProxyPassReverse / http://127.0.0.1:8080/
        RemoteIPHeader X-Forwarded-For

**Comment by hhxsv5** [comment]
The [example](https://github.com/hhxsv5/laravel-s#cooperate-with-apache) on the document has these parts more than yours: DEFLATE, Balancer, RewriteEngine, Log.
Do you think these are unnecessary?

**Comment by totwoto** [comment]
> 文档中的[示例](https://github.com/hhxsv5/laravel-s#cooperate-with-apache)包含以下部分：DEFLATE，Balancer，RewriteEngine，Log。
> 您认为这些不必要吗？

This is just my personal configuration. Because I configured Apache according to the example of the official website and did not forward to port 5200, I additionally installed nginx to monitor port 8080. Using Apache's reverse proxy function, I simply forward all requests from domain names to port 8080 of nginx. There is no problem in the configuration of nginx using the official website again

**Comment by Niroj11** [comment]
One of the questions I have is if we use reverse proxy to server it. How can I deploy this in the cloud server. If I need to server the application how can I simply deploy it like Laravel.

**Comment by hhxsv5** [comment]
@Niroj11 I suggest adding Nginx/Apache reverse proxy on the outer layer of Swoole Http Server. As for how to deploy the cloud server, sorry, I have no experience in this area.
For more detailed Apache documentation, please see [here](https://httpd.apache.org/docs/2.4/howto/reverse_proxy.html).
