### ISSUE TITLE
Target class [swoole] does not exist.

### ISSUE THREAD

**Issue by caiyaonan** [hhxsv5/laravel-s#224]
环境：
php:7.2.7
nginx
laravel6

创建了异步任务，在网页发起请求的时候 出现了这个错误Target class [swoole] does not exist.
![image](https://user-images.githubusercontent.com/9747682/75138451-37375100-5725-11ea-94c1-5785d43729cc.png)

**Comment by hhxsv5** [comment]
程序入口是`public/index.php`，说明还运行在fpm下，看[常见问题](https://github.com/hhxsv5/laravel-s/blob/master/KnownIssues-CN.md#class-swoole-does-not-exist)。

**Comment by hhxsv5** [comment]
#62
