### ISSUE TITLE
jwt 错乱

### ISSUE THREAD

**Issue by Maplejay** [hhxsv5/laravel-s#225]
1. Your software version (Screenshot of your startup)
    
    | Software | Version |
    | --------- | --------- |
    | PHP | 7.2 |
    | Swoole | 4.0 |
    | Laravel/Lumen | 5.5 |

2. Detail description about this issue(error/log)

    Hhxsv5\LaravelS\Illuminate\Cleaners\SessionCleaner::class,
    Hhxsv5\LaravelS\Illuminate\Cleaners\AuthCleaner::class,
    Hhxsv5\LaravelS\Illuminate\Cleaners\JWTCleaner::class,
加了这三个，jwt的用户还是会错乱

3. Some `reproducible` code blocks and `steps`

    ```PHP
    // TODO: your code
    ```

**Comment by hhxsv5** [comment]
Please provide a reproducible project archive(zip).

**Comment by Maplejay** [comment]
代码不能发出去，能提供个思路吗，拓展包，用的是"tymon/jwt-auth": "1.0.0-rc.1"，然后通过id,tokenById

**Comment by hhxsv5** [comment]
#50

**Comment by Maplejay** [comment]
这两篇看过了，也尝试了上面说的方案，未能解决

**Comment by Maplejay** [comment]
[project (2).zip](https://github.com/hhxsv5/laravel-s/files/4261893/project.2.zip)
@hhxsv5

**Comment by hhxsv5** [comment]
红框的都是不需要配置的
![image](https://user-images.githubusercontent.com/7278743/75513800-d6fc2400-5a30-11ea-8ad4-7909403f298d.png)
尝试如下方案：
1.验证JWT之前，手动[setRequest](https://jwt-auth.readthedocs.io/en/develop/auth-guard/#set-the-request-instance-explicitly).
2.打开[destroy_controllers](https://github.com/hhxsv5/laravel-s/blob/master/Settings-CN.md#destroy_controllers)
