### ISSUE TITLE
Laravel 6中清理RememberToken的Cookie失败导致混乱的登录态 Failed to clean up Cookie of RememberToken in Laravel 6 leads to messy login status

### ISSUE THREAD

**Issue by greenhat616** [hhxsv5/laravel-s#226]
1. Your software version (Screenshot of your startup)
    
    | Software | Version |
    | --------- | --------- |
    | PHP | 7.4.3 |
    | Swoole | 4.4.15 |
    |   LaravelS          |3.6.1 |
    | Laravel/Lumen | 6.17.1 |

2. Detail description about this issue(error/log)

多个用户反馈，登录状态会出现错乱情况。也已经注册了清理器。

```PHP
'register_providers'       => [
    ],
    'cleaners' => [
        Hhxsv5\LaravelS\Illuminate\Cleaners\SessionCleaner::class,
        Hhxsv5\LaravelS\Illuminate\Cleaners\AuthCleaner::class,
    ],
    'destroy_controllers'      => [
        'enable'        => false,
        'excluded_list' => [
            //\App\Http\Controllers\TestController::class,
        ],
    ],
 ```
控制器编写时也没有在构建方法中初始化验证相关的信息。这个问题似乎是在昨晚更新 Laravel 依赖后出现的。

我们还额外使用了：
* laravel artisan optimize
* laravel artisan view:cache
* Redis 作为缓存，会话存储器
* 默认 rememberMe

**Comment by greenhat616** [comment]
如果需要提供源码进行调试的话，还望联系 Telegram: https://t.me/@LaPG5Cb14FGecbs
虽然不是什么重要的代码，但是不太希望代码开源后被利用潜在的问题非法获取用户数据。所以如果需要需要的话，咱们私发以下吧:(

**Comment by hhxsv5** [comment]
首先线上请先回滚到之前版本，其次`laravel-s`还不完全支持`Laravel 6.x`，因为`7.x`即将发布，`laravel-s`的可能会跳过支持`6.x`，直接支持`7.x`。
另外，在开发流程上，应该在测试环境充分测试，保证质量后后再上生产环境。

**Comment by hhxsv5** [comment]
@greenhat616 加QQ群细聊：62075835

**Comment by greenhat616** [comment]
好的。已加群。
我们昨天对 Laravel 做的重要更新主要有两点：登录默认保持登录状态（以前不会“记住我”），更新依赖。
状况： 未登录的用户初次访问网站就会发现登录有别人的账户（这个过程肯定有 Cookies 下发）
于是我们经过多次 LaravelS 配置调整（无用），然后切回 CGI 环境测试（发现之前被错误显示的用户依然显示）
结合以上情况，我们推断： LaravelS 在登录时（默认的 Auth ）使用 RememberMe 后，会下发 Cookies（保存登录状态的令牌）。而这个Cookie无法保证下发后销毁（会被其他未分配的用户获取到）。
备注： 以上实验条件我们都有做清空 Sessions 的处理

**Comment by hhxsv5** [comment]
Laravel 6改了CookieJar::getQueuedCookies()，不再返还name=>cookie的映射，而是返回cookie的数组，导致CookieCleaner清理Remember Cookie失败。
[5.8 getQueuedCookies](https://github.com/laravel/framework/blob/5.8/src/Illuminate/Cookie/CookieJar.php#L192) [6.x getQueuedCookies](https://github.com/laravel/framework/blob/6.x/src/Illuminate/Cookie/CookieJar.php#L215)

[此提交](https://github.com/hhxsv5/laravel-s/commit/d968c363c692c70df7eb31f8f7c58c78140ebe29)已兼容Laravel 6，请升级laravel-s到`v3.6.2`。

**Comment by greenhat616** [comment]
大佬辛苦了(≧∇≦)/

**Comment by greenhat616** [comment]
经验证，已经成功修复。感谢作者的付出 👍
