### ISSUE TITLE
请教下，控制器代码是否是运行在协程中？

### ISSUE THREAD

**Issue by wh469012917** [hhxsv5/laravel-s#229]
1. Your software version (Screenshot of your startup)
    
    | Software | Version |
    | --------- | --------- |
    | PHP | 7.3.1|
    | Swoole | 4.4.15|
    | Laravel/Lumen | 6.14.0|

我看到代码中有这样一个类：`Hhxsv5\LaravelS\Swoole\Coroutine\Context` 用来操作当前协程的数据，但是 `Coroutine::getuid()` 却返回的是 -1，可以确定不是运行在协程中，有没有办法隔离请求之间的数据？比如我们之前有把当前用户放到容器中：
```
app()->instance('user', $user);
```
但是这样会使得每一个请求取到的都是 一样的

**Comment by hhxsv5** [comment]
laravel-s 运行在 swoole 的同步阻塞模式，默认关闭协程，因为 laravel 协程下不安全的。
更多明细参考[协程](https://github.com/hhxsv5/laravel-s/blob/master/README-CN.md#%E5%8D%8F%E7%A8%8B)。
之前打算用Context类隔离协程间请求级数据，但对 laravel 容器整体改造工作量太大，放弃了。

**Comment by wh469012917** [comment]
那是否目前可以使用 $request 来做请求间的隔离，目前是否有对$request做重置的操作？

**Comment by hhxsv5** [comment]
不行，成也`容器`，败也`容器`。

**Comment by wh469012917** [comment]
如果不行的话，有没有什么解决方案？还是说目前无解

**Comment by hhxsv5** [comment]
无解。

laravel-s 基于 Swoole Http Server 常驻内存后每个请求减少了一系列的初始化开销：加载 PHP 文件、初始化 Laravel 框架、初始化数据库连接等资源。即比如完成一个请求需要走 10 步 (1 到 10)，现在只需走 4 步 (7-10)。
另外，Swoole 由 C/C++ 编写，内置的 Http Server 性能高于 Nginx+FPM。

laravel-s 这种模式已经足以应对大部分业务场景，我司内部许多微服务也在使用。

如有协程需要，建议使用 Swoft Hyperf 等协程框架。
