### ISSUE TITLE
兼容laravelcollective/html包FORM SESSION token的问题

### ISSUE THREAD

**Issue by stevenyangecho** [hhxsv5/laravel-s#23]
通过
`    {!!Form::open( array( 'method' => 'POST',)) !!}`
自动创建表单,会自动创建 csrf token 的字段,多用户登录后,会发现token值会混乱掉,导致无法提交表单.

同时用` {{csrf_token()}}`这个手动生成的字段,token值没有问题.

同一页面观察,发现不断刷新页面,FORM自动生成的token每次都会变化,截图如下

![1](https://user-images.githubusercontent.com/5569554/38074019-e8f36f3c-335f-11e8-9da7-28e3813d7930.jpg)
刷新之后
![2](https://user-images.githubusercontent.com/5569554/38074047-0082f7e4-3360-11e8-9e6a-f6fa07534152.jpg)

**Comment by stevenyangecho** [comment]
https://github.com/LaravelCollective/html/blob/623a150c91e2d3f92eeee9f9eda58a841e3cb548/src/FormBuilder.php#L225
        `$token = ! empty($this->csrfToken) ? $this->csrfToken : $this->session->token();`
问题似乎出在这里,这个 $this->csrfToken 会保存..改成直接都每次取的话,就没问题了 $this->session->token()

有从laravels方面解决的方案没

**Comment by hhxsv5** [comment]
我测试下。

**Comment by hhxsv5** [comment]
基于Laravel5.1+LaravelCollective/html 5.1测试，没有复现。

```Blade
{!! Form::open(['method' => 'POST']) !!}
{{ csrf_token() }}
```

```Html
<form method="POST" action="http://127.0.0.1:8011/test-html" accept-charset="UTF-8"><input name="_token" type="hidden" value="0ik8r8ZbymT6HXk3QQHSKhwrqNpOQYEMCcNbpT3F">
0ik8r8ZbymT6HXk3QQHSKhwrqNpOQYEMCcNbpT3F
```

提供下一个精简可重现的例子。

**Comment by stevenyangecho** [comment]
是由于单例的关系,得模拟不同用户来测试
和 #25 应该是一个问题
看到最近有修复,Save snapshots for members of $app,应该能解决这个问题,应该是很重要的修复,有没有相关文档呢?

**Comment by hhxsv5** [comment]
#25 是保存了初始化Laravel时$app的一些成员属性，每次请求时重新覆盖到$app，目前只有`config`和`cookie`，应该不影响session。这是底层支持，上层无需关注。你现在还能重现吗？
