### ISSUE TITLE
TcpServer 运行一段时间 收不到数据

### ISSUE THREAD

**Issue by andy236726493** [hhxsv5/laravel-s#231]
1. Your software version (Screenshot of your startup)
    
    | Software | Version |
    | --------- | --------- |
    | PHP | 7.2 |
    | Swoole |4.4.9-alpha |
    | Laravel|5.8.37  |
    | Laravels| 3.6.2  |

2. Detail description about this issue(error/log)

TcpServer 运行一段时间 收不到数据, 下面是 logs
connect reactorId---2[2020-03-10 12:01:00 *28151.3]	WARNING	swWorker_reactor_is_empty (ERRNO 9012): worker exit timeout, forced to terminate
[2020-03-10 12:01:00 *28148.0]	WARNING	swWorker_reactor_is_empty (ERRNO 9012): worker exit timeout, forced to terminate
[2020-03-10 12:01:00 *28149.1]	WARNING	swWorker_reactor_is_empty (ERRNO 9012): worker exit timeout, forced to terminate
[2020-03-10 12:01:00 *28150.2]	WARNING	swWorker_reactor_is_empty (ERRNO 9012): worker exit timeout, forced to terminate

3. Some `reproducible` code blocks and `steps`

 public function onConnect(Server $server, $fd, $reactorId)
    {
        echo "connection open: {$fd}\r\n";
        echo "connect reactorId---".$reactorId;
        $server->send($fd, 'Welcome to LaravelS.');
    }

**Comment by hhxsv5** [comment]
没有复现，建议上传你的工程(脱敏、压缩包)到这里。
我本地测试截图：
![image](https://user-images.githubusercontent.com/7278743/76390486-6fd35d80-63a8-11ea-9a8b-3730ec5f71e7.png)
![image](https://user-images.githubusercontent.com/7278743/76390507-7e217980-63a8-11ea-8997-a0210877b60f.png)
![image](https://user-images.githubusercontent.com/7278743/76389511-5a5d3400-63a6-11ea-9023-d2efdc5a1968.png)
