### ISSUE TITLE
负载均衡的情况下如何区分websocket的fd

### ISSUE THREAD

**Issue by Insua** [hhxsv5/laravel-s#232]
1. Your software version (Screenshot of your startup)
    
    | Software | Version |
    | --------- | --------- |
    | PHP | 7.1 |
    | Swoole | 4.1 |
    | Laravel/Lumen | 5.8 |

2. Detail description about this issue(error/log)

负载均衡的时候 如何去区分不同单机请求的fd，开发时单机调试的时候，我是把fd存到表里，然后根据用户身份去查fd，再推送websocket消息，负载均衡多机部署的时候，怎么存fd，怎么去推送到不同服务器的fd上去？

**Comment by hhxsv5** [comment]
建议使用非中心化存储，比如本地共享内存的Swoole Table，将FD与UserId保存在本地，不用担心多机部署时的FD冲突。
至于如何推送至多服务器？
结合Redis pub/sub(或其他类似的消息队列)，发送消息时推送用户Id与消息体到Redis Channel(pub)，再开启一个自定义进程监听Channel(sub)，得到用户Id查找本地 Swoole Table表，再找到FD，push消息体即可。
