### ISSUE TITLE
能否使用sub/pub模式监控redis?

### ISSUE THREAD

**Issue by Insua** [hhxsv5/laravel-s#234]
1. Your software version (Screenshot of your startup)
    
    | Software | Version |
    | --------- | --------- |
    | PHP | 7.1.33 |
    | Swoole | 4.4.15 |
    | Laravel/Lumen | 5.8.33 |

2. Detail description about this issue(error/log)

    使用laravel-s监控redis，不是用定时器轮询哦，而是使用发布模式，类似於php artisan queue:work监控队列的方式

**Comment by hhxsv5** [comment]
可以在自定义进程sub

**Comment by Insua** [comment]
您好，我试了，但是订阅不到信息
```
<?php

namespace App\Processes;

use Hhxsv5\LaravelS\Swoole\Process\CustomProcessInterface;
use Log;
use Redis;
use Swoole\Http\Server;
use Swoole\Process;

class TaskProcess implements CustomProcessInterface
{

    private static $quit = false;
    /**
     * @inheritDoc
     */
    public static function callback(Server $swoole, Process $process)
    {
        while (!self::$quit) {
            Log::info('process running');
            Redis::subscribe(["tasks"], function ($message) {
                Log::info('message', ['message' => $message]);
            });
        }
    }

    /**
     * @inheritDoc
     */
    public static function onReload(Server $swoole, Process $process)
    {
        Log::info('process reloading');
        self::$quit = true;
    }
}
```

我再另一个普通 laravel 应用里去 pub 信息，在另一个应用里使用 laravel 自带的 command 能sub 到，但是在这个 laravel-s 应用里用自定义进程，就订阅不到
laravels.php 已配置 ps -aux 也看到 process 进程

**Comment by hhxsv5** [comment]
检查日志/控制台没有其他错误信息吗？
我本地测试是可以的
![image](https://user-images.githubusercontent.com/7278743/76586941-569fed80-651d-11ea-827d-35e177967248.png)
![image](https://user-images.githubusercontent.com/7278743/76586957-5e5f9200-651d-11ea-8288-e7b584033499.png)
![image](https://user-images.githubusercontent.com/7278743/76586966-64557300-651d-11ea-870b-fc3fcb3f53c6.png)

**Comment by Insua** [comment]
谢谢，可以了，redis 必须配置 read_time_out，我没配置 ，所以出错了。
我本质上还是为了解决 https://github.com/hhxsv5/laravel-s/issues/232 这个问题，现在我使用的方案是把websocket单独做一个服务，不用负载均衡，websocket并发没那么高 ，单台也抗得住，触发推送服务，就让负载均衡的所有服务器都向 redis pub，然后websocket应用去sub然后推送

**Comment by never615** [comment]
> 谢谢，可以了，redis 必须配置 read_time_out，我没配置 ，所以出错了。
> 我本质上还是为了解决 #232 这个问题，现在我使用的方案是把websocket单独做一个服务，不用负载均衡，websocket并发没那么高 ，单台也抗得住，触发推送服务，就让负载均衡的所有服务器都向 redis pub，然后websocket应用去sub然后推送

你read_time_out设置的什么？设置-1不行，那这样早晚还是会redis连接异常出现啊。。。。
