### ISSUE TITLE
HTTP回应超过160KB就会卡掉

### ISSUE THREAD

**Issue by tai1030** [hhxsv5/laravel-s#235]
1. Your software version (Screenshot of your startup)
    
    | Software | Version |
    | --------- | --------- |
    | PHP | 7.4.3 |
    | Swoole | 4.4.16 |
    | Laravel | 7.1.2 |
    | LaravelS | 3.6.4 |

2. Detail description about this issue(error/log)
   ```
			$test = '';
			for($i = 0; $i < 160 * 1024; $i++) {
				$test .= '.';
			}
   ```
   一个普通Laravel控制器, 当HTTP回应超过160KB (包括回应标头), 请求就会卡掉.
   在postman调试, 看到成功返回200 OK, 及有完整的回应标头, 看到content-length是163840
   但没有回文, 请求一直等待回应完成, 跑了几分钟也未有timeout.
   请问怎样解决? buffer_output_size / socket_buffer_size / package_max_length 加到很大也不成功.
预设配置如下, 这个配置是100%没有回应.
```
        'buffer_output_size' => 2 * 1024 * 1024,
        'socket_buffer_size' => 128 * 1024 * 1024,
        'package_max_length' => 4 * 1024 * 1024,
```

但把它们 / 1024, 这样设定, 就会间隔性成功回应, 但下一个请求又没有回应, 再下一个请求又成功回应.
```
        'buffer_output_size' => 2 * 1024,
        'socket_buffer_size' => 128 * 1024,
        'package_max_length' => 4 * 1024,
```

3. Some `reproducible` code blocks and `steps`

    ```PHP
    // TODO: your code
    ```

**Comment by hhxsv5** [comment]
已重现问题，经排查，不是 laravel-s 的问题，应该是 Swoole 处理空 `favicon.ico` 文件导致的问题。已提交 Issue 至 Swoole，详情请看 [3182](https://github.com/swoole/swoole-src/issues/3182)。
临时解决办法，你可以降级 Swoole 至 4.4.15。

**Comment by tai1030** [comment]
@hhxsv5 我遇到的应该不是这问题

我查找laravelS的源码, 发现 \Hhxsv5\LaravelS\Swoole\DynamicResponse::sendContent() 中,
有一个检测chunkLimit的逻辑, 而chunkLimit就是在使用config(swoole.buffer_output_size)
我把buffer_output_size设定为1024后, 请求成功率是100%, 但回应速度慢了.
但把buffer_output_size设定为预设的2 * 1024 * 1024, 就大概有50%请求会出现阻塞的问题.

回文长度是160KB, 如buffer_output_size是预设的2 * 1024 * 1024, 就不会进入chunk回圈,
直接执行$this->swooleResponse->end($content);
是有约50%的请求能成功传送回应内文.

当buffer_output_size是1024, 就会进入chunk回圈, 分割传送回文.
那就100%成功.

这是环境问题吗? 我在使用WSL ubuntu 18.04, 有什么设定能突破160KB的限制? 谢谢

**Comment by hhxsv5** [comment]
你直接用创建Swoole Http Server测试看看。

**Comment by tai1030** [comment]
你对, 看来这是Swoole的问题了.

```
<?php

$http = new Swoole\Http\Server("127.0.0.1", 8080);

$http->on("start", function ($server) {
    echo "Swoole http server is started at http://127.0.0.1:8080\n";
});

$http->on("request", function ($request, $response) {
	$body = '';
	for($i = 0; $i < (160 * 1024); $i++) {
		$body .= '.';
    }

    echo 'Content length: ' . strlen($body) . "\n";

    $response->header("Content-Type", "text/plain");
    $response->end($body . "\n");
});

$http->start();
```

**Comment by tai1030** [comment]
原来是Swoole的已知问题, 找到issue了.
WSL1的bug, 其中一个解决方法是升级到WSL2.
https://github.com/swoole/swoole-src/issues/2386

但我测试过, 在laravels config把buffer_output_size由预设的 2*1024*1024 改为 159 * 1024,
就能避开这问题了, 运作正常, 上生产时再改回2*1024*1024.
其他遇到相同问题的朋友, 可以参考一个这个简单解决方法.
