### ISSUE TITLE
composer.json 应该去掉 "ext-pcntl": "*", 吧

### ISSUE THREAD

**Issue by pifeifei** [hhxsv5/laravel-s#236]
1. Your software version (Screenshot of your startup)
    
    | Software | Version |
    | --------- | --------- |
    | PHP | 7.2|
    | Swoole | 4.4.x|
    | Laravel/Lumen | TODO |

2. Detail description about this issue(error/log)

   我是用window开发的

3. Some `reproducible` code blocks and `steps`

composer require hhxsv5/laravel-s

我下载源码查询了, 没有用 pcntl 扩展, 建议去掉, 要不装不上

[git search pnctl](https://github.com/hhxsv5/laravel-s/search?q=pcntl&unscoped_q=pcntl)

**Comment by hhxsv5** [comment]
laravel-s 需要对进程通过发[信号](https://www.php.net/manual/zh/pcntl.constants.php)来控制，依赖`pnctl`，不能移除，比如[这里](https://github.com/hhxsv5/laravel-s/search?q=SIGUSR1&unscoped_q=SIGUSR1)。
windows上建议使用 docker 开发，这里有开箱即用的[docker-compose](https://github.com/hhxsv5/docker)。

**Comment by pifeifei** [comment]
谢谢, 我在提供一种方法,

composer.json
{
    "config" :{
       "platform": {
             //"扩展":"版本号", 
            "ext-pcntl": "7.2",
            "ext-posix": "7.2"
        }
    }
}

** 缺点**是本机不能运行，可以配合虚拟机，本机开发敲代码，传到虚拟机运行，需要足够内存，不然会卡
