### ISSUE TITLE
请问一个项目的代码如何支持多开(运行多次)？

### ISSUE THREAD

**Issue by boyfoo** [hhxsv5/laravel-s#237]
你好，原本项目因为是同步阻塞的，并且只有http请求，所以使用了dispatch_mode=3模式运行laravels，而如今又要开发websocket需求，websocket不支持dispatch_mode=3，也就是说我要再运行一个php bin/laravels start 并且dispatch_mode=1或2的服务来专门处理websocket

原本是想通过环境变量来改变端口和dispatch_mode 后发现由于laravels.pid问题无法一个项目运行多个，有什么办法处理这种情况么

**Comment by hhxsv5** [comment]
你对 laravel-s 理解有偏差，laravel-s 可同时支持 http/websocket/tcp/udp 等协议，start 命令只是开启所有配置的服务。swoole dispatch_mode为2也可以支持同步阻塞。
