### ISSUE TITLE
blade templating engine not working

### ISSUE THREAD

**Issue by shahabgohar** [hhxsv5/laravel-s#240]
| Version 3.6.4 |
    | --------- | --------- |
   Laravel version : 6.5.1
  php 7.4.4
  

   I was trying to link my css files but blade template engine is not working when i viewed the page source . So as a test i stopped laravel-s and run it on local apache server where my app worked fine and blade template engine was working fine

**Comment by hhxsv5** [comment]
Can you give a specific code example?

**Comment by shahabgohar** [comment]
OOps my bad i did a mistake. Sorry blade templating engine is working fine . but how to access files in public directory.

**Comment by hhxsv5** [comment]
laravel-s has a [built-in](https://github.com/hhxsv5/laravel-s/blob/master/Settings.md#handle_static) static file server, but it is recommended to use Nginx to do this(configure root to the public directory).

**Comment by shahabgohar** [comment]
Thanks a lot for your time

**Comment by hhxsv5** [comment]
You are welcome.
