### ISSUE TITLE
关于 EasyWechat 微信服务器回调通知的问题

### ISSUE THREAD

**Issue by swarmchen** [hhxsv5/laravel-s#241]
```
<?php

namespace App\Http\Controllers\Wechat;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use EasyWeChat;
use Log;

class WechatController extends Controller
{
	// 微信服务器响应请求接口
	public function index(Request $request)
	{
		$app = EasyWeChat::officialAccount('web');
		$app['request'] = $request;

		Log::info('line 18');

		$app->server->push(function($message){

			Log::info('line 22');

			if(isset($message['Event']) && $message['Event'] == 'subscribe') {
				return new Text("欢迎");
			}
			return NULL;
		});

		return $app->server->serve();
	}
}
```

重启laravels后，去公众号点击菜单，微信会发送菜单点击事件过来。
“line 18” 微信服务器访问一次打印一次
“line 22” 微信服务器访问总数多少次就打印多少次 （比如从重启到现在微信服务器一共请求 5 次，它一次就打印 5 次"line 22"，下次访问一次就打印6次"line 22"）

请问 原因是什么 ？

**Comment by hhxsv5** [comment]
看起来像是因为[单例问题](https://github.com/overtrue/wechat/blob/master/src/OfficialAccount/Server/ServiceProvider.php#L39)，参考[注意事项](https://github.com/hhxsv5/laravel-s/blob/master/README-CN.md#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9)。
Application本质是单例容器，server作为容器内的成员属性也是单例，所以多次push就会积累多次事件。建议写个[Cleaner](https://github.com/hhxsv5/laravel-s/blob/master/Settings-CN.md#cleaners)来清理server单例。
```php
use EasyWeChat;

class EasyWeChatCleaner implements CleanerInterface
{
    public function clean(Container $app, Container $snapshot)
    {
        $app = EasyWeChat::officialAccount('web');
        unset($app['server']);
    }
}
```

**Comment by Hanson** [comment]
重复原因在于单例，匿名函数一直push 导致 handler 一直在叠加，所以解决问题在于 push 之前清理掉 handlers 就可以了

easywechat 已提合并 https://github.com/overtrue/wechat/pull/1873
