### ISSUE TITLE
Websocket 经常 CLOSE_WAIT

### ISSUE THREAD

**Issue by addls** [hhxsv5/laravel-s#243]
1. Your software version (Screenshot of your startup)
    
    | Software | Version |
    | --------- | --------- |
    | PHP | 7.3.11 |
    | Swoole | 4.4.16 |
    | LaravelS | 3.6.1 |
    | Laravel| 6.16.0 |

2. Detail description about this issue(error/log)

    `tcp        0      0 172.18.0.4:5200         172.18.0.1:56464        CLOSE_WAIT`
`tcp        0      0 172.18.0.4:5200         172.18.0.1:56484        CLOSE_WAIT`
`tcp        0      0 172.18.0.4:5200         172.18.0.1:56470        CLOSE_WAIT`

3. Some `reproducible` code blocks and `steps`

    ```sh
    ./bin/laravels start
    ```
html websocket连接后直接刷新页面，重复几次，就会有CLOSE_WAIT, 另外在onClose方法中写日志发现没有触发这个方法。

**Comment by addls** [comment]
Reason: onMessage中有程序循环了.

**Comment by hhxsv5** [comment]
😂
