### ISSUE TITLE
 使用LaRecipe文档功能页面打不开

### ISSUE THREAD

**Issue by udeth** [hhxsv5/laravel-s#244]
在使用 php bin/laravels start 启动服务后无法 使用LaRecipe文档功能,页面打不开,通过f12查看是静态资源报404。

**Comment by hhxsv5** [comment]
#105

**Comment by udeth** [comment]
handle_static=true
并确定document_root真实指向public目录下，但public下的静态资源并不能被访问到。

**Comment by hhxsv5** [comment]
restart了吗？确认配置是否被缓存了 config:clear？

**Comment by udeth** [comment]
都有操作过，一直访问不到。

**Comment by hhxsv5** [comment]
进 QQ群 62075835 细聊
