### ISSUE TITLE
 `overtrue/wechat` 包微信开放平台接收请求验证票据固定唯一问题

### ISSUE THREAD

**Issue by lisgroup** [hhxsv5/laravel-s#248]
1. Your software version (Screenshot of your startup)
    
    | Software | Version |
    | --------- | --------- |
    | PHP | 7.3.6 NTS |
    | Swoole | 4.4.12 |
    | Laravel | 5.8 |

2. Detail description about this issue(error/log)

   使用 `overtrue/wechat` 包开发微信第三方开放平台，用来接收验证票据的接口会一直使用第一次数据，如何在 `cleaners` 中增加清理呢？目前使用下面的办法解决的，但是发现有很多 `ServiceProvider` 类，都需要一一添加吗？
```
// 用于清理注册了单例的 ServiceProvider
    'register_providers'       => [
        Overtrue\LaravelWeChat\ServiceProvider::class,
    ],
```

3. Some `reproducible` code blocks and `steps`

① 开启  `wechat.php` 配置项的 `route` 注释的路由代码

```
  /*
     * 路由配置
     */
    'route' => [
        /*
         * 开放平台第三方平台路由配置
         * 配置后 http://example.com/open-platform/serve 则为开放平台第三方应用设置的授权事件接收 URL
         */
        'open_platform' => [
            'uri' => 'serve',
            'action' => Overtrue\LaravelWeChat\Controllers\OpenPlatformController::class,
            'attributes' => [
                'prefix' => 'open-platform',
                'middleware' => null,
            ],
        ],
    ],
```

② 模拟 POST 请求，请求地址 ： http://127.0.0.1:5200/open-platform/serve?encrypt_type=aes&msg_signature=5209bb506be412eab6013fdf89213bd37f9d3479&nonce=991710142&signature=4e01a46e5db49206606391f2de9d91360294077b&timestamp=1587609878

wechat.log 日志

```PHP
[2020-04-27 17:48:03] EasyWeChat.DEBUG: Request received: {"method":"POST","uri":"http://127.0.0.1:5200/open-platform/serve?encrypt_type=aes&msg_signature=5209bb506be412eab6013fdf89213bd37f9d3479&nonce=991710142&signature=4e01a46e5db49206606391f2de9d91360294077b&timestamp=1587609878","content-type":null,"content":"{\"type\":\"object\",\"title\":\"empty object\",\"properties\":{}}"} []
[2020-04-27 17:48:03] EasyWeChat.DEBUG: Server response created: {"content":"success"} []
```

**Comment by hhxsv5** [comment]
#185

**Comment by lisgroup** [comment]
easywechat 读取的是php://input，但Swoole下这个输入流无效，参考[已知问题](https://github.com/hhxsv5/laravel-s/blob/master/KnownIssues-CN.md#%E4%BD%BF%E7%94%A8%E5%8C%85-overtruewechat)，
```
$app['request'] = $request;//在原有代码添加这一行，将当前Request赋值给$app['request']
```
赋值 `$request` 对象给easywechat。
那我需要到  `vendor/overtrue/laravel-wechat/src/ServiceProvider.php`，在
```
    /**
     * Register the provider.
     */
    public function register()
    {
        $this->setupConfig();

        $apps = [
            'official_account' => OfficialAccount::class,
            'work' => Work::class,
            'mini_program' => MiniProgram::class,
            'payment' => Payment::class,
            'open_platform' => OpenPlatform::class,
            'open_work' => OpenWork::class,
        ];
      // 在此处增加代码？
    }
```

**Comment by hhxsv5** [comment]
不需要清理ServiceProvider，只需要在用到easywechat的app之前赋值$request

**Comment by lisgroup** [comment]
> 不需要清理ServiceProvider，只需要在用到easywechat的app之前赋值$request

那接收通知的地址配置如图：
![微信图片_20200428144948](https://user-images.githubusercontent.com/31757678/80456161-b46a8680-895f-11ea-998a-25b94e0dfc68.png)
对应的 `'action' => Overtrue\LaravelWeChat\Controllers\OpenPlatformController::class`，那我需要重新实现代码，在新的方法里面的 $app之前赋值$request？

其中 `Overtrue\LaravelWeChat\Controllers\OpenPlatformController` 代码如下：

```
<?php

/*
 * This file is part of the overtrue/laravel-wechat.
 *
 * (c) overtrue <i@overtrue.me>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

namespace Overtrue\LaravelWeChat\Controllers;

use EasyWeChat\OpenPlatform\Application;
use EasyWeChat\OpenPlatform\Server\Guard;
use Overtrue\LaravelWeChat\Events\OpenPlatform as Events;

class OpenPlatformController extends Controller
{
    /**
     * Register for open platform.
     *
     * @param \EasyWeChat\OpenPlatform\Application $application
     *
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function __invoke(Application $application)
    {
        $server = $application->server;

        $server->on(Guard::EVENT_AUTHORIZED, function ($payload) {
            event(new Events\Authorized($payload));
        });
        $server->on(Guard::EVENT_UNAUTHORIZED, function ($payload) {
            event(new Events\Unauthorized($payload));
        });
        $server->on(Guard::EVENT_UPDATE_AUTHORIZED, function ($payload) {
            event(new Events\UpdateAuthorized($payload));
        });
        $server->on(Guard::EVENT_COMPONENT_VERIFY_TICKET, function ($payload) {
            event(new Events\VerifyTicketRefreshed($payload));
        });

        return $server->serve();
    }
}
```

**Comment by hhxsv5** [comment]
是在这里改，`OpenPlatformController `是`vendor`中的控制器，不建议修改它。
你可以加一个`前置中间件`，`中间件`中修改下`request`即可：
```php
public function handle($request, Closure $next)
{
    app('wechat.open_platform.{account}')['request'] = $request;
    return $next($request);
}
```

**Comment by hhxsv5** [comment]
@lisgroup 解决了没？

**Comment by lisgroup** [comment]
> @lisgroup 解决了没？

我使用全局注册这个 `BeforeMiddleware` 中间件确实是可以了，但是你说的这个 [前置中间件](https://learnku.com/docs/laravel/7.x/middleware/7459#0a21a0)，我不注册到 $middleware 变量中如何使用前置中间件的？

`Kernel.php`
![121](https://user-images.githubusercontent.com/31757678/80553460-825b3200-89fc-11ea-826f-dbd7448f99cf.png)

`BeforeMiddleware.php`
![222](https://user-images.githubusercontent.com/31757678/80553404-5475ed80-89fc-11ea-9966-d1effacd4ab8.png)

**Comment by hhxsv5** [comment]
中间件分为两类，一是全局中间件，二是路由中间件。如果不注册全局`$milddleware`，那你需要把中间件配置到具体路由上。
![image](https://user-images.githubusercontent.com/7278743/80562107-45e9ff00-8a19-11ea-8738-32e53ae2b3d1.png)

**Comment by lisgroup** [comment]
没在意配置项也有 `middleware` 选项，哈哈这次彻底搞好了。
