### ISSUE TITLE
Laravel passport  配置参数污染问题

### ISSUE THREAD

**Issue by glzjin** [hhxsv5/laravel-s#25]
一开始是页面会莫名的退出登录，然后再次尝试登录的时候就出错了。查看日志提示是 AuthManager  的某个方法未定义。

Method attempt does not exist. {“exception”:”[object] (BadMethodCallException(code: 0): Method attempt does not exist.

这就有点奇怪了，明明在 php-fpm  下啥事都没有。更加邪门的是，这个在正式环境下才有问题，测试环境下一点问题都没有。后来仔细排查，阅读了这部分的所有相关源码之后，发现 Auth driver  加载的居然是 api 的，然而这个是 web 的路由呀。仔细追查下去，发现是 Laravel passport  在加载时改写了 config，在调用 shouldUse 方法时，如果是 api 路由，就把默认的 driver 改成他自己了，这样在 api 路由当然没问题，可老铁。。。如果处理这个请求的 Worker 后来又去请求 web 了，默认的 driver 就一直是 api 了，所以才会出现上面这种情况。

知道是什么原因了，解决就好说了，把 config 给重置下，可怎么重置也略有点蛋疼。。。

**Comment by glzjin** [comment]
我的修复在这- -https://github.com/glzjin/laravel-s/commit/82d16c71abc11fdf8aebd7083aa5de7dd381fa54

**Comment by glzjin** [comment]
怕其他包也可能会用这种方式来修改配置，毕竟他们没考虑到这种情况- -所以我就直接清空再加载了，免得用其他包的时候也遇到这种问题。

**Comment by hhxsv5** [comment]
是因为Passport通过`setDefaultDriver()`强行修改了`auth.defaults.guard`。

你的解决方法没有大问题，不过有点儿复杂，可以简化下。

**Comment by hhxsv5** [comment]
考虑在启动`Worker`时保留一份初始配置，每次请求`clone`即可。

**Comment by glzjin** [comment]
嗯，希望能有更简单的解决办法吧🤣

**Comment by hhxsv5** [comment]
@glzjin 试下master的代码，看能否修复你的问题。

**Comment by glzjin** [comment]
好嘞，回去试试。


来自阿里邮箱 iPhone版 ------------------原始邮件 ------------------发件人：XieBiao <notifications@github.com>日期：2018-04-25 10:37:21收件人：hhxsv5/laravel-s <laravel-s@noreply.github.com>抄送：glzjin <glzjin@zhaojin97.cn>, Mention <mention@noreply.github.com>主题：Re: [hhxsv5/laravel-s] Laravel passport 配置参数污染问题 (#25)@glzjin 试下master的代码，看能否修复你的问题。

**Comment by glzjin** [comment]
@hhxsv5 经测试问题已经解决，辛苦了，感谢！

**Comment by hhxsv5** [comment]
谢谢支持，见[v1.10.16](https://github.com/hhxsv5/laravel-s/releases/tag/v1.10.16)。
