### ISSUE TITLE
Can't push data in controller.

### ISSUE THREAD

**Issue by Gildars** [hhxsv5/laravel-s#250]
**Environment:**
- laradock
- php 7.4.5
- laravel 7.7.1
- nginx
- php-fpm
```
+---------------------------+---------+
| Component                 | Version |
+---------------------------+---------+
| PHP                       | 7.4.5   |
| Swoole                    | 4.4.17  |
| LaravelS                  | 3.7.0   |
| Laravel Framework [local] | 7.7.1   |
+---------------------------+---------+
>>> Protocols
+----------------+--------+-------------------------------+--------------+
| Protocol       | Status | Handler                       | Listen At    |
+----------------+--------+-------------------------------+--------------+
| Main HTTP      | On     | Laravel Framework             | 0.0.0.0:5200 |
| Main WebSocket | On     | App\Services\WebSocketService | 0.0.0.0:5200 |
+----------------+--------+-------------------------------+--------------+

```
I can connect to ws server, but when I try to push data in controller getting an error.
```
$fd = 1; // Find fd by userId from a map [userId=>fd].
        /**@var \Swoole\WebSocket\Server $swoole */
        $swoole = app('swoole');
        $success = $swoole->push($fd, 'Push data to fd#1 in Controller');
```
**Error**
`Target class [swoole] does not exist.`

**Comment by hhxsv5** [comment]
Hi, please make sure you request to Swoole Http Server, not FPM.
[Class swoole does not exist](https://github.com/hhxsv5/laravel-s/blob/master/KnownIssues.md#class-swoole-does-not-exist) may be helpful.

**Comment by Gildars** [comment]
@hhxsv5 Thank you! 
I just opened port 5200 in the workspace container. 
![изображение](https://user-images.githubusercontent.com/16268697/81200974-5d068f00-8fcd-11ea-833a-fa97d162a22f.png)

Also sent all requests to http://mydomain.local: 5200/
