### ISSUE TITLE
Laravel-s + Dcat admin出现csrf token mismatch错误

### ISSUE THREAD

**Issue by sparksisnotspark** [hhxsv5/laravel-s#251]
1. Your software version (Screenshot of your startup)
    
    | Software | Version |
    | --------- | --------- |
    | PHP | 7.3.15 |
    | Swoole | 4.4.17 |
    | Laravel/Lumen | 7.8.1 |

2. Detail description about this issue(error/log)

    Laravel-s + Dcat admin + nginx部署以后，登陆admin后台出现csrf token mismatch。后台是dcat 默认的测试后台。直接上php-fpm部署的话，就不会出现csrf token mismatch。这是什么原因导致的？

**Comment by sparksisnotspark** [comment]
![image](https://user-images.githubusercontent.com/13254289/81290582-e6d05e00-909a-11ea-82a4-ff19bb9fbc3e.png)

![image](https://user-images.githubusercontent.com/13254289/81290654-07001d00-909b-11ea-92fd-b78b5c6eef78.png)

登陆之后，图片也是出这个错误

**Comment by sparksisnotspark** [comment]
如果后端直接是php-fpm的话，就都是正常的

**Comment by hhxsv5** [comment]
没用过Dcat admin，猜测可能是Request对象缓存了，比如在单例、控制器的构造方法初始化$request，参考[注意事项](https://github.com/hhxsv5/laravel-s/blob/master/README-CN.md#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9)。

**Comment by sparksisnotspark** [comment]
> 没用过Dcat admin，猜测可能是Request对象缓存了，比如在单例、控制器的构造方法初始化$request，参考[注意事项](https://github.com/hhxsv5/laravel-s/blob/master/README-CN.md#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9)。
感谢回复，我再试一下。

**Comment by hhxsv5** [comment]
已新增 `DcatAdminCleaner`。
```php
'cleaners' => [
    Hhxsv5\LaravelS\Illuminate\Cleaners\SessionCleaner::class,
    Hhxsv5\LaravelS\Illuminate\Cleaners\AuthCleaner::class,
    Hhxsv5\LaravelS\Illuminate\Cleaners\DcatAdminCleaner::class,
],
```

**Comment by hooklife** [comment]
@sparksisnotspark 
我自己操作了一下，添加了一个 cleaner 类，在 app/cleaners 下面新建文件 DcatAdminCleaner.php
```
<?php

namespace App\Cleaners;
use Dcat\Admin\Octane\Listeners\FlushAdminState;
use Hhxsv5\LaravelS\Illuminate\Cleaners\BaseCleaner;

class DcatAdminCleaner extends BaseCleaner
{
    public function clean()
    {
        $flushAdminState = new FlushAdminState($this->currentApp);
        $flushAdminState->handle(null);
    }
}

```

**Comment by hooklife** [comment]
@hhxsv5 现在有很多应用针对 octane 写了一些清理的类，laravel-s  是否考虑兼容一下，例如这个
https://learnku.com/docs/dcat-admin/2.x/laravel-octane/10817

**Comment by hhxsv5** [comment]
@hooklife  我得调研下
