### ISSUE TITLE
请问 http_compression 设为 false 是有什么特殊原因吗

### ISSUE THREAD

**Issue by NicoChenyt** [hhxsv5/laravel-s#252]
* 遇到的问题

当做 gRPC 服务端使用时，返回超过65535字节的内容时会导致 grpc 报错。分析一波后发现是因为[这里](https://github.com/hhxsv5/laravel-s/blob/e5a7ad6bbd726a0a7b91f84af622d2f619e18d4a/config/laravels.php#L79) swooled 的 http_compression 被设置为 false 导致的。改成 true 后就正常了。

```
'swoole'                   => [
        ...
        'http_compression'   => false,
        ...
]
```

* 疑问

这个值设为 false 是有什么原因吗？改成 true 会有什么其他影响？

**Comment by hhxsv5** [comment]
我们推荐的用法是在`Swoole Http Server`外面加`Nginx`代理，由`Nginx`处理`域名解析` `ssl` `gzip`等等。所以`LaravelS`默认关闭了`Swoole`的[http_compression](https://wiki.swoole.com/#/http_server?id=http_compression) ，避免与`Nginx`重复压缩。
你提到的gRPC具体报什么错误？

**Comment by NicoChenyt** [comment]
@hhxsv5  只要返回的数据量超过65535就会报这个错，必现。

> Incoming frame of size 96014 exceeds local window size of 65535.
The (un-acked, future) window size would be 4194304 which is not exceeded.
This would usually cause a disconnection, but allowing it due tobroken HTTP2 implementations in the wild.
See (for example) https://github.com/netty/netty/issues/6520
