### ISSUE TITLE
支持分布式么

### ISSUE THREAD

**Issue by peter6968** [hhxsv5/laravel-s#253]
使用socket功能的话是基于单机部署还是集群版部署

**Comment by peter6968** [comment]
使用socket功能的话是基于单机部署还是集群版部署

**Comment by hhxsv5** [comment]
可使用[Nginx](https://docs.nginx.com/nginx/admin-guide/load-balancer/tcp-udp-load-balancer/)做代理。

**Comment by peter6968** [comment]
> 可使用[Nginx](https://docs.nginx.com/nginx/admin-guide/load-balancer/tcp-udp-load-balancer/)做代理。

使用nginx代理后，不同节点的client能配置互通么，还是需要通过开发实现互通

**Comment by hhxsv5** [comment]
不能互通，可以通过消息队列来实现，参考#232 。
