### ISSUE TITLE
使用swoole_tracker显示代码内存泄露

### ISSUE THREAD

**Issue by jingfengshi** [hhxsv5/laravel-s#254]
1. Your software version (Screenshot of your startup)
    
    | Software | Version |
    | --------- | --------- |
    | PHP | 7.2.24 |
    | Swoole | 4.4.17|
    | Laravel/Lumen | laravel|

2. Detail description about this issue(error/log)

    `我使用了swoole官方的tracker工具，想对项目进行检测下是否存在内存泄露的情况，结果给我显示包内源码有这种情况，请问是不是swoole_tracker的检测方式有问题呀？`
   
3. Some `reproducible` code blocks and `steps`

![image](https://user-images.githubusercontent.com/19483102/82188116-f6179d00-991f-11ea-9699-97ca5c822a02.png)
![image](https://user-images.githubusercontent.com/19483102/82188193-16475c00-9920-11ea-8810-2d855065848d.png)

**Comment by hhxsv5** [comment]
这里每次`$server`会[重置](https://github.com/hhxsv5/laravel-s/blob/master/src/Swoole/Request.php#L29)，不会泄露，不必在意。
