### ISSUE TITLE
php bin/laravels start TypeError

### ISSUE THREAD

**Issue by dream798** [hhxsv5/laravel-s#256]
PHP                         | 7.4.5   |
Swoole                    | 4.5.1   |
LaravelS                  | 3.7.3   |
Laravel Framework [local] | 7.12.0 

when run "php bin/laravels start"
it shows:

   TypeError 

  Argument 1 passed to Hhxsv5\LaravelS\Illuminate\LaravelSCommand::preSet() must be of the type array, null given, called in /opt/project/local.swoole.com/vendor/hhxsv5/laravel-s/src/Illuminate/LaravelSCommand.php on line 178

  at vendor/hhxsv5/laravel-s/src/Illuminate/LaravelSCommand.php:201
    197|         $jsonConfig = json_encode($config, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
    198|         return file_put_contents(base_path('storage/laravels.json'), $jsonConfig) > 0 ? 0 : 1;
    199|     }
    200| 
  > 201|     protected function preSet(array &$svrConf)
    202|     {
    203|         if (!isset($svrConf['enable_gzip'])) {
    204|             $svrConf['enable_gzip'] = false;
    205|         }

      +16 vendor frames 
  17  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

**Comment by hhxsv5** [comment]
It should have failed to read the configuration `config/laravels.php`, please try to clear config cache `php artisan config:clear`.
