### ISSUE TITLE
How to set Header or Cookie at response

### ISSUE THREAD

**Issue by Arkanius** [hhxsv5/laravel-s#259]
Hi, I'm tryind to set some header and cookies in my response and it is not possible. I know that some default functions of php laravel can't work with swoole but I'd like to use the functions of the php-swoole  extension like the class: *Swoole\Http\Response*

I tried to get the instance of swoole by running *app('swoole');" and set the response but it's not possible as well.

Anyone know if theres any way to do this?

Tks!

**Comment by hhxsv5** [comment]
Hello @Arkanius 
Same as using under PHP-FPM,  [Attaching Headers](https://laravel.com/docs/7.x/responses#attaching-headers-to-responses) [Attaching Cookies](https://laravel.com/docs/7.x/responses#attaching-cookies-to-responses) through Laravel Response, NOT by `app('swoole')`.

**Comment by Arkanius** [comment]
Sorry @hhxsv5 , it really worked well, in my case I was with a local problem not related with swoole. Tks!
