### ISSUE TITLE
WebSocketHandlerInterface如何监听php bin/laravels start事件

### ISSUE THREAD

**Issue by kuaifan** [hhxsv5/laravel-s#261]
在WebSocketHandlerInterface里面能否监听到运行php bin/laravels start的事件。

**Comment by hhxsv5** [comment]
为什么要这么做？

**Comment by kuaifan** [comment]
需要开初始化环境的时候处理一些数据，有什么办法可以判断到系统初始化

**Comment by hhxsv5** [comment]
参考 [事件回调函数](https://github.com/hhxsv5/laravel-s/blob/master/README-CN.md#%E9%85%8D%E7%BD%AEswoole%E7%9A%84%E4%BA%8B%E4%BB%B6%E5%9B%9E%E8%B0%83%E5%87%BD%E6%95%B0)。

**Comment by kuaifan** [comment]
有用
