### ISSUE TITLE
laravels的websocket可以实现语音通话吗？

### ISSUE THREAD

**Issue by kuaifan** [hhxsv5/laravel-s#268]
语音小白一个，swoole没弄过语音通话，不知道什么现实的

**Comment by hhxsv5** [comment]
当然可以，建立全双工的TCP长连接即可。

**Comment by kuaifan** [comment]
赞，能否提供简单例子

**Comment by hhxsv5** [comment]
我也没有相关的经验，可以看看这个项目[webrtc](https://github.com/swoole-plus/webrtc)。
