### ISSUE TITLE
http 请求时，错误没有渲染出来

### ISSUE THREAD

**Issue by Hanson** [hhxsv5/laravel-s#269]
## 环境
    | Software | Version |
    | --------- | --------- |
    | PHP | 7.4.3 |
    | Swoole | 4.5.2 |
    | Laravel/Lumen |  7.15.0 |

具体表现为一直访问转圈，错误信息没有渲染

![image](https://user-images.githubusercontent.com/10583423/84971192-cb06b000-b14e-11ea-8ed3-5362b7492794.png)

从请求可以看出已经返回500，但是 time 一直是 pending ，这也是没有渲染错误的主要原因

![image](https://user-images.githubusercontent.com/10583423/84971257-e70a5180-b14e-11ea-9a21-76c376775fcc.png)

再看请求返回的 header 可以看出实际上服务器已经返回了错误信息（有 response 长度）

原因猜测可能跟 laravels 的 http 返回处理有关系

**Comment by hhxsv5** [comment]
请提供复现的代码以及Swoole/Laravel日志。
看到你请求头中有`X-Ratelimit-*`，有无可能是频率限制引起的？
