### ISSUE TITLE
ab内外网测试差异

### ISSUE THREAD

**Issue by dishcheng** [hhxsv5/laravel-s#273]
![image](https://user-images.githubusercontent.com/26062252/86863510-e8032300-c0fd-11ea-9473-649e5c5947b8.png)
服务器是两核四G的，内网直接走端口qps高达2600，走外网配置的nginx只有100不到，这算正常的吗？
nginx直接参考的文档配置的，页面抛的是404

**Comment by hhxsv5** [comment]
有差异是正常的，差异大小取决于施压机器与被压机器之间网络通畅程度。
