### ISSUE TITLE
lumen  6.0 框架 集成了 Laravels 发现定时任务-- laravel的任务调度 存在问题

### ISSUE THREAD

**Issue by dafa168** [hhxsv5/laravel-s#274]
1. Your software version (Screenshot of your startup)
    
    | Software | Version |
    | --------- | --------- |
    | PHP | 7.2.32|
    | Swoole | 4.4.18|
    | Laravel/Lumen | 6.*|

2. Detail description about this issue(error/log)

     1、时间间隔不对， 有时候两分钟，有时候四分钟  
     2、在任务调度中 app/Console/Kernel.php  schedule方法 会被执行两次 

3. Some `reproducible` code blocks and `steps`

    ```PHP
    //laravels.php 
    'timer'                    => [
        'enable'        => true,
        'jobs'          => [
            // Enable LaravelScheduleJob to run `php artisan schedule:run` every 1 minute, replace Linux Crontab
            \Hhxsv5\LaravelS\Illuminate\LaravelScheduleJob::class,


     //  任务调度 
    protected function schedule(Schedule $schedule)
    {
        info(__METHOD__ . ' ------------ schedule:run start ------------------------');

        $start = date('Ymd');
        $end = date('Ymd');

        $this->analyze = config('bi_analyze.analyze');
      
        foreach ($this->analyze as $key => $item) {

                $keys = array_keys($item);
                foreach ($keys as $k) {
                    $job = $schedule->command("command:build_data --option={$k} --start={$start} --end={$end}")
                        ->runInBackground();
                }

    ```

log日志里面： 

[2020-07-17 10:34:35] local.INFO: App\Console\Kernel::schedule ------------ schedule:run start ------------------------  
[2020-07-17 10:34:36] local.INFO: App\Console\Kernel::schedule ------------ schedule:run start ------------------------  

[2020-07-17 10:54:36] local.INFO: App\Console\{closure} --- task_list_min :"order_alert"  
[2020-07-17 10:57:46] local.INFO: App\Console\{closure} --- task_list_min :"order_alert"

**Comment by linzi007** [comment]
also found this issue

**Comment by hhxsv5** [comment]
1. 时间间隔有误差：几秒以内是正常的；几分钟的误差可能是你任务执行时间太久导致，建议加上`runInBackground()`让任务后台运行，不阻塞整个Schedule；
2. schedule方法被执行两次：是否忘记关掉Linux Crontab？

**Comment by dafa168** [comment]
我们自己写了新的方式跑任务，暂时先不用这个了。
