### ISSUE TITLE
请问是否可以在不使用任意laravel组件的情况下 在http请求方法内使用协程

### ISSUE THREAD

**Issue by boyfoo** [hhxsv5/laravel-s#276]
1. Your software version (Screenshot of your startup)
    
    | Software | Version |
    | --------- | --------- |
    | PHP | 7.2.25 |
    | Swoole | 4.4.8 |
    | Laravel/Lumen | 6.0 |

2. Detail description about this issue(error/log)

    假设有这样的场景，接收到客户的请求，要向其他多个服务器发送一个类似广播的请求 

3. Some `reproducible` code blocks and `steps`

    ```PHP
    public function store(Request $request)
    {
        go(function () {
            dump(1);
            $cli = new \Swoole\Coroutine\Http\Client("127.0.0.1", 5400);
            $cli->get('/sleep');
            dump($cli->body);
            $cli->close();
        });

        go(function () {
            dump(1);

            $cli = new \Swoole\Coroutine\Http\Client("127.0.0.1", 5500);
            $cli->get('/sleep');
            dump($cli->body);
            $cli->close();

        });
   }
    ```

情况这种情况 不使用laravel内部组件 可否使用协程？

**Comment by hhxsv5** [comment]
目前不行，主要是容器在协程环境下有问题，请参考[文档](https://github.com/hhxsv5/laravel-s/blob/master/README-CN.md#%E5%8D%8F%E7%A8%8B)。
