### ISSUE TITLE
Integration with AWS load balancer

### ISSUE THREAD

**Issue by juber-ivre** [hhxsv5/laravel-s#279]
This is more a question than an issue.

Anyone used AWS Load balancer rather than Nginx? Or perhaps a combination of both?

Any tips on set it up?

Thanks in advance

**Comment by hhxsv5** [comment]
@juber-ivre I have no experience with AWS Load balancer,  [this document](https://aws.amazon.com/elasticloadbalancing/getting-started/?nc1=h_ls) may be useful.

**Comment by immersivevreducation** [comment]
@hhxsv5 Thanks for that. I'm used to AWS load balancer overall but I was wondering if I would need to keep Nginx attached to the application or if I could use AWS LB without Nginx.

**Comment by hhxsv5** [comment]
@immersivevreducation LaravelS is originally an HTTP serve based on Swoole. Nginx is usually used to proxy, resolve domain names, load balance, and process static files. But Swoole's support for static files is not complete. If you don't have static file requirements, you don't need to use Nginx.

**Comment by immersivevreducation** [comment]
@hhxsv5 Makes perfect sense. Thank you so much for that. Hope that helps someone else on the same situation.

**Comment by hhxsv5** [comment]
@immersivevreducation Anytime.
