### ISSUE TITLE
Target class [swoole] does not exist

### ISSUE THREAD

**Issue by whs891015** [hhxsv5/laravel-s#283]
1. Your software version (Screenshot of your startup)
    
    | Software | Version |
    | --------- | --------- |
    | PHP | 7.2 |
    | Swoole |  4.5.0-alpha |
    | Laravel/Lumen | Laravel6.18.19 |

2. Detail description about this issue(error/log)

    Target class [swoole] does not exist.

3. Some `reproducible` code blocks and `steps`

     public function handle()
    {
        Redis::rpush('camera_request',$this->data);
    }
    public function finish(){
        Log::info('处理完成',$this->data);
    }
   使用: $data = ['num'=>rand(10,9999),'time'=>now()];
        $task = new CameraTask($data);
        Task::deliver($task);
    // TODO: your code
  

1. swoole 扩展已安装
2.LaravelS也正常启动

**Comment by hhxsv5** [comment]
没有运行LaravelS环境下，#224

**Comment by whs891015** [comment]
已解决谢谢了
