### ISSUE TITLE
request()->header('cookie') 取不到信息

### ISSUE THREAD

**Issue by wangzhoudong** [hhxsv5/laravel-s#284]
1. Your software version (Screenshot of your startup)
    
    | Software | Version |
    | --------- | --------- |
    | PHP | 7.3.13 |
    | Swoole | 4.5.2 |
    | Laravel/Lumen | 5.5.49 |

2. Detail description about this issue(error/log)

    `request()->header('cookie') 取不到信息 但是用request()->cookie()能拿到信息`

**Comment by hhxsv5** [comment]
`$request->cookie('name')` 是正确用法，参考文档[Cookies](https://learnku.com/docs/laravel/5.5/requests/1297#cookies)。

**Comment by wangzhoudong** [comment]
> `$request->cookie('name')` 是正确用法，参考文档[Cookies](https://learnku.com/docs/laravel/5.5/requests/1297#cookies)。

2个方法返回信息，不一样，一个是返回原生的字符串，一个是返回数组。php-fpm 下通过request()->header('cookie')是能拿到原生的字符串的

**Comment by hhxsv5** [comment]
由于`Swoole\HTTP\Request`对象已经将`Cookie`从头部中拆分出来了，拆分成$request->header与$request->cookie，所以`Illuminate\Http\Request`对象的`headers`属性中没有`cookie`，我得到的是`null`。
而FPM下是通过`$_SERVER['HTTP_COOKIE']`来获取的请求头`Cookie`的原始值。
下面是我的例子：
```php
Route::get('/', function (\Illuminate\Http\Request $request) {
    return [php_sapi_name(), $request->cookie('abc'), $request->header('cookie')];
});
```

![image](https://user-images.githubusercontent.com/7278743/89998152-bf9fb300-dcbf-11ea-8249-cc79851d4183.png)
