### ISSUE TITLE
Can not publish

### ISSUE THREAD

**Issue by error1001es** [hhxsv5/laravel-s#285]
1. Your software version (Screenshot of your startup)
    
    | Software | Version |
    | --------- | --------- |
    | PHP | 7.4.9 | 
    | Swoole |  4.5.2 |
    | Laravel/Lumen |  7.24 |

2. Detail description about this issue(error/log)
     just follow installation instructions
     i typed command composer require `hhxsv5/laravel-s:~3.7.0` -vvv
     next typed `php artisan laravels publish` and got error `Command "laravels" is not defined.`
     next tried add line to `config/app.php`
     `'providers' => [
    //...
    Hhxsv5\LaravelS\Illuminate\LaravelSServiceProvider::class,
     ],`
    and got error ` Class 'Hhxsv5\LaravelS\Illuminate\LaravelSServiceProvider' not found`

**Comment by hhxsv5** [comment]
Please check if laravel-s is installed successfully.
```bash
composer show hhxsv5/laravel-s
```
Refer to the [installation steps](https://github.com/hhxsv5/laravel-s#install).

**Comment by error1001es** [comment]
Package hhxsv5/laravel-s not found
but i follow installation steps.

**Comment by error1001es** [comment]
![image](https://user-images.githubusercontent.com/49606492/90096737-edcfd200-dd55-11ea-8ab7-fce543bbf0a4.png)

**Comment by hhxsv5** [comment]
![image](https://user-images.githubusercontent.com/7278743/90206879-634fa700-de17-11ea-9b63-6bb755dc12d8.png)
It may be that memory limit was reached.

try `COMPOSER_MEMORY_LIMIT=-1  composer require "hhxsv5/laravel-s:~3.7.0" -vvv`
