### ISSUE TITLE
想问下，我想使用session，应该怎么写呢？

### ISSUE THREAD

**Issue by wotemenige** [hhxsv5/laravel-s#290]
1.http请求；
2.第一个人第一次进来存入session；
3第二个人第一次进来，就获取到了第一个人的session；

请问这个问题怎么解决

**Comment by hhxsv5** [comment]
[配置清理器](https://github.com/hhxsv5/laravel-s/blob/master/Settings-CN.md#cleaners).

**Comment by wotemenige** [comment]
> [配置清理器](https://github.com/hhxsv5/laravel-s/blob/master/Settings-CN.md#cleaners).

谢谢，您回复的很及时
