### ISSUE TITLE
swoole自动关闭

### ISSUE THREAD

**Issue by whs891015** [hhxsv5/laravel-s#291]
1. Your software version (Screenshot of your startup)
    
    | Software | Version |
    | --------- | --------- |
    | PHP | 7.2 |
    | Swoole | 4.5|
    | Laravel/Lumen | 3.7 |

2. Detail description about this issue(error/log)

   运行 php bin/laravels start提示 Swoole is running, press Ctrl+C to quit

如何关闭swoole
3. Some `reproducible` code blocks and `steps`

    ```PHP
    // TODO: your code
    ```

**Comment by hhxsv5** [comment]
`php bin/laravels stop`，请看[文档](https://github.com/hhxsv5/laravel-s/blob/master/README-CN.md#%E8%BF%90%E8%A1%8C)。

**Comment by whs891015** [comment]
![bug](https://user-images.githubusercontent.com/23496956/91253902-8709da00-e793-11ea-93e7-9ec72377ae0e.png)

**Comment by whs891015** [comment]
问题出现在我start之后为什么会自动关闭了

**Comment by hhxsv5** [comment]
看看`storage`目录下的日志？

**Comment by whs891015** [comment]
storage 没有日志只有一个配置文件

**Comment by hhxsv5** [comment]
执行`php -m`看看有没有什么[不兼容的扩展](https://wiki.swoole.com/#/getting_started/extension)。

**Comment by whs891015** [comment]
已解决 我手误把入口文件删了 谢谢了
