### ISSUE TITLE
laravels结合nginx的配置的疑问

### ISSUE THREAD

**Issue by wotemenige** [hhxsv5/laravel-s#292]
我看文档上写着：
   location / {
        try_files $uri @laravels;
   }
  
location @laravels {
         xxx
  }
如果这样写的话，静态资源也走了 @laravels了啊； 那怎么分配静态资源呢？

**Comment by hhxsv5** [comment]
[try_files](http://nginx.org/en/docs/http/ngx_http_core_module.html#try_files)指令优先从配置的`root`目录中查找`$uri`文件，找到文件直接响应，否则再将请求转发给`@laravels`。

**Comment by wotemenige** [comment]
> [try_files](http://nginx.org/en/docs/http/ngx_http_core_module.html#try_files)指令优先从配置的`root`目录中查找`$uri`文件，找到文件直接响应，否则再将请求转发给`@laravels`。

我的根目录指定到了public，那么，访问项目都是走的php-fpm，没有走监听了；

**Comment by wotemenige** [comment]
> > [try_files](http://nginx.org/en/docs/http/ngx_http_core_module.html#try_files)指令优先从配置的`root`目录中查找`$uri`文件，找到文件直接响应，否则再将请求转发给`@laravels`。
> 
> 我的根目录指定到了public，那么，访问项目都是走的php-fpm，没有走监听了；

应该是我理解错了，这样是可以的；谢谢

**Comment by wotemenige** [comment]
> [try_files](http://nginx.org/en/docs/http/ngx_http_core_module.html#try_files)指令优先从配置的`root`目录中查找`$uri`文件，找到文件直接响应，否则再将请求转发给`@laravels`。

好像还是不行； 比如我public里面有个ce目录，ce目录下面有个index.html； 如果我访问 xxx.com/ce/ 就会报laravel的404； 我加上 xxx.com/ce/index.html就可以了。 也就是访问xx.com/ce/ 也走了 @laravels； 不知道这个问题怎么解决呢？

**Comment by wotemenige** [comment]
> [try_files](http://nginx.org/en/docs/http/ngx_http_core_module.html#try_files)指令优先从配置的`root`目录中查找`$uri`文件，找到文件直接响应，否则再将请求转发给`@laravels`。

额，然后我改成 location / {
try_file $uri $uri/ @laravels;
}


这样就可以了啊

**Comment by hhxsv5** [comment]
如果你需要查找目录，就需要加$uri/
