### ISSUE TITLE
多端口协议问题

### ISSUE THREAD

**Issue by whs891015** [hhxsv5/laravel-s#293]
1、创建了tcp（异步服务器）
2、在控制中
/**@var Server $swoole */
  $swoole = app('swoole');
 $result = $swoole->send($fd,'0204809061000D');
3、我想收到发送条信息的返回的值
4、onReceive监听了客户端的所有的信息，不知道哪条信息是发送这条信息（$swoole->send($fd,'0204809061000D')）的返回值

**Comment by hhxsv5** [comment]
`$result`是send()的返回值、结果，不是send 0204809061000D给客户端后客户端send的数据，你需要自己实现这层逻辑绑定。
比如：
控制器中：send ['id'=>'abc', 'msg'=>'msg1']
客户端：onReceive 收到['id'=>'abc', 'msg'=>'msg1']，然后 send带上一个来源Id src_id [ 'id'=>'efg', 'msg'=>'msg2', 'src_id' => 'abc']
服务端：onReceive就会受到[ 'id'=>'efg', 'msg'=>'msg2', 'src_id' => 'abc']，判断src_id='abc'就知道了。
