### ISSUE TITLE
为什么session会重复呢？

### ISSUE THREAD

**Issue by wotemenige** [hhxsv5/laravel-s#294]
我的使用场景：
1.用户进来后，如果没有session信息，我会让用户去授权，然后重新进来，并存上session；如果有session，然后根据session看用户表里是否有用户信息，如果没有再去授权；授权处存储用户id，session(['user'=>1]);

比如现在的用户id是1；我的session是这样设置的  session(['user'=>1]);

2.现在的问题是：我把用户表的用户数据给清除了；也就是session还在，但是用户数据没了；然后我发现第一个接口检测到session不存在了，就去授权，然后存入用户信息；session(['user'=>2]);然后第二个接口，请求的时候还是会带上session('user'）=1;

但这第二个接口的session应该是被第一个接口的session覆盖了啊，为啥还会出现session('user')=1的情况呢？

**Comment by hhxsv5** [comment]
[打开Cleaner][https://github.com/hhxsv5/laravel-s/blob/master/Settings-CN.md#cleaners]

**Comment by wotemenige** [comment]
就是清不掉。。。我去
