### ISSUE TITLE
同一台机器多个项目时nginx配置？

### ISSUE THREAD

**Issue by endingman** [hhxsv5/laravel-s#295]
多个项目 nginx 怎么配置？

端口可以不同项目设置不同的端口吗？

然后 nginx 配置 upstream swoole 不同端口吗？

**Comment by hhxsv5** [comment]
不同的项目，监听不同的端口，Nginx设置不同的域名，转发到不同的upstream。

**Comment by endingman** [comment]
看懂了，配置文件。谢谢。
