### ISSUE TITLE
异步任务投递有个地方不明白

### ISSUE THREAD

**Issue by wotemenige** [hhxsv5/laravel-s#296]
问题描述：
根据文档上面的异步任务队列：
![image](https://user-images.githubusercontent.com/30307725/92495754-e2bf7300-f229-11ea-99d2-bd5da5461984.png)

我开了两个task_work:
在任务类的construct里面两个task都能用到，
但是在handle里面只用了一个；

我开了四个task_work:
在任务类的construct里面四个task都能用到，
但是在handle里面只能用2-3个；不知道咋回事呢？

**Comment by hhxsv5** [comment]
不太清楚你的问题，请举例说明。

**Comment by wotemenige** [comment]
比如说：
我开了四个task_num,
然后我出发了TestEvent事件，然后TestListen监听到了，然后投递TestTask里面的handle,
但其实在handle里面执行的task也就是2-3个；

但是我在TestTask的构造函数里面，就会看到有4个task_num执行；

顺便再问一个问题：我设置task_num=1;在最后的任务类TestTask里面的handle执行代码报错，说 async task needs to set task_worker_num >=2 是咋回事呢；

**Comment by wotemenige** [comment]
> 不太清楚你的问题，请举例说明。
比如说：
我开了四个task_num,
然后我出发了TestEvent事件，然后TestListen监听到了，然后投递TestTask里面的handle,
但其实在handle里面执行的task也就是2-3个；

但是我在TestTask的构造函数里面，就会看到有4个task_num执行；

顺便再问一个问题：我设置task_num=1;在最后的任务类TestTask里面的handle执行代码报错，说 async task needs to set task_worker_num >=2 是咋回事呢；

**Comment by wotemenige** [comment]
![image](https://user-images.githubusercontent.com/30307725/92624109-b4a96400-f2f9-11ea-96ab-7e81775743ac.png)

就是示例文档上面的异步队列；在最后任务类里面的construct和handle里面，可以使用的task_num不一样呢

**Comment by hhxsv5** [comment]
> > 不太清楚你的问题，请举例说明。
> > 比如说：
> > 我开了四个task_num,
> > 然后我出发了TestEvent事件，然后TestListen监听到了，然后投递TestTask里面的handle,
> > 但其实在handle里面执行的task也就是2-3个；
> 
> 但是我在TestTask的构造函数里面，就会看到有4个task_num执行；
> 
> 顺便再问一个问题：我设置task_num=1;在最后的任务类TestTask里面的handle执行代码报错，说 async task needs to set task_worker_num >=2 是咋回事呢；
如果任务不是在worker进程中投递的，那它是通过sendMessage实现的，但由于不能向自己进程sendMessage，所以需要设置两个及以上的task worker进程。

**Comment by hhxsv5** [comment]
在控制器中投递的任务可以使用所有Task进程，其他地方投递的只能使用N-1个进程。
