### ISSUE TITLE
多端口混合协议，创建tcp服务；在OnReceive()里面接受不到事件；

### ISSUE THREAD

**Issue by wotemenige** [hhxsv5/laravel-s#297]
按照文档上配置了多端口协议；
使用telnet测试也成功了；
但是我在代码里面写：

![image](https://user-images.githubusercontent.com/30307725/92705422-48c10d00-f386-11ea-9ab0-60659bb2fdb7.png)

也就是最后输出的$msg，是连接上服务器后，OnCennect方法发送的；
然后socket_write();也就是客户端发送给服务器数据；
服务器接手后返回的数据，我这边接受不到；

**Comment by hhxsv5** [comment]
相同的问题 #298
