### ISSUE TITLE
关于tcp服务，给服务端发送数据，一定要加上/r/n的问题

### ISSUE THREAD

**Issue by wotemenige** [hhxsv5/laravel-s#298]
![image](https://user-images.githubusercontent.com/30307725/92829777-2d4a1680-f407-11ea-99d7-7735e39f7755.png)

我这边给5291的tcp服务发送数据；如果不加/r/n就会一直循环；
加了/r/n就可以停止了；

我想着单独的swoole可以不用加/r/n啊；为什么这里一定要加/r/n呢？

**Comment by hhxsv5** [comment]
Server端默认是以`\r\n`作为EOF判断，具体请看[TCP 粘包问题](https://wiki.swoole.com/#/learn?id=tcp%e7%b2%98%e5%8c%85%e9%97%ae%e9%a2%98)。

**Comment by wotemenige** [comment]
> Server端默认是以`\r\n`作为EOF判断，具体请看[TCP 粘包问题](https://wiki.swoole.com/#/learn?id=tcp%e7%b2%98%e5%8c%85%e9%97%ae%e9%a2%98)。

好的，谢谢；我发现配置文件：laravels中的配置：

       'settings'=>[
           'open_eof_check'=>true,
             'package_eof'=>"\r\n",
       ],

把这一段代码关闭也是可以的
