### ISSUE TITLE
携程只能在自定义进程中使用吗？

### ISSUE THREAD

**Issue by wotemenige** [hhxsv5/laravel-s#299]
想问一下，laravels配置中的携程如果打开了，就会影响全局吗？

也就是说，我打开了携程，我整个项目就只能用自定义进程对吗？

![image](https://user-images.githubusercontent.com/30307725/92939720-b487a080-f480-11ea-9a47-4f94cf5fc8f0.png)

**Comment by hhxsv5** [comment]
想问一下，laravels配置中的携程如果打开了，就会影响全局吗？
>> 会影响，不建议打开
也就是说，我打开了携程，我整个项目就只能用自定义进程对吗？
>> 自定义进程启动时已自动打开协程，不用再全局开启

**Comment by cbcfrank** [comment]
请问，自定义进程中如果不想启用协程，需要如何声明，谢谢。
