### ISSUE TITLE
$_SERVER中缺少HTTPS字段导致asset()函数返回的URL总是http开头

### ISSUE THREAD

**Issue by efans007** [hhxsv5/laravel-s#30]
1. Tell us your PHP version(`php -v`)

php 7.0.6

2. Tell us your Swoole version(`php --ri swoole`)

2.1.3

3. Tell us your `Laravel`/`Lumen` version(check composer.json & composer.lock)

Laravel 5.2.45

4. Detail description about this issue(error/log)

站点是https的，在模板文件中引入css文件
```HTML
<link rel="stylesheet" href="{{asset('/css/admin/bootstrap-multiselect.css')}}">
```
asset('/css/admin/bootstrap-multiselect.css')返回的URL是 http://xxxx 而不是 https://xxxx
https站点下尝试加载非https的内容，导致报错
通过追查asset()函数，最终发现是根据$_SERVER['HTTPS']的值来决定以https或以http开头生成URL

对比nginx+phpfpm，nginx+laravelS除$_SERVER['HTTPS']以外，还少了不少字段，如：
SERVER_NAME、REQUEST_SCHEME

**Comment by hhxsv5** [comment]
FPM下是由FPM自动解析了Nginx服务器信息，而使用Swoole时需Nginx增加转发这些信息(通过Header)
```Nginx
location @laravels {
        proxy_http_version 1.1;
        # proxy_connect_timeout 60s;
        # proxy_send_timeout 60s;
        # proxy_read_timeout 120s;
        proxy_set_header Connection "keep-alive";
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Real-PORT $remote_port;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_set_header Scheme $scheme;
        proxy_set_header Server-Protocol $server_protocol;
        proxy_set_header Server-Name $server_name;
        proxy_set_header Server-Addr $server_addr;
        proxy_set_header Server-Port $server_port;
        proxy_pass http://laravels;
}
```
拉Master代码试试。

**Comment by hhxsv5** [comment]
见 [v1.10.17](https://github.com/hhxsv5/laravel-s/tree/v1.10.17)。
