### ISSUE TITLE
在服务器上并没有得到预期的性能提升

### ISSUE THREAD

**Issue by nameisshow** [hhxsv5/laravel-s#301]
本地环境RPS 20+，使用laravel-s加速后RPS提高到150+，但是在线上服务器（16核32G）几乎没有提升，压测时使用top命令查看，发现CPU几乎不动，占用不到2%。
使用时laravels.php配置没动。
会是什么原因呢？

**Comment by tai1030** [comment]
`app('server')->stats();`

检查一下闲置worker 或 task worker 的数量，
如果长期都是 0 闲置，那要在laravels.php调大一下worker的数量。
或者如有使用异步任务，task worker的数量也要调一下。

不同项目，有不同的实际情况，预设laravels.php配置不是适用于所有项目。

**Comment by nameisshow** [comment]
感谢回应我的问题。其实不是配置的问题，好像是我本地电脑或者本地ab软件的问题，用别的机器试了速度飞快，总访问量50000，并发访问量1000的情况下，空载RPS600+，带数据库负载也接近500，而且cpu占用也很低，平均10%的样子，总之很厉害【大拇指】

**Comment by hhxsv5** [comment]
类似的问题，参考 #267
