### ISSUE TITLE
怎么在laravel-s中配置https服务器，一直启动提示ssl配置错误。

### ISSUE THREAD

**Issue by RussellCao824** [hhxsv5/laravel-s#302]
### 启动laravels后提示ssl配置错误：

![image](https://user-images.githubusercontent.com/40130894/93775235-be658c80-fc54-11ea-92bd-4a43ef753e27.png)

### config/laravels.php配置文件中的内容：

![image](https://user-images.githubusercontent.com/40130894/93775657-48155a00-fc55-11ea-8b4d-be735aa0ca4b.png)

### 是我使用的姿势不对吗？请使用laravels配置过https的大佬指点迷津。

**Comment by hhxsv5** [comment]
你这是安装`Swoole`扩展时，需要启用编译参数[--enable-openssl](https://wiki.swoole.com/#/environment?id=%e9%80%9a%e7%94%a8%e5%8f%82%e6%95%b0)。

**Comment by RussellCao824** [comment]
> 你这是安装`Swoole`扩展时，需要启用编译参数[--enable-openssl](https://wiki.swoole.com/#/environment?id=%e9%80%9a%e7%94%a8%e5%8f%82%e6%95%b0)。

明白了，大佬。我直接跟nginx配合使用了，在nginx中完成ssl协议处理，再转发进swoole的内置http服务器中。还是官方推荐的好。
