### ISSUE TITLE
定时任务问题

### ISSUE THREAD

**Issue by whs891015** [hhxsv5/laravel-s#304]
控制器中$swoole = app('swoole');   $swoole->push($row['value'], json_encode($data));是可以推送的，
定义一个定时任务一分钟执行一次的推送报错
 Class swoole does not exist at /Application/vendor/laravel/framework/src/Illuminate/Container/Container.php:803

**Comment by hhxsv5** [comment]
[Class swoole does not exist](https://github.com/hhxsv5/laravel-s/blob/master/KnownIssues-CN.md#class-swoole-does-not-exist)
