### ISSUE TITLE
并发写入mysql时提示SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction

### ISSUE THREAD

**Issue by cbcfrank** [hhxsv5/laravel-s#306]
在有并发写入msyql时，提示 SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction；

请问下是否我哪里配置没对。

**Comment by Louis-Ni** [comment]
检查你的代码。有可能是事务没提交，后提交的事务等待上一个事务释放锁

**Comment by cbcfrank** [comment]
> 检查你的代码。有可能是事务没提交，后提交的事务等待上一个事务释放锁

是的没错，是这个问题，并发时提交锁死了。因为没有通读过源码，仅仅只是看README文档，并没有看到关于线程池方面的介绍。不知道是否可以通过线程池来解决这个问题？

**Comment by Louis-Ni** [comment]
> > 检查你的代码。有可能是事务没提交，后提交的事务等待上一个事务释放锁
> 
> 是的没错，是这个问题，并发时提交锁死了。因为没有通读过源码，仅仅只是看README文档，并没有看到关于线程池方面的介绍。不知道是否可以通过线程池来解决这个问题？

线程池?? 你在swoole里面  哪来的线程池给你跑?  而且这跟线程池有什么关系?

**Comment by cbcfrank** [comment]
> > > 检查你的代码。有可能是事务没提交，后提交的事务等待上一个事务释放锁
> > 
> > 
> > 是的没错，是这个问题，并发时提交锁死了。因为没有通读过源码，仅仅只是看README文档，并没有看到关于线程池方面的介绍。不知道是否可以通过线程池来解决这个问题？
> 
> 线程池?? 你在swoole里面 哪来的线程池给你跑? 而且这跟线程池有什么关系?

在swoole官网是有提到线程池的（ https://wiki.swoole.com/#/coroutine/conn_pool ）
是我理解错了吗？我的想法是在laravelS中如何用到这块，避免出现上述问题。

**Comment by Louis-Ni** [comment]
> > > > 检查你的代码。有可能是事务没提交，后提交的事务等待上一个事务释放锁
> > > 
> > > 
> > > 是的没错，是这个问题，并发时提交锁死了。因为没有通读过源码，仅仅只是看README文档，并没有看到关于线程池方面的介绍。不知道是否可以通过线程池来解决这个问题？
> > 
> > 
> > 线程池?? 你在swoole里面 哪来的线程池给你跑? 而且这跟线程池有什么关系?
> 
> 在swoole官网是有提到连接池的（ https://wiki.swoole.com/#/coroutine/conn_pool ）
> 是我理解错了吗？线程池的说法口误，我的想法是在laravelS中如何用到这块连接池，避免出现上述问题。

#69 你先看这个issue吧。 你提的其实没太大意义的

**Comment by uniteweiwei** [comment]
我都直接使用自动事务了,手动难处理,要是有报错那就报错吧.没办法
