### ISSUE TITLE
修改LARAVELS_INOTIFY_RELOAD为true后，不能热更新代码

### ISSUE THREAD

**Issue by rangerdong** [hhxsv5/laravel-s#31]
1. Tell us your PHP version(`php -v`)
`php7.2  + lumen`

2. Tell us your Swoole version(`php --ri swoole`)

`3.0.0-alpha`

3. Tell us your `Laravel`/`Lumen` version(check composer.json & composer.lock)

`Lumen (5.6.3)`

4. Detail description about this issue(error/log)

`已经安装inotify拓展，版本为 2.0.0  但是更新代码后不生效，并且reload配置更新为true， 我是搭建在docker容器内的`

5. Give us a `reproducible` code block

```PHP
.env
LARAVELS_INOTIFY_RELOAD=true
```

**Comment by hhxsv5** [comment]
更改文件是在Linux环境下？

**Comment by rangerdong** [comment]
是的，在docker环境下

**Comment by hhxsv5** [comment]
修改文件要在Linux内，不能再容器外部修改。`Inotify`无法检测容器外的变更。

**Comment by rangerdong** [comment]
意思目录映射后的代码更新，inotify检测不到吗？那这种情况怎么更新呢 在容器内git更新？

**Comment by hhxsv5** [comment]
手动重启或或配置Crontab定时重启。
