### ISSUE TITLE
控制器推送异步任务报错

### ISSUE THREAD

**Issue by zhaitailang** [hhxsv5/laravel-s#311]
1. Your software version (Screenshot of your startup)
    
    | Software | Version |
    | --------- | --------- |
    | PHP | 7.4.8|
    | Swoole | 4.5.3 |
    | LaravelS | 3.7.8 |
    | Laravel | 7.25.0 |

2. Detail description about this issue(error/log)
   前一段时间开发出现这个错误  我升级了laravels到最新版本，错误也没在出现过，今天写一个新的异步任务开始报错，之前写的异步任务也无法正常执行了。
   [2020-10-23 17:08:56] local.ERROR: Uncaught ArgumentCountError: Too few arguments to function 
   Hhxsv5\LaravelS\Swoole\Server::onTask(), 2 passed and exactly 4 expected in 
   /home/vagrant/laravel_exchange/vendor/hhxsv5/laravel-s/src/Swoole/Server.php:283
  Stack trace:
  #0 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught ArgumentCountError: 
  Too few arguments to function Hhxsv5\\LaravelS\\Swoole\\Server::onTask(), 2 passed and exactly 4 expected in 
  /home/vagrant/laravel_exchange/vendor/hhxsv5/laravel-s/src/Swoole/Server.php:283
  Stack trace:
  #0 {main}
    thrown at /home/vagrant/laravel_exchange/vendor/hhxsv5/laravel-s/src/Swoole/Server.php:283)
    [stacktrace]
    #0 {main}
"} 

3. Some `reproducible` code blocks and `steps`

    ```PHP
    use Hhxsv5\LaravelS\Swoole\Task\Event;
    public function store(Request $request)
    {
        $data = [
            'symbol'=>$request->symbol,
            'type'=>$request->type,
            'transaction'=>$request->transaction,
            'price'=>$request->price,
            'volume'=>$request->volume,
        ];
        $event = new OrderEvent($data);
        Event::fire($event);
    }

   use App\Listeners\OrderListener;
   use Hhxsv5\LaravelS\Swoole\Task\Event;
   class OrderEvent extends Event
   {
         protected $listeners = [
             // 监听器列表
             OrderListener::class,
         ];
         private $data;
         /**
          * Create a new event instance.
          *
          * @return void
          */
          public function __construct($data)
          {
             $this->data = $data;
          }  
         public function getData()
        {
            return $this->data;
        }
   }

      use Hhxsv5\LaravelS\Swoole\Task\Listener;
      class OrderListener extends Listener
       {
           protected $event;
           /**
              * Handle the event.
              *
              * @param  AssetsSystem  $event
              * @return void
              */
           public function handle()
           {
                $data = $this->event->getData();
                \Log::info('order',[$data]);
          }
      }
```

**Comment by Louis-Ni** [comment]
这个on task函数是swoole 底层回调的。 你看看配置是否正确

**Comment by yzh0325** [comment]
> 这个on task函数是swoole 底层回调的。 你看看配置是否正确

我也遇到了这个问题，请问是要检查什么配置呢
