### ISSUE TITLE
php7.4不支持吗

### ISSUE THREAD

**Issue by huchenghua** [hhxsv5/laravel-s#314]
1. Your software version (Screenshot of your startup)
    
    | Software | Version |
    | --------- | --------- |
    | PHP | 7.4 |
    | Swoole | 4|
    | Laravel/Lumen | 8|

2. Detail description about this issue(error/log)

    `  Problem 1
    - This package requires php 7.2.* but your PHP version (7.4.12) does not satisfy that requirement.
`

3. Some `reproducible` code blocks and `steps`

    ```PHP
    // TODO: your code
    ```

**Comment by hhxsv5** [comment]
支持，请看具体是什么包依赖php 7.2.*。
