### ISSUE TITLE
控制器基类中的构造函数中执行中间件，获取属性中字段，第二次刷新就报错！

### ISSUE THREAD

**Issue by dafa168** [hhxsv5/laravel-s#316]
1. Your software version (Screenshot of your startup)
    
    | Software | Version |
    | --------- | --------- |
    | PHP | 7.2.9|
    | Swoole | 4.4.19|
    | Laravel/Lumen | 6.*|

2. Detail description about this issue(error/log)

    username 属性找不到 。。。。

3. Some `reproducible` code blocks and `steps`

    Controller.php
```
<?php
namespace App\Http\Controllers;
class Controller extends BaseController
{
    protected $user;
    public function __construct()
    {
        //执行中间件获取用户信息
        $this->middleware(function ($request, $next) {
            $this->user = $this->getUser();
            return $next($request);
        });
    }

    /**
     * 获取用户信息
     * @return array
     */
    public function getUser()
    {
        $user = collect(Auth::user())->all();
        return $user;
    }
}
```

IndexController.php  
```
<?php
namespace App\Http\Controllers\Admin;
class IndexController extends Controller
{
    public function index()
    {
        $user = $this->user ;
        echo $user->username;  // TODO: 第一次进入可以获取，在刷新一次，就报错了。
        return view('admin.index.index', compact('user'));
    }
}
```

**Comment by Louis-Ni** [comment]
[看下有没有打开这个](https://github.com/hhxsv5/laravel-s/blob/master/Settings-CN.md#cleaners)

**Comment by hhxsv5** [comment]
常见的[单例控制器](https://github.com/hhxsv5/laravel-s/blob/master/KnownIssues-CN.md#%E5%8D%95%E4%BE%8B%E6%8E%A7%E5%88%B6%E5%99%A8)问题。

**Comment by dafa168** [comment]
> [看下有没有打开这个](https://github.com/hhxsv5/laravel-s/blob/master/Settings-CN.md#cleaners)

已经打开了， 控制器默认是全部销毁的。

**Comment by dafa168** [comment]
> 常见的[单例控制器](https://github.com/hhxsv5/laravel-s/blob/master/KnownIssues-CN.md#%E5%8D%95%E4%BE%8B%E6%8E%A7%E5%88%B6%E5%99%A8)问题。

两种解决方法(二选一) ！ 已经采用了第二种方法。 问题还是存在的。 
```
    'destroy_controllers'      => [
        'enable'        => true,
        'excluded_list' => [],
    ],
```

**Comment by dafa168** [comment]
销毁控制器，应该是要销毁到控制器的基类。
