### ISSUE TITLE
如何根据域名动态加载env文件？

### ISSUE THREAD

**Issue by WangNingkai** [hhxsv5/laravel-s#317]
1. Your software version (Screenshot of your startup)
    
    | Software | Version |
    | --------- | --------- |
    | PHP | 7.4.12|
    | Swoole | 4.5.3 |
    | Laravel/Lumen | 8.15 |

2. Detail description about this issue(error/log)

![image](https://user-images.githubusercontent.com/23030927/99780561-9f4e8280-2b51-11eb-9452-c9970eef80ba.png)

 请问如果使用此项目，如何根据域名动态加载env文件

**Comment by hhxsv5** [comment]
laravel-s与php-fpm的运行模式不同，导致请求的生命周期也不同。
- laravel-s：常驻进程，启动一次，启动时加载.env等配置、初始化框架，请求处理完后进程不会退出，请求级局部变量回收资源，全局和静态资源将保留；
- php-fpm：请求级进程，每次请求到来时都会加载.env等配置、初始化框架，请求结束后销毁并回收所有资源；

按域名动态加载.env配置，这个需求我认为是不合理的，如果一定要实现，你可以把多域名的配置存进数据库，然后在业务代码中来读库实现。

**Comment by WangNingkai** [comment]
感谢您的解答，我也考虑了多种方法，确实目前折中的做法就是存在数据库
