### ISSUE TITLE
LaravelS failed to start if Swoole extension is enabled through command line arguments

### ISSUE THREAD

**Issue by filakhtov** [hhxsv5/laravel-s#319]
1. Your software version (Screenshot of your startup)
    
    | Software | Version |
    | --------- | --------- |
    | PHP | 7.4.12 |
    | Swoole | 4.5.5 |
    | Laravel | 8.16.1 |

2. Detail description about this issue(error/log)

I was playing with Swoole, but don't have it enabled via PHP config, instead I use the command line option when I need to run Swoole, like so:

```bash
php -d extension="swoole.so" ...
```

LaravelS is running the `./artisan laravels config` command in the subprocess when starting, leading to:

```
$ php -d extension="swoole.so" ./bin/laravels start
 _                               _  _____ 
| |                             | |/ ____|
| |     __ _ _ __ __ ___   _____| | (___  
| |    / _` | '__/ _` \ \ / / _ \ |\___ \ 
| |___| (_| | | | (_| |\ V /  __/ |____) |
|______\__,_|_|  \__,_| \_/ \___|_|_____/ 
                                           
Speed up your Laravel/Lumen
>>> Components

   Error 

  Call to undefined function Hhxsv5\LaravelS\Illuminate\swoole_version()

  at vendor/hhxsv5/laravel-s/src/Illuminate/LaravelSCommand.php:105
    101▕                 phpversion(),
    102▕             ],
    103▕             [
    104▕                 'Swoole',
  ➜ 105▕                 swoole_version(),
    106▕             ],
    107▕             [
    108▕                 'LaravelS',
    109▕                 $laravelSVersion,

      +15 vendor frames 
  16  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
```

Given the above `artisan` command is purely information, it would be nice to handle this failure gracefully or collect this same information without using a subprocess. Possibly a switch to disable information banner?

3. Some `reproducible` code blocks and `steps`

Brand new, clean Laravel project with LaravelS installed and not having Swoole enabled in the configuration, but running the project using:

```bash
php -d extension="swoole.so" ./bin/laravels start
```

**Comment by hhxsv5** [comment]
This is not a normal way to start. 
Please add the swoole.so to php.ini.

**Comment by filakhtov** [comment]
Swoole works just fine this way:
```
$ php -d extension="swoole.so" test-server.php 
Swoole http server is started at http://127.0.0.1:9501
```
with the hello world example provided by the Swoole team:
```php
<?php
use Swoole\Http\Server;
use Swoole\Http\Request;
use Swoole\Http\Response;

$server = new Swoole\HTTP\Server("127.0.0.1", 9501);

$server->on("start", function (Server $server) {
    echo "Swoole http server is started at http://127.0.0.1:9501\n";
});

$server->on("request", function (Request $request, Response $response) {
    $response->header("Content-Type", "text/plain");
    $response->end("Hello World\n");
});

$server->start();
```
The reason that might help convince you is development against multiple services some of which use extensions that are incompatible with Swoole. This requires to go and edit configuration files back and forth every time, and makes it impossible to run two incompatible services at the same time... Please consider this @hhxsv5. Thank you 🙇‍♂️

**Comment by hhxsv5** [comment]
We are trying to support this feature.

**Comment by hhxsv5** [comment]
Please upgrade laravel-s to v3.7.13.

**Comment by filakhtov** [comment]
Just wanted to confirm that the fix that was implemented solved the problem and allows to run the service by enabling the extension from the command line arguments. Thank you very much 🙇‍♂️
