### ISSUE TITLE
使用非默认80端口号进行集成，路由主机地址返回错误，没有正确带端口号

### ISSUE THREAD

**Issue by methzeal** [hhxsv5/laravel-s#32]
环境centos lnmp
PHP 版本号 7.2.4
SWOOLE版本号2.1.1
Laravel 版本号5.6

网站地址设置如果是非默认80，经过nginx + laravels处理后路由地址不带端口号，导致路由错误
var_dump(env('APP_URL'))----->http://xxxx:8081
var_dump(URL::current())------>http://xxxx

环境配置
.env
APP_URL=http://xxxx:8081

config/app.php
'url' => env('APP_URL', 'http://xxxx:8081'),

错误展示
var_dump(env('APP_URL'))----->http://xxxx:8081
var_dump(URL::current())------>http://xxxx

以上问题放弃nginx + laravels 仅使用apache提供服务则完全正常

**Comment by hhxsv5** [comment]
文档已修复，Nginx配置Host为`$http_host`即可。
```Nginx
proxy_set_header Host $http_host;
```
