### ISSUE TITLE
请问服务启动后，可以使用laravel的orm或者Redis::xxx吗，会出现单例问题吗

### ISSUE THREAD

**Issue by Tobecoder** [hhxsv5/laravel-s#321]
`// 先将上一个阶段的数据落地到mysql
            ProduceMaterialProcedure::create([
                'produce_material_id' => $procedure['produce_material_id'],
                'employee_user_id' => $procedure['employee_user_id'],
                'produce_num' => $procedure['produce_num'],
                'material_part_remainder_seconds' => $procedure['material_part_remainder_seconds'],
                'task_remainder_seconds' => 0,
                'every_material_seconds' => $procedure['every_material_seconds'],
                'start_at' => $procedure['start_at'],
                'end_at' => $procedure['end_at'],
                'speed_end_at' => $procedure['employee_user_id'] ? $procedure['speed_end_at'] : 0,
            ]);

            // 更新任务已生产数
            Redis::hIncrBy(RedisKey::getMaterialProduceWithUser($userId, $position), 'produce_num', $procedure['produce_num']);`

类似这种代码，会不会出现并发问题，麻烦大佬告知一下

**Comment by hhxsv5** [comment]
如果你理解了下面这两个例子，那就不会有并发问题。
数据库和Redis均是单例连接，如果请求中对全局的连接做了修改，那请求结束或需要**重置**回去，可以写[Cleaner](https://github.com/hhxsv5/laravel-s/blob/master/README-CN.md#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9)来清理。

- 数据库：
手动开启的事务，没有进行提交或回滚，会影响后续请求，
```php
try {
    DB::beginTransaction();
    // ...
    DB::commit():
} catch (\Throwable $e) {
    DB::rollBack():
}
```
建议使用闭包的写法：
```php
DB::transaction(function(){
      // ... 
});
```

- Redis：框架Redis abc连接配置了db 0，但业务代码中修改为db1：Redis::connection('abc')->select(1)，这种写法是**错误**的，会导致后续在获取abc连接时db错误，应避免业务代码中去切换db。
