### ISSUE TITLE
关于队列中直接调用model模型，导致多条数据更新的问题

### ISSUE THREAD

**Issue by wotemenige** [hhxsv5/laravel-s#324]
一个小例子，放到队列中执行的：

$a = Model::where('id',$u_id)->first();
.
.
中间还有一些别的操作；
.
.
$a->update(['num'=>1]);
这样更新会把不是$u_id的数据也更新；

如果这么写：
$a = Model::where('id',$u_id)->first();
.
.
中间还有一些别的操作；
.
.
Model::where('id',$u_id)->update(['num'=>1]);
就没有问题；
不知道这是怎么回事呢？

**Comment by hhxsv5** [comment]
没有复现，理论上不应该有这样的问题。请上传可重现问题的工程。
