### ISSUE TITLE
tcp socket bug

### ISSUE THREAD

**Issue by zoucan666** [hhxsv5/laravel-s#326]
1. Your software version (Screenshot of your startup)
    
    | Software | Version |
    | --------- | --------- |
    | PHP | 7.2 |
    | Swoole | 4.5 |
    | Laravel/Lumen | 5.6 |

2. Detail description about this issue(error/log)

    tcp socket 启动后，用Telnet 测试可以连接并进入 onReceive 方法，而tcp客户端能连接却无法进入 onReceive，如果换做 swoole 原生的代码，则完全 ok

3. Some `reproducible` code blocks and `steps`

    ```PHP
    public function onReceive(Server $server, $fd, $reactorId, $data)
    {
        logger('TCP Received data', [$fd, $data]);
        $server->send($fd, "Server: " . $data);
    }
    ```

**Comment by hhxsv5** [comment]
`Telnet`使用`\r\n`作为结束，检查是否配置[open_eof_check](https://wiki.swoole.com/#/server/setting?id=open_eof_check)。

```php
[
    'open_eof_check' => true, 
    'package_eof'    => "\r\n",
];
```
