### ISSUE TITLE
路由中间件不起作用

### ISSUE THREAD

**Issue by leopoldwong** [hhxsv5/laravel-s#328]
protected function bindWebSocketEvents()
    {
        parent::bindWebSocketEvents();

        if ($this->enableWebSocket) {
            $this->swoole->on('Open', function (WebSocketServer $server, SwooleRequest $request) {
                // Start Laravel's lifetime, then support session ...middleware.
                $laravelRequest = $this->convertRequest($this->laravel, $request);
                $this->laravel->bindRequest($laravelRequest);
                $this->laravel->cleanProviders();
                $this->laravel->handleDynamic($laravelRequest);
                $this->triggerWebSocketEvent('onOpen', func_get_args());
                $this->laravel->saveSession();
                $this->laravel->clean();
            });
        }
    }

protected function bindWebSocketEvents()
    {
        if ($this->enableWebSocket) {
            $this->swoole->on('HandShake', function () {
                $this->triggerWebSocketEvent('onHandShake', func_get_args());
            });

            $this->swoole->on('Open', function () {
                $this->triggerWebSocketEvent('onOpen', func_get_args());
            });

            $this->swoole->on('Message', function () {
                $this->triggerWebSocketEvent('onMessage', func_get_args());
            });

            $this->swoole->on('Close', function (WebSocketServer $server, $fd, $reactorId) {
                $clientInfo = $server->getClientInfo($fd);
                if (isset($clientInfo['websocket_status']) && $clientInfo['websocket_status'] === \WEBSOCKET_STATUS_FRAME) {
                    $this->triggerWebSocketEvent('onClose', func_get_args());
                }
                // else ignore the close event for http server
            });
        }
    }

https://wiki.swoole.com/#/websocket_server
onHandShake 事件回调是可选的
设置 onHandShake 回调函数后不会再触发 onOpen 事件，需要应用代码自行处理
onHandShake 中必须调用 response->status() 设置状态码为 101 并调用 response->end() 响应，否则会握手失败.
内置的握手协议为 Sec-WebSocket-Version: 13，低版本浏览器需要自行实现握手
可以使用 server->defer 调用 onOpen 逻辑

现在的代码无法调用路由中间件信息

**Comment by hhxsv5** [comment]
1.请修正issue代码格式；
2.请按issue模板提交问题。
