### ISSUE TITLE
ws connection return 404

### ISSUE THREAD

**Issue by glkhg** [hhxsv5/laravel-s#33]
1. Tell us your PHP version(`php -v`)
7.1.14
`TODO`

2. Tell us your Swoole version(`php --ri swoole`)
3.0.0-alpha
`TODO`

3. Tell us your `Laravel`/`Lumen` version(check composer.json & composer.lock)
5.5.40
`TODO`

4. Detail description about this issue(error/log)
![image](https://user-images.githubusercontent.com/9195834/39704092-dfeed2fe-523c-11e8-8ea0-98b56db3b655.png)

`TODO`

5. Give us a `reproducible` code block and `steps`
My nginx config file is the same as you suggested(I used ssl cr), my js code is like this
var ws = new WebSocket("wss://wqw.hfvi.cn/ws");
        ws.onopen = function() {
            console.log("send message");
        };

        ws.onmessage = function (evt) {

        };

        ws.onclose = function() {

        };
```PHP
//TODO: Your code
```

**Comment by hhxsv5** [comment]
Do you follow this steps  [Enable Websocket](https://github.com/hhxsv5/laravel-s/blob/master/README.md#enable-websocket-server) ?

**Comment by glkhg** [comment]
我代码是粘贴到  app/Service/WebsocketService.php  这个文件里的，laravels.php也是按照文档配置的

**Comment by hhxsv5** [comment]
Nginx配置贴出来看看

**Comment by glkhg** [comment]
map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}
upstream laravels {
    server 127.0.0.1:5200 weight=5 max_fails=3 fail_timeout=30s;
    #server 192.168.0.2:5200 weight=3 max_fails=3 fail_timeout=30s;
    #server 192.168.0.3:5200 backup;
}
server {
	listen       443;
	server_name  wqw.hfvi.cn;
	ssl on;
	ssl_certificate /usr/local/etc/nginx/servers/sslkey/wqw.hfvi.cn_ssl.crt;
	ssl_certificate_key /usr/local/etc/nginx/servers/sslkey/wqw.hfvi.cn_ssl.key;
	ssl_session_timeout 5m;
	ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
	ssl_ciphers AESGCM:ALL:!DH:!EXPORT:!RC4:+HIGH:!MEDIUM:!LOW:!aNULL:!eNULL;
	ssl_prefer_server_ciphers on;
    root /Users/michael/htdocs/laravel/public;
    access_log /Users/michael/htdocs/log/nginx/$server_name.access.log  main;
    index index.html index.htm;
    # Nginx handles the static resources(recommend enabling gzip), LaravelS handles the dynamic resource.
    location / {
        try_files $uri @laravels;
    }
    # Response 404 directly when request the PHP file, to avoid exposing public/*.php
    #location ~* \.php$ {
    #    return 404;
    #}
    # Http and Websocket are concomitant, Nginx identifies them by "location"
    # Javascript: var ws = new WebSocket("ws://laravels.com/ws");
    location =/ws {
        proxy_http_version 1.1;
        # proxy_connect_timeout 60s;
        # proxy_send_timeout 60s;
        # proxy_read_timeout: Nginx will close the connection if client does not send data to server in 60 seconds; At the same time, this close behavior is also affected by heartbeat setting of Swoole
        # proxy_read_timeout 60s;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Real-PORT $remote_port;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_set_header Scheme $scheme;
        proxy_set_header Server-Protocol $server_protocol;
        proxy_set_header Server-Name $server_name;
        proxy_set_header Server-Addr $server_addr;
        proxy_set_header Server-Port $server_port;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_pass http://laravels;
    }
    location @laravels {
        proxy_http_version 1.1;
        # proxy_connect_timeout 60s;
        # proxy_send_timeout 60s;
        # proxy_read_timeout 60s;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Real-PORT $remote_port;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_set_header Scheme $scheme;
        proxy_set_header Server-Protocol $server_protocol;
        proxy_set_header Server-Name $server_name;
        proxy_set_header Server-Addr $server_addr;
        proxy_set_header Server-Port $server_port;
        proxy_pass http://laravels;
    }
}

**Comment by hhxsv5** [comment]
Nginx配置没问题，注释掉ssl，用ws试试看看。

**Comment by hhxsv5** [comment]
Nginx重启了吗？
```Bash
nginx -s reload
```

**Comment by glkhg** [comment]
清理缓存后就好了，谢谢，这个破谷歌浏览器，一点都不让我省心。

**Comment by hhxsv5** [comment]
😓

**Comment by glkhg** [comment]
上次也是瞎跳转，排查了这么久，谢谢你

**Comment by hhxsv5** [comment]
没事，踩坑积攒经验。
