### ISSUE TITLE
onOpen 没法获取用户当前登录信息

### ISSUE THREAD

**Issue by YangHaHabiu** [hhxsv5/laravel-s#332]
swoole:4.4.18
php:7.2.6
laravel5.8
laravels:3.7.0

登录还是走php-fpm
登录使用session验证 session driver 是file
没法在onOpen 获取用户信息(Auth::guard()->user()) 打印是null

请问是什么问题

**Comment by hhxsv5** [comment]
请升级到最新版v3.7.12
