### ISSUE TITLE
Support Serverless

### ISSUE THREAD

**Issue by falstack** [hhxsv5/laravel-s#334]
### 想把 lumen + swoole 部署到阿里云函数计算，但是`laravel-s`有点问题：

1. [LaravelSCommand.php#L205](https://github.com/hhxsv5/laravels/blob/master/src/Illuminate/LaravelSCommand.php#L205) 建议使用`storage_path`，因为 `base_path`在`serverless`环境里是只读不可写的，所以无法写入`laravels.conf`到`base_path`
2. [Portal.php#L341](https://github.com/hhxsv5/laravel-s/blob/master/src/Console/Portal.php#L341)里不要使用`basePath`，`serverless`环境下也是不可读的，希望也能改成可配置

改好上面两个就能跑通了

![image](https://user-images.githubusercontent.com/16357724/105468107-8ab57480-5cd1-11eb-83bd-7c9f6e20d946.png)

**Comment by hhxsv5** [comment]
Portal::$basePath是根据入口文件`bin/laravels`文件执行`realpath(__DIR__ . '/../')`计算相对路径得到的，手动配置就不灵活了。

**Comment by falstack** [comment]
在使用函数计算的时候，代码目录是可读，但不可写的，所以`laravel.conf`无法写到`project/storage`目录下，需要在启动的时候设置临时目录为`storage`目录，参考：[laravel 迁移函数计算](https://help.aliyun.com/document_detail/166253.html?spm=a2c4g.11174283.6.807.20685212xe82KT)文档的`2-3`步骤

所以使用`base_path`就不行了，需要使用`storage_path`

目前我配置 Protal 的 getConfigPath 函数是这么写的：
``` php
protected function getConfPath()
{
    $options = $this->input->getOptions();
    if ($options['env'] === 'local')
    {
        return $this->basePath . '/storage/laravels.conf';
    }

    return '/tmp/storage/laravels.conf';
}
```

启动项目时加了`--env`来做环境区分，但这里怎么去写这段代码更好，我还没有明确的答案。

**Comment by hhxsv5** [comment]
目前看，使用环境变量区分是最佳实践，具体情况[文档](https://github.com/hhxsv5/laravel-s/blob/master/README-CN.md#%E9%98%BF%E9%87%8C%E4%BA%91%E5%87%BD%E6%95%B0%E8%AE%A1%E7%AE%97).
```php
protected function getConfigPath()
{
    $storagePath = getenv('APP_STORAGE_PATH');
    if ($storagePath === false) {
        $storagePath = $this->basePath . '/storage';
    }
    return $storagePath . '/laravels.conf';
}
```

**Comment by hhxsv5** [comment]
[v3.7.14](https://github.com/hhxsv5/laravel-s/releases/tag/v3.7.14).
