### ISSUE TITLE
laravel8集成laravels api接口参数获取不到？

### ISSUE THREAD

**Issue by hcweb** [hhxsv5/laravel-s#335]
Speed up your Laravel/Lumen
>>> Components
+---------------------------+---------+
| Component                 | Version |
+---------------------------+---------+
| PHP                       | 7.4.14  |
| Swoole                    | 4.5.9   |
| LaravelS                  | 3.7.13  |
| Laravel Framework [local] | 8.24.0  |
+---------------------------+---------+
>>> Protocols
+-----------+--------+-------------------+-----------------------+
| Protocol  | Status | Handler           | Listen At             |
+-----------+--------+-------------------+-----------------------+
| Main HTTP | On     | Laravel Framework | http://127.0.0.1:5200 |
+-----------+--------+-------------------+-----------------------+`

访问不带参数的接口正常 访问带参数的接口后参数获取不到  请大佬赐教  感谢！

**Comment by hhxsv5** [comment]
请给出示例代码。

**Comment by hcweb** [comment]
> 请给出示例代码。

`public function like(Request $request){
        $member_id=$request->post('member_id');
        $post_id=$request->post('post_id');
        $type=$request->post('type');
        //点赞
        $data=null;
        if ($type === 'confirm') {
            $data=Like::create([
                'member_id'=>$member_id,
                'post_item_id'=>$post_id
            ]);
        }
        //取消点赞
        if ($type === 'cancle') {
            $data=Like::where('member_id',$member_id)->where('post_item_id',$post_id)->delete();
        }
        return response()->json([
            'data'=>$data,
            'message' => $data?'ok':'error',
        ]);
    }`

**Comment by hcweb** [comment]
> > 请给出示例代码。
> 
> `public function like(Request $request){ $member_id=$request->post('member_id'); $post_id=$request->post('post_id'); $type=$request->post('type'); //点赞 $data=null; if ($type === 'confirm') { $data=Like::create([ 'member_id'=>$member_id, 'post_item_id'=>$post_id ]); } //取消点赞 if ($type === 'cancle') { $data=Like::where('member_id',$member_id)->where('post_item_id',$post_id)->delete(); } return response()->json([ 'data'=>$data, 'message' => $data?'ok':'error', ]); }`

如果不用集成的话是正常的 集成以后参数就获取不到 用的https

**Comment by hhxsv5** [comment]
注意markdown格式化，没法看了
