### ISSUE TITLE
如何查询当前正在进行中的异步任务

### ISSUE THREAD

**Issue by kuaifan** [hhxsv5/laravel-s#336]
+---------------------------+---------+
| Component                 | Version |
+---------------------------+---------+
| PHP                       | 7.4.14  |
| Swoole                    | 4.6.2   |
| LaravelS                  | 3.7.15  |
| Laravel Framework [local] | 8.25.0  |
+---------------------------+---------+

我想查看当前正在进行中的任务，看看是否有任务堵在那里进行中

**Comment by hhxsv5** [comment]
使用[stats()](https://wiki.swoole.com/#/server/methods?id=stats)函数，关注`task*`字段。
