### ISSUE TITLE
好像不支持laravel8.0?

### ISSUE THREAD

**Issue by Funny-dot** [hhxsv5/laravel-s#338]
1. Your software version (Screenshot of your startup)
    
    | Software | Version |
    | --------- | --------- |
    | PHP | 7.2|
    | Swoole | 4.3|
    | Laravel/Lumen | 8.0|

2. Detail description about this issue(error/log)

   error

3. Some `reproducible` code blocks and `steps`

 [root@d06414ac90e9 laravel-s]# php bin/laravels start
PHP Fatal error:  Uncaught Error: Class 'Hhxsv5\LaravelS\Console\Portal' not fou
nd in /www/wwwroot/192.168.99.100/skeleton/farms/vendor/hhxsv5/laravel-s/bin/lar
avels:161
Stack trace:
#0 {main}
  thrown in /www/wwwroot/192.168.99.100/skeleton/farms/vendor/hhxsv5/laravel-s/b
in/laravels on line 161

Fatal error: Uncaught Error: Class 'Hhxsv5\LaravelS\Console\Portal' not found in
 /www/wwwroot/192.168.99.100/skeleton/farms/vendor/hhxsv5/laravel-s/bin/laravels
:161
Stack trace:
#0 {main}
  thrown in /www/wwwroot/192.168.99.100/skeleton/farms/vendor/hhxsv5/laravel-s/b
in/laravels on line 161

**Comment by hhxsv5** [comment]
`vendor/hhxsv5/laravel-s/ `不见了?

**Comment by Funny-dot** [comment]
![image](https://user-images.githubusercontent.com/27287970/106987090-acb9f700-67a7-11eb-9ff7-66e822b70b23.png)
@hhxsv5   有的

**Comment by Funny-dot** [comment]
![image](https://user-images.githubusercontent.com/27287970/106987130-be9b9a00-67a7-11eb-8a9b-8fc862ca724e.png)

**Comment by hhxsv5** [comment]
你是用的`Windows`? 试试`composer dumpautoload`

**Comment by Funny-dot** [comment]
不是哦，docker

**Comment by Funny-dot** [comment]
![image](https://user-images.githubusercontent.com/27287970/106987735-138be000-67a9-11eb-88a6-ff3d53b0903b.png)

**Comment by hhxsv5** [comment]
你autoload.php都没生成成功，自己排查下吧。

**Comment by hhxsv5** [comment]
是在项目根目录启动`php bin/laravels start`，不是在`vendor`目录。

**Comment by Funny-dot** [comment]
已解决
