### ISSUE TITLE
使用easywechat支付，每次回调回来的订单地址不正确

### ISSUE THREAD

**Issue by wotemenige** [hhxsv5/laravel-s#339]
1.比如 我的订单id是123，现在支付成功后，微信在回调地址返给我的是123；好的没问题；

2.我第二次支付，生成的订单id是456，支付成功后，微信在回调地址返给我的还是123；

3.然后我重新启动项目，发现微信就能把正常的订单号给我推送过来了；

这到底是啥情况。。。

**Comment by hhxsv5** [comment]
参考[常见问题](https://github.com/hhxsv5/laravel-s/blob/master/KnownIssues-CN.md#%E4%BD%BF%E7%94%A8%E5%8C%85-overtruewechat)。
