### ISSUE TITLE
Class 'Hhxsv5\LaravelS\Console\Portal' not found

### ISSUE THREAD

**Issue by khalid-o** [hhxsv5/laravel-s#340]
Hi there,
Every time I run this command: ``` php vendor/hhxsv5/laravel-s/bin/laravels start```
It return this error

```
PHP Fatal error:  Uncaught Error: Class 'Hhxsv5\LaravelS\Console\Portal' not found in /var/www/html/vendor/hhxsv5/laravel-s/bin/laravels:161
Stack trace:
#0 {main}
  thrown in /var/www/html/vendor/hhxsv5/laravel-s/bin/laravels on line 161
```

I use: 
- "hhxsv5/laravel-s": "~3.7.0"
- "laravel/lumen-framework": "^8.0"

Thank you

**Comment by hhxsv5** [comment]
1.Publish laravel-s files: `php artisan laravels publish`
2.Start laravel-s: `php bin/laravels start`

**Comment by khalid-o** [comment]
It's work!
Thank you so much.

**Comment by hhxsv5** [comment]
My pleasure.

**Comment by khalid-o** [comment]
I'm sorry, But I have an other issue.
I have an API built with Lumen, implement a basic authentication, It's work.
But, when authenticate with correct api key, then edit it to wrong keys, it still authenticated!

**Comment by hhxsv5** [comment]
Set the [cleaners](https://github.com/hhxsv5/laravel-s/blob/master/Settings.md#cleaners).
