### ISSUE TITLE
Invalid conversion between multiple Laravel headers and Swoole headers

### ISSUE THREAD

**Issue by filakhtov** [hhxsv5/laravel-s#341]
1. Your software version (Screenshot of your startup)
    
    | Software | Version |
    | --------- | --------- |
    | PHP | 7.4.14 |
    | Swoole | 4.5.9 |
    | Laravel/Lumen | 8.26.1 |

2. Detail description about this issue(error/log)

Laravel supports multiple response headers with the same name (as per HTTP standard). It is achieved by calling `HeaderBag::set()` with an array as a second argument, something like:

```php
$request->headers->set('trailer', ['a', 'b']);
```

This is accounted for in LaravelS, i.e. it [iterates over all header values](https://github.com/hhxsv5/laravel-s/blob/34ffd7b1abe86eb5aa48103cb38cd4195921cd2e/src/Swoole/Response.php#L52-L54) and calls `Swoole\Http\Response::header()` method. However, this usage is incorrect, according to the [Swoole documentation](https://wiki.swoole.com/#/http_server?id=setheader), namely:

> - 重复设置相同 $key 的 HTTP 头会覆盖，取最后一次

which Google Translate helped me with:

> - repeating the same set of `$key` HTTP head Will overwrite, take the last

i.e., in normal words, only the last value will be preserved.

3. Some `reproducible` code blocks and `steps`

```php
$response = new Response();
$response->headers->set('X-My-Header', ['a', 'b', 'c']);
return $response;
```

When this snippet put into any controller the result will be:
```
> GET / HTTP/1.1
> Host: localhost
> User-Agent: curl/7.64.1
> Accept: */*

< HTTP/1.1 200 OK
< Server: LaravelS
< Date: Thu, 18 Feb 2021 05:36:17 GMT
< Content-Type: text/html
< Content-Length: 0
< X-My-Header: c
```
but the expected outcome should have multiple `X-My-Header` headers.

Perhaps, we should look at header folding? Or is that something for Swoole to enable support for?

**Comment by hhxsv5** [comment]
Swoole (<4.6.0) does not support setting the header key with the same name, 
LaravelS supports it now, but you need to upgrade Swoole to 4.6.x.
A new version of LaravelS will be released in the next few days.

**Comment by hhxsv5** [comment]
[v3.7.17](https://github.com/hhxsv5/laravel-s/releases/tag/v3.7.17)

**Comment by filakhtov** [comment]
Thank you very much! We have finally got around to properly testing it, as we were blocked by swoole/swoole-src#4133 when we first tried everything together, but once Swoole actually addressed their issue everything is working properly now!
