### ISSUE TITLE
建议：Laravel下handleDynamic中，将ob_end_clean 方法替换成 ob_end_flush。因为没有var_dump之类的输出，真心不好调试呀

### ISSUE THREAD

**Issue by aiqiu506** [hhxsv5/laravel-s#342]
1. Your software version (Screenshot of your startup)
    
    | Software | Version |
    | --------- | --------- |
    | PHP | TODO |
    | Swoole | TODO |
    | Laravel/Lumen | TODO |

2. Detail description about this issue(error/log)

    `TODO`

3. Some `reproducible` code blocks and `steps`

    ```PHP
    // TODO: your code
    ```

**Comment by hhxsv5** [comment]
`ob_end_flush`是flush到输出缓冲区内容并关闭缓冲，在Swoole下，原本想要HTTP响应输出的结果输出到控制台了，不符合框架本意。
你要调试，有两个方案：
- [Laravel Dump Server](https://github.com/beyondcode/laravel-dump-server)
- 日志，其中`Log::channel('stderr')->debug('debug message');` 记录日志到标准错误，控制台会展示。
