### ISSUE TITLE
is there some way to create websocket client with laravel-s? 

### ISSUE THREAD

**Issue by hundan2020** [hhxsv5/laravel-s#344]
I need to create a websocket client with php, but I didn't found the description with that, if there is some class or functions to use for creating websocket client in laravel-s?

**Comment by hhxsv5** [comment]
- [Sync Client](https://github.com/swoole/swoole-src/blob/master/tests/include/api/swoole_websocket_server/websocket_client.php) 
- [Coroutine Client](https://www.swoole.co.uk/docs/modules/swoole-corooutine-http-client-upgrade)
