### ISSUE TITLE
Task 无法执行，报错Swoole\Server::task(): task method can't be executed without task worker

### ISSUE THREAD

**Issue by hadeswang2016** [hhxsv5/laravel-s#347]
1. Your software version (Screenshot of your startup)
    
    | Software | Version |
    | --------- | --------- |
    | PHP | 7.3|
    | Swoole |  4.4.20|
    | Laravel/Lumen | Lumen  5.5|

2. Detail description about this issue(error/log)

![image](https://user-images.githubusercontent.com/18191772/112571273-b1ec0780-8e22-11eb-9cc0-62addb5c4ab2.png)

开启task_worker_num，还是报错
![image](https://user-images.githubusercontent.com/18191772/112571308-c3351400-8e22-11eb-815b-324ede0c877d.png)

3. Some `reproducible` code blocks and `steps`

    ```PHP
    // TODO: your code
    ```

**Comment by hhxsv5** [comment]
重新生成或清理配置缓存
```
php artisan cache:config
// OR
php artisan cache:clear 
```
