### ISSUE TITLE
Laravel 8集成Laravels后CPU100%，内存飙升

### ISSUE THREAD

**Issue by Stone-ChenLijun** [hhxsv5/laravel-s#349]
我的环境：
|  程序   | 版本  |
|  ----  | ----  |
| PHP  | 7.3.27-9+ubuntu16.04.1+deb.sury.org+1 |
| Swoole  | 4.6.4 |
| LaravelS  | 3.7.19 |
| Laravel Framework [local]  | 8.25.0 |
| Nginx | 1.17.3 |
| OS | Manjaro 21.0 Ornara |

我参照[这里](https://laravelacademy.org/post/19700)的教程配置了我的http和websocket服务。

启动http后，相较原来未引入swoole时，请求时间减少了9成，有很大的提升，但是会在某个莫名的时间点，突然某个CPU
会直接满载，然后内存不断上涨，直至100%，导致死机。

![image](https://user-images.githubusercontent.com/22467090/114114955-7d914480-9914-11eb-9541-6471bfd2259c.png)

我尝试了文档中说明内存泄漏部分的代码，在请求后销毁所有控制器。
```php
'destroy_controllers' => [
      'enable'        => true,
      'excluded_list' => [],
  ],
```
并且使用了debug-memory-leak路由查询，在某次出现CPU100%和内存飙升时，多次diff_mem查询的结果均为0。

因为暂时查不出问题所在，我又加上了websocket(这才是我引入laravel-s的原因)，但是前端websocket一开始链接，就100%出现CPU100%，内存直线上升，在死机前，我停掉了laravels。在webscoket连接中触发问题时，请求debug-memory-leak接口，接口一直在请求中，没有任何反应。

全程laravels和laravel的日志一个字都没有打印，我都查不到任何东西。
在webscoekt服务的构造器中打印了一行日志，也啥都查不到。
```
class WebSocketService implements WebSocketHandlerInterface
{

    public function __construct()
    {
        Log::channel('stderr')->debug('debug message');
    }
```
![image](https://user-images.githubusercontent.com/22467090/114116915-23927e00-9918-11eb-98e6-30a9161f709d.png)

内存上两个箭头指向的分别是前端websocket接入和手动停止laravels的时间点。

**Comment by hhxsv5** [comment]
1. laravel和swoole日志有没有异常？
2. swoole 4.6.4版本非常新，我生产环境使用4.5.11，降级试试
3. 可否上传一个能重现问题的工程(脱敏)到这里。

**Comment by Stone-ChenLijun** [comment]
我发现原因了，原来XDebug和swoole是冲突的。我看的这些文档都没有讲，也没有看到。
今天我停止了laravels，本地运行php artisan migrate时，也触发了CPU 100%和内存飙升，报错访问了不可到达的内存区，
google查了下才发现是这个问题。
我本地使用的是laradock的环境，默认构建的镜像中启用了xdebug，试着关闭了xdebug，结果一切正常了。
客户端连接webscoket的动作，引爆了这种冲突。

打扰了，抱歉。。

**Comment by hhxsv5** [comment]
解决就好，这里有[冲突扩展列表](https://wiki.swoole.com/#/getting_started/extension)。

**Comment by Stone-ChenLijun** [comment]
谢谢
