### ISSUE TITLE
Apache 配置文档多了一个/

### ISSUE THREAD

**Issue by Stone-ChenLijun** [hhxsv5/laravel-s#352]
1. Your software version (Screenshot of your startup)
    
    | Software | Version |
    | --------- | --------- |
    | PHP | 7.4.7 |
    | Swoole | 4.6.4 |
    | Laravel/Lumen | 3.7.19 |
    | Server system | Centos 7.8 |
    | Server | Apache 2.4 |

2. Detail description about this issue(error/log)

    使用apache服务器，laravel提示404，文档中介绍apache配置的这一行，`RewriteRule ^/(.*)$ balancer://laravels/%{REQUEST_URI} [P,L]` 中的 `%{REQUEST_URI}` 实际匹配到的字符是包含`/`的，导致有两个`/`，所以报了404。去掉laravels后面的那个`/`就正常了。

    比方说我请求 `http://a.test/api/admin/user/login`，从 laravel 抛出的404异常中获取当前url，其实是`http://a.test//api/admin/user/login`。

**Comment by hhxsv5** [comment]
谢谢支持，已更正。
