### ISSUE TITLE
bug:自动销毁控制器机制有偶发失效的情况

### ISSUE THREAD

**Issue by egege** [hhxsv5/laravel-s#353]
1. Your software version (Screenshot of your startup)
    
+--------------------------+---------+
| Component                | Version |
+--------------------------+---------+
| PHP                      | 7.2.27  |
| Swoole                   | 4.5.1   |
| LaravelS                 | 3.7.3   |
| Laravel Framework [test] | 6.17.1  |
+--------------------------+---------+

2. Detail description about this issue(error/log)

    虽然使用了LaravelS提供的自动销毁控制器机制，但是偶发情况下，控制器还是只会被构造一次。测试反应出现频率大概为一天两次，暂时没有找到稳定复现的情形。不知道作者的公司线上是否有这种问题？还是已经在最新版修复。

3. Some `reproducible` code blocks and `steps`

    ```PHP
    // TODO: your code
    ```

**Comment by hhxsv5** [comment]
我这边没用控制器的构造方法，先尝试重现。

**Comment by egege** [comment]
我把代码从控制器改到具体的方法里了，没有再出现类似的问题。
