### ISSUE TITLE
laravel app('swoole')无法使用  Constant PAYLOAD already defined

### ISSUE THREAD

**Issue by changrisheng** [hhxsv5/laravel-s#358]
1. Your software version (Screenshot of your startup)
    
    | Software | Version |
    | --------- | --------- |
    | PHP | 7.3.27|
    | Swoole | 4.6.3|
    | Laravel/Lumen | 8.41.0|

2. 错误的详细情况
3. 刚开始的错误是需要我主动给用户端发送消息时 app('swoole') 无法new
4. 查看了相关信息后发现是走了index.php 入口 导致无法获取，以下是错误信息
[previous exception] [object] (ReflectionException(code: -1): Class swoole does not exist at /var/www/laravel8/vendor/laravel/framework/src/Illuminate/Container/Container.php:833)
[stacktrace]

5. 我修改了ngin配置文件
![image](https://user-images.githubusercontent.com/42760653/118959323-cbc64880-b994-11eb-8c46-d714b3713ac2.png)
6. 我进行了进一步测试 app('swoole') 可以调用
7. 但是项目中还包含了其他的的接口
8. 如果是第一次访问接口是正常的，
9. 但是二次请求之后（以下是错误信息）
![image](https://user-images.githubusercontent.com/42760653/118959613-134cd480-b995-11eb-8091-811104525659.png)

如果链接成功后从WebSocketService  中发出的信息正常
![image](https://user-images.githubusercontent.com/42760653/118960419-db925c80-b995-11eb-97ad-0d7cf5bd31fb.png)

3. 以下是我修改的代码

使用的拓展：
dingo/api": "^3.0",
tymon/jwt-auth": "dev-develop
按照文档我项目中使用了
![image](https://user-images.githubusercontent.com/42760653/118960270-b1d93580-b995-11eb-984c-b6fd139ff0c5.png)

因为是第一次使用swoole进行搭建聊天室，
个人想法是最后的清理器没有起到作用，导致我接口没有办法正常调用
感谢大佬的帮助  Thanks♪(･ω･)ﾉ

**Comment by changrisheng** [comment]
现在主要的问题是，我如果app('swoole') 可以正常使用，那么项目中我接口就只能请求一次

**Comment by corlonmimo** [comment]
解决了？
