### ISSUE TITLE
Task报错 Fatal error: Swoole\Server::start(): failed to start server. Error: start_check: onTask event callback must be set in vendor/hhxsv5/laravel-s/src/Swoole/Server.php on line 402

### ISSUE THREAD

**Issue by oydm** [hhxsv5/laravel-s#359]
Task报错
Warning: Swoole\Server\Port::on(): unknown event types[Tasks] in  vendor/hhxsv5/laravel-s/src/Swoole/Server.php on line 95
PHP Fatal error:  Swoole\Server::start(): failed to start server. Error: start_check: onTask event callback must be set in vendor/hhxsv5/laravel-s/src/Swoole/Server.php on line 402

Fatal error: Swoole\Server::start(): failed to start server. Error: start_check: onTask event callback must be set in vendor/hhxsv5/laravel-s/src/Swoole/Server.php on line 402

**Comment by oydm** [comment]
将文件名为 vendor/hhxsv5/laravel-s/src/Swoole/Server.php中的代码行  Tasks改为Task 就可以了  回调事件名写错了

**Comment by hhxsv5** [comment]
为啥在Port上设置Task回调？
