### ISSUE TITLE
Error: Call to undefined function Symfony\Component\Console\Input\str_starts_with() 

### ISSUE THREAD

**Issue by tinyu0** [hhxsv5/laravel-s#364]
1. Your software version (Screenshot of your startup)
    
| Component                   | Version                                   |
+-----------------------------+-------------------------------------------+
| PHP                         | 7.2.33                                    |
| Swoole                      | 4.5.0                                     |
| LaravelS                    | 3.7.19                                    |
| Laravel Framework [testing] | Lumen (5.8.12) (Laravel Components 5.8.*) |
+-----------------------------+-------------------------------------------+

2. Detail description about this issue(error/log)

Error: Call to undefined function Symfony\Component\Console\Input\str_starts_with() in /var/www/html/vendor/symfony/console/Input/InputOption.php on line 59

3. Some `reproducible` code blocks and `steps`

php /bin/laravels start 

4.问题原因
"symfony/console":4.4.27 改用php8的 str_starts_with()代替0 === strpos()写法，并在"symfony/polyfill-php80"兼容php8以下版本，通过composer autoload 会自动引入，然而定义的启动laravels 命令没有引用composer的autoload文件，导致 "symfony/polyfill-php80"的兼容文件没有加载而引起的错误

**Comment by hhxsv5** [comment]
感谢反馈，我验证下

**Comment by ActorMan** [comment]
请问这个改怎么处理呢

**Comment by tinyu0** [comment]
> 请问这个改怎么处理呢

在 composer.json 中把版本降下来即可

 "symfony/console": "4.4.26.*",

**Comment by dxkrs** [comment]
> > 请问这个改怎么处理呢
> 
> 在 composer.json 中把版本降下来即可
> 
> "symfony/console": "4.4.26",

但是项目中其他很多包，都已经依赖这个symfony/console的^5.0了，怎么办？

**Comment by WangNingkai** [comment]
同问 目前如何处理啊

**Comment by tinyu0** [comment]
入侵式修复，在bin/laravels中引入composer的autoload

`include dirname(__DIR__) . '/vendor/autoload.php';`

**Comment by szc1233444** [comment]
大佬们有别的办法吗

**Comment by hhxsv5** [comment]
Try v3.7.20.
