### ISSUE TITLE
请问下，按照文档配好nginx后，路由规则怎么写啊，按照laravel的写法，都是404

### ISSUE THREAD

**Issue by ActorMan** [hhxsv5/laravel-s#365]
请问下，按照文档配好nginx后，路由规则怎么写啊，按照laravel的写法，都是404

**Comment by ActorMan** [comment]
我在项目里使用 app('swoole')是报错的，如果想使用是不是只能通过curl进行通信啊

**Comment by hhxsv5** [comment]
[Nginx配置](https://github.com/hhxsv5/laravel-s/blob/master/README-CN.md#%E4%B8%8Enginx%E9%85%8D%E5%90%88%E4%BD%BF%E7%94%A8%E6%8E%A8%E8%8D%90)
[常见错误](https://github.com/hhxsv5/laravel-s/blob/master/KnownIssues-CN.md#class-swoole-does-not-exist)
