### ISSUE TITLE
运行时报错 "Call to undefined function Symfony\Component\Console\Input\str_starts_with()"

### ISSUE THREAD

**Issue by fogbow-cn** [hhxsv5/laravel-s#367]
运行环境：
PHP                       | 7.3.18  |
| Swoole                    | 4.7.0   |
| LaravelS                  | 3.7.19  |
| Laravel Framework [local] | 8.50.0

![WechatIMG1235](https://user-images.githubusercontent.com/26078515/128793070-c75b7fe8-0d9f-4365-89d7-275dbbb3bb61.jpeg)

**Comment by hhxsv5** [comment]
重复问题 #364

**Comment by fogbow-cn** [comment]
谢谢，刚看到
