### ISSUE TITLE
how to validate token with tymon/jwt-auth in websocket server

### ISSUE THREAD

**Issue by gzanthony** [hhxsv5/laravel-s#369]
hi, my laravel is 8.0 and swoole version is 4.6.7, i have create websocket server , my question is how to auth user token by JWTAuth,
below is my code:

$request = \Illuminate\Http\Request::capture();
$request->headers->set('Authorization', "Bearer " . $data['token'] ?? "");
JWTAuth::setRequest($request)->user();

and it always expection , error is "Target class [request] does not exist."
so i don't get it why not working~

**Comment by hhxsv5** [comment]
Before the onOpen event is triggered, the HTTP request to establish the WebSocket has passed the Laravel route, so Laravel's Request and Auth information are readable, Session is readable and writable, but only in the onOpen event.
```php
$request = request(); // or app('request')
```

**Comment by gzanthony** [comment]
i have change the code:
    public function onOpen(Server $server, Request $request)
    {
        try {
            $req = \Illuminate\Http\Request::capture();
            $req->headers->set('Authorization', "Bearer " . $req->get['token'] ?? "");
            JWTAuth::setRequest($req);
        } catch (\Exception $e) {
            var_dump($e->getMessage());
        }
        $server->push($request->fd, 'Welcome to Laravels');
        $this->wsTable->set("fd:" . $request->fd, ['value' => 0]);
    }

now it's throw error 'Trying to access array offset on value of type null'

**Comment by gzanthony** [comment]
not working yet, i give up the time is limit, use other way for auth user.
try this fix next time.

**Comment by hhxsv5** [comment]
You CANNOT call Illuminate\Http\Request::capture(),  should call request() or app('request') instead.

**Comment by gzanthony** [comment]
i try this
```php
try {
            $req = request();
            $req->headers->set('Authorization', 'Bearer ' . $request->get['token'] ?? "");
            $user = JWTAuth::setRequest($req)->parseToken()->user();
            var_dump($user);
        } catch (\ErrorException $error) {
            var_dump($error->getMessage());
        }
```

but is return null;

i use the same code on php-fpm+nginx environment it work fine.
sames like probably not load the .env file because i have try var_dump(env('JWT_SECRET')); the result is null, can't load environment config??

**Comment by hhxsv5** [comment]
Try to clear config cache: `php artisan config:clear`.

**Comment by gzanthony** [comment]
after clear config , the env('JWT_SECRET') is come out, but $user = JWTAuth::setRequest($req)->parseToken()->user(); still null

**Comment by gzanthony** [comment]
change code:
```php
try {
            $req = request();
            $req->headers->set('Authorization', 'Bearer ' . $request->get['token'] ?? "");
            JWTAuth::setRequest($req)->parseToken();
            $user = JWTAuth::parseToken()->authenticate();
            var_dump($user);
        } catch (\ErrorException $error) {
            var_dump($error->getMessage());
        }
```
it's works fine, :)  problem solve, thank for you help

**Comment by hhxsv5** [comment]
For WebSocket::OnOpen(), you can directly [configure](https://jwt-auth.readthedocs.io/en/develop/lumen-installation/) JWT auth route middleware to verify JWT through routing automatically.

web.php
```php
$router->get('/ws', function () {
         // Respond any content with status code 200
         return 'websocket';
})->middleware(['auth']);
```

onOpen:
```php
$user = Auth::user();
```

[Refer](https://github.com/hhxsv5/laravel-s#enable-websocket-server)
