### ISSUE TITLE
lumen下用tymondesigns/jwt-auth包会报错

### ISSUE THREAD

**Issue by rangujie** [hhxsv5/laravel-s#37]
![image](https://user-images.githubusercontent.com/17881618/39852768-f0d4dfe4-5450-11e8-8cb0-c601c90848cb.png)

**Comment by Guxinpei** [comment]
@rangujie Now do you fix this problem？We have the same problem.

**Comment by rangujie** [comment]
![image](https://user-images.githubusercontent.com/17881618/40213975-e6718d1e-5a8a-11e8-949c-b898627156fb.png)
目前这样解决的

**Comment by hhxsv5** [comment]
@rangujie 你这样auth那块儿没有问题吗？

**Comment by Guxinpei** [comment]
@rangujie 厉害了，您是直接把之前的身份验证机制又实现了一遍么？

**Comment by rangujie** [comment]
@hhxsv5  目前没有问题

**Comment by rangujie** [comment]
@Guxinpei  没有啊   只是用了jwt这个扩展包

**Comment by hmilyfyj** [comment]
@hhxsv5 根据 @Guxinpei  同学的截图，我在 Laravel 也遇到了这个问题，处理方式是注释掉图片中的最后一行（如下），但是不知道是否会带来负作用，所以不会以此作为解决方法。

```
 $this->app->register($providerCls, [], true);
```

**Comment by hmilyfyj** [comment]
dev-master 下，该问题已解决，感谢！

**Comment by hhxsv5** [comment]
@rangujie 拉dev-master验证下lumen呢？

**Comment by rangujie** [comment]
@hhxsv5 可以了
