### ISSUE TITLE
使用swoole-tracker发现内存泄漏

### ISSUE THREAD

**Issue by MidnightDJ** [hhxsv5/laravel-s#379]
<img width="630" alt="1634211819(1)" src="https://user-images.githubusercontent.com/23242278/137311025-df497b8b-e567-4605-be80-3e5fcb883f73.png">

<img width="446" alt="1634211899(1)" src="https://user-images.githubusercontent.com/23242278/137311218-9fd59fd6-6ba3-4522-8e43-8f791621ecb0.png">

请问有人遇到过类似的问题么？我该怎么修改我的代码？

**Comment by hhxsv5** [comment]
Swoole Tracker不准确的，建议使用[smem](https://wenda.swoole.com/detail/107690)统计实际内存占用。
请阅读[关于内存泄露](https://github.com/hhxsv5/laravel-s/blob/master/README-CN.md#%E5%85%B3%E4%BA%8E%E5%86%85%E5%AD%98%E6%B3%84%E9%9C%B2)。
