### ISSUE TITLE
3.4.4版本 Hhxsv5\LaravelS\Console\Portal::execute() 方法返回值为null导致laravel8下stop info等操作时异常抛出

### ISSUE THREAD

**Issue by liuxiangxin** [hhxsv5/laravel-s#380]
1. 软件版本
    
    | Software | Version |
    | --------- | --------- |
    | PHP | 7.4.23 |
    | Swoole | 4.6.7 |
    | Laravels | 3.4.4 |
    | Laravel/Lumen | 8.36.2 |
    | symfony/console| v5.2.6 |
    
2. 问题描述
进行laravels restart stop info help等操作时会引发 symfony/console组件 抛出 PHP Fatal error:  Uncaught TypeError: Return value of "Hhxsv5\LaravelS\Console\Portal::execute()" must be of the type int, "null" returned.错误提示。

3. 目前解决

    ```PHP
    // Hhxsv5\LaravelS\Console\Portal::execute() 方法中增加数值类型返回值
    return (int) $re;
    ```

**Comment by hhxsv5** [comment]
LaravelS 版本有点老了，尝试升级新版v3.7.21
```bash
composer up hhxsv5/laravel-s -vvv
```
