### ISSUE TITLE
worker process pid 一直增大，然后系统会慢慢变慢

### ISSUE THREAD

**Issue by litongleo** [hhxsv5/laravel-s#385]
laravels: worker process 一直增大，我用ps -aux 查看系统运营情况，发现laravels: worker process 占用的这些进程 pid 一直在增大，隔段时间需要重新启动，因为会变慢，这个市哪里问题，不断调用正常增长还是没长连接成功？哪位大神指导下

root      131325  0.0  0.2 1694648 86728 ?       Sl   13:34   0:01 /************* laravels: master process
root      131337  0.0  0.0 443276 14928 ?        S    13:34   0:00 /************* laravels: manager process
root      131355  0.0  0.4 755088 131760 ?       Sl   13:34   0:27 /************* laravels: worker process 0
root      131356  0.1  0.4 775600 152688 ?       Sl   13:34   0:30 /************* laravels: worker process 1
root      131357  0.1  0.4 775892 152700 ?       Sl   13:34   0:32 /************* laravels: worker process 2
root      131358  0.0  0.3 747164 126324 ?       Sl   13:34   0:16 /************* laravels: worker process 3
root      131359  0.0  0.3 738672 114156 ?       Sl   13:34   0:10 /************* laravels: worker process 4
root      131360  0.0  0.4 752356 131208 ?       Sl   13:34   0:11 /************* laravels: worker process 5
=========

**Comment by hhxsv5** [comment]
[关于内存泄露](https://github.com/hhxsv5/laravel-s/blob/master/README-CN.md#%E5%85%B3%E4%BA%8E%E5%86%85%E5%AD%98%E6%B3%84%E9%9C%B2)
