### ISSUE TITLE
TimeZone设置没有用，偶尔会生成UTC时间

### ISSUE THREAD

**Issue by menthe** [hhxsv5/laravel-s#388]
1. Your software version (Screenshot of your startup)
+--------------------------+-----------------------------------------+
| Component                | Version                                 |
+--------------------------+-----------------------------------------+
| PHP                      | 8.0.10                                  |
| Swoole                   | 4.8.3                                   |
| LaravelS                 | 3.7.26                                  |
| Laravel Framework [prod] | Lumen (8.3.2) (Laravel Components ^8.0) |
+--------------------------+-----------------------------------------+

2. Detail description about this issue(error/log)

   Lumen 8情况下，Carbon::now()有时候会生成UTC的时间，和我们PRC相差8个小孩，APP_TIMEZONE已经设置成PRC

3. Some `reproducible` code blocks and `steps`

date_default_timezone_set(env('APP_TIMEZONE', 'Asia/Shanghai'));

**Comment by hhxsv5** [comment]
@menthe 在哪里使用Carbon::now()

**Comment by menthe** [comment]
@hhxsv5 Model的创建，以及其他在controller中更新model时候的时候

**Comment by hhxsv5** [comment]
提供下示例代码吧

**Comment by menthe** [comment]
后来直接在controller入口处，设置了时区，目前没有发现问题了。

**Comment by hhxsv5** [comment]
建议全局搜一下date_default_timezone_set，可能其他地方在修改。
