### ISSUE TITLE
关于报错:Return value of "Hhxsv5\LaravelS\Console\Portal::execute()" must be of the type int

### ISSUE THREAD

**Issue by anstou** [hhxsv5/laravel-s#391]
版本情况:
+---------------------------+---------+
| Component                 | Version |
+---------------------------+---------+
| PHP                       | 8.1.1   |
| Swoole                    | 4.8.4   |
| LaravelS                  | 3.4.4   |
| Laravel Framework [local] | 8.76.2  |
+---------------------------+---------+

错误代码:
PHP Fatal error:  Uncaught TypeError: Return value of "Hhxsv5\LaravelS\Console\Portal::execute()" must be of the type int, "null" returned. in /mnt/d/laravelS/vendor/symfony/console/Command/Command.php:301

补充代码:
Hhxsv5\LaravelS\Console\Portal::execute方法内给switch代码块内的start/stop/restart/reload/info的执行加一个return,在方法底部增加一个return 0;的方法,用于满足Symfony\Component\Console\Command\Command::run方法的结果校验

**Comment by hhxsv5** [comment]
LaravelS 版本过低，请升级到最新版v3.7.28。
