### ISSUE TITLE
Switch mode to SWOOLE_BASE

### ISSUE THREAD

**Issue by juber-nunes** [hhxsv5/laravel-s#395]
This is more a question as opposed to a bug.

Would be possible to switch mode from Swoole_process to Swoole_base? I cannot find any reference of it here but as per swoole documentation we could change it 

https://wiki.swoole.com/#/learn?id=swoole_base

Thanks in advance

**Comment by juber-ivre** [comment]
Anyone??? please

**Comment by hhxsv5** [comment]
Confirming...

**Comment by xuanyanwow** [comment]
@hhxsv5  Hello，请问关于切换 `SWOOLE_BASE` 模式是什么原因未推进~

**Comment by hhxsv5** [comment]
SWOOLE_BASE下有诸多的限制，无计划支持。
https://wiki.swoole.com/#/learn?id=swoole_base
