### ISSUE TITLE
服务无法关闭

### ISSUE THREAD

**Issue by rsaLive** [hhxsv5/laravel-s#397]
1. Your software version (Screenshot of your startup)
    
   php bin/laravels stop 一直wainting

2. Detail description about this issue(error/log)

   超时之后，再次reload 或者stop ，又提示process does not exits 
   再次start  提示，alreay running 

3. Some `reproducible` code blocks and `steps`

    
![image](https://user-images.githubusercontent.com/14867935/153333488-3de7ab58-cb1a-41ae-b435-7a48fc59f144.png)

**Comment by hhxsv5** [comment]
一般是因为Swoole进程有代码没跑完，比如定时任务Timer进程、Worker进程写了死循环、Task Worker进程慢任务没跑完。

**Comment by mnizfd** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by xuqihua** [comment]
> 一般是因为Swoole进程有代码没跑完，比如定时任务Timer进程、Worker进程写了死循环、Task Worker进程慢任务没跑完。

how to ?  怎么解决呢？ kill -9 ？

**Comment by hhxsv5** [comment]
一般是切掉流量入口，等一段时间，再强制kill。
