### ISSUE TITLE
How can i test websocket

### ISSUE THREAD

**Issue by IBugraGezer** [hhxsv5/laravel-s#399]
My app uses websocket. When i run "php artisan test" command, i get the error "Class Swoole does not exists"  because of websocket. How can i test websocket codes?

**Comment by uptonyuan** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by mnizfd** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by hhxsv5** [comment]
> My app uses websocket. When i run "php artisan test" command, i get the error "Class Swoole does not exists" because of websocket. How can i test websocket codes?

app('swoole') is only available in the Swoole environment, like Laravel routing, async tasks, timer jobs.

```php
Route::get('/send-websocket-message', function () {
    $fd = 1; // Find fd by userId from a map [userId=>fd].
    /**@var \Swoole\WebSocket\Server $swoole */
    $swoole = app('swoole');
    $success = $swoole->push($fd, 'Push data to fd#1 in Controller');
    var_dump($success);
});
```

**Comment by IBugraGezer** [comment]
Are you planning to implement tests?
