### ISSUE TITLE
WARNING	swPort_onRead_http: Content-Length is too big, MaxSize=[2088960].

### ISSUE THREAD

**Issue by mountainguan** [hhxsv5/laravel-s#40]
在laravels配置里找不到这个设置的位置...应该是swoole的文件上传大小限制，google都搜不到这几个名词

**Comment by mountainguan** [comment]
这是我在logs里看见的

**Comment by hhxsv5** [comment]
配置Swoole的[package_max_length](https://wiki.swoole.com/wiki/page/510.html)

**Comment by mountainguan** [comment]
设置完还是没有效果
![](http://ww1.sinaimg.cn/large/6ace449bgy1frlb4fvpwwj20hq0h3wgk.jpg)

log:
![](http://ww1.sinaimg.cn/large/6ace449bgy1frlb5b6xhcj20hf0autal.jpg)

**Comment by mountainguan** [comment]
把官方的length配置也试了，log依旧跟上面一样
![](http://ww1.sinaimg.cn/large/6ace449bgy1frlbxkdlk2j20cr03j0su.jpg)

**Comment by mountainguan** [comment]
雾草，我又破案了...原来是artisan laravels reload只重新加载代码，不重载laravels的配置

**Comment by hhxsv5** [comment]
😅reload只重启worker进程；你改的swoole配置，需要重启所有进程，应该用restart。

**Comment by mountainguan** [comment]
因为之前改的都是逻辑代码，发现reload挺好用就一直用reload；完全忽视了进程没重启，知道我调试把断点设到了laravels的源码里才发现...
