### ISSUE TITLE
使用websocket推送数据，Swoole\WebSocket\Server::push(): session#1 does not exists

### ISSUE THREAD

**Issue by chaoshuaidehujiayu** [hhxsv5/laravel-s#400]
1. Your software version (Screenshot of your startup)
    
    | Software | Version |
    | --------- | --------- |
    | PHP | 7.4.27 |7.4.27
    | Swoole | 4.8.5 |4.8.5
    | laravels| 3.7.3 |3.7.3
    | Laravel/Lumen | 8.83.1 |8.83.1

2. Detail description about this issue(error/log)
![image](https://user-images.githubusercontent.com/42015805/156133778-1d53b0d0-52d9-4fca-8d72-cb23e79b95d8.png)
按照文档中的操作报错
![image](https://user-images.githubusercontent.com/42015805/156133904-e3192510-8cf7-4bcc-a85e-566b4a002504.png)
websocket是连接成功的
   

3. Some `reproducible` code blocks and `steps`

    ```PHP
    // TODO: your code
    ```

**Comment by hhxsv5** [comment]
FD错了，1只是个例子。
你应该先在onOpen中获取到FD，保存将用户Id与FD的映射关系保存到Redis或Swoole Table，然后控制器中根据用户Id反向获取FD进行推送。
参考：[使用Swoole Table](https://github.com/hhxsv5/laravel-s#use-swooletable)
