### ISSUE TITLE
执行异步任务投递时报错

### ISSUE THREAD

**Issue by hcweb** [hhxsv5/laravel-s#401]
`[2022-03-06 20:13:52] local.ERROR: Uncaught ErrorException: Swoole\Server::task(): task method can't be executed without task worker in /www/wwwroot/xxxx/vendor/hhxsv5/laravel-s/src/Swoole/Server.php:295
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 /www/wwwroot/xxxx/vendor/hhxsv5/laravel-s/src/Swoole/Server.php(295): Swoole\Server->task()
#2 [internal function]: Hhxsv5\LaravelS\Swoole\Server->onPipeMessage()
#3 /www/wwwroot/xxxx/vendor/hhxsv5/laravel-s/src/Swoole/Server.php(409): Swoole\Server->start()
#4 /www/wwwroot/xxxx/vendor/hhxsv5/laravel-s/src/Console/Portal.php(158): Hhxsv5\LaravelS\Swoole\Server->run()
#5 /www/wwwroot/xxxx/vendor/hhxsv5/laravel-s/src/Console/Portal.php(59): Hhxsv5\LaravelS\Console\Portal->start()
#6 /www/wwwroot/xxxx/vendor/symfony/console/Command/Command.php(298): Hhxsv5\LaravelS\Console\Portal->execute()
#7 /www/wwwroot/xxxx/bin/laravels(167): Symfony\Component\Console\Command\Command->run()
#8 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught ErrorException: Swoole\\Server::task(): task method can't be executed without task worker in /www/wwwroot/xxxx/vendor/hhxsv5/laravel-s/src/Swoole/Server.php:295
Stack trace:
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /www/wwwroot/xxxx/vendor/hhxsv5/laravel-s/src/Swoole/Server.php(295): Swoole\\Server->task()
#2 [internal function]: Hhxsv5\\LaravelS\\Swoole\\Server->onPipeMessage()
#3 /www/wwwroot/xxxx/vendor/hhxsv5/laravel-s/src/Swoole/Server.php(409): Swoole\\Server->start()
#4 /www/wwwroot/xxxx/vendor/hhxsv5/laravel-s/src/Console/Portal.php(158): Hhxsv5\\LaravelS\\Swoole\\Server->run()
#5 /www/wwwroot/xxxx/vendor/hhxsv5/laravel-s/src/Console/Portal.php(59): Hhxsv5\\LaravelS\\Console\\Portal->start()
#6 /www/wwwroot/xxxx/vendor/symfony/console/Command/Command.php(298): Hhxsv5\\LaravelS\\Console\\Portal->execute()
#7 /www/wwwroot/xxxx/bin/laravels(167): Symfony\\Component\\Console\\Command\\Command->run()
#8 {main}
  thrown at /www/wwwroot/xxxx/vendor/hhxsv5/laravel-s/src/Swoole/Server.php:295)
[stacktrace]
#0 {main}
"} `
![QQ图片20220306202025](https://user-images.githubusercontent.com/12317944/156922911-79adf398-7f76-4431-9363-6b6d7b7eb16d.png)
![QQ图片20220306202031](https://user-images.githubusercontent.com/12317944/156922913-02d3f16e-bd3f-49d6-8f69-6b6993096789.png)

`<?php

namespace App\Jobs;

use App\Models\Post;
use App\Models\PostItem;
use App\Models\Test;
use App\Models\TestItem;
use Hhxsv5\LaravelS\Swoole\Task\Task;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldBeUnique;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;
use Illuminate\Support\Facades\Log;

class ArticleTask extends Task
{
    // 待处理任务数据
    private $data;

    // 任务处理结果
    private $result;

    /**
     * Create a new job instance.
     *
     * @return void
     */
    public function __construct($data)
    {
        //
        $this->data = $data;
    }

    /**
     * Execute the job.
     *
     * @return void
     */
    public function handle()
    {
        Log::info('开始任务');
        $list=$this->data;
        foreach ($list as $vo) {
            $post_data = [
                'media_id' => $vo['media_id'],
                'media_type' => 'news',
                'is_temporary' => '永久素材',
                'p_updated_at' => $vo['update_time'] ? $vo['update_time'] : 0,
            ];
            //
            $post=Post::where('media_id',$vo['media_id'])->first();
            if($post){
                $post->update($post_data);
            }else{
                $post = Post::create($post_data);
            }
            

            // 插入文章
            foreach ($vo['content']['news_item'] as $key => $news_item) {
                $post_item_data = [
                    'title' => $news_item['title'],
                    'thumb_media_id' => $news_item['thumb_media_id'],
                    'thumb_url' => $news_item['thumb_url'],
                    'author' => $news_item['author'],
                    'digest' => $news_item['digest'],
                    'show_cover_pic' => $news_item['show_cover_pic'],
                    'content_source_url' => $news_item['content_source_url'],
                    'content' => str_replace("data-src", "src", $news_item['content']),
                    'post_id' => $post->id,
                    'sort' => $key,
                    'p_updated_at' => $vo['content']['update_time'],
                    'p_created_at' => $vo['content']['create_time'],
                ];
                //先查询文章是否存在
                $postItem=PostItem::where('title',$news_item['title'])->first();
                if($postItem){
                    $postItem->update($post_item_data);
                }else {
                    PostItem::create($post_item_data);
                }
                
            }
        }
    }

    public function finish()
    {
        Log::info('任务处理完成');
    }
}
`
`<?php

namespace App\Jobs;

use Hhxsv5\LaravelS\Swoole\Task\Task;
use Hhxsv5\LaravelS\Swoole\Timer\CronJob;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

class WechatCronJob extends CronJob
{
    protected $offset=0;
    // 该方法可类比为 Swoole 定时器中的回调方法
    public function run()
    {
        Log::info('xxxxxxtn');
        $app = app('wechat.official_account');
        $lists = $app->material->list('news', $this->offset, 20);
        $total = $lists['total_count'];
        $list = $lists['item'];
        $task = new ArticleTask($list);
        $success = Task::deliver($task);  // 异步投递任务，触发调用任务类的 handle 方法
        
        if ($success) {
            Log::info('start:'.$this->offset);
            if ($this->offset >= $total) {
                $this->offset=0;
            }else {
               $this->offset+=20;
            }
            Log::info('end:'.$this->offset);
        }
    }

    // 每隔 1000ms 执行一次任务
    public function interval()
    {
        return 1000;   // 定时器间隔，单位为 ms
    }

    // 是否在设置之后立即触发 run 方法执行
    public function isImmediate()
    {
        return false;
    }
}
`

**Comment by hhxsv5** [comment]
`task method can't be executed without task worker` 
请在`config/laravels.php`中配置`task_worker_num`。
