### ISSUE TITLE
Lumen9  Command "laravels" is not defined.      

### ISSUE THREAD

**Issue by szy4211** [hhxsv5/laravel-s#403]
1. Your software version (Screenshot of your startup)
    
    | Software | Version |
    | --------- | --------- |
    | PHP |  8.1.4  |
    | Swoole |  4.8.8 |
    | Laravel/Lumen | 9.0.1) |

2. Detail description about this issue(error/log)

```PHP

php artisan laravels publish -vvv

In Application.php line 683:
                                                                  
  [Symfony\Component\Console\Exception\CommandNotFoundException]  
  Command "laravels" is not defined.

```

3. Some `reproducible` code blocks and `steps`

    ```PHP

    // bootstrap/app.php
    $app->register(Hhxsv5\LaravelS\Illuminate\LaravelSServiceProvider::class);

    ```

4. 使用Lumen:8.x 正常，使用Lumen:9.x提示没有找到命令`laravels`。已在` bootstrap/app.php`注册服务

**Comment by hhxsv5** [comment]
确实有问题，明天我看看。

**Comment by hhxsv5** [comment]
这是Lumen v9.0.1的Bug，目前已有[PR#1230](https://github.com/laravel/lumen-framework/pull/1230)修复，但未发布新版，暂时只有使用9.x分支。
`composer require laravel/lumen-framework:9.x-dev`

**Comment by hhxsv5** [comment]
升级lumen-framework到9.0.2，即可修复。
`composer require laravel/lumen-framework:9.0.2`

**Comment by szy4211** [comment]
> 升级lumen-framework到9.0.2，即可修复。 `composer require laravel/lumen-framework:9.0.2`

感谢回复，已做出相应更新
