### ISSUE TITLE
Prometheus

### ISSUE THREAD

**Issue by malikdoksoz** [hhxsv5/laravel-s#406]
Can i use Prometheus without Docker? I installed everything manually on my Ubuntu OS I don't want to use docker.

**Comment by hhxsv5** [comment]
Of course you can, but installing Promethues+Grafana manually is a bit harder than Docker.

**Comment by malikdoksoz** [comment]
I am getting an error like this.
![Ekran Resmi 2022-06-05 17 15 22](https://user-images.githubusercontent.com/26676061/172054932-343095b5-70d4-4a04-bead-6860853f8115.png)

**Comment by hhxsv5** [comment]
What version of Swoole is installed?
Show me the LaravelS startup output.

**Comment by malikdoksoz** [comment]
![Ekran Resmi 2022-06-07 16 28 05](https://user-images.githubusercontent.com/26676061/172392607-8cce187d-8cf5-4057-8ca5-6486ebc85de8.png)

**Comment by hhxsv5** [comment]
It turns out that you installed Open Swoole, not Swoole.
The Open Swoole stats() method has no connection_num field. Currently, the Prometheus component of laravel-s is not compatible with Open Swoole. It is recommended that you install swoole to solve it.

```bash
pecl install swoole
```

**Comment by malikdoksoz** [comment]
I didn't know that, thank you. You've probably seen the security breach on Swoole. 
[https://github.com/swoole/swoole-src/issues/4434](url) [https://www.reddit.com/r/PHP/comments/q7euy2/swoole_forked_to_open_swoole_due_to_disagreement/](url)

Which one do you think I should use in my project? (openswoole or swoole)

**Comment by hhxsv5** [comment]
That security issue has been fixed in the new version, and I recommend using Swoole.
