### ISSUE TITLE
请问该如何创建一个websocket客户端?

### ISSUE THREAD

**Issue by ygcool** [hhxsv5/laravel-s#407]
如题，需要链接外部ws进行订阅，是在自定义进程创建吗？能否有一个简易示例，谢谢。期待回复

**Comment by hhxsv5** [comment]
可以在自定义进程中使用[Swoole\Coroutine\Http\Client](https://wiki.swoole.com/#/coroutine_client/http_client?id=upgrade)连接外部WebSocket。
