### ISSUE TITLE
laravel-s 有提供链路追踪的能力吗？

### ISSUE THREAD

**Issue by huangdijia** [hhxsv5/laravel-s#409]
laravel-s 有提供链路追踪的能力吗？如果没有，可否搭配 https://github.com/Vinelab/tracing-laravel 实用？有没有什么要注意的？

**Comment by hhxsv5** [comment]
laravel-s目前没有原生提供链路追踪的能力。关于Tracing-laravel，我没有验证过，你可以在开发环境试试。

**Comment by huangdijia** [comment]
> 
laravel-s目前没有原生提供链路追踪的能力。关于Tracing-laravel，我没有验证过，你可以在开发环境试试。

后续有计划支持吗？

**Comment by hhxsv5** [comment]
暂时没有计划，laravel-s还是主要聚焦在laravel与swoole的结合性上。
