### ISSUE TITLE
server load average too high 服务器平均负载过高

### ISSUE THREAD

**Issue by Stone-ChenLijun** [hhxsv5/laravel-s#412]
My Environment
我的环境：
|  程序   | 版本  |
|  ----  | ----  |
| PHP  | 7.4.19 |
| Swoole  | 4.6.7 |
| LaravelS  | 3.7.19 |
| Laravel Framework [local]  | 8.36.2 |
| Nginx | 1.18 |
| OS | Ubuntu Server 20.04 |

worker_num=32（这个我试过8,16,32）
task_worker_num=16

我的线上服务器配置是8核16G,在实际使用过程中，发现Htop看到的平均负载非常高。
uptime 返回的结果是 22:38:08 up 65 days, 15:56,  1 user,  load average: 169.08, 168.26, 162.86

但是在看CPU和内存平均负载时，有发现不高，只会在某些瞬时某个核的CPU会爆到100%，但很快就下去，在此期间其他的几个核的使用率都很低。

之前我怀疑是我在这台一起跑者mysql，导致问题，但是我把mysql迁出去。这个负载平均值也是这么高。
服务器的CPU负载一直低于30%。内存使用一直稳定在10G/15.6G左右。

向请问下，可能导致这个平均负载这么高的原因是什么。

**Comment by hhxsv5** [comment]
用top看是什么进程占了CPU，然后使用[调试工具](https://wiki.swoole.com/#/question/use?id=%e8%b0%83%e8%af%95%e5%b7%a5%e5%85%b7)分析该进程里干了什么，同时结合日志进行排查，包括(swoole日志、laravel日志)。
