### ISSUE TITLE
Cache store [] is not defined.

### ISSUE THREAD

**Issue by ybrmzj** [hhxsv5/laravel-s#42]
我的运行环境如下：
+-------------------+------------------------------------------+
| Component         | Version                                  |
+-------------------+------------------------------------------+
| PHP               | 7.2.4                                    |
| Swoole            | 2.1.3                                    |
| Laravel Framework | Lumen (5.5.2) (Laravel Components 5.5.*) |
+-------------------+------------------------------------------+

config/cache.php 相关配置：

    'default' => env('CACHE_DRIVER', 'redis'),

    'stores' => [
        'redis' => [
            'driver' => 'redis',
            'connection' => env('CACHE_REDIS_CONNECTION', 'default'),
        ],
  
执行步骤：
开启websocket服务，
在postman中请求一个api接口（有启用throttle中间件），
第一次返回正常，第二次报错：
 Oops! An unexpected error occurred: Cache store [] is not defined.     

错误日志：
[ERROR] LaravelS: onRequest: Uncaught exception "InvalidArgumentException"([0]Cache store [] is not defined.) at /xxx/vendor/illuminate/cache/CacheManager.php:96,
#0 /xxx/vendor/illuminate/cache/CacheManager.php(80): Illuminate\Cache\CacheManager->resolve(NULL)
#1 /xxx/vendor/illuminate/cache/CacheManager.php(58): Illuminate\Cache\CacheManager->get(NULL)
#2 /xxx/vendor/illuminate/cache/CacheManager.php(69): Illuminate\Cache\CacheManager->store(NULL)
#3 /xxx/vendor/illuminate/cache/CacheServiceProvider.php(28): Illuminate\Cache\CacheManager->driver()
#4 /xxx/vendor/illuminate/container/Container.php(749): Illuminate\Cache\CacheServiceProvider->Illuminate\Cache\{closure}(Object(Laravel\Lumen\Application), Array)
#5 /xxx/vendor/illuminate/container/Container.php(631): Illuminate\Container\Container->build(Object(Closure))
#6 /xxx/vendor/illuminate/container/Container.php(586): Illuminate\Container\Container->resolve('cache.store', Array)
#7 /xxx/vendor/laravel/lumen-framework/src/Application.php(230): Illuminate\Container\Container->make('cache.store', Array)
#8 /xxx/vendor/illuminate/container/Container.php(885): Laravel\Lumen\Application->make('cache.store')
#9 /xxx/vendor/illuminate/container/Container.php(813): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#10 /xxx/vendor/illuminate/container/Container.php(780): Illuminate\Container\Container->resolveDependencies(Array)
#11 /xxx/vendor/illuminate/container/Container.php(631): Illuminate\Container\Container->build('Tymon\\JWTAuth\\P...')
#12 /xxx/vendor/illuminate/container/Container.php(586): Illuminate\Container\Container->resolve('Tymon\\JWTAuth\\P...', Array)
#13 /xxx/vendor/laravel/lumen-framework/src/Application.php(230): Illuminate\Container\Container->make('Tymon\\JWTAuth\\P...', Array)
#14 /xxx/vendor/tymon/jwt-auth/src/Providers/AbstractServiceProvider.php(377): Laravel\Lumen\Application->make('Tymon\\JWTAuth\\P...')
#15 /xxx/vendor/tymon/jwt-auth/src/Providers/AbstractServiceProvider.php(201): Tymon\JWTAuth\Providers\AbstractServiceProvider->getConfigInstance('providers.stora...')
#16 /xxx/vendor/illuminate/container/Container.php(749): Tymon\JWTAuth\Providers\AbstractServiceProvider->Tymon\JWTAuth\Providers\{closure}(Object(Laravel\Lumen\Application), Array)
#17 /xxx/vendor/illuminate/container/Container.php(631): Illuminate\Container\Container->build(Object(Closure))
#18 /xxx/vendor/illuminate/container/Container.php(586): Illuminate\Container\Container->resolve('tymon.jwt.provi...', Array)
#19 /xxx/vendor/laravel/lumen-framework/src/Application.php(230): Illuminate\Container\Container->make('tymon.jwt.provi...', Array)
#20 /xxx/vendor/illuminate/container/Container.php(503): Laravel\Lumen\Application->make('tymon.jwt.provi...')
#21 /xxx/vendor/illuminate/container/Container.php(238): Illuminate\Container\Container->rebound('tymon.jwt.provi...')
#22 /xxx/vendor/illuminate/container/Container.php(332): Illuminate\Container\Container->bind('tymon.jwt.provi...', Object(Closure), true)
#23 /xxx/vendor/tymon/jwt-auth/src/Providers/AbstractServiceProvider.php(202): Illuminate\Container\Container->singleton('tymon.jwt.provi...', Object(Closure))
#24 /xxx/vendor/tymon/jwt-auth/src/Providers/AbstractServiceProvider.php(75): Tymon\JWTAuth\Providers\AbstractServiceProvider->registerStorageProvider()
#25 /xxx/vendor/laravel/lumen-framework/src/Application.php(193): Tymon\JWTAuth\Providers\AbstractServiceProvider->register()
#26 /xxx/vendor/hhxsv5/laravel-s/src/Illuminate/Laravel.php(244): Laravel\Lumen\Application->register(Object(Tymon\JWTAuth\Providers\LumenServiceProvider), Array, true)
#27 /xxx/vendor/hhxsv5/laravel-s/src/Illuminate/Laravel.php(267): Hhxsv5\LaravelS\Illuminate\Laravel->reRegisterServiceProvider('\\Tymon\\JWTAuth\\...')
#28 /xxx/vendor/hhxsv5/laravel-s/src/LaravelS.php(123): Hhxsv5\LaravelS\Illuminate\Laravel->cleanRequest(Object(Illuminate\Http\Request))
#29 /xxx/vendor/hhxsv5/laravel-s/src/LaravelS.php(78): Hhxsv5\LaravelS\LaravelS->handleDynamicResource(Object(Illuminate\Http\Request), Object(Swoole\Http\Response))
#30 {main}

**Comment by mountainguan** [comment]
是不是redis没开

**Comment by hhxsv5** [comment]
尝试下基本的Cache功能是否可用
```PHP
Cache::put('bar', 'baz' . time(), 20);
$ret = Cache::get('bar');
var_dump($ret);
```

**Comment by gazben** [comment]
@hhxsv5 Same here. 

CACHE_DRIVER=file

```
+-------------------+------------------------------------------+
| Component         | Version                                  |
+-------------------+------------------------------------------+
| PHP               | 7.2.6                                    |
| Swoole            | 2.2.0                                    |
| Laravel Framework | Lumen (5.6.3) (Laravel Components 5.6.*) |
+-------------------+------------------------------------------+
```

**Comment by hhxsv5** [comment]
Release [v1.11.3](https://github.com/hhxsv5/laravel-s/releases/tag/v1.11.3)。
