### ISSUE TITLE
dcat-admin使用问题

### ISSUE THREAD

**Issue by ygcool** [hhxsv5/laravel-s#421]
laravels.php配置文件里面添加了dcatadmin清理器，swoole.dispatch_mode设为了2（用到了ws服务，看laravel-s文档开启ws需要将dispatch_mode需要设为2）：
```
...
'cleaners' => [
        Hhxsv5\LaravelS\Illuminate\Cleaners\SessionCleaner::class,
        Hhxsv5\LaravelS\Illuminate\Cleaners\AuthCleaner::class,
        Hhxsv5\LaravelS\Illuminate\Cleaners\DcatAdminCleaner::class,
 ],
...

'swoole' => [
        'dispatch_mode' => 2,
]
```
首次进页面可以显示菜单，刷新页面后会导致后台菜单不显示的问题。请问有什么办法可以解决吗？谢谢，期待回复

PHP：8.1.9
swoole：5.0.1
laravle-s：3.7.34
laravel：9.40.1

**Comment by hhxsv5** [comment]
参考 #251

**Comment by ygcool** [comment]
> 参考 #251

谢谢。解决了，除了添加[默认dcatadmin清理器](https://github.com/hhxsv5/laravel-s/issues/251#issuecomment-762279133)，额外再加一个[清理器](https://github.com/hhxsv5/laravel-s/issues/251#issuecomment-971224092)即可解决。

**Comment by weifq** [comment]
> > 参考 #251
> 
> 谢谢。解决了，除了添加[默认dcatadmin](https://github.com/hhxsv5/laravel-s/issues/251#issuecomment-762279133)清理器，额外再加一个[清理器](https://github.com/hhxsv5/laravel-s/issues/251#issuecomment-971224092)即可解决。

你好，我遇到了和你一样的问题，排查了DcatAdminCleaner里面的代码，屏蔽了“admin.menu”这行代码才解决了这个问题，请问您这边是额外加了哪个清理器解决的呢？

**Comment by weifq** [comment]
参考 #251 里面的 [hooklife](https://github.com/hooklife) 的回答，已解决
