### ISSUE TITLE
我用WebSocket对接go-cqhttp有问题和疑问

### ISSUE THREAD

**Issue by asmydream** [hhxsv5/laravel-s#422]
1. Your software version (Screenshot of your startup)
    
     Software Version
    PHP  8.0
     Swoole 5.0.1
     Laravel 9.20

问题1：启动WebSocket服务WebSocket Handler类中的onMessage方法是一直循环执行的吗？ 打印了一下，是一直循环打印下去，这个怎么能终止一直执行。
问题2：怎么获取到客户端发送的消息。客户端发送的josn格式消息，不想走路由来获取。
我想获取到消息然后处理这个消息的请求。
补充，我只想启动WebSocket服务，http的服务可以关闭或者不打开吗？

**Comment by asmydream** [comment]
是我错了，没有热更新代码的问题，想再次咨询一下，如何关闭 http server

**Comment by hhxsv5** [comment]
http server是websocket的基础，建立websocket连接时会先创建http请求，所以不能关闭http server
