### ISSUE TITLE
按照文档配置nginx完成后访问index.php还是会变成下载

### ISSUE THREAD

**Issue by singi2016cn** [hhxsv5/laravel-s#426]
参照 https://github.com/hhxsv5/laravel-s/blob/master/README-CN.md 配置 nginx 后，访问index.php还是会变成下载。
打开下面的配置也没用

```
# 当请求PHP文件时直接响应404，防止暴露public/*.php
location ~* \.php$ {
   return 404;
}
```

**Comment by singi2016cn** [comment]
修改index.php成aaaaaa.php，然后再改回就正常了。 = =！

**Comment by hhxsv5** [comment]
使用swoole后不应该访问任何.php文件（除非你laravel里有/index.php这样的路由），index.php是针对fpm的产物。
