### ISSUE TITLE
在监听事件中和routes/web.php中获取的sessionID相同，但是在websocket监听的事件中不能获取session值

### ISSUE THREAD

**Issue by eiixy** [hhxsv5/laravel-s#43]
![2 8 mo 7 5 i2vqd2qs](https://user-images.githubusercontent.com/22978107/40834660-01d14056-65c4-11e8-8f10-88623b470e44.png)
![aiqcdqkcfc ro4j_ k 3lpl](https://user-images.githubusercontent.com/22978107/40834729-33bb53cc-65c4-11e8-9a63-5da7d366792c.png)
![zi 4 ma5h m6g_t o 9 zk](https://user-images.githubusercontent.com/22978107/40834730-346404d6-65c4-11e8-8c72-8dc5d8d6829f.png)

**Comment by hhxsv5** [comment]
WebsocketService目前不属于Laravel生命周期，是原始的swoole_websocket_server的事件类，没有经过Laravel初始化（包含Session初始化等），无法拿到Session数据。这个我可以处理下，支持onOpen事件中拿到初始化Laravel，Session信息。

**Comment by hhxsv5** [comment]
已修复 [8677fe2](https://github.com/hhxsv5/laravel-s/commit/8677fe249393d913b49a5f3a032aaed130b4a947) 拉dev-master试试。

**Comment by hhxsv5** [comment]
```PHP
public function onOpen(\swoole_websocket_server $server, \swoole_http_request $request)
{
    // 在触发onOpen事件之前Laravel的生命周期已经完结，所以Laravel的Request、Session是可用的
    \Log::info('New WebSocket connection', [$request->fd, request()->all(), session()->getId(), session('xxx')]);
}
```

**Comment by eiixy** [comment]
嗯，解决了
