### ISSUE TITLE
看最新的文档，sendMessage方法的第二个参数可以传递-1，是否可以修改呢？ 

### ISSUE THREAD

**Issue by dafa168** [hhxsv5/laravel-s#433]
https://github.com/hhxsv5/laravel-s/blob/0839a829497c491cb2e4c84b05762a0c224b1223/src/Swoole/Task/BaseTask.php#L83

swoole官方文档 ： https://wiki.swoole.com/#/server/setting?id=task_ipc_mode

**Comment by hhxsv5** [comment]
- 这里是要发消息给Task进程，Task 进程编号范围是 [$server->setting['worker_num'], $server->setting['worker_num'] + $server->setting['task_worker_num'] - 1]，[sendMessage方法](https://wiki.swoole.com/#/server/methods?id=sendmessage)不支持-1。
- -1 只支持[task](https://wiki.swoole.com/#/server/methods?id=task)与[taskwait](https://wiki.swoole.com/#/server/methods?id=taskwait)方法。
