### ISSUE TITLE
mysql 8.0.27 提示 Packets out of order. Expected 1 received 0. Packet size=145

### ISSUE THREAD

**Issue by donglf681** [hhxsv5/laravel-s#439]
1. Your software version (Screenshot of your startup)
    
    | Software | Version |
    | --------- | --------- |
    | PHP | PHP 7.2.34-24+ubuntu20.04.1|
    | Swoole | 4.7.1|
    | Laravel | 5.5.49 |

2. Detail description about this issue(error/log)

    `Uncaught exception 'Illuminate\Database\QueryException': [0]Packets out of order. Expected 1 received 0. Packet size=145 (SQL: select * from `user_extend` where `user_id` = 13182244 limit 1) called in /var/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664`

3. Some `reproducible` code blocks and `steps`

    ```PHP
        /**
     * @param array|string[] $columns
     * @return null|\Illuminate\Database\Eloquent\Builder|mixed|Model|object|UserExtend
     */
    public function getByUserId(int $userId, array $columns = ['*'])
    {
        return $this->model->newQuery()
            ->select($columns)
            ->where('user_id', $userId)
            ->first();
    }
    ```

> mysql 版本是  8.0.27，现在是应用每天都会偶发一两次，都是发生在查询的时候报的错误

**Comment by hhxsv5** [comment]
https://blog.csdn.net/qq_39256527/article/details/80818267

**Comment by dellif** [comment]
@hhxsv5 MySQL已经配置已经调整，还是会出现这个错误，请问还有哪些方面会影响到的 ？

**Comment by uptonyuan** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by mnizfd** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by dellif** [comment]
![image](https://github.com/hhxsv5/laravel-s/assets/24838282/23cef2ad-5cb0-4720-896f-d4b6341b4159)
已经设置了，仍然还是出现问题，可以排除的是网络没有波动，laravels框架里面是否还有其他参数需要优化配置的 ？

**Comment by mnizfd** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by uptonyuan** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by fdmadong** [comment]
// 关闭持久连接
PDO::ATTR_PERSISTENT => false,

**Comment by mnizfd** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
