### ISSUE TITLE
Trying to access array offset on value of type int

### ISSUE THREAD

**Issue by develop-kevin** [hhxsv5/laravel-s#443]
1. Your software version (Screenshot of your startup)
    
+---------------------------+---------+
| Component                 | Version |
+---------------------------+---------+
| PHP                       | 7.4.33  |
| Swoole                    | 4.8.12  |
| LaravelS                  | 3.7.36  |
| Laravel Framework [local] | 5.8.38  |
+---------------------------+---------+

2. Detail description about this issue(error/log)
![image](https://github.com/hhxsv5/laravel-s/assets/30752149/bc4244c1-907c-410e-a3f8-6a68bc86d09d)

**Comment by hhxsv5** [comment]
@develop-kevin 你反馈后还有问题后再重开。
