### ISSUE TITLE
请问如何启动服务时仅开启ws服务

### ISSUE THREAD

**Issue by lwhdev** [hhxsv5/laravel-s#446]
| PHP                       | 7.3.0   |
| Swoole                    | 4.4.16  |
| LaravelS                  | 3.7.36  |
| Laravel Framework [local] | 7.30.6  |

一定要开启http服务,ws才能使用吗

**Comment by hhxsv5** [comment]
对，你可以去了解下websocket的建立过程。建立websocket协议需要先建立http，再upgrade为websocket。另外不用担心资源浪费，websocket和http是共用一套worker进程组。

**Comment by lwhdev** [comment]
好的,谢谢
