### ISSUE TITLE
Target class [swoole] does not exist error in console command with laravels server start and up

### ISSUE THREAD

**Issue by NVD-R** [hhxsv5/laravel-s#459]
1. Your software version (Screenshot of your startup)
    
 | Component                 | Version |
+---------------------------+---------+
| PHP                       | 8.2.6   |
| Swoole                    | 5.0.1   |
| LaravelS                  | 3.7.37  |
| Laravel Framework [local] | 10.32.1 |

2. Detail description about this issue(error/log)

Laravels is start and up but in console kernel or commands cant accsees to app('swoole')

 `Target class [swoole] does not exist.`

3. Some `reproducible` code blocks and `steps`

    ```PHP
   public function handle()
    {
        dd(app('swoole'));
    }
    ```

**Comment by hhxsv5** [comment]
Known issues[Class swoole does not exist](https://github.com/hhxsv5/laravel-s/blob/master/KnownIssues.md#class-swoole-does-not-exist)

**Comment by NVD-R** [comment]
so i cant call Task deliver in kernel console schedule.
do you have any solution?
