### ISSUE TITLE
开启laravels的时候swoole日志->fatal: Not a git repository (or any of the parent directories): .git

### ISSUE THREAD

**Issue by hjinjsj** [hhxsv5/laravel-s#46]
1. Tell us your PHP version(`php -v`)

`TODO` php5.6.33 php7.0.19

2. Tell us your Swoole version(`php --ri swoole`)

`TODO` php5.6.33->1.10.1  php7.0.19->2.0.9

3. Tell us your `Laravel`/`Lumen` version(check composer.json & composer.lock)

`TODO` Lumenv5.2.5

4. Detail description about this issue(error/log)

`TODO`   php artisan laravels start
storage/logs/swoole-2018-06.log
>>>fatal: Not a git repository (or any of the parent directories): .git
>>>fatal: Not a git repository (or any of the parent directories): .git
>>>fatal: Not a git repository (or any of the parent directories): .git

但是不影响api接口调用

5. Give us a `reproducible` code block and `steps`

```PHP
//TODO: Your code
```

**Comment by hhxsv5** [comment]
安装最新版`swoole`试试。
