### ISSUE TITLE
启动的工作目录问题

### ISSUE THREAD

**Issue by tantalate** [hhxsv5/laravel-s#464]
使用 `php bin/laravels` 启动之后，当前目录是laravel项目的根目录。
默认laravel项目的入口文件在public目录下，代码中可能会有依赖当前目录的代码（例如使用` File::files();`获取目录下的文件列表），工作目录不同可能导致代码行为不一样。

我目前 cd public 然后使用 `php ../bin/laravels`来启动，可以保持跟fpm方式一样的工作目录，目前测试是OK的，但是不清楚会不会对laravels有其他影响。
如果没有影响，是不是supervisord配置中也可以改为 `directory=/var/www/laravel-s-test/public`

**Comment by hhxsv5** [comment]
没影响，laravel-s内部都是使用绝对路径。
