### ISSUE TITLE
websocket fd 自增问题

### ISSUE THREAD

**Issue by methzeal** [hhxsv5/laravel-s#47]
1. Tell us your PHP version(`php -v`)

PHP 7.2.5 (cli) (built: May 11 2018 17:15:07) ( NTS )

2. Tell us your Swoole version(`php --ri swoole`)

Version => 2.1.3

3. Tell us your `Laravel`/`Lumen` version(check composer.json & composer.lock)

Laravel version | 5.6.21

4. Detail description about this issue(error/log)

websocket新连接fd自增总会跳过一个，比如当前fd 4，下一个连接就会变成6而不是5
是设定原因还是bug？

5. Give us a `reproducible` code block and `steps`

[2018-06-06 11:06:10] local.INFO: New Websocket connection [2] 
[2018-06-06 11:06:14] local.INFO: New Websocket connection [4] 
[2018-06-06 11:06:16] local.INFO: New Websocket connection [6]

**Comment by hhxsv5** [comment]
使用了Http服务吗？

**Comment by methzeal** [comment]
开启了http服务

**Comment by hhxsv5** [comment]
http和websocket是共用worker进程，fd也是共用的。所有请求一个http页面fd加1，再连一个websocket fd再加1。

**Comment by methzeal** [comment]
了解了
