### ISSUE TITLE
request 设置的参数，后面的代码获取不到

### ISSUE THREAD

**Issue by xianlinzhang** [hhxsv5/laravel-s#474]
1. Your software version (Screenshot of your startup)
    
    | Software | Version |
| PHP                       | 8.1.28  |
| Swoole                    | 4.8.13  |
| LaravelS                  | 3.7.35  |

2. Detail description about this issue(error/log)

在控制器里设置了请求参数，在数据仓库里获取不到

3. Some `reproducible` code blocks and `steps`

CorpPoolController.php
    ```
    request()->mergeIfMissing(['is_pool' => 1]);
    ```

CorpRepository,php
    ```
    request('is_pool');
    ```

CorpRepository,php里获取到 is_pool 是null?

**Comment by uptonyuan** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by xianlinzhang** [comment]
https://github.com/hhxsv5/laravel-s/blob/PHP-7.x/KnownIssues-CN.md#%E5%8D%95%E4%BE%8B%E6%8E%A7%E5%88%B6%E5%99%A8
