### ISSUE TITLE
unit/feature test examples?

### ISSUE THREAD

**Issue by luke-momentusresearch** [hhxsv5/laravel-s#476]
hi, how do I unit/feature/integration test aspects of my code's integration with this framework, e.g. timer/cron/swoole tables?

**Comment by uptonyuan** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by hhxsv5** [comment]
It is difficult to test integration through phpunit, usually through manual testing.
