### ISSUE TITLE
require symfony/console >=7.0.0

### ISSUE THREAD

**Issue by grvoyt** [hhxsv5/laravel-s#479]
1. Your software version (Screenshot of your startup)
    
    | Software | Version |
    | --------- | --------- |
    | PHP | 8.3 |
    | Swoole | 5+ |
    | Laravel| 10.10 |

2. Detail description about this issue(error/log)

Laravel 10.10 requires symfony/console ^6.
Laravel-s 3.8+ requires symfony/console ^7.

```
hhxsv5/laravel-s[v3.8.0, ..., v3.8.1] require symfony/console >=7.0.0 -> found symfony/console[v7.0.0, ..., v7.1.4] but the package is fixed to v6.4.11
```

Laravel 10.10 composer.json

```
"symfony/console": "^6.2",
```

is it possible to add both version 6 and 7?

**Comment by hhxsv5** [comment]
Fixed at [v3.8.2](https://github.com/hhxsv5/laravel-s/releases/tag/v3.8.2)
