### ISSUE TITLE
使用第三方库flash作为提示，与fpm运行结果不一致

### ISSUE THREAD

**Issue by wangqingwei** [hhxsv5/laravel-s#48]
1. Tell us your PHP version(`php -v`)

7.1.16

2. Tell us your Swoole version(`php --ri swoole`)

4.0.0-beta

3. Tell us your `Laravel`/`Lumen` version(check composer.json & composer.lock)

5.5.40

4. Detail description about this issue(error/log)

使用第三方库flash做表单验证提醒，当第一次提醒成功时候有一次提醒，当第二次成功的时候有两个提醒，每次会增多，刷新都没用，而在fpm下运行不会出现此结果，该库的地址https://github.com/laracasts/flash，麻烦大神帮我看看
![image](https://user-images.githubusercontent.com/9195834/41100205-513d305e-6a93-11e8-8753-6757da87183f.png)

5. Give us a `reproducible` code block and `steps`

```PHP
// controller
flash("添加成功")->success()->important();
return view('test');

// view
@extends('layouts.app')
@section('content')
    @include('flash::message')
@endsection
```

**Comment by hhxsv5** [comment]
使用Swoole HttpServer后，单例、全局变量、静态变量会被常驻内存，这是导致出现这个问题的根本原因。而在FPM每次请求开始时初始化变量，请求完成后所有变量会自动回收。所以表现不一样。
所以要解决这个问题，最直接有效的就是每次`请求前重置`或`请求完成后清理`这些`请求上下文`。
具体参考[单例问题](https://github.com/hhxsv5/laravel-s/blob/master/README-CN.md#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9)

具体到这里issue，因`FlashServiceProvider`中注册的是单例，而此单例的成员`$messages`也被常驻内存，调用`flash("添加成功")->success()->important();`是往`$messages`中追加，估每次消息会叠加。
[FlashNotifier.php#L95](https://github.com/laracasts/flash/blob/master/src/Laracasts/Flash/FlashNotifier.php#L95)
[Collection.php#L1719](https://github.com/laravel/framework/blob/v5.5.40/src/Illuminate/Support/Collection.php#L1719)

最终解决方案有两个：
1. 通过`前置中间件`在每次请求处理前重置messages `app('flash')->messages = [];`。
2.每次请求处理前重新注册`FlashServiceProvider`，配置[register_providers](https://github.com/hhxsv5/laravel-s/blob/master/Settings-CN.md)

**Comment by wangqingwei** [comment]
按照文档设置 register_providers 已经解决，谢谢

**Comment by wangqingwei** [comment]
按照文档设置 register_providers 已经解决，谢谢
