### ISSUE TITLE
一个项目能不能在不同端口运行多次？

### ISSUE THREAD

**Issue by kawais** [hhxsv5/laravel-s#481]
1. Your software version (Screenshot of your startup)
    
    | Software | Version |
    | --------- | --------- |
    | PHP | 7.43|
    | Swoole | 4.x|
    | Laravel/Lumen | 8.x|

2. Detail description about this issue(error/log)

    我需要将同一份代码的项目在不同端口运行，于是将代码分别复制到A/B两个目录中，配置了不同的端口号，
但是分别运行php bin/laravels start时，第一个正常，第二个会出现大量文件未找到的错误
PHP Fatal error:  During class fetch: Uncaught ErrorException: include(/A/vendor/illuminate/database/Eloquent/Concerns/HasEvents.php): failed to open stream: Input/output error in /A/vendor/composer/ClassLoader.php:576
无论哪个先开始，另一个就会出错。不知道是哪里不对。

**Comment by hhxsv5** [comment]
执行composer dump-autoload试试
