### ISSUE TITLE
支持启动2个laravels服务吗

### ISSUE THREAD

**Issue by yuanning456** [hhxsv5/laravel-s#483]
一个laravel项目里面，如果想启动2个端口号不一样的laravels服务来做2个长连接业务； 如何支持

**Comment by hhxsv5** [comment]
通过[多端口混合协议](https://github.com/hhxsv5/laravel-s/blob/master/README-CN.md#%E5%A4%9A%E7%AB%AF%E5%8F%A3%E6%B7%B7%E5%90%88%E5%8D%8F%E8%AE%AE)来实现。
