### ISSUE TITLE
请问上传文件最大多大？怎么调整参数

### ISSUE THREAD

**Issue by wangqingwei** [hhxsv5/laravel-s#49]
1. Tell us your PHP version(`php -v`)

`TODO`

2. Tell us your Swoole version(`php --ri swoole`)

`TODO`

3. Tell us your `Laravel`/`Lumen` version(check composer.json & composer.lock)

`TODO`

4. Detail description about this issue(error/log)

`TODO`

5. Give us a `reproducible` code block and `steps`

```PHP
//TODO: Your code
```

**Comment by hhxsv5** [comment]
[大小限制](https://github.com/hhxsv5/laravel-s/blob/master/KnownCompatibleIssues-CN.md#%E5%A4%A7%E5%B0%8F%E9%99%90%E5%88%B6)
