### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined method swoole_http_response::gzip()

### ISSUE THREAD

**Issue by tanteng** [hhxsv5/laravel-s#5]
`
[2018-02-07 14:54:30 *154.0]    ERROR   zm_deactivate_swoole (ERROR 503): Fatal error: Uncaught Error: Call to undefined method swoole_http_response::gzip() in /var/www/tanteng.me/vendor/hhxsv5/laravel-s/src/Swoole/DynamicResponse.php:13
Stack trace:
#0 /var/www/tanteng.me/vendor/hhxsv5/laravel-s/src/Swoole/Response.php(54): Hhxsv5\LaravelS\Swoole\DynamicResponse->gzip()
#1 /var/www/tanteng.me/vendor/hhxsv5/laravel-s/src/LaravelS.php(84): Hhxsv5\LaravelS\Swoole\Response->send(1)
#2 /var/www/tanteng.me/vendor/hhxsv5/laravel-s/src/LaravelS.php(59)
[2018-02-07 14:54:30 $113.0]    WARNING swManager_check_exit_status: worker#0 abnormal exit, status=255, signal=0
`
安装了 ziplib 模块还是不行，环境 PHP7 + Swoole 最新版

**Comment by hhxsv5** [comment]
执行下面的命令 确认zlib是否启用成功
```Bash
php --ri swoole|grep zlib
```

**Comment by tanteng** [comment]
php -m 有 zlib 模块
但是 php --ri swoole|grep zlib 没有输出

**Comment by hhxsv5** [comment]
贴下系统版本，swoole版本。

**Comment by tanteng** [comment]
确实没有 zlib 库，我使用的是 docker，在 dockerfile 加了安装命令，现在可以成功访问了。

`
#####################################
# zlib:
#####################################
RUN apt-get update && \
    apt-get install -y libz-dev
`

**Comment by tanteng** [comment]
另外还请教一个问题，使用 php artisan laravels start 启动了常驻进程后，需不需要配合 Supervisor 来监控

**Comment by hhxsv5** [comment]
可以监管起来，不过Laravel需要非daemonize运行。

**Comment by RoderickKennedy** [comment]
> 用ldconfig -p|grep libz确定下系统有没有libz
> 贴下系统版本，swoole版本。
| PHP                | 7.3.9                                    |
| Swoole            | 4.4.12                                   |
现在的版本已经启用gzip, 而是转向引用http_compression
https://wiki.swoole.com/wiki/page/973.html， 
php --ri swoole|grep zlib 可民正常打印出相应的版本信息的，这个扩展默认也是安装有的，zlib => 1.2.7
这个代码应该要修改的，是个版本兼容问题
