### ISSUE TITLE
 使用 jwt 时，auth 获取当前登录用户有问题。

### ISSUE THREAD

**Issue by terranc** [hhxsv5/laravel-s#50]
1. Tell us your PHP version(`php -v`)

PHP 7.1.8 

2. Tell us your Swoole version(`php --ri swoole`)

4.0.0-alpha

3. Tell us your `Laravel`/`Lumen` version(check composer.json & composer.lock)

Laravel 5.6

4. Detail description about this issue(error/log)

不是用 laravels 是一切正常的，但是用后，每运行一段时间，jwt 的接口就会出现401，jwt 的 token 是新声称的（jwt的 token 是新生成的）。
尝试过把`reactor_num`和`worker_num`设置成`1`，没有解决问题。

5. Give us a `reproducible` code block and `steps`

middleware
```php
public function handle($request, Closure $next)
    {

        $admin = auth()->user();

        try {
            // ...
        } catch (\Exception $e) {
			// 每次会走进来这里
            throw new BadRoleException();
        }

        return $next($request);
    }
```

laravels.php
```php
        'daemonize'          => env('LARAVELS_DAEMONIZE', true),
        'dispatch_mode'      => 1,
        'reactor_num'        => 1,
        'worker_num'         => 1,
        'task_ipc_mode'      => 3,
        'task_max_request'   => 3000,
        'task_tmpdir'        => @is_writable('/dev/shm/') ? '/dev/shm' : '/tmp',
        'message_queue_key'  => ftok(base_path('public/index.php'), 1),
        'max_request'        => 3000,
        'open_tcp_nodelay'   => true,
        'pid_file'           => storage_path('laravels.pid'),
        'log_file'           => storage_path(sprintf('logs/swoole-%s.log', date('Y-m'))),
        'log_level'          => 5,
        'document_root'      => base_path('public'),
        'buffer_output_size' => 32 * 1024 * 1024,
        'socket_buffer_size' => 128 * 1024 * 1024,
        'reload_async'       => true,
        'max_wait_time'      => 60,
        'enable_reuse_port'  => true,
```

**Comment by igo9go** [comment]
使用jwt，二个用户同时请求这个返回结果都一样了，二个人的信息是不一样的

**Comment by hhxsv5** [comment]
@igo9go 在配置中重新注册下ServiceProvider即可，[here](https://github.com/hhxsv5/laravel-s/blob/master/README-CN.md#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9)

**Comment by PeteLuo** [comment]
我使用jwt也是有同样问题，两个用户同时请求两个人的信息就会变成一样的，register_providers已经添加了JWT的JWTAuthServiceProvider。
![image](https://user-images.githubusercontent.com/18900661/45070563-6490d900-b104-11e8-9425-e5c8f76fcbd9.png)

系统环境：Ubuntu16.04
JWT："tymon/jwt-auth": "^0.5.12"
laravel-s："hhxsv5/laravel-s": "~3.0"

**Comment by terranc** [comment]
@PeteLuo 我最后还是换成https://github.com/swooletw/laravel-swoole来解决的，不过貌似它们也是有需要配置重新注册的provider，最后我的配置是：
```php
        Illuminate\Auth\AuthServiceProvider::class,
        App\Providers\AuthServiceProvider::class,
        Tymon\JWTAuth\Providers\LaravelServiceProvider::class,
```

你可以在laravel-s里尝试一下把这些都重新注册下

**Comment by Barbery** [comment]
上线前手贱升级了laravels的版本，发现最新的V3.1.0设置了register_provider还是不行，auth实例还是被cache起来了，没有被清除掉。配置不变，换回V2.0.7又一切正常。 @hhxsv5

**Comment by Barbery** [comment]
已解决该问题，说下我的方法：
auth的对象没有释放的问题，对比了下代码和调试，似乎新版本是https://github.com/hhxsv5/laravel-s/blob/v2.0.7/src/Illuminate/Laravel.php#L152 这里没了Facade::clearResolvedInstance auth这个对象，我监听了laravels.received_request事件后，手动clear auth对象就正常了

**Comment by Eli-jah** [comment]
Problem solved partially, at least by now. Here is the solution:

Coding @ config/laravels.php as follows:

'register_providers' => [
        /* middleware service providers */
        Dingo\Api\Provider\DingoServiceProvider::class,
        Dingo\Api\Provider\HttpServiceProvider::class,
        /* auth service providers */
        Illuminate\Auth\AuthServiceProvider::class,
        App\Providers\AuthServiceProvider::class,
        Tymon\JWTAuth\Providers\LaravelServiceProvider::class,
],

Git it a try, and wish it would work for you, too.

**Comment by hhxsv5** [comment]
@Yoruchiaki 不要乱试了，先跟踪下代码找到User数据缓存在哪里了，再看情况清理对应对象或属性即可。因为各个版本Laravel 存储User数据位置不一样，不能给出一个很完美的解决方案，需要根据自己情况处理。

`反正核心思想就是要清理这些被缓存的数据。`

```php
class AuthManger
{
      private $user;
      public function getUser()
      {
          if (is_null($this->user)) {
             $this->user = $this->findUser($sessionId);
          }
          return $this->user;
      }
}

$this->app->singleton('auth', function ($app) {
    return new AuthManager($app);
});
```

将AuthManger注册为单例后，每个Swoole Worker进程内都会有一个这样的单例。同一进程内，上次请求存储的用户数据，其他请求就会读取到这个用户数据，所以需要每次请求开始 或 结束 清理对应的单例或成员数据。

**Comment by flymorn** [comment]
解决方法：
第一步：config/laravels.php
```
'register_providers' => [
        // 重载auth相关服务
        \Illuminate\Auth\AuthServiceProvider::class,
        \App\Providers\AuthServiceProvider::class,
        \Tymon\JWTAuth\Providers\LaravelServiceProvider::class,
    ]
```

第二步，建立全局中间件  EveryRequest.php
```
public function handle($request, Closure $next)
    {
        // swoole请求进来的时候删掉缓存
        if (PHP_SAPI == 'cli') {
            \Illuminate\Support\Facades\Facade::clearResolvedInstance('auth');// swoole下解决auth单例问题
        }

        return $next($request);
    }
```

以上2步缺一不可

**Comment by dafa168** [comment]
这个全局中间件设置了但是没啥效果。@flymorn

**Comment by hhxsv5** [comment]
@all After a week of debugging, I have passed the test locally for the Laravel/Lumen 5.1-5.8 user authorization. Please try the `Master` branch code(`composer require hhxsv5/laravel-s:dev-master -vvv`), if there is no problem, I will release v3.4.0, thanks for your support.

**Comment by hhxsv5** [comment]
And you need to republish configuration `php artisan laravels publish`.

**Comment by hhxsv5** [comment]
[v3.4.0](https://github.com/hhxsv5/laravel-s/releases/tag/v3.4.0)

**Comment by pensacola1989** [comment]
Hi，已经更新到了3.4.1，依然有问题。。。

```bash
hhxsv5/laravel-s                    v3.4.1             🚀LaravelS is a glue that is used to quickly integrate Swoole into Laravel or Lumen and then give them be...

```

**Comment by hhxsv5** [comment]
根据实际情况[打开这些注释](https://github.com/hhxsv5/laravel-s/blob/master/config/laravels.php#L44)
