### ISSUE TITLE
使用laravel-admin配合laravels导出文件时报错

### ISSUE THREAD

**Issue by methzeal** [hhxsv5/laravel-s#53]
1. Tell us your PHP version(`php -v`)
7.2.5

2. Tell us your Swoole version(`php --ri swoole`)
2.1.3

3. Tell us your `Laravel`/`Lumen` version(check composer.json & composer.lock)
5.6.21

4. Detail description about this issue(error/log)
用laravels做http服务器，在使用laravel-admin后台导出cvs文件时报错500
laravels log会记录文件信息
而使用nginx则会直接输出cvs文件以供下载

laravels输出格式问题吗？

5. Give us a `reproducible` code block and `steps`

```

**Comment by hhxsv5** [comment]
请提供可重现的代码示例。

**Comment by hhxsv5** [comment]
swoole http server模式下 不能使用header()函数，需使用Laravel Response对象设置header。

**Comment by never615** [comment]
楼主解决了吗?
父laravel-admin原库的导出代码:
```
    public function export()
    {
        $filename = $this->getTable().'.csv';

        $headers = [
            'Content-Encoding'    => 'UTF-8',
            'Content-Type'        => 'text/csv;charset=UTF-8',
            'Content-Disposition' => "attachment; filename=\"$filename\"",
        ];

        response()->stream(function () {
            $handle = fopen('php://output', 'w');

            $titles = [];

            $this->chunk(function ($records) use ($handle, &$titles) {
                if (empty($titles)) {
                    $titles = $this->getHeaderRowFromRecords($records);

                    // Add CSV headers
                    fputcsv($handle, $titles);
                }

                foreach ($records as $record) {
                    if ($record) {
                        fputcsv($handle, $this->getFormattedRecord($record));
                    }
                }
            });

            // Close the output stream
            fclose($handle);
        }, 200, $headers)->send();

        exit;
    }
```

**Comment by hhxsv5** [comment]
[源代码 Export](https://github.com/z-song/laravel-admin/blob/3ef35ab2ec669ceb38b20b201538d4200f478869/src/Grid/Exporters/CsvExporter.php#L15)
Swoole下不能用 `exit`，目前来看，你可以自己写个类，继承自`CsvExporter`，覆盖父类的`export`方法，这个方法中使用`Laravel`的[StreamDownload](https://learnku.com/docs/laravel/5.8/responses/3895#9313a4)`输出csv的内容`，然后返回这个$response对象，交给上层`Controller`响应。

**Comment by hhxsv5** [comment]
你得升级下LaravelS，刚刚才支持[StreamedResponse](https://github.com/hhxsv5/laravel-s/commit/103986a614e3112fce0c88b8cc52691e745baa19)。

**Comment by never615** [comment]
使用StreamedResponse,laravel-admin可以导出,同时需要修改laravel-admin基础源码:https://github.com/z-song/laravel-admin/pull/3527
