### ISSUE TITLE
事务中嵌套事务使用会报错

### ISSUE THREAD

**Issue by yumotingfeng** [hhxsv5/laravel-s#55]
1. Tell us your PHP version(`php -v`)
7.2.6
`TODO`

2. Tell us your Swoole version(`php --ri swoole`)
4.0.0
`TODO`

3. Tell us your `Laravel`/`Lumen` version(check composer.json & composer.lock)
5.5.33
`TODO`

4. Detail description about this issue(error/log)
error
`TODO`

5. Give us a `reproducible` code block and `steps`

```PHP
//TODO: Your code
```
public function test (Request $request)
    {
        $data = DB::transaction(function (){
            return DB::transaction(function (){
                return ['a' => 1];
            });
        });
        return $this->apiResponse(0, "success", $data);
    }

**Comment by hhxsv5** [comment]
Fixed in [v2.0.2](https://github.com/hhxsv5/laravel-s/releases/tag/v2.0.2)
