### ISSUE TITLE
$swoole = app('swoole'); 报错 Class swoole does not exist

### ISSUE THREAD

**Issue by cnbeir** [hhxsv5/laravel-s#62]
1. Tell us your PHP version(`php -v`)

7.2.5

2. Tell us your Swoole version(`php --ri swoole`)

2.0.7

3. Tell us your `Laravel`/`Lumen` version(check composer.json & composer.lock)

5.6.24

4. Detail description about this issue(error/log)

在Controller中，调用 $swoole = app('swoole'); 报错 Class swoole does not exist

**Comment by hhxsv5** [comment]
很可能你还在FPM环境下。

```PHP
var_dump($_SEVER['SERVER_SOFTWARE']);
```

确保是使用的`swoole-http-server`。

**Comment by hhxsv5** [comment]
是的，LaravelS start后会启动swoole_http_server，不再需要FPM。可直连，也可Nginx反向代理。

**Comment by hhxsv5** [comment]
默认情况swoole监听127.0.0.1:5200，可直接请求http://127.0.0.1:5200

**Comment by cnbeir** [comment]
配置好了后，报了Controller不存在的错误，麻烦再帮我看一下，谢谢
ReflectionException (-1)
Class App\Http\Controllers\IndexController does not exist
nginx的root指向项目的public目录，我甚至吧public/index.php 里面内容都注释掉 也还是报这个错误
laravels已经restart试过了 还是一样

**Comment by cnbeir** [comment]
nginx配置 就是按照你的示例一样配置的

**Comment by hhxsv5** [comment]
LaravelS不会执行public/index.php。类不存在，请检查类名与文件名完全一致。若还不能解决，加QQ群细聊：698480528
