### ISSUE TITLE
使用dingoApi出现的问题

### ISSUE THREAD

**Issue by shengtaolee** [hhxsv5/laravel-s#64]
1. Tell us your PHP version(`php -v`)
v7.2.1

2. Tell us your Swoole version(`php --ri swoole`)
v2.2.0

3. Tell us your `Laravel`/`Lumen` version(check composer.json & composer.lock)

lumen v5.5.2

4. Detail description about this issue(error/log)

使用了dingoapi,并对接口进行限流1分钟60次,使用postman快速请求一定次数之后就会报错,事实上都不需要达到限流次数就开始报错了.

5. Give us a `reproducible` code block and `steps`
return $this->response->collection($items, new AdvertsTransformer());
就是一个简单的接口返回,使用了dingo的transformer,当快速请求多次之后就会报这个错误

Type error: Argument 1 passed to Dingo\\Api\\Http\\RateLimit\\Handler::rateLimitRequest() must be an instance of Dingo\\Api\\Http\\Request, instance of Illuminate\\Http\\Request given, called in /xxxx/vendor/dingo/api/src/Http/Middleware/RateLimit.php on line 64

```PHP
//TODO: Your code
```

**Comment by shengtaolee** [comment]
如果方便的话,可以加下QQ吗?

**Comment by hhxsv5** [comment]
目前dingo api还存在兼容性问题，要限流建议使用[ThrottleRequests](https://github.com/laravel/framework/blob/5.6/src/Illuminate/Routing/Middleware/ThrottleRequests.php)。有交流群：698480528

**Comment by shengtaolee** [comment]
好的,谢谢
