### ISSUE TITLE
Can i change WebSocket ping timeout? Just like laravel-swoole

### ISSUE THREAD

**Issue by tinfot** [hhxsv5/laravel-s#65]
1. Tell us your PHP version(`php -v`)

`7.2.3`

2. Tell us your Swoole version(`php --ri swoole`)

`4.0.1`

3. Tell us your `Laravel`/`Lumen` version(check composer.json & composer.lock)

`5.6.26`

4. Detail description about this issue(error/log)

How can i change websocket connection ping timeout?

5. Give us a `reproducible` code block and `steps`

Code copy from `swoole_websocket.php` and  Laravel-swoole:
```PHP
/*
    |--------------------------------------------------------------------------
    | Websocket client's heartbeat interval timeout (ms)
    |--------------------------------------------------------------------------
    */
    'ping_timeout' => 60000,
```

**Comment by hhxsv5** [comment]
Sure, it's Swoole's configuration, see [heartbeat](https://www.swoole.co.uk/docs/modules/swoole-server/configuration).
Modify config/laravels.php, eg:
```PHP
[
    //...
    'swoole'             => [
            //...
          'heartbeat_idle_time' => 600,
          'heartbeat_check_interval' => 60,
    ],
]
```

**Comment by tinfot** [comment]
Thanks bro.

**Comment by oknixus** [comment]
这里还需要设置在`nginx`中设置 `proxy_read_timeout 60s`，默认是60s

**Comment by hhxsv5** [comment]
@oknixus 是的，这个[Nginx文档](https://github.com/hhxsv5/laravel-s/blob/master/README-CN.md#%E5%90%AF%E7%94%A8websocket%E6%9C%8D%E5%8A%A1%E5%99%A8)中也有提及。
