### ISSUE TITLE
准备用laravel-s加速 octobercms时报错。请求协助！

### ISSUE THREAD

**Issue by Johnzero** [hhxsv5/laravel-s#68]
http://octobercms.com 是基于laravel开发的cms系统。性能一直是个比较大的问题。想用laravel-s加速框架运行，发现很多错误！请大神看下什么问题。(https://github.com/octobercms)

**Comment by hhxsv5** [comment]
1. 对照[注意事项](https://github.com/hhxsv5/laravel-s/blob/master/README-CN.md#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9) 检查。
2.提供详细的报错信息。

**Comment by hhxsv5** [comment]
本地测试后，除了因`public/index.php`文件不存在而导致的`ftok`错误之外，没有发现其他错误。
```PHP
// 修改laravels.php
'message_queue_key'  => ftok(base_path('index.php'), 1),
```

**Comment by hhxsv5** [comment]
`octobercms`对`Laravel`改动执行流程改动较大，不建议结合`LaravelS`使用。
