### ISSUE TITLE
这个框架里含有阻塞代码吗？

### ISSUE THREAD

**Issue by gouchaoer** [hhxsv5/laravel-s#69]
能兼容laravel很好，问题是协程/异步中不能使用任何阻塞的代码，数据库、redis以及rpc等都不能是阻塞的，但是我并没有看到有协程客户端封装，如果用的laravel原生的就会有问题吧

阻塞在一个fpm worker处理一个http请求中没问题，但会导致同时处理很多http请求的swoole worker下别的http请求得不到调度。。。测试方法为你在逻辑的sql里这么写“select sleep(1）”这样模拟重一点的阻塞

**Comment by boneq** [comment]
@hhxsv5 php协程是个暂存的方式吧，这个得用类似进程池的方式吧
进程池一般有大小和最少保持的，在我个人感觉一次的请求所造成的sql操作可以在池中用不同的sql也是可以的，使用完成sql后马上放回池中而不是释放sql连接
可以异步到一个进程中，这个进程来处理全局的sql操作，这个进程实例最少个未使用的保持sql连接，也不能多于最大数量

或者也可以是一个用户请求一次所有的sql占用一个连接，这样会容易使用完所有的连接

**Comment by oknixus** [comment]
> * 现在是同步阻塞的，Laravel相比在FPM下最大的提升是常驻内存，然后可以使用Swoole的很多特性，例如WebSocket Server、异步任务、定时器等等。
> * 目前没有引入异步客户端的计划，也不打算引入，用`协程`代替。
> * `协程MySQL`这是目前在攻克的一个难题，因为在Laravel中数据库连接是`单例`的，不能实现并发调用，正在引入`连接池`来解决。

老哥，请问有引入连接池了吗？

**Comment by hhxsv5** [comment]
@boneq 从生产环境使用看来，使用`持久连接`即可，无需连接池。

**Comment by Stone-ChenLijun** [comment]
老哥，我在生产环境用了这个，有很多数据卡在事务中，无法提交。我在A接口开启了一个事务，因为异常，事务没有正常关闭。然后有人开始在调用其他接口，这些其他接口创建了很多数据，但是这些数据没有直接出现在数据库中，而是卡在那个之前那个事务中。因为laravels的服务没有重启，那个事务就一直卡在Running状态，没有人能commit他。然后出现问题后，那些卡在事务里的数据非常重要，不能丢，手动恢复又非常难。

我现在陷入了两难的境地，想问下有没有什么解决方案。

**Comment by hhxsv5** [comment]
@Stone-ChenLijun 这属于规范问题。FPM下每个请求全新建立的数据库连接，之前请求没正常关闭的事务都会因断开连接而关闭；而Swoole常驻内存下，目的就是为了复用资源，复用数据库连接，需要规范的事务处理，确保每个事务都要Commit或Rollback。实在不行，你可以写个Cleaner，检测所有的数据库连接，如果事务未关闭，执行Rollback。

**Comment by Stone-ChenLijun** [comment]
@hhxsv5 我其实是有做的，但是我catch的是Exception，但经过测试，catch Exception无法捕获语法致命错误，比如以下这种代码
```php
try {
  DB::beginTransaction();
  $a = User::find(1);  // $a结果为null，这里可能是个复杂的逻辑
  $a->name; // 抛出致命问题，$a is null
  DB::commit();
} catch (\Exception $e) {
  // 这里的catch实际上无法捕获到null的这种Exception，但改成Throwable是可以捕获到的，现在我已经改成这种写法了。
  DB::rollBack();
  // 报告异常
}
```

另外还有一个问题，我这边有某个查询sql因为还没优化的问题，导致sql执行时间过长达到分钟级。而后续其他的查询sql好像被前面这个耗时sql堵塞住了，没有直接返回结果，等前面这个sql执行完了，后面这个sql才开始执行，过程中也没有用事务，锁数据库。

**Comment by chenbaba** [comment]
`  try {
            $pattern = '/Message\(\"(.*?)\"\)(\\r\\n|\\r|\\n)/U';
            preg_match($pattern, $comment, $result);
        } catch (\Throwable $e) {
            return false;
        }`
在php5.6之后 ,最建议还是使用Throwable 

阻塞问题,在原生的swoole下是可以用协程解决,但是目前laravels没做到全面兼容.
文档也给到了具体的介绍
![image](https://user-images.githubusercontent.com/20589437/128486779-a9c10581-228f-40ea-9a77-b3cf17ec4527.png)
