### ISSUE TITLE
Laradock + laravel-s got 502 Bad Gateway Error in a web browser

### ISSUE THREAD

**Issue by adon988** [hhxsv5/laravel-s#71]
1. Tell us your PHP version(`php -v`)

    php7.2

2. Tell us your Swoole version(`php --ri swoole`)

    Version => 4.0.3

3. Tell us your `Laravel`/`Lumen` version(check composer.json & composer.lock)

    Laravel Framework 5.6.29

4. Detail description about this issue(error/log)

    When I used [laradock](http://laradock.io/) as environment running laravel-s ~ 

    each step is fine~ but when I visit homepage

    Get  **502 Bad Gateway** error in web browser.

   Is anyone also used laradock and laravel-s to build project? Who can help me~ 

5. Give us a `reproducible` code block and `steps`
lar
    Here is my nginx conf

```
map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}
upstream laravels {
    # By IP:Port
    server 127.0.0.1:5200 weight=5 max_fails=3 fail_timeout=30s;
    # By UnixSocket Stream file
    #server unix:/xxxpath/laravel-s-test/storage/laravels.sock weight=5 max_fails=3 fail_timeout=30s;
    #server 192.168.1.1:5200 weight=3 max_fails=3 fail_timeout=30s;
    #server 192.168.1.2:5200 backup;
}
server {
    listen 80;
    server_name laravels.oo;
    root /var/www/laravels/public;
    # access_log /var/log/$server_name.access.log  main;
    autoindex off;
    index index.html index.htm;
    # Nginx handles the static resources(recommend enabling gzip), LaravelS handles the dynamic resource.
    location / {
        try_files $uri @laravels;
    }
    # Response 404 directly when request the PHP file, to avoid exposing public/*.php
    #location ~* \.php$ {
    #    return 404;
    #}
    # Http and WebSocket are concomitant, Nginx identifies them by "location"
    # Javascript: var ws = new WebSocket("ws://laravels.com/ws");
    location =/ws {
        proxy_http_version 1.1;
        # proxy_connect_timeout 60s;
        # proxy_send_timeout 60s;
        # proxy_read_timeout: Nginx will close the connection if the proxied server does not send data to Nginx in 60 seconds; At the same time, this close behavior is also affected by heartbeat setting of Swoole.
        # proxy_read_timeout 60s;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Real-PORT $remote_port;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_set_header Scheme $scheme;
        proxy_set_header Server-Protocol $server_protocol;
        proxy_set_header Server-Name $server_name;
        proxy_set_header Server-Addr $server_addr;
        proxy_set_header Server-Port $server_port;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_pass http://laravels;
    }
    location @laravels {
        proxy_http_version 1.1;
        # proxy_connect_timeout 60s;
        # proxy_send_timeout 60s;
        # proxy_read_timeout 60s;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Real-PORT $remote_port;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_set_header Scheme $scheme;
        proxy_set_header Server-Protocol $server_protocol;
        proxy_set_header Server-Name $server_name;
        proxy_set_header Server-Addr $server_addr;
        proxy_set_header Server-Port $server_port;
        proxy_pass http://laravels;
    }
}
```

**Comment by hhxsv5** [comment]
It may be that the network between the two containers is `unreachable`. Try modifying the listening ip to `0.0.0.0`.

**Comment by adon988** [comment]
Thanks for reply~ but still not working. Page still show 502 Bad Gateway message~ @@

**Comment by hhxsv5** [comment]
'server 127.0.0.1:5200 weight=5 max_fails=3 fail_timeout=30s;'

Try:
make a link from Nginx container to PHP container, then
change this ip of upstream to your PHP container name.

**Comment by wokill** [comment]
nginx 与php在同一个容器当中，且已经更改监听地址为0.0.0.0 。但是依然是这样的情况。。

**Comment by reallovelei** [comment]
10.12.90.238 - - [03/Aug/2018:22:44:25 +0800] "GET /api/ab/index HTTP/1.0" 200 57 "-" "ApacheBench/2.3" "-""0.111" "0.111"
10.12.90.238 - - [03/Aug/2018:22:44:25 +0800] "GET /api/ab/index HTTP/1.0" 200 57 "-" "ApacheBench/2.3" "-""0.131" "0.131"
10.12.90.238 - - [03/Aug/2018:22:44:25 +0800] "GET /api/ab/index HTTP/1.0" 200 57 "-" "ApacheBench/2.3" "-""0.155" "0.155"
10.12.90.238 - - [03/Aug/2018:22:44:25 +0800] "GET /api/ab/index HTTP/1.0" 502 179 "-" "ApacheBench/2.3" "-""0.000" "0.000"
10.12.90.238 - - [03/Aug/2018:22:44:25 +0800] "GET /api/ab/index HTTP/1.0" 502 179 "-" "ApacheBench/2.3" "-""0.000" "0.000"
10.12.90.238 - - [03/Aug/2018:22:44:25 +0800] "GET /api/ab/index HTTP/1.0" 502 179 "-" "ApacheBench/2.3" "-""0.000" "0.000"
10.12.90.238 - - [03/Aug/2018:22:44:25 +0800] "GET /api/ab/index HTTP/1.0" 502 179 "-" "ApacheBench/2.3" "-""0.000" "0.000"
10.12.90.238 - - [03/Aug/2018:22:44:25 +0800] "GET /api/ab/index HTTP/1.0" 502 179 "-" "ApacheBench/2.3" "-""0.000" "0.000"
10.12.90.238 - - [03/Aug/2018:22:44:25 +0800] "GET /api/ab/index HTTP/1.0" 502 179 "-" "ApacheBench/2.3" "-""0.000" "0.000"
10.12.90.238 - - [03/Aug/2018:22:44:25 +0800] "GET /api/ab/index HTTP/1.0" 502 179 "-" "ApacheBench/2.3" "-""0.000" "0.000"
10.12.90.238 - - [03/Aug/2018:22:44:25 +0800] "GET /api/ab/index HTTP/1.0" 502 179 "-" "ApacheBench/2.3" "-""0.000" "0.000"
10.12.90.238 - - [03/Aug/2018:22:44:25 +0800] "GET /api/ab/index HTTP/1.0" 502 179 "-" "ApacheBench/2.3" "-""0.000" "0.000"
10.12.90.238 - - [03/Aug/2018:22:44:25 +0800] "GET /api/ab/index HTTP/1.0" 502 179 "-" "ApacheBench/2.3" "-""0.000" "0.000"
10.12.90.238 - - [03/Aug/2018:22:44:25 +0800] "GET /api/ab/index HTTP/1.0" 502 179 "-" "ApacheBench/2.3" "-""0.000" "0.000"
10.12.90.238 - - [03/Aug/2018:22:44:25 +0800] "GET /api/ab/index HTTP/1.0" 502 179 "-" "ApacheBench/2.3" "-""0.000" "0.000"
10.12.90.238 - - [03/Aug/2018:22:44:25 +0800] "GET /api/ab/index HTTP/1.0" 502 179 "-" "ApacheBench/2.3" "-""0.000" "0.000"
10.12.90.238 - - [03/Aug/2018:22:44:25 +0800] "GET /api/ab/index HTTP/1.0" 502 179 "-" "ApacheBench/2.3" "-""0.000" "0.000"
10.12.90.238 - - [03/Aug/2018:22:44:25 +0800] "GET /api/ab/index HTTP/1.0" 502 179 "-" "ApacheBench/2.3" "-""0.000" "0.000"
10.12.90.238 - - [03/Aug/2018:22:44:25 +0800] "GET /api/ab/index HTTP/1.0" 502 179 "-" "ApacheBench/2.3" "-""0.000" "0.000"
10.12.90.238 - - [03/Aug/2018:22:44:25 +0800] "GET /api/ab/index HTTP/1.0" 502 179 "-" "ApacheBench/2.3" "-""0.000" "0.000"
10.12.90.238 - - [03/Aug/2018:22:44:25 +0800] "GET /api/ab/index HTTP/1.0" 502 179 "-" "ApacheBench/2.3" "-""0.000" "0.000"
10.12.90.238 - - [03/Aug/2018:22:44:25 +0800] "GET /api/ab/index HTTP/1.0" 502 179 "-" "ApacheBench/2.3" "-""0.000" "0.000"
10.12.90.238 - - [03/Aug/2018:22:44:25 +0800] "GET /api/ab/index HTTP/1.0" 502 179 "-" "ApacheBench/2.3" "-""0.000" "0.000"
10.12.90.238 - - [03/Aug/2018:22:44:25 +0800] "GET /api/ab/index HTTP/1.0" 502 179 "-" "ApacheBench/2.3" "-""0.000" "0.000"
10.12.90.238 - - [03/Aug/2018:22:44:25 +0800] "GET /api/ab/index HTTP/1.0" 502 179 "-" "ApacheBench/2.3" "-""0.000" "0.000"
10.12.90.238 - - [03/Aug/2018:22:44:25 +0800] "GET /api/ab/index HTTP/1.0" 502 179 "-" "ApacheBench/2.3" "-""0.000" "0.000"
10.12.90.238 - - [03/Aug/2018:22:44:25 +0800] "GET /api/ab/index HTTP/1.0" 502 179 "-" "ApacheBench/2.3" "-""0.000" "0.000"
10.12.90.238 - - [03/Aug/2018:22:44:25 +0800] "GET /api/ab/index HTTP/1.0" 502 179 "-" "ApacheBench/2.3" "-""0.000" "0.000"
10.12.90.238 - - [03/Aug/2018:22:44:25 +0800] "GET /api/ab/index HTTP/1.0" 502 179 "-" "ApacheBench/2.3" "-""0.000" "0.000
同样的问题 好多502

**Comment by KaramanisWeb** [comment]
Laradock is using different containers for your workspace and nginx.
* Swoole server will run in Workspace container.
* Nginx server runs in the Nginx container.

Now in the nginx configuration file your proxy_pass should point to the workspace container IP address.

Example:
```
upstream laravels {
    server 172.19.0.5:5200 weight=5 max_fails=3 fail_timeout=30s;
}
```

To find out the IP address of your workspace container do the following: 

`docker ps` to see the list of your active containers, then

`docker inspect YOUR_WORKSPACE_CONTAINER_ID_HERE`
to inspect the container and in the NetworkSettings search for the backend network there you will find the IP address you should use.

**Comment by sowork** [comment]
@KaramanisWeb Every time you restart the IP will change. Is there any solution?

**Comment by KaramanisWeb** [comment]
@sowork 

You have 2 other options:

1.  **_The one you already mentioned define network aliases on the Workspace container, example:_**

```
      networks:
        frontend:
            aliases:
                - workspace.dev
        backend:
            aliases:
                - workspace.dev
```
and on the project nginx configuration you use it like this:
```
upstream laravels {
    server workspace.dev:5200 weight=5 max_fails=3 fail_timeout=30s;
}
```

2. **_The other one is to expose the workspace 5200 port, example:_**
```
      ports:
        - "${WORKSPACE_SSH_PORT}:22"
        - "5200:5200"
```

and on the project nginx configuration you use it (with docker host IP) like this:
```
upstream laravels {
    server 10.0.75.1:5200 weight=5 max_fails=3 fail_timeout=30s;
}
