### ISSUE TITLE
coroutine mysql error when using orderByRaw?  double quotes ?

### ISSUE THREAD

**Issue by scil** [hhxsv5/laravel-s#72]
1. Tell us your PHP version(`php -v`)

7.1

2. Tell us your Swoole version(`php --ri swoole`)

4.0.2

3. Tell us your `Laravel`/`Lumen` version(check composer.json & composer.lock)

Laravel 5.6

4. Detail description about this issue(error/log)

when query expression contains 'orderByRaw', error occurs.

5. Give us a `reproducible` code block and `steps`

```PHP
// file : routes/web.php

Route::get('/test', function () {

    Schema::dropIfExists('test_articles');

    Schema::create('test_articles', function ($table) {
        $table->enum('type', ['first', 'normal', 'note']);
    }
    );
    $items = [
        ['type' => 'first'],
        ['type' => 'note'],
        ['type' => 'first'],
        ['type' => 'normal'],
        ['type' => 'first'],
    ];

    foreach ($items as $item) {
        \DB::table('test_articles')->insert($item);
    }

    return \DB::table('test_articles')

        // orderbyRaw produce error when   'driver' => 'sw-co-mysql',
        ->orderByRaw("FIELD(type, \"first\", \"normal\", \"note\")")

         // orderBy works well
        // ->orderBy('type')

        ->get(['type',]);

});
```

when  'driver' => 'sw-co-mysql',
 orderbyRaw produce error :

 Illuminate \ Database \ QueryException (1054)
Unknown column 'first' in 'order clause' (SQL: select `type` from `test_articles` order by FIELD(type, "first", "normal", "note")) (SQL: select `type` from `test_articles` order by FIELD(type, "first", "normal", "note"))

**Comment by hhxsv5** [comment]
The problem you mentioned can be fixed, remove the double quotes.

**Comment by scil** [comment]
You are right!

Thank you!
