### ISSUE TITLE
关于 PID 文件的合理存放路径

### ISSUE THREAD

**Issue by wi1dcard** [hhxsv5/laravel-s#78]
1. Tell us your PHP version(`php -v`)

doesn't matter

2. Tell us your Swoole version(`php --ri swoole`)

doesn't matter

3. Tell us your `Laravel`/`Lumen` version(check composer.json & composer.lock)

doesn't matter

4. Detail description about this issue(error/log)

是否考虑将默认 pid 文件移动到 `storage/framework/laravels.pid` 内？因为默认 laravel 项目的 storage 文件夹是没有被 git ignore 的，开发的时候需要手动创建一下 .gitignore，似乎不太友好。

5. Give us a `reproducible` code block and `steps`

```PHP
// config/laravels.php
return [
    // ...
    'swoole' => [
        'pid_file' => storage_path('laravels.pid'),
    ],
    //...
];
```

**Comment by hhxsv5** [comment]
似乎都没有ignore https://github.com/laravel/laravel/blob/master/.gitignore

**Comment by wi1dcard** [comment]
@hhxsv5 在这里：<https://github.com/laravel/laravel/blob/master/storage/framework/.gitignore>

**Comment by wi1dcard** [comment]
不过，放在缓存目录感觉也有点怪，大佬斟酌吧，萌新瑟瑟发抖

**Comment by hhxsv5** [comment]
呃 framework下的.gitignore也需要加上pidfile配置，你是想避免手动建.gitignore?

**Comment by wi1dcard** [comment]
没，想到的一个小提议而已，没什么多大关系，先close吧
