### ISSUE TITLE
ERROR	zm_deactivate_swoole (ERROR 503)

### ISSUE THREAD

**Issue by bornli** [hhxsv5/laravel-s#79]
1. Tell us your PHP version(`php -v`)

7.1.7

2. Tell us your Swoole version(`php --ri swoole`)

2.2.0

3. Tell us your `Laravel`/`Lumen` version(check composer.json & composer.lock)

Lumen (5.4.7)

4. Detail description about this issue(error/log)

1、启动 php artisan laravels  start  -d
2、curl http://127.0.0.1:5200

报错：

[2018-08-28 18:38:24 *12547.4]	ERROR	zm_deactivate_swoole (ERROR 503): Fatal error: Uncaught Error: __clone method called on non-object in /data/home/bornli/wwwroot/ctp-core/vendor/hhxsv5/laravel-s/src/Illuminate/Laravel.php:326
Stack trace:
#0 /data/home/bornli/wwwroot/ctp-core/vendor/hhxsv5/laravel-s/src/LaravelS.php(121): Hhxsv5\LaravelS\Illuminate\Laravel->__clone()
#1 {main}
  thrown in /data/home/bornli/wwwroot/ctp-core/vendor/hhxsv5/laravel-s/src/Illuminate/Laravel.php on line 326.
[2018-08-28 18:38:24 $12513.0]	WARNING	swManager_check_exit_status: worker#4 abnormal exit, status=255, signal=0
[2018-08-28 18:38:24] [ERROR] LaravelS: worker[4] error: exitCode=255, signal=0

5. Give us a `reproducible` code block and `steps`

**Comment by bornli** [comment]
更换到  hhxsv5/laravel-s     2.0.7  版本就可以

**Comment by hhxsv5** [comment]
用最新版 3.0。

**Comment by bornli** [comment]
最开始使用的就是3.0  ，然后报错，用2.0就好了

**Comment by hhxsv5** [comment]
`3.0` 需要`Swoole>=4.1.0`

**Comment by hhxsv5** [comment]
我本地没复现。`onWorkerStart`时初始化`$this->laravel`成员，`onRequest`时`clone`该对象，正常情况`$this->laravel`一定是有值的。可否发一份能重现问题的精简包？

**Comment by KaramanisWeb** [comment]
Just made a pull request for the fix.

The issue was in `Illuminate\Laravel.php` in `__clone` method, in lumen projects it should not try to clone the Laravels kernel since its a null object and will throw the error reported above.

**Comment by hhxsv5** [comment]
@KaramanisWeb Thanks.

see v3.0.1

**Comment by bornli** [comment]
It's ok,thanks
