### ISSUE TITLE
为什么装3.0的时候找不到包，2.0没问题？

### ISSUE THREAD

**Issue by minxinqing** [hhxsv5/laravel-s#81]
1. Tell us your PHP version(`php -v`)

7.2.2

2. Tell us your Swoole version(`php --ri swoole`)

4.1

3. Tell us your `Laravel`/`Lumen` version(check composer.json & composer.lock)

laravel 5.4

4. Detail description about this issue(error/log)

 [InvalidArgumentException]
  Could not find package hhxsv5/laravel-s in a version matching ~3.0

**Comment by hhxsv5** [comment]
你可能使用的[Composer中国镜像](https://pkg.phpcomposer.com/)，该镜像于7月暂停更新了。
查看项目所使用的镜像源：`composer config --list|grep repositories`

目前可使用[Laravel-China的Composer镜像](https://laravel-china.org/composer) 或默认的packagist镜像。

**Comment by minxinqing** [comment]
真的是，换laravel-china的镜像就好了

**Comment by wi1dcard** [comment]
Composer 中国镜像好像凉凉了，现在官网还挂着修复 bug 的通知

**Comment by hhxsv5** [comment]
@wi1dcard 还是希望它能坚持下来。

**Comment by hhxsv5** [comment]
阿里云Composer全量镜像：https://mirrors.aliyun.com/composer/index.html

**Comment by wi1dcard** [comment]
@hhxsv5 LearnKu 看到的吗😂

**Comment by hhxsv5** [comment]
@wi1dcard 阿里云技术群发的

**Comment by hhxsv5** [comment]
Laravel China 镜像完成历史使命，将于9月4日停用
