### ISSUE TITLE
安装包找不到，中国Composer镜像同步延迟

### ISSUE THREAD

**Issue by guchangsheng** [hhxsv5/laravel-s#82]
1. Tell us your PHP version(`php -v`)
   php7.0.2
`TODO`

2. Tell us your Swoole version(`php --ri swoole`)
 swoole   4.0.2 
`TODO`

3. Tell us your `Laravel`/`Lumen` version(check composer.json & composer.lock)
lumen5.5
`TODO`

4. Detail description about this issue(error/log)

`TODO`

5. Give us a `reproducible` code block and `steps`

```PHP
//TODO: Your code
```
##############################################

composer require "hhxsv5/laravel-s:~3.0" --ignore-platform-reqs
报以下错误 :
 - The requested package hhxsv5/laravel-s ~3.0 exists as hhxsv5/laravel-s[dev-feature/connection_pool, dev-feature/coroutine_clients, dev-master, v                                                            1.0.0, v1.0.1, v1.0.3, v1.0.4, v1.0.5, v1.0.6, v1.0.7, v1.1.0, v1.1.1, v1.1.10, v1.1.11, v1.1.2, v1.1.4, v1.1.5, v1.1.6, v1.1.7, v1.1.8, v1.1.9, v1.10                                                            .0, v1.10.1, v1.10.10, v1.10.11, v1.10.12, v1.10.13, v1.10.14, v1.10.15, v1.10.16, v1.10.17, v1.10.18, v1.10.19, v1.10.2, v1.10.3, v1.10.5, v1.10.6, v                                                            1.10.7, v1.10.8, v1.10.9, v1.11.0, v1.11.1, v1.11.2, v1.11.3, v1.2.2, v1.3.0, v1.3.1, v1.3.2, v1.3.3, v1.3.4, v1.3.5, v1.3.6, v1.4.0, v1.4.1, v1.4.2,                                                             v1.4.3, v1.5.0, v1.5.1, v1.5.2, v1.5.3, v1.6.0, v1.6.1, v1.6.10, v1.6.11, v1.6.12, v1.6.13, v1.6.2, v1.6.3, v1.6.4, v1.6.5, v1.6.6, v1.6.7, v1.6.8, v1                                                            .6.9, v1.7.0, v1.7.1, v1.7.10, v1.7.11, v1.7.12, v1.7.13, v1.7.14, v1.7.3, v1.7.4, v1.7.5, v1.7.6, v1.7.7, v1.7.8, v1.7.9, v1.8.0, v1.8.1, v1.8.10, v1                                                            .8.11, v1.8.12, v1.8.13, v1.8.14, v1.8.2, v1.8.3, v1.8.4, v1.8.5, v1.8.6, v1.8.7, v1.8.8, v1.8.9, v1.9.0, v1.9.1, v1.9.10, v1.9.11, v1.9.12, v1.9.13,                                                             v1.9.14, v1.9.15, v1.9.16, v1.9.17, v1.9.2, v1.9.4, v1.9.5, v1.9.6, v1.9.7, v1.9.8, v1.9.9, v2.0.0, v2.0.0-Alpha, v2.0.1, v2.0.2, v2.0.3, v2.0.4] but                                                             these are rejected by your constraint.

 最后用2.0版本安装成功，但项目运行遇到一些兼容性错误，

**Comment by hhxsv5** [comment]
参考 #81

**Comment by guchangsheng** [comment]
解决了，确实是这样
