### ISSUE TITLE
超全局变量获取不到

### ISSUE THREAD

**Issue by guchangsheng** [hhxsv5/laravel-s#84]
1. Tell us your PHP version(`php -v`)
php7.0.2
`TODO`

2. Tell us your Swoole version(`php --ri swoole`)
version swoole 4.0.2 
`TODO` 

3. Tell us your `Laravel`/`Lumen` version(check composer.json & composer.lock)
lumen 5.5 
`TODO`

4. Detail description about this issue(error/log)

`TODO`

5. Give us a `reproducible` code block and `steps`

```PHP
//TODO: Your code
```
        */
    public static function url()
    {

        $server = $_SERVER;

        $ssl = (!empty($server['HTTPS']) && $server['HTTPS'] == 'on');

        $sp = strtolower($server['SERVER_PROTOCOL']);

        $protocol = substr($sp, 0, strpos($sp, '/')) . (($ssl) ? 's' : '');

        $port = $server['SERVER_PORT'];

        $port = ((!$ssl && $port == '80') || ($ssl && $port == '443')) ? '' : ':' . $port;

        #var_dump($server);die;
        $host = isset($host) ? $host : $server['HTTP_HOST'] . $port;

        $host .= preg_replace("/\?.*/", "", $server["REQUEST_URI"]);

        return $protocol . '://' . $host;
    }

#使用了不少扩展包，涉及到调用$_server变量的地方会报错，读不到

**Comment by hhxsv5** [comment]
LaravelS `3.0`已废弃超级全局变量的使用，因为在协程模式下是不安全的。获取请求信息统一使用`Request`对象，响应输出统一使用`Response`对象。
[更多注意事项](https://github.com/hhxsv5/laravel-s/blob/master/README-CN.md#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9)
