### ISSUE TITLE
异步任务队列投递失败

### ISSUE THREAD

**Issue by minxinqing** [hhxsv5/laravel-s#85]
又有个新问题，我想通过“自定义进程”去监听一个消息队列，然后把队列里的任务使用“异步的任务队列”处理，结果任务全部投递失败，代码如下：
```PHP
for ($i = 0; $i < 5; $i ++) {

            $task = new MessageTask('task data' . ($i + 1));
            $ret = Task::deliver($task);
            var_dump($ret);//判断是否投递成功
            \Log::info('delever task' . ($i + 1));
        }
```

**Comment by hhxsv5** [comment]
注意看文档，[自定义进程](https://github.com/hhxsv5/laravel-s/blob/master/README-CN.md#%E8%87%AA%E5%AE%9A%E4%B9%89%E8%BF%9B%E7%A8%8B)中投递Task deliver() 第二参数要穿true。
