### ISSUE TITLE
有什么好办法解决进程内存一直增长

### ISSUE THREAD

**Issue by minxinqing** [hhxsv5/laravel-s#86]
我起了个“自定义进程”监听队列，然后投递异步任务队列，TASK里只做了一件事情，把接收到的数据插入数据库。观察这个task进程的内存占用量，在一直增长，有什么办法能在任务完成后释放掉这部分增长的内存吗（找了半天没找到在哪增长的）？还是说只能通过max_request参数来重启进程？

**Comment by hhxsv5** [comment]
具体代码提来看看

**Comment by minxinqing** [comment]
神奇了，我用我本地php7.1.13跑这个任务，内存就不会逐渐增加，用7.2.2跑内存就会慢慢增长，可是用同事的7.2.9跑内容也不会增加。
难道是php版本原因？

**Comment by minxinqing** [comment]
我升级到7.2.9也不行，还能是什么原因啊？
现在测试的是原生的php代码，内存一直往上涨。
```PHP
<?php
$dbms='mysql';     //数据库类型
$host='127.0.0.1';
$dbName='homestead';    //使用的数据库
$user='homestead';      //数据库连接用户名
$pass='secret';          //对应的密码
$dsn="$dbms:host=$host;dbname=$dbName";

$dbh = new \PDO($dsn, $user, $pass); //初始化一个PDO对象

for($i=0; $i< 100000; $i ++) {

    $sql = "insert into books (title, author,created,updated) values ('xxx', 'dddd', 234,555)";
    $dbh->exec($sql);
    unset($sql);
    if ($i % 100 ==0) {
        print_r(memory_get_usage()/1024/1024);
        echo "\r\n";
    }
}

```

![image](https://user-images.githubusercontent.com/3809601/45219524-c22c4d80-b2dd-11e8-9bc7-a31e63a9f220.png)

**Comment by wi1dcard** [comment]
Mark 一下，刚自己测了下那段代码似乎在我的环境上没毛病

**Comment by hhxsv5** [comment]
PHP 5.6与PHP 7.2下测试 未出现内存持续增加的情况。

**Comment by minxinqing** [comment]
找到原因了，因为我的环境上装了 [Zend Server Z-Ray](http://www.zend.com/en/products/server/z-ray) 扩展，一个类似 laravel-debugbar 的调试工具。

**Comment by hhxsv5** [comment]
那应该是持续追加数组、字符串这雷问题导致。尝试清理下。

**Comment by minxinqing** [comment]
直接把它给禁了。都不记得上次用它是什么时候了，应该是在某篇文章上看过它，于是就安装尝试了下。
