### ISSUE TITLE
负责处理http请求的worker进程占用内存一直在递增

### ISSUE THREAD

**Issue by minxinqing** [hhxsv5/laravel-s#88]
+-------------------+---------------------------------------+
| Component         | Version                               |
+-------------------+---------------------------------------+
| PHP               | 7.1.20-1+ubuntu16.04.1+deb.sury.org+1 |
| Swoole            | 4.0.2                                 |
| Laravel Framework | 5.4.36                                |
+-------------------+---------------------------------------+

负责处理http请求的worker进程占用内存一直在递增，没有任何业务逻辑，直接在路由文件里返回数组。
```
Route::get('/history/list', function (){
        return ['code' => 0, 'data' => []];
    });
```
测试的时候循环批量请求20来次，然后ps查看进程观察出来的结果。

**Comment by wi1dcard** [comment]
个人感觉20来次看不出什么，有可能还没有回收，长时间挂着观察才有是否存在内存泄漏的参考价值

**Comment by minxinqing** [comment]
线上也在用着，单个进程都跑到快60M内存了，然后应该是到max_request限制重启之后就下来了

**Comment by scil** [comment]
Help this list can help more or less. [Mode Map Base Items Checklist](https://github.com/scil/LaravelFly/wiki/Mode-Map-Base-Items).

Besides data pollution, Memory control is important to mix swoole and laravel. Let's make it better.

**Comment by wi1dcard** [comment]
Hi @scil,  I'm watching LaravelFly and Laravel-S for a long time. They both are nice projects.  However, there's a question in my head that doesn't really matter. I wonder if you are Chinese? Or you can read Chinese? 😄

**Comment by scil** [comment]
Yes, I'm chinese. 😄

**Comment by wi1dcard** [comment]
@scil You pro in English. 👍

**Comment by hhxsv5** [comment]
@scil  Nice checklist!
@minxinqing @wi1dcard 昨晚经ab压测发现确实存在内存递增问题，虽然有`max_request`最后一道防线，但应在代码层面做到最优。今天排查下。

**Comment by wi1dcard** [comment]
@hhxsv5 感谢大佬加持，关注进展

**Comment by hhxsv5** [comment]
[Illuminate/Laravel.php#L139](https://github.com/hhxsv5/laravel-s/blob/master/src/Illuminate/Laravel.php#L139) 此处每次请求会`clone`快照内容到`$this->app`中，而`$this->app`中的原始对象被其他地方引用，引用计数没有归零，无法GC回收，导致内存持续增加。
打算不再使用clone对象的方式，使用赋值数组或重置成员属性的方式来避免引用。

**Comment by hhxsv5** [comment]
了解下[垃圾回收机制](https://secure.php.net/manual/zh/features.gc.php)。

**Comment by wi1dcard** [comment]
@minxinqing 自荐一个自己的博文：<https://wi1dcard.cn/tutorials/php-reference-variable/>

**Comment by hhxsv5** [comment]
@wi1dcard 👍
@minxinqing 已[移除clone](https://github.com/hhxsv5/laravel-s/commit/2e12529c633ae939243a643b7726a344182c26ec)

**Comment by minxinqing** [comment]
@hhxsv5 
方便发一个版出来吗？

**Comment by hhxsv5** [comment]
[v3.0.3](https://github.com/hhxsv5/laravel-s/releases/tag/v3.0.3)
