### ISSUE TITLE
版本3.0之后, 在Lumen中使用 app('auth'), app('request') 等失效原因. 

### ISSUE THREAD

**Issue by RJustice** [hhxsv5/laravel-s#89]
1. Tell us your PHP version(`php -v`)

7.1.21

2. Tell us your Swoole version(`php --ri swoole`)

4.1.2

3. Tell us your `Laravel`/`Lumen` version(check composer.json & composer.lock)

Lumen  5.7.1

主要是关于3.0版本起的 比如  app('auth') , app('request') 等因为绑定的 alias 失效. 

我查看了从2.0.7到3.0 升级的文件修改. 

主要查看到  
```
vendor/hhxsv5/laravel-s/src/Illuminate/Laravel.php 
line:325

$this->app = clone $this->app;
```

注释这一行绑定的 alias 都可以通过 app() 来获取到相应的对象内容. 

在文件 /hhxsv5/laravel-s/src/LaravelS.php 中,  因为 使用了 

$laravel = clone $this->laravel

触发了 对象中的 __clone 方法,  

我没有查看所有的代码,  所以不清楚  Laravel.php 中的 clone $this->app 具体有什么用,  应该来说不需要再复制一次这里面的app,  因为 laravel 已经在 Laravels.php 中复制了,

**Comment by hhxsv5** [comment]
clone存在gc无法回收等问题，会导致内存持续增加，已[移除clone](https://github.com/hhxsv5/laravel-s/commit/2e12529c633ae939243a643b7726a344182c26ec)

**Comment by hhxsv5** [comment]
[v3.0.3](https://github.com/hhxsv5/laravel-s/releases/tag/v3.0.3)
