### ISSUE TITLE
Inotify监听排除指定目录-如vendor

### ISSUE THREAD

**Issue by xiusin** [hhxsv5/laravel-s#93]
如题

**Comment by hhxsv5** [comment]
目前没支持，但可以做。你需要注意的是 监听文件变化自动reload 这个特性主要用于开发环境，不建议用到正式环境。

**Comment by xiusin** [comment]
@hhxsv5 其实可以加一个选择忽略的文件夹, 有的时候远程开发环境打开inotify光vendor里的目录就够喝一壶的,而且这些文件监控也没有意义..

**Comment by hhxsv5** [comment]
可以，支持后关闭此issue。

**Comment by xiusin** [comment]
ok

**Comment by hhxsv5** [comment]
升级到v3.0.5
laravels.php中配置[inotify_reload.excluded_dirs](https://github.com/hhxsv5/laravel-s/blob/master/Settings-CN.md)。
