### ISSUE TITLE
laravel 对象可能没有初始化

### ISSUE THREAD

**Issue by zjuxxd** [hhxsv5/laravel-s#94]
1. Tell us your software version
    How to know it?
    ```Bash
    # PHP
    php -v
    # Swoole
    php --ri swoole
    # Laravel
    grep 'laravel/framework' composer.json
    # Lumen
    grep 'laravel/lumen-framework' composer.json
    ```

    | Software | Version |
    | --------- | --------- |
    | PHP | 7.1.23 |
    | Swoole | 4.2.5 |
    | Laravel | 5.5 |

2. Detail description about this issue(error/log)
我们在试用该框架，在做一个简单的性能测试。请求的实现里面做了一个下载文件的处理，然后返回给客户端。我们想看下在这种情况下的性能，在测试中碰到了下面的错误：

`LaravelS: onRequest: Uncaught exception "TypeError"([0]Argument 1 passed to Hhxsv5\LaravelS\LaravelS::convertRequest() must be an instance of Hhxsv5\LaravelS\Illuminate\Laravel, null given, called in /home/deploy/apps/codebase/releases/codebase_1.0.3242/vendor/hhxsv5/laravel-s/src/LaravelS.php on line 122) at /home/deploy/apps/codebase/releases/codebase_1.0.3242/vendor/hhxsv5/laravel-s/src/LaravelS.php:110,
#0 /home/deploy/apps/codebase/releases/codebase_1.0.3242/vendor/hhxsv5/laravel-s/src/LaravelS.php(122): Hhxsv5\LaravelS\LaravelS->convertRequest(NULL, Object(Swoole\Http\Request))`

3. Give us a `reproducible` code block and `steps`

    ```PHP
    请求的实现为下载一个小文件，然后返回：
    file_get_contents($url)

    该问题不稳定重现，在压力测试的时候比较容易复现
    ```

**Comment by hhxsv5** [comment]
暂未重现，怎样压测的？

**Comment by zjuxxd** [comment]
@hhxsv5 I've uploaded a demo to reproduce the problem. Please use following request for testing:
/api/test/2
[blog.tar.gz](https://github.com/hhxsv5/laravel-s/files/2552524/blog.tar.gz)

**Comment by hhxsv5** [comment]
Nice!

**Comment by hhxsv5** [comment]
@zjuxxd 未复现。
![image](https://user-images.githubusercontent.com/7278743/48194115-165bb880-e387-11e8-8f96-e130dcaf1723.png)
![image](https://user-images.githubusercontent.com/7278743/48194133-207db700-e387-11e8-95a9-aec58b5f7b99.png)

**Comment by zjuxxd** [comment]
I tried again. Not able to reproduce now. Don't know what make this problem disappear.
