### ISSUE TITLE
高并发下容易出现错误SQLSTATE[HY000]: General error: 2014 Cannot execute queries while other unbuffered queries are active

### ISSUE THREAD

**Issue by zjuxxd** [hhxsv5/laravel-s#95]
1. Tell us your software version
    How to know it?
    ```Bash
    # PHP
    php -v
    # Swoole
    php --ri swoole
    # Laravel
    grep 'laravel/framework' composer.json
    # Lumen
    grep 'laravel/lumen-framework' composer.json
    ```

    | Software | Version |
    | --------- | --------- |
    | PHP | 7.1.23|
    | Swoole | 4.2.5 |
    | Laravel | 5.5 |

2. Detail description about this issue(error/log)

`SQLSTATE[HY000]: General error: 2014 Cannot execute queries while other unbuffered queries are active.  Consider using PDOStatement::fetchAll().  Alternatively, if your code is only ever going to run against mysql, you may enable query buffering by settingthe PDO::MYSQL_ATTR_USE_BUFFERED_QUERY attribute. (SQL: select * from `admin_user` where `id` = 1 and `admin_user`.`deleted_at` is null limit 1) {"exception":"[object] (Illuminate\\Database\\QueryException(code: HY000): SQLSTATE[HY000]: General error: 2014 Cannot execute queries while otherunbuffered queries are active.  Consider using PDOStatement::fetchAll().  Alternatively, if your code is only ever going to run against mysql, you may enable query buffering by setting the PDO::MYSQL_ATTR_USE_BUFFERED_QUERY attribute. (SQL: select * from `admin_user` where `id` = 1 and `admin_user`.`deleted_at` is null limit 1) at /home/deploy/apps/codebase/releases/codebase_1.0.3238/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, Doctrine\\DBAL\\Driver\\PDOException(code: HY000): SQLSTATE[HY000]: General error: 2014 Cannot execute queries while other unbuffered queries are active.  Consider using PDOStatement::fetchAll().  Alternatively, if your code is only ever going to run against mysql, you mayenable query buffering by setting the PDO::MYSQL_ATTR_USE_BUFFERED_QUERY attribute. at /home/deploy/apps/codebase/releases/codebase_1.0.3238/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:79, PDOException(code: HY000): SQLSTATE[HY000]: General error: 2014 Cannot execute queries while other unbuffered queries are active.  Consider using PDOStatement::fetchAll().  Alternatively, if your code is only ever going to run against mysql, you may enable query buffering by setting the PDO::MYSQL_ATTR_USE_BUFFERED_QUERY attribute. at /home/deploy/apps/codebase/releases/codebase_1.0.3238/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:77`

补充：
在mysql 的connection 里面已经加入了下面的配置，但是问题依旧
`'options'   => array(PDO::MYSQL_ATTR_USE_BUFFERED_QUERY => true),`

3. Give us a `reproducible` code block and `steps`

  业务代码为从一个表里面查询一个字段：
  User::whereId(1)->first()

  在压力测试的时候很容易复现该问题

**Comment by hhxsv5** [comment]
启用协程Runtime了吗？

**Comment by scil** [comment]
What about the test details? 

 If same error occurs with [laravel-swoole](https://github.com/swooletw/laravel-swoole) or [LaravelFly](https://github.com/scil/LaravelFly), it's may be a swoole bug？

**Comment by zjuxxd** [comment]
> 启用协程Runtime了吗？
'enable_coroutine' => true
这个设置是由配置的，我又重新测了一下，3000个请求有大约25%会失败

**Comment by zjuxxd** [comment]
> What about the test details?
> 
> If same error occurs with [laravel-swoole](https://github.com/swooletw/laravel-swoole) or [LaravelFly](https://github.com/scil/LaravelFly), it's may be a swoole bug？

I have not tried these two yet. Will try later.
The test steps:
1. Implement a simple request handler, just read a column from db then return.
2. use jmeter to run the performance test, main parameters of jmeter: (Num of threads: 15, ramp-up: 0, Loop count:200)
3. result 25% of request failed

**Comment by scil** [comment]
Maybe there's something wrong with your code.

LaravelFly uses laravel-s's  mysql db classes, and implements a jet simple connection pool, and works well while `ab -k -n 1000 -c 10`.

**Comment by hhxsv5** [comment]
@zjuxxd @scil I guess it is related to your MySQL server configuration. @zjuxxd  could you please paste a brief package hidden your sensitive information here?

**Comment by zjuxxd** [comment]
@hhxsv5 
[blog.tar.gz](https://github.com/hhxsv5/laravel-s/files/2552473/blog.tar.gz)

**Comment by zjuxxd** [comment]
@hhxsv5 I've uploaded a demo to reproduce the problem. Please use following request for testing:
/api/test/1
[blog.tar.gz](https://github.com/hhxsv5/laravel-s/files/2552507/blog.tar.gz)

**Comment by hhxsv5** [comment]
好，我看看。

**Comment by hhxsv5** [comment]
OK, I will try it.

**Comment by hhxsv5** [comment]
@scil @zjuxxd I didn't reproduce that question.
![image](https://user-images.githubusercontent.com/7278743/48194325-ab5eb180-e387-11e8-944a-aa513696a2b4.png)
![image](https://user-images.githubusercontent.com/7278743/48194353-be718180-e387-11e8-9eb8-2def22f34eb1.png)
![image](https://user-images.githubusercontent.com/7278743/48194343-b4e81980-e387-11e8-8c75-f10db62e7038.png)
![image](https://user-images.githubusercontent.com/7278743/48194382-d21ce800-e387-11e8-8c3b-0826c97a5d1e.png)

**Comment by zjuxxd** [comment]
Seems like the problem is related to some MySQL server configure. When I test with a local MySQL 5.6 installation, the problem is not able to reproduce. But when I'm using RDS in aliyun with default configuration, the problem is easy to reproduce.

**Comment by zjuxxd** [comment]
@hhxsv5 seems the issue is related to where the MySQL server is located. If I install MySQL in a remote server, the issue is able to reproduce. Hope this info could help you to reproduce.

**Comment by zjuxxd** [comment]
![image](https://user-images.githubusercontent.com/6159155/48258346-d3b1e300-e44f-11e8-93cd-5a062476e29d.png)
This is my test result

**Comment by zjuxxd** [comment]
I checked in your last screenshot, I can also see many none 2xx responses, can you also check what's is the error?

**Comment by zjuxxd** [comment]
@hhxsv5 Is there some update on this issue?

**Comment by hhxsv5** [comment]
I have reproduced this bug and temporarily disabled(enable_coroutine_runtime=>false) coroutine runtime for PDO. Note the new [configuration item name](https://github.com/hhxsv5/laravel-s/blob/master/Settings.md) in version [3.1.0](https://github.com/hhxsv5/laravel-s/releases/tag/v3.1.0).

**Comment by zjuxxd** [comment]
What's the impact if coroutine_runtime is disabled? Will it disable the coroutine for http, redis etc?

**Comment by hhxsv5** [comment]
Coroutine runtime is used for PDO, PhpRedis, MySQLi. Note the difference between [Runtime::enableCoroutine](https://wiki.swoole.com/wiki/page/965.html)  and [enable_coroutine](https://wiki.swoole.com/wiki/page/949.html).
